### ISSUE TITLE
Supported characters for getpot section names

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#10060]
## Rationale

I was converting `test/tests/outputs/format/test_json.py` to use the new hit parser. We currently use the original python parser to parse the output of `--dump` to make sure it is valid input file syntax and it makes it easier to test to see if the output is valid.
However, "*" is not a valid character in section names. Should it be allowed?
Currently the allowed characters are alphanumeric and `_./:<>-+`.

## Description

Put a `*` in the a section name in an input file. The parser will complain with:
`invalid section path character '*'`

## Impact

Allow more characters in section names in input files.
I don't really need to do this for my `--dump` tests but it brought up the question on what characters should be allowed.

**Comment by rwcarlsen** [comment]
I would lean toward being conservative about which characters we admit to the valid set - if for no other reason than preserving future flexibility (e.g. for new special syntax, etc.).  Obviously we can't allow ``]`` or ``=`` characters because they close section headers and separate field names (which have the same valid char set as section names) from field values.

**Comment by rwcarlsen** [comment]
``*`` is officially in with #10081.  I vote that as good enough for now.
