### ISSUE TITLE
Function interface improvement within SinglePhaseFluidPropertiesPT

### ISSUE THREAD

**Issue by lingzou** [idaholab/moose#10142]
## Rationale
Currently, within SinglePhaseFluidPropertiesPT, which should be based on pressure (`p`) and temperature (`T`), fluid viscosity (`mu`) and thermal conductivity (`k`) are calculated from density (`rho`) and temperature (`T`).
This is an obvious contradiction to the design of this base class.

## Description
It is proposed that, both mu and k should be redesigned as functions of `p` and `T`.
In addition, their derivatives w.r.t. `p` and `T` should also be provided.
There are proposed functions:
```c++
virtual Real mu(Real pressure, Real temperature) const = 0;
virtual Real k(Real pressure, Real temperature) const = 0;
virtual void
mu_dpT(Real pressure, Real temperature, Real & mu, Real & dmu_dp, Real & dmu_dT) const = 0;
virtual void
k_dpT(Real pressure, Real temperature, Real & k, Real & dk_dp, Real & dk_dT) const = 0;
```

## Impact
This will impact all downstream codes that uses SinglePhaseFluidPropertiesPT and its children classes.
@cpgr @WilkAndy @aprilnovak

**Comment by cpgr** [comment]
This was an intentional design decision to reduce the computational expense of calculating these fluid properties. Calculating fluid properties in `porous_flow` models can take a significant proportion of the overall time - we don't want to have to calculate density again inside `mu(pressure, temperature)`. 

The way it is set up at the moment, we always calculate density and then use that to compute viscosity when required. Making the proposed change, we would have to calculate density, and then calculate it again to calculate viscosity. This is especially bad for the CO2 model, where density calculation is very expensive.

Is there a specific example that you want these changes for?

**Comment by lingzou** [comment]
In pronghorn, in some of our fluids, for example, Helium properties provided by KTA, k and mu are provided as function of p and T. I am not familiar with CO2, but I believe you have your specific need to do so.
It might be an acceptable design for all us to ADD these new functions proposed above, instead of to redesign them.
What do you think?

**Comment by cpgr** [comment]
What about if we add `rho_mu(pressure, temperature, &rho, &mu)` and `rho_mu_dpT(pressure, temperature, &rho etc)` etc that we can use in `porous_flow`, as we always have density and viscosity, and make the changes you proposed in this issue?

The new methods would eliminate the need to calculate density twice for water and CO2, and would allow pronghorn to use the formulations you have.

**Comment by andrsd** [comment]
@cpgr So, I agree with @lingzou  that in `SinglePhaseFluidPropertiesPT` `mu` and `k` should be functions of `p` and `T` so that the API is consistent - we do that in our parallel branch for `SinglePhaseFluidProperties`. When we have the same quantity in terms of other variables we state it in its name - for example entropy (s) is computed as `s(Real v, Real u)`, but we also have `s_from_h_p(Real h, Real p, Real & s, Real & ds_dh, Real & ds_dp)`.  It would be nice to have this consistency in `SinglePhaseFluidPropertiesPT` as well. Thus, the API I would like to see would be: `mu(Real p, Real T)` and `mu_from_rho_T(Real rho, Real T)`. I see there are only 3 functions that would have to be renamed and I am happy to open a PR with this to update `fluid_properties` and `porous_flow` modules. Do you guys at CSIRO have some internal code depending on this API that we do not have access to?

**Comment by cpgr** [comment]
I don't think that there is anything that this will break.

These changes work, but I was thinking of the usage in `PorousFlowSingleComponentFluid`. Up until now, we have had fluid viscosities `mu(T)` and `mu(rho, T)`, so both could be used in this material with the same function. If we add more fluids with `mu(p, T)`, then this material might not be able to use them as `mu(rho, T)` won't be implemented. Any ideas @andrsd?

**Comment by cpgr** [comment]
Thats why I suggested `rho_mu(p, T, &rho, &mu)`, which would look like

````
rho_mu(p, T, rho, mu)
{
  rho = rho(p, T)
  mu = mu(p, T)
}
````
for fluids with `mu(p, T)`, and like
````
rho_mu(p, T, rho, mu)
{
  rho = rho(p, T)
  mu = mu_from_rho(rho, T)
}
````
for fluids with `mu(rho, T)`.

This would work consistently for all fluids in `PorousFlowSingleComponentFluid` without having to calculate density again inside the viscosity method.

**Comment by andrsd** [comment]
Well, porous flow does not have to use the "new" API, it can stick with `mu_from_rho_T(rho, T)` if it does not need `mu(p, T)`.

BTW: I also found some inconsistencies in the unit tests, the test would call `mu(p, T)` but on the interface where the first argument was supposed to be density - I fixed that in this PR.

**Comment by andrsd** [comment]
Also, the other app has its own material that computes the properties, they are not planning on using the one from porous flow. They just need to call `mu(p, T)`. They do not really care for `mu(rho, T)`. That's why I think having `mu(rho, T)` and `mu(p, T)` in the same interface is fine.  As I said, we already do a similar thing in the `SinglePhaseFluidProperties` branch.
