### ISSUE TITLE
mooseError to MooseException in FluidProperties

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10166]
## Rationale

Sometimes when i'm running simulations, MOOSE bombs out (mooseError) due to pressure or temperature, etc, going outside an allowable range.  It'd be better to through a MooseException instead of a mooseError, because then MOOSE can cut the timestep and try again.

## Description

Replace things like
```
mooseError("Pressure ", pressure,
                         " is out of range in Water97FluidProperties::inRegionPH");
```
with
```
throw MooseException("Pressure " + Moose::stringify(pressure) +
                         " is out of range in Water97FluidProperties::inRegionPH");
```
## Impact

Ability to cut timestep instead of completely crashing.   Tagging @cpgr , @andrsd

**Comment by cpgr** [comment]
You know, I didn't even know that MooseException existed! I sometimes hit this as well, so this would be useful

**Comment by andrsd** [comment]
Try this first:
```
if (non-physical-value)
  return std::numeric_limits<Real>::quiet_NaN();
```

This should propagate a `NaN` or `Inf` into the residual. When PETSc sees either one, it will stop the solve, MOOSE will cut the time step in half and will try to re-solve the time step.

I was thinking about this change, but did not have time to experiment with it. If it works for you guys, then I am in support of it.

I'd like to avoid `MooseException`, because we need to propagate them thought PETSc and do parallel syncs. `NaNs` and `Infs` are simpler and handled in PETSc.

**Comment by WilkAndy** [comment]
Here i disagree with you, @andrsd .  Firstly, the error message "Pressure -123456 is out of range" is very informative, so we need that (and could achieve that with a mooseWarning) and secondly this seems exactly the case where MooseException is appropriate to use: returning NaN seems a weird thing to do as the result is not necessarily NaN, but is just some number that our equation of state cannot (yet) compute.

Please instruct me what to do, and i'll do it.  Obviously my objections in the previous paragraph aren't strong game-changers.

a

**Comment by permcody** [comment]
There might be a compromise solution. You could print out a `mooseWarning` with the information you'd like to see AND return the NaN. I agree that it's useful to know the out of bounds value. @andrsd - Are you concerned about efficiency with your comment?

**Comment by andrsd** [comment]
@permcody Yes, I do not like the MPI communication we have in the code to handle the parallel exceptions.  NaN is IMO a simpler solution. It should achieve the same as the exception. 

@WilkAndy Keep the message if you want it. My objection was against the way how to terminate the solve.

**Comment by tophmatthews** [comment]
I've done this exact thing in BISON (converting error to exceptions) and it helped avoid unnecessary run terminations. What is decided as the better way here, `MooseException` or `quiet_NaN`?

**Comment by andrsd** [comment]
The difference is this: if you use `MooseException`, there will be a parallel communication to propagate the exception to each CPU. Then we set a `quiet_NaN` to the residual to terminate the solve and I think there will be another parallel communication on PETSc level. So just using the `quiet_NaN` will eliminate one parallel communication.  But, you may want to catch exceptions in your custom Executioner to do different things based on the exception. Then, `quiet_NaN` does not have that flexibility and cleanliness like exceptions.

**Comment by WilkAndy** [comment]
Sounds like ```MooseException``` is better.

**Comment by andrsd** [comment]
@WilkAndy Exceptions are not as bad in MOOSE, because users have pretty much only one place where they can handle their exceptions. In general, exceptions can be raised any where and handled any where, so it can be hard to see the path the code would take from raising the exception to handling it - which is the main downside of code that is using exceptions (I have seen and had to deal with pretty bad ones). In general, exceptions can even have different types, which makes the whole thing even more complicated. In MOOSE we gave you one type, making it simpler. So you have only the good bits you can use - are we not the nicest developers? ;-)

**Comment by WilkAndy** [comment]
Yep, that last sentence is so true.

**Comment by tophmatthews** [comment]
Awesome, thanks for the insight

**Comment by WilkAndy** [comment]
Lots of discussion above but no definitive conclusion, i think.  Also, no action by me, sorry!  I'm going to implement the MooseException instead of quiet_NaN

**Comment by andrsd** [comment]
Yeah, it is one of those things where both approaches can be valid under different scenarios depending on the application needs.
