### ISSUE TITLE
Add a kernel (|\nabla \|^2) in phase field module

### ISSUE THREAD

**Issue by kkq561** [idaholab/moose#10347]
## Rationale

I would like to include a kernel (|\nabla \|^2) in phase field module for phase field model of oxidation (oxide kinetic growth problem via cation/anion vacancies and electrons).

## Description
In oxide kinetics problem, we need to add an expression (|\nabla \|^2) in A-C equation. Specifically, it is for including electrostatic contributions in phase field simulation (|\nabla \electric field|^2). The detail information is described in the recent paper (Sherman and Voorhees, Physical Review E 2017, https://journals.aps.org/pre/abstract/10.1103/PhysRevE.95.032801). 

## Impact
This will be useful for users to directly perform phase field model of oxidation using phase field module in moose rather than connecting similar kernels in other modules (e.g., JouleHeatingKernel in heat conduction module).

**Comment by permcody** [comment]
Don’t do that, just turn on both the phase field AND hear conduction
modules in your app (do this in the Makefile).

**Comment by dschwen** [comment]
@permcody, I discussed this with @laagesen. The issue is a bit misleading. We'd like to add a kernel for a very similar PDE to phase field because we think using the "Joule Heating" kernel would be very confusing. All constants and coupled variables have names that are specific to a Joule heating problem. We'd have to supply some PF order parameter as the "Temperature" in the way we use that PDE - that would look odd.

**Comment by dschwen** [comment]
I'm open to other suggestions. Do we have a general policy for structurally identical PDEs that have coefficients that can mean multiple different physical things?

**Comment by laagesen** [comment]
Kyoungdoc, I think it would help if you changed the wording of this issue, since you are not literally adding the JouleHeatingSource to the phase-field module, but adding a kernel with similar physics with different materials as input. Can you please change the issue title and the wording of the text so that it focuses more on the problem you are working on, rather than referencing the JouleHeatingKernel?
