### ISSUE TITLE
Add parameter force_preaux to GeneralUserObject

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#10355]
## Rationale

I'd like to put this out for discussion. In certain situations it is desirable to bump a userobject to PREAUX, e.g. if another UO depends on it that in turn an AuxVar depends on (situation `UO1->UO2-> AuxVar`) or if an ElementUO depends on the GeneralUO. I would like to add a parameter force_preaux to force the GeneralUserObject to be bumped into PREAUX. Currently, you trick MOOSE into doing that by adding a dummy dependence in an AuxKernel.

## Description

I would only allow this for GeneralUserObject because they cannot depend on AuxVariables so the possible issue `AuxVar->UO` that would be destroyed by `force_preaux = true` does not apply. 
Dependency resolution among general & elemental UOs is not done correctly anyway I think (always `ElementUO` and then `GeneralUO`), so that is not an argument against this.

**Comment by permcody** [comment]
Hmm, I don't like this, but I also understand the current need for it. Ideally MOOSE will someday get to a more on-demand DAG-like evaluation where you don't have to do hackish things like this. I like the fact that this hack is mostly hidden from the user and it works nicely for simple coupling cases that are "one deep". 

Since I don't see a DAG like capability showing up anytime in the near feature, I could be convinced to add this parameter since you are already using an even uglier hack to get what you want as it is.
