### ISSUE TITLE
Let side and neighbor materials obtain the reference of their corresponding element materials

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10369]
## Rationale
We have a material requiring a large amount of data and do not want them to be duplicated in the memory. Currently, we use a general user object to load the data and let the three copies of materials get the data from the user object. However, this makes the input not very user friendly: the userobject and material have two separate blocks although they are closely related and `block` parameter must be the same. This is getting worse when we have lots of materials (>40).

## Description
So I am proposing to let the two copies of material able to get the reference of the element material. Then they can just refer to the data held in the element material. Any other suggestions?

## Impact
Better user experience on creating materials.

**Comment by permcody** [comment]
What data specifically, material properties? I ask because if it's not part of the public interface you'd have to dynamic cast it down to your specific materials in order to do anything useful (which is why the UserObject interface is templated instead). Also, this may be more challenging that it sounds here. Right now we don't differentiate between element, side, and neighbor materials at the type level but in order to set references properly we'd have to construct these in a specific order. Realistically, this would probably be better satisfied by constant pointers instead.

**Comment by YaqiWang** [comment]
Oh, I did not think of the type casting. The data are the multigroup cross sections for neutron transport calculation. Maybe I already can do this with existing moose interface functions on my side. It will be ugly. I possibly will close this issue in the future unless you want to work on it.

**Comment by YaqiWang** [comment]
I can achieve the better user interface without this, so closing.
