### ISSUE TITLE
Petsc options not being read from input file

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#10396]
## Rationale
`-ksp_monitor_true_residual` and `-options_left` not getting picked up by petsc when passed through MOOSE input file

## Description
When passed in input file these options have no effect. When passed on the command line, they work as desired.

## Impact
Don't have complete control of PetSc through input file petsc options.

**Comment by lindsayad** [comment]
This is actually pretty weird. If I move these options to the front of the petsc options list, then they are picked up... This needs some more investigation

**Comment by permcody** [comment]
We've run into this before with other options. `-log-summary` comes to mind. It has to be set before the input file is even read or it doesn't take effect. This behavior might be falling into that category but it's difficult to say why.

As a work around we could always sort options for the user based on our knowledge of their required placement, but I'd rather dig in and figure out why those limitations exist rather than hacking around the problem.

**Comment by lindsayad** [comment]
What's interesting here though is that these options will or will not get
used depending on their ordering in the input file's vector of strings, so
it appears that they can be set from the input file.

**Comment by GiudGiud** [comment]
@lindsayad is this resolved

**Comment by lindsayad** [comment]
No and I think I may have run across the reason for it last week...

**Comment by lindsayad** [comment]
Ok `-ksp_monitor_true_residual` is working in `petsc_options`. `-options_left` is not working from `petsc_options` because its value is being set to `NULL` which is equivalent to `false`. If I set `-options_left` in `petsc_options_iname` and `1` in `petsc_options_value` that works
