### ISSUE TITLE
Allow XFEM to cut the mesh based level set function

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#10421]
## Rationale

It would be convenient to use the level set function to cut the mesh with XFEM. The zero level set function represents the material interface. Based on the sign of the level set value, the material properties are assigned to either side of the interface. 
## Description

XFEM cuts the mesh based on the geometry information, such as radius and origins for circle. For complicated geometry, the level set function is more appropriate to represent the geometry. 

## Impact

New capability is added and no impact on existing codes.

**Comment by permcody** [comment]
Tag @aeslaughter - Not sure if there's an opportunity to tie into existing level set stuff here or not, but I'd like to consolidate effort if appropriate.

**Comment by jiangwen84** [comment]
Thanks @permcody, very good suggestion. I will stop by @aeslaughter to discuss this.

**Comment by aeslaughter** [comment]
I don't think there is anything specific about level set, it could just as easily be phase field. What is really being done is to cut elements based on a field variable.

**Comment by jiangwen84** [comment]
@aeslaughter It is true for this issue topic. However, we plan to use XFEM to model moving interface problems, where we need the level set to propagate based on the velocity calculated from XFEM. I imagine it might be tricky to let XFEM work with level set module and maybe we need some discussion there.

**Comment by permcody** [comment]
It's not tricky to use one module from another. There are of course choices and trade-offs for various design choices. If you plan to make this a core capability and want XFEM to require the level-set module, that's fine. We do this all over the place already (e.g. phase-field requires tensor mechanics). It's also nice to have the modules organized into clean separate physics even if it means we have more interdependencies.

On the other hand, if this level-set capability is unrelated to the physics implemented in the level set module and neither interact with each other, then it might make sense to keep them separate. I just want to make sure you know that we do have a level-set capability to avoid re-inventing the wheel. If you decide that it's not going to work for your needs, fine. So long as you make that decision rather than just be unaware that there are other options.

**Comment by aeslaughter** [comment]
The level set module shouldn't be required, the logic for splitting an
element based on a variable should not be dependent on how that variable
evolves. In fact, you will want to build this XFEM functionality using
simple variable fields that you can explicitly control with functions to
build the capability, then driving it with level set should be trivial.
