### ISSUE TITLE
RenameBlock doesn't work with new_block_name

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10470]
## Rationale

When RenameBlock is used in this way
```
old_block_name = '1 2'
new_block_name = 'same_name same_name'
```
it doesn't correctly change the block name of both blocks to the same name.

## Description

Using two RenameBlocks, the first with new_block_id and the second with new_block_name works fine.  Eg:
```
old_block_name = '1 2'
new_block_id = '100 100'
...
old_block_id = '100'
new_block_name = 'same_name'
```
so the bug is probably pretty minor.

## Impact

Ability for users to merge block names into a single name, without having to use two RenameBlocks.

Tagging @hsheldon

**Comment by permcody** [comment]
Just looked at the code briefly. The issue here is that in the name -> name case, no ids are updated. Instead entries in a map are updated and probably written out with the mesh format, but there are issues with that because mesh formats likely expect unique names with each ID. Your workaround though is fundamentally different. In the ID case, every element with an old ID is actually updated to a new ID so you are change IDs on an element by element basis. After they are all updated, a single "map name" update puts them all into a single block.

Renaming a block and reassigning elements to new IDs are fundamentally different operations. This will have to be detected and accounted for when fixing this ticket.

**Comment by permcody** [comment]
One more thing, joining blocks together will likely fail for mixed element type meshes when the mesh is written out.

**Comment by WilkAndy** [comment]
I'm slowly working on this - 5 mins here-and-there.
