### ISSUE TITLE
Dependency Resolution for MOOSE

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#1050]
This is a big one:

We talked about changing MOOSE so that we can have dependency resolution based on which objects insid of which systems are coupled to one and other.  

The idea is to change the coupling interfaces so that when values from any system are requested we keep track of the parent system and the object itself in the DependencyResolver.  One idea is to have a pure virtual function in the coupling interface so that derived classes will supply their own system names so we don't have to do any RTTI.  Once he have that done we should be able to determine a minimum execution order for any simulation based on the objects enabled for that simulation.

There are further extensions to this that we'll get to later where we'll be able to optimize this so that we'll be able to do all of these calculations in a single loop or "minimum" number of loops in cycles are present.

**Comment by aeslaughter** [comment]
We talked about this a bit a few weeks ago in the MOOSE cube and after spending a lot of time in the warehouses, I think we can get closer to complete dependency resolution by adding more intermediate base class objects:

MooseObject <--- ElementalMooseObject <--- ... (Anything that executes/computes on elements)
MooseObject <--- NodalMooseObject <--- ... (Anything that executes/compute on nodes)
MooseObject <--- ExecuteMooseObject <--- ... (Anything with a single execute call)

This would be able to resolve dependencies for each of the base class groups, of course, this wouldn't allow the dependencies between elemental and nodal to be resolved, but I am not sure we want that anyway: having a node loop, element loop, node loop, etc. seems like a bad idea.

Just wanted to get this written down since we talked about it.

**Comment by permcody** [comment]
Yeah, we've talked about this before and making it happen isn't quite as
difficult as the implication for performance. Good to write things down
though.

**Comment by friedmud** [comment]
In the case where you have an element->node->element->node dependency... I don't see anything wrong with running the loops multiple times.  It's up to users to decide whether or not it's necessary for their application...

The idea of intermediate classes could work...  I've talked about "binning" objects that can execute simultaneously before... that could be one way to do it.

**Comment by friedmud** [comment]
Actually: a worse situation is when you have element->element dependencies... it means that you might need to run the element loop twice in a row!

**Comment by permcody** [comment]
This is a moving target. We keep talking about new ways of handling it. We have improved the interfaces enough that we can get more information in most cases. Regardless, we'll close this ticket and move discussion to the newer ticket: #6369
