### ISSUE TITLE
Code in CrankNicolson::preSolve() should be in a better place

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10553]
## Rationale
Currently, the code in `CrankNicolson::preSolve()` is basically doing some initial setup. Note that the `_t_step` is one there but not zero. It may create dangerous situation in other objects which doing initialization based on `_t_step == 0`.

## Description
The best solution IMHO is to create an `init` function in time integrators and let executioner call it in executioner's `init`.

## Impact
Not sure if this will cause any impact. This can be checked by changing `_t_step` to 0 at the begining and turn it back in `CrankNicolson::preSolve()`. I noticed this because I added an assertion in my material with stateful properties. But because I am using `_time` to switch works either on initial or during transient, this is not a problem to me. It does prevent me from adding an assertion though to make the code safer.

**Comment by andrsd** [comment]
> It may create dangerous situation in other objects which doing initialization based on _t_step == 0

Not really, because `_t_step` is bumped from 0 to 1 in `Transient::init` which is always called before any solve starts. So, when we get into time steppers `_t_step` is no longer zero. 

Moreover, `_t_step == 1` is actually correct, because in the __first__ time step we do not have `Residual_old` yet, so we need to compute it and that's what's happening there. After that, `Residual_old` is known, so we do not have to do anything special.

**Comment by YaqiWang** [comment]
Yes, but I think the code should be before `_t_step` is bumped up in `Transient::init`. The check is correct. But for example a material has something in its `computeQpProperties` like
```
if (_t_step == 0)
{
  // do some initial evaluation here.
  _mat_prop[_qp] = _another_prop[_qp] * 2;
}
else
{
  _mat_prop[_qp] = _mat_prop_old[_qp] + c * _dt;
}
```
Evaluating residual in `CrankNicolson::preStep()` will enter a wrong branch. Am I right?

**Comment by andrsd** [comment]
If we moved it into `init`, which is called before `_t_step` is bumped, then you do not need the if-statement. But effectively you are doing the same things, just the condition is different. I do not see a problem with the current way.

Also, just because you do something in Materials does not mean you should be doing the same in the time integrators. It depends _what_ you are after _in which context_.

If you are having issues with Crank-Nicolson, let's see a concrete example rather then theoretical one.

**Comment by YaqiWang** [comment]
People do use this:
```
./framework/src/executioners/Transient.C:  if (_t_step == 0)
./framework/src/postprocessors/ChangeOverTimePostprocessor.C:  if (_t_step == 0)
./framework/src/postprocessors/ChangeOverTimePostprocessor.C:    if (_t_step == 0)
./modules/phase_field/src/userobjects/PolycrystalUserObjectBase.C:  mooseAssert(_t_step == 0, "PolyIC only works if we begin in the initial condition");
./modules/solid_mechanics/src/materials/CombinedCreepPlasticity.C:  if (_t_step == 0 && !_app.isRestarting())
./modules/solid_mechanics/src/materials/PLC_LSH.C:  if (_t_step == 0 && !_app.isRestarting())
./modules/solid_mechanics/src/materials/ReturnMappingModel.C:  if (_t_step == 0 && !_app.isRestarting())
./test/src/postprocessors/TestPostprocessor.C:    if (_t_step == 0)
./test/src/postprocessors/TestPostprocessor.C:    if (_t_step == 0)
```
They are not seeing problem only because they are not using CN.

**Comment by aeslaughter** [comment]
@YaqiWang I have improved the level set module, please rebase this and remove the changes you made to level set and let's see if it behaves better.

**Comment by YaqiWang** [comment]
I realized that `_t_step` is still one in `CrankNicolson::init()` because the accumulation of `_t_step` in `Transient` happens a little earlier. I will submit a small PR for it.
