### ISSUE TITLE
Fix validParams Declaration Errors

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#10586]
## Rationale
Declarations of validParams are required in the header files.  However, we've been getting away with omitting it in many circumstances.  That needs to be fixed!

## Description
We should make it a compile error if you forget or mess up the declaration of your valid params.  We'll do this by adding a `static_assert` to the generic definition of validParams()

## Impact
Reduce error rate.

**Comment by permcody** [comment]
@friedmud - It looks like BISON is not building on Falcon with this change. I'm not sure why it's not reproducible on our Macs or the test systems, but there's definitely a problem (check the BISON build log failure). 

I've spent a few minutes looking into this and it appears that the issue is with an Action that's calling the ValidParams method for a Function that it builds. The header for said function is indeed included in the .C file of the action where the call is actually made but it's clearly hitting the generic (static_assert) version during compilation instead of the actual body of the method. Now it's true that the body of the method wouldn't be available in the unrelated ".C" ("Action" versus "Function"), but the header should be there. I haven't dug into it any more than this so far.

**Comment by permcody** [comment]
Tag @gardnerru

**Comment by friedmud** [comment]
Ok - I’ll check it out

**Comment by gardnerru** [comment]
I dont want to sound terribly needy but our nightly testing and external collaborator share are kaput until this is uncovered. Thanks in advance.
