### ISSUE TITLE
NodalEqualValueConstraint requires moose numbered node id's instead of nodeset name

### ISSUE THREAD

**Issue by veeshy** [idaholab/moose#10795]
## Rationale
NodalEqualValueConstraint currently requires knowing the node id that moose uses which generally requires creation of a mesh, running it through moose to get the mesh out with the moose renumbering then investigate by hand what the node numbers you want to apply on are, then subtract one since libmesh numbering starts at 0 and exodus starts at 1. 

Discussion at https://groups.google.com/forum/#!topic/moose-users/zIeMIP-Bf9M

## Description
This kernel applies on the same nodes a nodal bc applies so it can take a nodeset in then grab the node ids through the _mesh then use those nodes.

## Impact
More general interface with backwards compatibility so no impact except for easier to use kernel.

**Comment by veeshy** [comment]
I almost have a working version of this, but am not sure how to setup the params. Currently, nodes is a required parameter, is it possible to not require it? If someone provides the two nodeset names instead of the node id's, they should not need to supply dummy node inputs because of the nodes being marked required.

**Comment by permcody** [comment]
There's not a good way to "un-require" a parameter because it generally means you'd be violating an assumption in the underlying object. Maybe that number is used to size a vector that's indexed into, or the parameter is required to initialize a reference. You can "supress" a parameter but that's also a hack. If we are indeed going to allow users to enter a "this" or "that" type of parameter, both will have to be marked as optional and then code will have to be added in the constructor of the object to ensure that one of the two parameters was indeed supplied.

**Comment by andrsd** [comment]
@veeshy Your changes have to touch the parent class `NodalScalarKernel`

**Comment by veeshy** [comment]
Cool, doesn't seem too bad.

Is there a smart "default" param to give for `<std::vector<dof_id_type>>` and `<std::vector<BoundaryName>>` so I can easily check which "this" or "that" was supplied?

**Comment by andrsd** [comment]
You can key it off of the vector size. If both are zero, error out. If both are non-zero, error out. If one is zero and the other non-zero, use the non-zero one.

Also, it would be nice to tell people to update their input file + meshes if they used node IDs.
