### ISSUE TITLE
Remove warning "warning: overriding commands for target..."

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10929]
## Rationale

When i compile i get these sorts of messages:

```/apps/geomodel/moose/projects_andy/moose/framework/app.mk:183: warning: ignoring old commands for target `/apps/geomodel/moose/projects_andy/moose/modules/tensor_mechanics/build/header_symlinks/TensorMechanicsRevision.h'```

Are they necessary?  Can we remove them?

## Description

As above

## Impact

Compilation looks cleaner

**Comment by permcody** [comment]
Will you "git clean" first and make sure it's not some problem moving from the old to the new system? That's unlikely since the new system and the old system work in different areas.

It might also be some customization to the Makefile. Are you running into this when building the modules, or building a specific module? Let us know how to replicate, or at least what you are doing specifically.

**Comment by friedmud** [comment]
This will happen if you have two header files named the same thing in
different directories.  Is that the case here?  Maybe an old one laying
around?

**Comment by WilkAndy** [comment]
Yep, the "git clean" removed some rubbish that was obviously causing this.  Thanks @permcody and @friedmud .
