### ISSUE TITLE
Add SinglePhaseFluidProperties::e_from_p_T()

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#11133]
## Rationale

There are several `xxx_from_p_T()` routines already present in this class, `e_from_p_T()` is currently missing but it would be useful for me to have.

## Description

`SinglePhaseFluidProperties` already implements `e_from_v_h()` and `e_from_p_rho()`, I'd like to add `e_from_p_T()` plus the associated derivatives, `de_dp` and `de_dT`.

## Impact

This would be a new pure virtual API, so derived classes will also need to implement the API. If there are derived classes in external apps this might cause them to break (?) If so I'll try to implement it in a more backwards compatible way.

**Comment by andrsd** [comment]
You can implement the new method in the base class, then implement it the apps and then come back here and make it pure virtual. This is how we did it in the past.

**Comment by joshuahansel** [comment]
@jwpeterson @andrsd `e_from_p_T` used to exist. I eliminated it because it was redundant, since we have `e_from_p_rho` in conjunction with `rho_from_p_T`. If you have some kind of strict performance concern, then you may need to do something. Otherwise you don't need to do anything. If you still want to implement `e_from_p_T` for convenience, then you can make a non-pure virtual function in `SinglePhaseFluidProperties` that calls `e_from_p_rho` in conjunction with `rho_from_p_T`. Derived classes, if they have some optimization, may override this.

**Comment by jwpeterson** [comment]
@joshuahansel I needed the derivatives de/dp and de/dT and nothing else provided that, therefore I don't think it's redundant?

**Comment by joshuahansel** [comment]
By redundant, I mean that e, de/dp, and de/dT can all be computed in a generic way (independent of the particular fluid properties):
```
rho_from_p_T(p, T, rho, drho_dp, drho_dT)
e_from_p_rho(p, rho, e, de_dp_partial, de_drho)
de_dp = de_dp_partial + de_drho * drho_dp
de_dT = de_drho * drho_dT
```
So if you want to put this exact implementation in the base class, that's fine. But otherwise you, in some way, are duplicating relations between fluid properties that we've already defined.

**Comment by jwpeterson** [comment]
OK, I see what you are saying... Let me make a PR implementing this in the base class and see how it goes, but I think I will also keep the subclass specializations as they might be a hair faster...

**Comment by joshuahansel** [comment]
Ok that's fine, just remember that for any overriding of this base class implementation, you should add derivative checks and a consistency check for `e_from_p_T`: For example in `IdealGasFluidPropertiesTest.C`, just do the following:
```
REL_TEST(_fp->e_from_p_T(p, T), e, REL_TOL_CONSISTENCY);
DERIV_TEST(_fp->e_from_p_T, p, T, REL_TOL_DERIVATIVE);
```

**Comment by andrsd** [comment]
I did that in #11146

**Comment by jwpeterson** [comment]
> I did that in #11146

Thanks @andrsd, I will base my branch off yours then.
