### ISSUE TITLE
Need a new registerMooseObject macro

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11132]
## Rationale

This is probably my fault. I defined a template general user object, with name like `MyUO<unsigned int>`. Now I am having trouble to call `registerMooseObject` because `<` is an illegal letter used for naming.

## Description

I am proposing to add this
```
#define registerMooseObjectName(app, classname, name)                                              \
  static char combineNames(dummyvar_for_registering_obj_##name, __LINE__) =                        \
      Registry::add<classname>(                                                                    \
          {app, #classname, "", "", nullptr, nullptr, nullptr, __FILE__, __LINE__, "", ""})
```
into `Registry.h`, so that I can give a different legal name for the object.

## Impact

None.

**Comment by YaqiWang** [comment]
If you agree, I can send in a PR.

**Comment by permcody** [comment]
Wait, so you want users to put the template argument in the input file? How is this used? We might be able to just handle this with an alias (or typedef). That's actually what "RealVectorValue" is for instance. It's just a typedef to `TypeVector<Real>`. Since we haven't designed the system to expose templates directly to end users I wonder if you'll run into other problems.

**Comment by YaqiWang** [comment]
Yes, users can say `type = MyUO<unsigned int>`. You can find an example in Rattlesnake... I have not thought about typedef. Maybe it is better.

**Comment by permcody** [comment]
I'd suggest we try the typedef first. If you really want a few different types you can give them different user-friendly names and avoid exposing C++ specific syntax to your end users.

**Comment by YaqiWang** [comment]
Yes, typedef solves my problem. Thanks @permcody .
