### ISSUE TITLE
CSV Robustness issue

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#11171]
## Rationale

A user has reported that during very fast steps some CSV data is missing from the output file:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/6EsBgt8ahz8/4OCFPs2qAgAJ

## Description

We have optimized outputting of CSV data to avoid opening/closing and re-writing all data every time step. Perhaps there are circumstances where this system breaks down. This may be difficult to reproduce, but we can start with a few simple things like checking return codes of all I/O operations to see if we can get more detailed diagnostic information.

## Impact

CSV output system, somewhat critical, but localized to just output.

**Comment by permcody** [comment]
@mangerij - You may want to grab this PR. I wonder if one of the file open commands is failing.

**Comment by mangerij** [comment]
Ah, didn't get the notification for some reason. Yes, I will check today or possibly tomorrow.

**Comment by mangerij** [comment]
This didn't seem to fix the issue. I will email you the log (terminal output from Blues), input file, and .csv output for three runs.

**Comment by permcody** [comment]
Well I have a new theory. The "FormattedTable" object, which manages the
post processor data (the storage, screen printing, and file I/O) is a
utility. It doesn't really understand time or the postprocessor system, it
just takes new data and inserts it into the right place in the table and
manages what has been output and to where. Take a look at this code right
here:
https://github.com/idaholab/moose/blob/devel/framework/src/utils/FormattedTable.C#L137-L142

There are a couple of assumption on data insertion. First, for Real data,
we all know you can't just compare equals, so you have to do a tolerance
comparison to know if the incoming data belongs in the current row, or some
new row. I believe that the problem here is that your time step dt is so
small, that you are actually falling below our default tolerance which is
1e-12 in this utility.

How about you go into that table and jack up that tolerance a bit (1e-13,
or 1e-14)? If you go to far, you might start getting more rows than time
steps so be careful! If this fixes your issue, we'll just need to think
about a better way to insert row data. Instead of just letting the
FormattedTable decide when new rows are added, we might just have MOOSE
tell the table to create a new row (since it would know).

**Comment by andrsd** [comment]
I recommend that @mangerij will start with this simple input file:
```
[Mesh]
  type = GeneratedMesh
  dim = 1
  xmin = 0
  xmax = 1
  nx = 10
[]

[Functions]
  [./fn_right]
    type = ParsedFunction
    value = sin(t)
  [../]
[]

[Variables]
  [./u]
  [../]
[]

[Kernels]
  [./td]
    type = TimeDerivative
    variable = u
  [../]
  [./diff]
    type = Diffusion
    variable = u
  [../]
[]

[BCs]
  [./left]
    type = DirichletBC
    variable = u
    boundary = left
    value = 0
  [../]
  [./right]
    type = FunctionDirichletBC
    variable = u
    boundary = right
    function = fn_right
  [../]
[]

[Postprocessors]
  [./pps1]
    type = FunctionValuePostprocessor
    function = fn_right
  [../]
[]

[Executioner]
  type = Transient
  dt = 0.001
  num_steps = 10000
  solve_type = NEWTON
[]

[Outputs]
  csv = true
[]
```
It takes 10,000 steps and produces a csv via a PPS (all info he provided on the mailing list). Run that several times (we still do not know how he ran his input files) and make sure he sees all time steps in it (there should be 10,002 - 10K normals steps + IC + header). Then start modifying it, i.e. adding more post-processors, etc. until the error appears. Then, he sends that input file back to us, to see if we can reproduce it.

Otherwise, everything else is just blind guessing...

**Comment by dschwen** [comment]
I think @permcody nailed it. With e 1e-11 timestep that absoluteFuzzyEqual will not properly distinguish your timesteps!

**Comment by mangerij** [comment]
But my first file was the only one above e-11 ! I will check early morning.
Thanks guys

**Comment by friedmud** [comment]
@mangerij If that's the case - it's definitely time to rethink your units!  That tiny timestep is going to cause all kinds of problems...

**Comment by mangerij** [comment]
Hmm, so that did it. Changing https://github.com/idaholab/moose/blob/devel/framework/src/utils/FormattedTable.C#L137-L142

` if (back_it == _data.rend() || !MooseUtils::absoluteFuzzyEqual(time, back_it->first))`

to

` if (back_it == _data.rend() || !MooseUtils::absoluteFuzzyEqual(time, back_it->first, 1e-14))`

gives the all time steps in the files that had them missing (just tested on dt > 1e-14 now). 

Why is 1e-12 the default tolerance? What is dtmin default? Is there a problem to just introduce this change? I'm seeing that 1e-15 to 1e-16 might be the absolute lower bounds on my time step (we're planning to look at dynamics in the THz frequency regime).

I'm using a small time step due to units on my mobility constant 1e23. In the equations, I have a time derivative kernel that is 1/mobility * d (orderparameter)/dt, and I don't have convergence issues. I'm not sure I want to adjust the units or use artificial scaling. I use a consistent _and real_ units (attoamperes, nanonewtons, nanometers, _seconds_, ...) system in Ferret and it hasn't failed me so far. But that's a different discussion I think.

**Comment by amjokisaari** [comment]
@mangerij , there's no problem with using real units, I use real units in my simulations too.  I just choose the units to that everything is near the order of unity.  Attojoules (or eV), nanometers, _microseconds_... 

I think it's dangerous to use numbers that are quite huge or quite tiny because the framework designers build in tolerances to avoid things like division by zero, also to avoid issues like floating point errors.

**Comment by mangerij** [comment]
Well, I've already carefully picked everything near order unity for
convergence reasons. And you know this from our Nanoscale paper, we solved
everything in scaled time because we never cared about the dynamics. But
that PDE can be applied to real systems if the mobility is known (which it
is known for a very few select materials).

So I keep the same units as the previous work, but now instead of taking
time step of dt ~ 1, I'm taking dt' = G*dt where G is large and dt is small
-- and it leads to no convergence issues that I see. If I switch to
microseconds then the near order unity becomes violated for much of the
coefficients and I immediately get convergence issues.

**Comment by amjokisaari** [comment]
interesting, you're saying that you are dealing with some seriously multiscale physics in the one simulation in this case?

**Comment by dschwen** [comment]
A tolerance of 1e-11 seems quite large for double precision numbers. If I understand [this article](https://en.wikibooks.org/wiki/Floating_Point/Epsilon) correctly it should be more of the order of 1e-15
