### ISSUE TITLE
Misleading error message in Kernel without variable parameter

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11192]
## Rationale
Adding a kernel block without a a`variable` parameter, like

```
[Kernels]
  [./dt]
    type = TimeDerivative
  [../]
[]
```

results in

```
*** ERROR ***
dt: Cannot add Kernel for variable , it is not a nonlinear variable!
```

Note there is an empty string inserted into that error message. I suggest for empty variable names this gets changes to.

```
*** ERROR ***
dt: No variable specified for Kernel to act on!
```

## Description

PR #11039 most likely resulted in this new output. The error message is unintuitive and most likely unintentional (empty string insertion).

## Impact

More user friendly error messages.

**Comment by andrsd** [comment]
It is more complicated.

* we want to make a check that Kernels are set on `NonlinearVariables` (if you set them on AuxVariables, we want to error out) - that was the purpose of #11039
* so we make this check in `FEProblemBase`, because we know what kind of object we are building. However the requiredness check is done in `_nl->addKernel` which is done after the check-variable-kind. We had to do it before, because otherwise it tripped another non-sensical error message (IIRC).
* we could probably improve the logic like so:
    ```
    if (parameters.hasParam<NonlinearVariableName>("variable"))
    {
      if (!_nl->hasVariable(parameters.get<NonlinearVariableName>("variable")))
        mooseError(name,
                   ": Cannot add Kernel for variable ",
                   parameters.get<NonlinearVariableName>("variable"),
                   ", it is not a nonlinear variable!");
    }
    ```
    So, if the variable was not specified, we continue with `_nl->addKernel` and that should trip the requiredness check to error out. 

Note that if the variable was not specified, there should not be an empty string in the input parameters. Now, an evil user could do: ``` variable = ''``` 😈

**Comment by jwpeterson** [comment]
I agree that the error message is misleading when the user forgets to specify a variable. 

We can definitely improve the error message as @andrsd suggested, but to be consistent, one should also do that for AuxKernels, BCs, NodalKernels, ScalarKernels, ... I also do not want to duplicate too much of the error checking logic that is already in `InputParameters::checkParams()` but that is currently called called later in Factory::create()...

**Comment by dschwen** [comment]
You could make a wrapper for the error message that just spits out a different string when the variable name is empty. That would take care of `variable = ''` as well. And an empty string is never a valid variable name, right?
