### ISSUE TITLE
Vectorpostprocessor enhancements

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#11300]
## Rationale

Several low-risk enhancements to the VectorPostprocessor (VPP) system have been requested and designed to enable more flexibility in how that system manages vectors and writes output. These enhancements will enable new capabilities such as online processing of entire time histories and reduced output in certain circumstances.

## Description

The Mastodon developers have requested the ability to maintain stateful VectorPostprocessors (VPP), where they can assume that values written in a previous invocation are still there on a subsequent invocation. The idea is that developers can accumulate data over time in these vectors. Currently for optimization reasons, MOOSE doesn't preserve these values at all. 

During design discussions, several capabilities were identified that need to be accounted for in a new design. We are proposing the addition of several new flags:

```
// Managing state of the VPP vectors
bool preserve_current;  // Preserves the current value in a vector. (default: false)
bool keep_old; // This would keep previous vector values in an old vector. (default: true)

// Managing output
bool contains_complete_history; // Would tell MOOSE not to output individual VPP files (default: false)
```

## Design ##
The design is that iff one of the state vectors is true, we can be efficient with how MOOSE manages storage as time is advanced. We can swap back if current doesn't need to be preserved, or if current needs to be preserved but we don't need old, we just leave things alone. Only when both Booleans are set to true is a vector copy required. If both vectors are false, we will clear the current vector when state is advanced. 

## Output ##
Currently the output system creates one file per VPP per output time.
```
<filebase>_<vpp name>_<serial number>.csv
```

If `contains_complete_history` is set to `true`, then we will output a single file as follows:
```
<filebase>_<vpp name>.csv
```

## Impact

Tag possible interested parties @cbolisetti, @aeslaughter, @dschwen, @bwspenc, @friedmud

**Comment by permcody** [comment]
Tag @YaqiWang

**Comment by YaqiWang** [comment]
Having a csv file for each time step is nasty. If we know beforehand the size of vector is not changing, creating one single file will be nice. But keep in mind we could have multiple vectors in one postprocessor, each of which is a two-dimensional array in transient (number of entries, number of time steps). Another thing, we do not have to use csv to store vpp, which is fairly restricted. We could use for example, xml. It is desired that the values can be viewed by eyes and easily copied out. I did not use vpp much, I even do not know if we have `getVectorPostprocessorValue`. Just my cents.

**Comment by bwspenc** [comment]
I'm all for the idea of outputting them all to one file, but I agree with the issues pointed out by @YaqiWang: the size of the vectors can change, and there are potentially multiple vectors computed by a VPP.

However, very often, we have the scenario where the size of the vectors doesn't change, and only one of the vectors changes. We wrote a script for the purpose of combining the results for multiple steps, and I'd love to be able to get rid of that.

**Comment by friedmud** [comment]
This is not about writing multiple timesteps to a CSV file.  That's not going to happen - it doesn't fit into CSV and becomes even more difficult to postprocess.  @aeslaughter already has a great set of python utilities to help us read in VPP datasets and postprocess them using Pandas.

This is about VPP's that naturally contain the full time-history of values.  This is something that's not actually supported in the current system - so we want to support it (this is a new use-case of VPPs).  Further, for these types, there is no reason to write separate files for each incremental amount of data.  We can overwrite the same file each time because the full set of data is contained within the VPP itself.

Here's an example of each:

`LineValueSampler`: Will always come out as a separate CSV per timestep because it produces a new full table of values every timestep.  Each column is the samples along the line for different variables.

`PointValueSamplerOverTime`: This theoretical VPP would sample multiple variables at a single point (producing one column for each).  Each timestep it would `push_back()` the current values onto the end of the VPP vectors... so the vectors grow each timestep and all of the data for the VPP is fully contained within the VPP.

In this case we can overwrite the CSV output (by setting `contains_complete_history = true`) because the vectors themselves contain a complete time history.

This second example is completely new - you currently can't do this with VPPs because of the way we handle state and output.  This new Issue will enable it.

**Comment by YaqiWang** [comment]
This `great set of python utilities` needs to be documented asap so that everybody can use and do not reinvent. If I have a 10,000 time steps I potentially will create 10,000 csv files accidentally...

**Comment by permcody** [comment]
Yaqi, Documentation is our top priority outside of our regular commitments. We are working on it.

**Comment by bwspenc** [comment]
@friedmud Thanks for the clarification. That makes sense. I'm also really curious about @aeslaughter's utilities.  Even if they're not documented, where are they?
