### ISSUE TITLE
VPP Parallel Consistency

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#11408]
## Rationale

Currently the only rule for VPP values is that they should be complete on processor 0 so they can be output.  However, if you're trying to use their values on other processors then _something_ needs to be done to make them parallel

## Description

Requirement: All processors shall compute a complete vector to processor 0... no matter what.  They can optionally compute parallel consistent values if it is natural.  If they end up "replicating" the values on all processors they should set `_is_broadcast = true` in their constructors to keep them from being broadcast again.

Consumers of VPP values will call one of three functions:

 - `VectorPostprocessorValue & getProcessorZeroVectorPostprocessorValue()`: if they only need the processor zero value
 - `VectorPostprocessorValue & getBroadcastVectorPostprocessorValue()`: If the full vector is needed on every processor
 - `ScatterVectorPostprocessorValue & getScatterVectorPostprocessorValue()`: If only the PID value is needed on every processor.  This is only valid for VPPs that compute vectors that are `num_procs` in length.

Calling these functions will trigger MOOSE to automatically broadcast/scatter the value from processor 0 to satisfy the needs of the consumers.

A `ScatterVectorPostprocessorValue` is just a `Real`... it will be filled up with the value for that processor.

## Impact

Small: not many people are calling `getVectorPostprocessorValue()` now.  It should be deprecated with this development (defaulting to `getBroadcastPostprocessorValue()` for maximum backwards compatibility).

**Comment by permcody** [comment]
Looks Good! Just two comments: 

- In MOOSE a lot of the "notify MOOSE of something, or declare/get something"-type methods are done with method calls. Instead of having the user directly set an inherited member, should we consider just having a method call (e.g. `declareParallelConsistent()` or `disableBroadcast()`)?

- I'm not completely sold on the name `getPostprocessorZeroVectorPostprocessorValue()`. Zero is used in MOOSE to mean vectors of zeros. I would suggest the term "Master", but we use that in the multiapps system. However, I still like that better than "Zero". Roy often uses "root" in the MPI routines. "RankZero"?

**Comment by friedmud** [comment]
I agree with both of these - I ended up going a slightly different direction for both things.

Look for the PR soon.
