### ISSUE TITLE
Markers segfault when run on displaced mesh

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11430]
## Rationale
Setting `used_displaced_mesh = true` causes Markers to segfault.

## Description
```
frame #2: 0x0000000101e67a3a libmoose-dbg.0.dylib`MooseVariableFE<double>::setNodalValue(this=0x000061c000002880, value=1, idx=0) at MooseVariableFE.C:626
   623 	void
   624 	MooseVariableFE<OutputType>::setNodalValue(Number value, unsigned int idx /* = 0*/)
   625 	{
-> 626 	  _dof_values[idx] = value; // update variable nodal value
   627 	  _has_nodal_value = true;
   628
   629 	  // Update the qp values as well
(lldb)
frame #3: 0x000000010112ac8e libmoose-dbg.0.dylib`Marker::computeMarker(this=0x00006170036c2318) at Marker.C:78
   75  	Marker::computeMarker()
   76  	{
   77  	  int mark = computeElementMarker();
-> 78  	  _field_var.setNodalValue(mark);
   79  	}
   80
   81  	ErrorVector &
```

The segfault occurs when setting the marker value (not when accessing the displaced mesh).

## Impact
Fix broken code

**Comment by permcody** [comment]
I'm going to label this as a task, despite the Impact statement. This is a new capability Markers with Displaced Mesh.

**Comment by dschwen** [comment]
Alternatively I could run it on the undisplaced mesh and explicitly find
the current element on the displaced mesh.

**Comment by dschwen** [comment]
And I would argue that throwing a segfault is always a bug. If no new
capability is added this should at least return a proper error (or the
parameter needs to be suppressed).

**Comment by permcody** [comment]
No, With the way we build out MOOSE, most tickets would be marked as
defects. There are so many new ways in which the software wasn't intended
or designed to function. From a SQA perspective, we'd have a defined scope
that the software would be expected to function . A defect would be more
along the lines of something within the scope that doesn't work correctly,
something that would require current users to fix in order to have
confidence in their answers.
