### ISSUE TITLE
Block-restricted quadrature rules

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11449]
## Rationale

There are needs to apply a higher order quadrature rule for certain regions and low order rules elsewhere in a simulation to reduce the computing cost compared with applying the high order rules everywhere. Our special needs is properly treat the control-rod cusping effect. This capability can be useful to other physics.

## Description

Currently, MOOSE maintains only one global quadrature rule. There are some implications on supporting this but *eventually the framework could be enhanced to accommodate this* as @permcody said.

## Impact
New capability.

**Comment by bwspenc** [comment]
This would be useful for XFEM in the regions near the crack tip where we have higher order interpolation functions. We're already sometimes breaking the mesh out into a separate block for this region just to cut down on the cost of having extra variables associate with that everywhere, so that would be an immediate win for us if we could also only do the higher order quadrature there. @jiangwen84

**Comment by friedmud** [comment]
This really should be possible.  Someone just needs to be inspired to do it
:-)

**Comment by lindsayad** [comment]
I believe this was closed by #15470
