### ISSUE TITLE
close aux system vectors in checkExceptionAndStopSolve

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11525]
## Rationale
The Aux system is not properly closed in some cases when an Exception is thrown during the solve.

## Description
@gardnerru has an input that fails with a  PETSc error complaining about solution vectors not being closed after an exception is thrown in `ComputeMultipleInelasticStress::updateQpState()`. I have tracked this down in a the debugger to a call to `_aux->update();` in `FEProblemBase::outputStep(EXEC_FAIL)`. Breaking on exceptions I was able to follow the trajectory of the exception through `checkExceptionAndStopSolve` where the nonlinear system vectors are all properly closed but the Auxiliary system remains open.

I have a small fix for this, which makes Russel's input deal with the exception gracefully and continue with the run

## Impact

Fix broken simulations.

**Comment by permcody** [comment]
Simple fix inside of a branch that only gets executed when there's an exception - good!

The problem is that this is ripe for a future regression. We are constantly going through the framework and refactoring close methods since they can be very expensive in a parallel simulation. Can we cook up a test case that will fail without this close? We have ExceptionKernel (https://github.com/idaholab/moose/blob/devel/test/src/kernels/ExceptionKernel.C) that we use to trigger these kinds of difficult to track down exception cases. Perhaps an ExceptionAuxKernel will do the trick?
