### ISSUE TITLE
PorousFlow: automatically add correct version of materials as necessary

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#11716]
## Rationale

Due to the lumping and full upwinding in the PorousFlow module, some kernels need materials with the properties evaluated at the quadrature points (we call these qp materials), some need materials evaluated using nodal variables (we call these nodal materials), and some need both.

Each PorousFlow material has a parameter `at_nodes` which we set to `true` if it is a nodal material, and `false` if it is a qp material. This means that a typical input file contains several duplicate material entries, with the only difference being the value of the `at_nodes` parameter.

Eg:

````
[Materials]
  [./temperature]
    type = PorousFlowTemperature
    at_nodes = true
  [../]
  [./temperature_qp]
    type = PorousFlowTemperature
    at_nodes = false
  [../]
  [./ppss]
    type = PorousFlow2PhasePS
    at_nodes = true
    phase0_porepressure = ppwater
    phase1_saturation = sgas
    capillary_pressure = pc
  [../]
  [./ppss_qp]
    type = PorousFlow2PhasePS
    at_nodes = false
    phase0_porepressure = ppwater
    phase1_saturation = sgas
    capillary_pressure = pc
  [../]
  [./porosity]
    type = PorousFlowPorosityConst
    at_nodes = true
    porosity = 0.1
  [../]
  [./permeability]
    type = PorousFlowPermeabilityConst
    at_nodes = false
    permeability = '1e-15 0 0 0 1e-15 0 0 0 1e-15'
  [../]
  [./relperm_water]
    type = PorousFlowRelativePermeabilityCorey
    at_nodes = true
    n = 1
    phase = 0
  [../]
  [./relperm_gas]
    type = PorousFlowRelativePermeabilityCorey
    at_nodes = true
    n = 1
    phase = 1
  [../]
[]
````
etc.

This can be confusing for our users. How do they know whether they need a qp material, a nodal material, or both?  At the moment, it is probably by trial and error, looking through the source code, using one of the tests as a guide etc.

We have some actions available to help, but the user still has to specify a number of materials that the actions don't set up.

We know which materials each kernel requires, so we should be able to add the correct versions as required, making it easier for users.

## Description

The action system could be used to add the correct version (qp or nodal) of each material, so that each material only needs to be added once. The above input would then look like
````
[Materials]
  [./temperature]
    type = PorousFlowTemperature
  [../]
  [./ppss]
    type = PorousFlow2PhasePS
    phase0_porepressure = ppwater
    phase1_saturation = sgas
    capillary_pressure = pc
  [../]
  [./porosity]
    type = PorousFlowPorosityConst
    porosity = 0.1
  [../]
  [./permeability]
    type = PorousFlowPermeabilityConst
    permeability = '1e-15 0 0 0 1e-15 0 0 0 1e-15'
  [../]
  [./relperm_water]
    type = PorousFlowRelativePermeabilityCorey
    n = 1
    phase = 0
  [../]
  [./relperm_gas]
    type = PorousFlowRelativePermeabilityCorey
    n = 1
    phase = 1
  [../]
[]
````

## Impact

Make it easier for users to set up PorousFlow simulations

**Comment by cpgr** [comment]
So, I have had a go at this, and it is not too hard to do using the action system and @WilkAndy's PorousFlow dependency resolver. I have an action that checks which type of material the added kernels need, and sets the `at_nodes` parameter in each material accordingly.

However, I'm not sure how best to implement it. I could do either of these:

1. Keep the normal `Materials` syntax and change the `at_nodes` parameter before the materials are added by the `AddMaterialAction`.
2. Have a custom PorousFlow materials section like the fluid properties module:
```
[Modules]
  [PorousFlow]
    [Materials]
      ...
```

I started off with 1 so that the input files wouldn't need as much change, but I think that I am leaning towards 2 now as it keeps all of this away from the other parts of MOOSE, and makes the action stuff a bit easier to follow (as it can all be self-contained).

Do you have any thoughts @WilkAndy? Both implementations would be backwards compatible, so all current working input files would still work.

**Comment by WilkAndy** [comment]
I find both the Action system and the PorousFlow dependency resolver quite hard to work with.  Whenever i need to debug an input file i have to step back through lots of code to finally discover the root cause of the problem.  Obviously i'm biased because i only ever see problematic input files, and i suspect most users like the Actions and never have any problems.

Aside: backwards compatibility - cool, but let's change the test input files to the simplest possible form.

**Comment by permcody** [comment]
It's a complicated but extremely flexible design. There are two parameters that you can turn on to help debug `Debug/show_parser=true` and `Debug/show_actions=true`. I'm always open to more idea on how to better provide information or diagnostics when things aren't working as expected. This system needs to be easier to use because we envision more and more use of it as time moves forward. For many types of simulations you don't want to create thousand line input files. Actions are there to simplify the setup of more complex problems. We have other things up our sleeves that should also help dump out a more normal (developer) looking input file for debugging but that system is still in the works.
