### ISSUE TITLE
Threaded GeneralUserObjects

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#11731]
## Rationale

Bison uses an HEMFluidProperties GeneralUserObject to supply water properties in a Material.  Since GeneralUserObjects are not threaded, only one is available, and this is causing tests to fail when run with --n-threads=2.

## Description

If I comment out the 'break' line in FeProblemBase::addUserObject, I can get the tests to pass threaded.

What's the reason not to create one GeneralUserObject per thread, and what is a reasonable solution?

## Impact

When this is resolved, we'll be one big step closer to having all Bison tests run properly threaded.

**Comment by andrsd** [comment]
RELAP-7 calls `FluidProperties`-derived object from a `Material` and runs threaded with no problems :-)

Now more seriously. The problem can be in `IAPWS95HEMFluidProperties`, which has some member variables, so the methods using those have to be thread safe.  You may need to add a spin lock in them (go look at `DGKernel.C` for an example). This may fix your threading issue.

The reason why there is only 1 instance is that general UOs are not associated to any mesh-like objects (compare with elemental UOs that are associated with elements), so there is no threaded loop like for elemental, side or internal side ones. Also note that any `FluidProperties`-derived objects are __not__ using `execute` (which is the primary design). Our design is that we are adding a special API that can be called from a threaded region, so care must be taken on our side be thread safe.

But, may be we should look into creating `ThreadedGeneralUserObject` so our fluid property lookups are not slowed down by that locking which would occur on every q-point. Also, if each thread would be in a different region, we would be switching back and forth, which is somewhat expensive.

**Comment by jasondhales** [comment]
IAPWS95HEMFluidProperties has as a member variable STR_vu_SBTL95.  STR_vu_SBTL95 works by taking a couple of inputs and computing all outputs based on those stored inputs.  With only one copy and threads, the calculation of outputs gets tangled with other threads resetting the inputs.

I understand that general UOs aren't associated with the mesh and don't have `execute`, but in my case, I need them to be threaded to avoid a shared memory clash.

I'm sure a spin lock would work, but I like `ThreadedGeneralUserObject` much better.

**Comment by andrsd** [comment]
I like the `ThreadedGeneralUserObject` as well, but it is going to take me some time to do. If you want to fix the threading issue right away, you can introduce the spin lock and we can revert it when `ThreadedGeneralUserObject` is done. Your call how you want to proceed.

**Comment by YaqiWang** [comment]
Just a suggestion: possibly derive the UO from ElementUO, then it will be threaded. Just make `execute` empty if not needed. We use GeneralUO quite intensively and it needs to stay unthreaded.

**Comment by permcody** [comment]
That will work, but it's definitely a hack. I'm going to recommend that you
don't do this.

**Comment by jasondhales** [comment]
So, is the solution to create a new `ThreadedGeneralUserObject` and have `FluidProperties` derive from that?

**Comment by permcody** [comment]
Yeah, except I'm not entirely sold on the name. That name implies that there's some sort of threading happening that may somehow speedup your calculation. Honestly, I think I'd prefer just having a new option called `create_threaded_copies = true` or something like that and then we can just handle this on the backend. @andrsd, thoughts?

**Comment by andrsd** [comment]
That's what I was thinking about. I think that inheritance might be more flexible than just a parameter in case we need to do changes, add interfaces, etc. 

I do not insist in the name, it was something I came up with in like 1 minute. If you have a better name, @permcody, let's use it.

**Comment by YaqiWang** [comment]
Another way is to separate the offending interface into an element UO, which can get the general UO. It may not be bad because that can make the general UO simply provide the evaluation without holding any state.

**Comment by andrsd** [comment]
Ummm, there is no offending interface. There is a state inside a general user object. This state is required for the evaluation inside the `GeneralUserObject`.

Then, the design of FluidProperty is using polymorphism. Kernels/BCs/etc call an API and the instance of the called class will do the right thing based on its type. There is only one child class that has this kind of state. So even if you took the state outside (which is a bad idea violating encapsulation) and changed the API, some other child class would need a different state and you would have to change the API again.  You want to use the OOP principles to work for you. You do not want to fight against them. 

Also, having the elemental UO getting the general UO is a bad idea here. The client objects work with the general UO API, benefiting from polymorphism.  If they worked with the Elemental UO. You would have to either a) switch the whole system to work with elemental UO (and I already said this won't happen, because there is no reason for that), or b) have 2 versions of each client object, one for elemental and one for general UO. Again, we are not doing this, because there is a simple and clean solution (which I described above) that will a) fix the problem, b) does not require any change in the user code.

**Comment by jasondhales** [comment]
I'll opt to wait for the new threaded general UO (whatever it is called) rather than going the spin lock route.

Thanks, @andrsd, for putting this on your to-do list.
