### ISSUE TITLE
DiscreteNucleation body force kernel for non-conserved order parameters

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11941]
## Rationale

The DiscreteNucleation system was primarily designed for nucleation on conserved order parameter fields through local modification of the free energy (to drive nucleation) using the `DiscreteNucleationMaterial`.  To use the system for nucleation in a grain growth simulation the free energy contribution is not straight forward to aadd (as the grain growth system uses hard coded free energies in the kernels). Furthermore when using `GrainTracker`s reserved order parameters the nucleus needs to be inserted within a single timestep, as the grain tracker will remap it to a new order parameter

## Description

Using the data in `DiscreteNucleationMap` a body force kernel will be created that acts on a reserved order parameter and adds a force (rate) of _map(r)/dt_. This should add a value between 0 and 1 (depending on the contents of the `DiscreteNucleationMap` object to teh non-conserved order parameter.

## Impact

Enable discrete nucleation in grain growth models. Tagging @amjokisaari, who needs this.

**Comment by amjokisaari** [comment]
This is great!   

A couple things (a lot of which we discussed, but I'm writing it here for the record).  

1) The reserved order parameter is remapped and it leaves a "halo" where it's not remapped by GrainTracker.  You mentioned maybe doing the reserved order parameter as an auxiliary variable.

2) The DiscreteNucleationData postprocessor is not really documented.  Is it supposed to be giving the number of nucleation events that are initiated in this time step, or the number of nuclei in the map (these are not equal if a non-zero hold time is used)?  In general, I think it could be very helpful to have a postprocessor tell the number of nuclei initiated in each time step.

3) I'm not sure if this is entirely necessary yet, but *what if* we want to hold the nucleus for a finite amount of time?  Currently, setting hold_time > 0 in the inserter definitely doesn't do that.  Actually it acts very badly, so maybe there should be some sort of check or message to the user for this case...

**Comment by dschwen** [comment]
1. I plan to add that. Stay tuned. 
2. This will be documented and I was planning to add a moose enum to chose which data to extract
3. Yeah, hold_time > 0 will do horrible things in conjunction with grain tracker remapping and the body force type kernel. There isn't really a good way to check for this error without adding a whole lot of code though (at the least the kernel would need access to the inserter... which could be obtained through the map.. let me think about this).

**Comment by amjokisaari** [comment]
Unfortunately, the example doesn't work with mesh adaptivity, either.  I tried adapting on bounds and on each order parameter, but I don't think it adapts the mesh soon enough to catch the change in the order parameter.  In the Hyrax nucleation algorithm,  I had to make it adapt the mesh BEFORE the nucleus was inserted into the nodal variable field... I wonder if something similar needs to happen here, or work with hold time.. ?

**Comment by dschwen** [comment]
Adaptivity is run at the end of a timestep. This will be tough to schedule correctly so that adaptivity, insertion, and GrainTracker run in the right order.

**Comment by amjokisaari** [comment]
Yeah, I understand.

My report that it didn't work with adaptivity on each of the order parameters was premature... didn't set the marker to combo, oops.  (It does not work when just adapting on bounds.) The method seems to work with adaptivity, but there definitely appears to be a resolution issue when adding in a new nucleus - the order parameter value can run far from what it's supposed to be (like -0.2 to 2.4).  It appears to self-correct with the next time steps, but it's not optimal.

**Comment by dschwen** [comment]
We'll figure something out. Adding GrainTracker to the mix complicates things. Let's talk with @permcody in the near future and brainstorm.

**Comment by amjokisaari** [comment]
Sounds good.  I'm going to continue with the problem development using it as it is and we'll polish it as we go.

**Comment by amjokisaari** [comment]
This is definitely moving forward!  Two things that I have run into now is:

1) Ideally, we would want to immediately set the order parameter value for an existing grain = 0 (or whatever the value is indicating out of that grain) when a new grain nucleates within it.  However, I don't know if that's challenging to code or not.  A nucleus very likely will span multiple grains (e.g., on a grain boundary).

2) Following from 1) and also its own idea, the time independent nucleation kernel should have a way to specify what I want to force the order parameter value to (not just 0 or 1).  For example, it is beneficial for me to set it to, e.g., 2 in the grain growth simulation because that forces the other order parameters to disappear faster and stabilize the nucleus.  Also, as @dschwen said, other models may have the order parameter change between different values, not just 0 and 1.

3) In my model, the new grain can bisect an old grain, cutting it in half and giving one of the new bisected pieces a new ID.  Unfortunately that means it gets assigned a new property (using something inherited from GrainDataTracker) because of the new ID.  Is there currently a way that specifies heritage of the new grain and its properties?  Tagging @permcody

**Comment by dschwen** [comment]
I think everything discussed here regarding the nucleation system can now be done. Closing. Please open a targeted ticket if issues remain.
