### ISSUE TITLE
Add MOOSE_DIR to moosedocs instructions

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#11948]
## Rationale
Incorrect (incomplete) instructions for:
http://mooseframework.org/moose/utilities/MooseDocs/setup.html

## Description
When using stork.sh to create an app, and then following these instructions:
  http://mooseframework.org/moose/utilities/MooseDocs/setup.html
The documentation system does not work

## Impact
None

**Comment by aeslaughter** [comment]
The real problem is that the moosedocs.py scripts assumes a few locations for MOOSE_DIR, so depending on what version of this file was copied MOOSE_DIR may or may not be required. 

The actual solution is to add a moosedocs.py script to the stork application. 

I will work on improving the documentation for the config file.

**Comment by lcarasik** [comment]
Thank you!

**Comment by milljm** [comment]
@lcarasik apologies on the non-response from me. I did not receive a notification that you left a comment.
