### ISSUE TITLE
Build team for RDG enhancements

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#12118]
## Description

RDG offers the possibility of modelling advection without the excessive artificial numerical diffusion present in current implementations within MOOSE.   Development of RDG within MOOSE will focus on framework enhancements to make RDG easier, enhancing the current RDG module, implementing RDG in the PorousFlow module, and potentially other enhancements depending on the interests of the team.  We plan to start on October 1 and finish by Christmas, including code, tests, doco and examples.

This issue is just a convenient place for people to register their interest to be part of the team.  It will be closed when we start the work.

## What to do

If you are interested in being involved in any capacity, please add your github handle below.

People who want to code C++ are welcome (of course!) both on the framework side, and on the physics module side, but just as important are people who can contribute to documentation and tests.  Tests could be code comparisons, comparisons with analytic solutions, as well as full-blown real-life examples.  The amount of time you donate is up to you.

**Comment by WilkAndy** [comment]
Including @permcody , @yidongxiainl , @andrsd , @joshuahansel , @mrodb , @rpodgorney

**Comment by cpgr** [comment]
I probably won't have much time to help until November, but let me know if there is anything I can help with

**Comment by andrsd** [comment]
Here is some insight on how we do things in the rDG module (by no means comprehensible - I will add to this as needed):

### BCs

There are 2 pieces of code that work together. An `IntegratedBC`-derived class and an `BoundaryFluxBase`-derived user object. The user object currently provides 2 pure virtuals; `getFlux` and `getJacobian`.  The BC class calls either one from corresponding `computeQp{Residual|Jacobian}`. On the first call the flux gets computed and stored in a cache, so that it is not recomputed every time in case we deal with vector-values flux (the module shows an example on a scalar equation).

There is a limitation on this design: If you need some extra values for compute the flux, the only way is to pass it as a part of you solution vector - it is the 3rd parameter in `getFlux`, `getJacobian`. I think I want to try to change this design, so that the flux is actually computed as a Material. We would provide a base class that would create the material properties for storing the flux and jacobian and would call some virtual method that people would have to implement. This should allow people to bring pretty much any value they needed in the flux computation.

### Internal Side Fluxes

The same design idea as for BCs, except we pass 2 solution vectors into `getFlux` and `getJacobian`. And instead of `IntegratedBC` we get the flux from `DGKernel`. The same idea with caching to avoid recomputing the flux over and over.  Originally this was not possible to do in another way, because we were missing `InterfaceMaterial`. That's currently being in progress (I am helping with that) and I hope it will be done by the end of the month. We would use the same idea I described for BCs.  

The downside of the general user object approach (besides the limited access to variable values) is that we have to take care of threading. Like when one DGKernel is on a different element/side pair and the other DGKernel needs fluxes. So there is some locking behind the scenes. The Material approach should fix that. Also, there is some weird interplay with execute_on. If you get it wrong (and most people will for the first time), the code fails with errors that values are not cached.

### 2 loop problem

This is the biggest problem with rDG. In multi-D, there has to be 2 sweeps through the mesh. This is currently solved with `ElementLoopUserObject` which is a `GeneralUserObject` and will do the extra loop and will cache the values for the loop forming the residual. I personally do not like the solution. I need to think about how to do this in a better way. I have ideas, but they all require a lot of MOOSE internal coding, so for the time being, I think we would stick with this approach. This is just a heads-up so you guys know that something major might and probably will have to change in future and it will have big impact on input files.

**Comment by YaqiWang** [comment]
I think the 2 loop problem possibly can be solved by deriving a new FEProblem. The new FEProblem can also hold new data that can be used by rDG bcs, etc.

**Comment by rpodgorney** [comment]
I won't be working on the coding per se, but I will gladly prepare some tests and help with documentation.


Have we decided where to house rDG?  Should it be its own module, or should we package it under porous_flow?

Robert Podgorney, PhD, PG
Computational Geosciences Group
Idaho National Laboratory

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: robert.podgorney@inl.gov<mailto:robert.podgorney@inl.gov>



________________________________

**Comment by andrsd** [comment]
> I think the 2 loop problem possibly can be solved by deriving a new FEProblem. The new FEProblem can also hold new data that can be used by rDG bcs, etc.

Yes, that's one of the designs I was exploring, but did not get far enough because of other work. I will certainly try that again.

**Comment by andrsd** [comment]
> Have we decided where to house rDG? Should it be its own module, or should we package it under porous_flow?

There is already rDG module in MOOSE. Your `porous_flow` specific classes should be in `porous_flow` module. We just need to make `rdg` module a dependency of `porous_flow`  module.

**Comment by yidongxiainl** [comment]
Hey guys, while you are discussing the coding plan, I'll leave a note on some further in-depth questions. First, will we be able to do mixed 2D/3D simulations with constant monomial (i.e. cell-averaged solution)? In rDG for CFD, we do not care about this feature as no mixed 2D/3D is needed. But for subsurface, this is a much needed feature for representing fractures easily. Recall from previous talk, I think we were not able to do it, because the degrees of freedom are defined within each element. Second, I observed some issue when doing tracer test with rDG earlier this year, in a case that permeability differs hugely between fractured planes and the surrounding rock matrix. The simulation converges, but not to the expected right solution. I think this is a more advanced thing to be discussed with Andy later on.

Sorry I was not responding to much in this practice and I was overly occupied by other project deliverables and milestones. But I'll put more effort to communicate with you guys as time approaches to the end of September.

**Comment by WilkAndy** [comment]
By the way, i'm on holidays for much of the remainder of September.  So if i don't respond here it's not because i'm not keen!

**Comment by andrsd** [comment]
@WilkAndy The Jacobian stores only entries w.r.t. the variables that are part of the flux vector. We currently build a map from the variable number to the component number and use that to index into the Jacobian matrix. It is not the most user-friendly code, but I think the base class can provide some API to make this easier.

**Comment by philippschaedle** [comment]
@WilkAndy Thanks for putting this together, I am looking forward to this effort. I am quite busy during October but happy to work on tests and real live examples afterwards. I could also do some coding on the physical side if that makes sense. 


@yidongxiainl re to your incorrect results. Have you been successful solving the fracture transport issue? I was working on the same thing and so far could not get correct results.

**Comment by WilkAndy** [comment]
Thansk @philippschaedle .  We look forward to your input in Nov and Dec.  I think i might be doing mostly testing + doco too :-)

**Comment by andrsd** [comment]
> My feeling is that implementing the Flux+Jacobian in a Material is a good start.

`InterfaceMaterial` is not ready yet, so if you want to jump into coding, you will have to use the user-object approach.  We talked about this yesterday and, what we plan on doing is to add the material approach as an alternative when all the needed things are in place. Then, migrate onto it.  We already have an ongoing effort to implement 2-phase flow with rDG and switching to the material approach would throw a monkey wrench into that. So we want to finish that first and make sure it works.  And unfortunately, we (or at least I) have other things to work on which have much higher priority :-(

The major problem with the material approach is that we are currently unable to resolve material dependencies on internal edges - I think there is an issue opened for it. I am talking about a case where one material would use the current and neighbor values to compute some other material property which would be then picked up by another material.

> 2\. why i don't see any reconstruction in the current rDG module?

It is there. The base class is `SlopeReconstructionBase` and 2 child classes `SlopeReconstructionOneD` and `SlopeReconstructionMultiD`. It is just that the test is not using that - probably for simplicity.

> 3\. I will need implicit

Implicit is definitely possible. There is not a test for it really.

Also, keep in mind that the module is quite crude right now, so there will be rough edges to deal with.

**Comment by permcody** [comment]
It's been quite awhile since @yidongxiainl originally implemented parts of that module and several new features have been added to MOOSE since that time. Notably the "Actually Explicit" capability and "RelationshipManagers". I can't remember if Yidong's implementation required a wider stencil of information or not. Do we need just one element neighbor's information for each element calculation or more? If just one for now (which I think is all we need) is there a potential that the stencil may expand for different types of problems in the future? Also, it seems like Yidong was reiniting neighboring elements so that he could get information off from them in a single pass. I remember we talked about a caching system at some point but that'll all play into how we go about deciding how to handle the 2 pass system (if that's what we end up doing or not). 

I'd like to see if @friedmud or @rwcarlsen have any interesting ideas here.

**Comment by yidongxiainl** [comment]
> Hi everyone,
> 
> I'd like to get started on this, and am wondering what our first task(s) should be. My feeling is that implementing the Flux+Jacobian in a Material is a good start. I'm less concerned about the 2-loop problem and the mixed-dimensional problem, because i just want to see something working. If this rDG doesn't work for some reason for PorousFlow then i'm not super excited to work on optimising (2-loop) or generalising (mixed-dim).
> 
> I don't know anything much about rDG, so have some questions.
> 
> 1. Are we planning to just do P0P1, as advocated by Yidong in https://link.springer.com/article/10.1007/s00603-016-0951-y ?  Or is our approach going to be more general?

Yes, P0P1 is nothing but second-order, cell-centered finite volume method here.

> 2. Is P0P1 equivalent to constant-monomial + TVD ?  This is suggested by https://www.sciencedirect.com/science/article/pii/S0045793009001030 .  Is that why i don't see any reconstruction in the current rDG module?

There is reconstruction base kernel for providing the data structures needed, but not implementing of specific variables at the level of rDG module. Last year Rich ordered the P0P1 implementation of the multi-dimensional Navier-Stokes equations be moved out of navies_stokes module and back in-house. So at this moment you did not get a chance to see a good example.

But for 1-D, in the rDG module, I implemented TVD for scalar transport equation. There is test case.

> 3. The current single test in rDG uses explicit time integration (http://mooseframework.org/modules/rdg/index.html).  Why?   I will need implicit.

For a pure convective transport, there is no need to have implicit, thought it also works. For porous flow and heat transport, of course we do implicit. The only additional thing for implicit is to calculate the Jacobians. 

> 4. My equations are not just the advection equation, and are more along the lines of https://www.sciencedirect.com/science/article/pii/S0045793017301536 .   That is, something like
>    0 = dM/dt + grad(F).  Here M is a nonlinear function of Variables, and F is a nonlinear function of Variables and their gradients: nonlinear and coupled advection and diffusion.  What's our proposal for solving such an equation?  Some Variables be constant-monomial, and others linear-Lagrange, and construct the gradients of the constant-monomial using...?

For P0P1, when we calculate Jacobians, we always only consider the P0 variables, i.e. constant-monomial. Here I really am tired of saying constant-monomial, as it was not part of my CFD training. In CFD language, it is just cell-average variable.

> 
> Can you experienced people answer these questions and can we try to design some tasks (github issues?) on which we can work?

**Comment by joshuahansel** [comment]
Is P0P1 equivalent to constant-monomial + TVD ?

To clarify earlier responses to this question, I believe in general “P0P1” does not imply TVD; TVD is an independent property of the scheme, determined by the numerical flux approximation and limitation during the reconstruction. “P0P1” should only tell you that the solution is constant-monomial reconstructed to linear.

-Josh

**Comment by yidongxiainl** [comment]
> Is P0P1 equivalent to constant-monomial + TVD ? To clarify earlier responses to this question, I believe in general “P0P1” does not imply TVD; TVD is an independent property of the scheme, determined by the numerical flux approximation and limitation during the reconstruction. “P0P1” should only tell you that the solution is constant-monomial reconstructed to linear.
> […](#)

No, P0P1 is not equivalent to constant-monomial + TVD. I'd like to confirm Joshua's understanding. A TVD scheme only exists for 1D, or 2D and 3D structured orthogonal grids in each direction. For generic unstructured grids in 2D and 3D, TVD does not exist. Note that we do not have to satisfy TVD in multi-dimensional unstructured grids.

**Comment by WilkAndy** [comment]
I don't want to side-track this issue, but perhaps unstructured-grid TVD is available, as in:

https://dl.acm.org/citation.cfm?id=1027300

Tell me what you think, ie, educate me!

**Comment by WilkAndy** [comment]
So far no one has suggested tasks.  I think my first task will be to create some doco explaining to myself how RDG P0P1 works in gory detail, since it seems we're going to focus on P0P1.

**Comment by yidongxiainl** [comment]
Andy, I know that is Kuzmin’s work. His method is kind of Flux Corrected Transport, and uses a larger stencil, but not compact stencil. In my earlier explanation, I would add that no TVD is possible with compact stencil in multi-D unstructured grids.

**Comment by yidongxiainl** [comment]
> I don't want to side-track this issue, but perhaps unstructured-grid TVD is available, as in:
> 
> https://dl.acm.org/citation.cfm?id=1027300
> 
> Tell me what you think, ie, educate me!

@WilkAndy Kuzmin's all works are based on FEM-FCT (Flux Corrected Transport), including the paper you mentioned. They are belong to node-based FEM. Rich was once attempting to get FEM-FCT into MOOSE, which never actually happened due to many limitation of data structure back then. I have no idea if today it is still an option @joshuahansel Nevertheless, in this context we are talking about cell-centered scheme.

@andrsd Is it possible Andy could have access to Bighorn repository? The best way for him to familiarize how P0P1 works in multi-D is Bighorn, where I implemented the multi-D Euler equations (i.e. the Navier-Stokes equations neglecting the viscous terms).

Meantime, I think I can send @WilkAndy a Bighorn documentation for him to learn P0P1 in detail.

**Comment by yidongxiainl** [comment]
[xia2016bighorn.pdf](https://github.com/idaholab/moose/files/2440636/xia2016bighorn.pdf)

@WilkAndy The Bighorn report is an 'unlimited release' document. So I feel Ok to attach it here for your use. Please feel free to raise questions regarding the report.

**Comment by WilkAndy** [comment]
Aha, thanks for the comments re Kuzmin's FCT, Yidong.

Great bighorn documentation - thanks for that (i've only skimmed it so far).

**Comment by hsheldon** [comment]
Happy to help when it comes to testing

**Comment by joshuahansel** [comment]
Is there a paper which describes the FCT method that you're referring to? Is it the one you linked to above?:
[https://www.sciencedirect.com/science/article/pii/S0021999104000221](url)

I'm a bit uncertain about your description of examining the residual - are you referring to the nonlinear residual? I'm not sure what you could do with the residual alone, since that will just tell you how close you are to solving the nonlinear system. I believe you need to the operators decomposed from the solution to compute the anti-diffusive fluxes.

**Comment by joshuahansel** [comment]
I've attached an FCT presentation I gave a few years ago:
[presentation.pdf](https://github.com/idaholab/moose/files/2501872/presentation.pdf)

I did it for scalar radiation transport, and Kuzmin's work was my basis. The main difference is that we had high-order diffusion (entropy viscosity) instead of no artificial diffusion for the high-order scheme. If you're trying to do something different than this algorithm, then I am unfamiliar with it.

**Comment by WilkAndy** [comment]
I'm shifting the Kuzmin stuff to #12370 as it's a diversion from the RDG.

**Comment by WilkAndy** [comment]
Closing this issue: I have built Kuzmin-Turek flux-limiting TVD advection into PorousFlow, and this is almost identical to RDG(P0P1) except it operates using nodal information rather than cell-centered information, so is more suitable in PorousFlow.
