### ISSUE TITLE
Don't trim output test option

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#12167]
## Rationale

We have some tests that require parsing large output, searching for regexp matches. If the output containing the regexp gets trimmed, then the test will fail.

## Description

The SON format tests produce over 7 MB of console output each. If new syntax is added, then we're liable to start trimming areas where regex's are being sought.

## Impact

Having a `dont_trim_output` test spec option would allow such tests in a robust fashion. @milljm

**Comment by YaqiWang** [comment]
I remember I once required such a capability for a different purpose of showing the detailed outputs of failing tests. But got rejected. Not sure if there is an issue hanging around though.

**Comment by permcody** [comment]
The problem is that we have to be careful. The reason we trim by default is when people leave in debugging statements. We've accidentally generated hundreds of gigabytes of outputs with really simple PRs before just because of debugging outputs. I'm fine adding in a option that might need to turn off trimming for individual tests, but I'm less inclined to turn it off globally. Perhaps you want to be able to turn it off globally when you run locally? I'm open to ideas, let us know your needs.

**Comment by YaqiWang** [comment]
This PR is good to me. I might just need to turn trimming off for few tests when fixing problems hard to be reproduced locally. Never need to turn it off globally.

**Comment by permcody** [comment]
Excellent. I don't see another ticket related to this, so I guess we're good.
