### ISSUE TITLE
GrainTracker incorrectly assigns unique ID when microstructure is complex

### ISSUE THREAD

**Issue by amjokisaari** [idaholab/moose#12236]
The GrainTracker occasionally assigns unique IDs incorrectly to grains when the microstructure is very complex and rapidly evolving (e.g., under nucleation of new grains and shrinking of old grains).  This is problematic because any material property tagged to that uniqueID is now incorrect.  

The two images below illustrate the issue.  The first is before the incorrect uniqueID reassignment, the second is after.  The grain with the changed ID is circled.

![before_reassign](https://user-images.githubusercontent.com/6676372/46376902-7c507400-c654-11e8-8e31-20e17de575e7.png)
![after_reassign](https://user-images.githubusercontent.com/6676372/46376908-7eb2ce00-c654-11e8-9eb5-9557c0163df7.png)

To reproduce this, grab my [MARMOT fork](https://hpcgitlab.inl.gov/jokiandr/marmot) and use the input file in input/GrainTrackerRemapBugEx.i.  The unique ID error occurs at time step 122. It also occurs at step 127 for a different grain in the upper right quadrant of the domain.

tagging @permcody @dschwen

**Comment by permcody** [comment]
OK - the first problem is that each nucleation event is holding for two timesteps so it's creating two grains on top of each other. We need to figure out why and perhaps, how to prevent that from occurring by accident in the future. We'll go from there once we get that problem fixed.

**Comment by amjokisaari** [comment]
We fixed the nucleation problem, but the grain tracker issue is still occurring.  I have pushed a new version of the input file to my MARMOT fork that makes the error show up faster, at time step 47.  Note the hold time in the input file is a negative number so you might want to set it back to zero with the nucleation bugfix.  Here's the pictures before and after the error.  The grain has been split by nuclei forming in the middle of it.  The contour line is for eta = 0.1, and I'm only showing unique IDs up to 10 so you can clearly see the change.

Before the new unique ID:
![before_reassign](https://user-images.githubusercontent.com/6676372/46503037-ef89ef80-c7e6-11e8-9a73-bc1e97f88225.png)
![before_reassign_uniquegr](https://user-images.githubusercontent.com/6676372/46503051-f4e73a00-c7e6-11e8-9618-7090def5fe43.png)


After the new unique ID:
![after_reassign](https://user-images.githubusercontent.com/6676372/46503060-fc0e4800-c7e6-11e8-91ed-11d6ae4e51e2.png)
![after_reassign_uniquegr](https://user-images.githubusercontent.com/6676372/46503062-fe70a200-c7e6-11e8-81fc-ad25cb6be754.png)

**Comment by permcody** [comment]
OK - Great. I can replicate this now. One more thing we'll have to decide on (if anyone cares) is how to fix the visualization of both the var_index and unique_grain fields. Take a look at this screenshot:

![screen shot 2018-10-04 at 4 32 57 pm](https://user-images.githubusercontent.com/3036960/46506902-354cb500-c7f3-11e8-8a67-68b62bcc0934.png)

The weird red outline is occurring because there are two physical grains located in the same space. This occurs because the nucleation is fairly large in comparison to the other grains so the nucleation and the underlying grain are both present. The kernels basically "repair" this in the next time step but that's what causes this artifact. I basically take the largest value and display it which might be the nucleation, or it might be the underlying grain. 

Maybe this doesn't happen in a real simulation?

**Comment by amjokisaari** [comment]
No, this can happen in a "real" simulation as well, though it's definitely
less likely.  I wouldn't say it's high priority to fix (for me?  maybe
there's a very important reason to fix it?) because I look at the bounds
calculation primarily.
