### ISSUE TITLE
Add unit parameter in MooseMesh

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#12281]
## Rationale

Radiation transport typically uses unit of cgs, i.e. centimeter for length in the mesh. This has created issues for us when couple with other physics, which often assume the unit of length is in meter. Currently we have to inform several places including materials, user objects that the mesh is in meter in our code.

## Description

So I am suggesting that we add a `unit` parameter in `MooseMesh`. `MooseMesh` should provide a static member `setDefaultUnit` that applications can use if desired. Other objects can quarry the unit and adjust accordingly. Then users will not have to inform objects the unit of length.

## Impact
More friendly user interface.

**Comment by permcody** [comment]
This is very difficult to implement correctly. I worked on another system that did allow for arbitrary units and it was a whole system in itself to perform conversion. To implement it properly, it propagates through the whole system. Imagine a Material property now that needs to be able to switch between meters and centimeters. Now you have to multiply that property by a conversion factor, but now the time stepper needs an adjustment too because it was expecting units per second, not per millisecond. Another conversion factor multiplication.

How do you expect this to work in the general case? 

It might be reasonable to allow units to be reported, but do we really want to allow them to just be set? They will rarely work correctly throughout the system automatically.

**Comment by YaqiWang** [comment]
Theoretically speaking, any source of data including mesh should carry information of the data unit. Then during the construction time, data can be synchronized. It sounds to me that mesh should be the place we anchor the unit of length. In the input, user can give either `1` or `1s`, `InputParameters` can have something like `addUnitParameter<MooseEnum>("end_time", "1year", "bla" )`, which will do the unit conversion and syntax check. I can see this will be a huge pain. I propose this because it is already a pain to me...

**Comment by YaqiWang** [comment]
BTW, it is not only a pain to developer like me, which I have to enable accepting control parameters from user to do unit conversion, but also to users. They need to add all the parameters in the input to make sure all consistent. I basically need one single place to get the unit. Options are mesh, FEProblem, Executioner, Action, etc.

**Comment by friedmud** [comment]
Closing this in favor of #12293
