### ISSUE TITLE
GhostAux

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#12298]
## Rationale

We need an AuxKernel that can show which elements are ghosted for a particular PID.

## Description

This should use the ghosting functors to figure out which elements are ghosted.

It should allow you to specify either Algebraic or Geometric - and use the correct set of ghosting functors.

## Impact

None: New Capability

**Comment by permcody** [comment]
This is already in. Look in the test app.

**Comment by permcody** [comment]
I added a bunch of tests that use this.

**Comment by permcody** [comment]
This would have to work with DistributedMesh to be useful for displaying Geometric RelationshipManagers. In MOOSE we don’t add Geometric at all in ReplicatedMesh mode. My version handles that. You probably missed this because you looked in the framework. I couldn’t really think of a good reason to make this a framework capability. We can chat about it tomorrow.

**Comment by GiudGiud** [comment]
This is already in the framework
https://mooseframework.inl.gov/source/auxkernels/GhostingAux.html
