### ISSUE TITLE
Richards module excav.ex01 test un-reliable on falcon

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#12503]
## Rationale

```
test:excav.ex01:   NOTE: All node and element ids are reported as global ids.
test:excav.ex01: 
test:excav.ex01: Sideset Distribution Factors:
test:excav.ex01: Comparing only the final step (step 3 on first, step 3 on second) on each database.
test:excav.ex01: 
test:excav.ex01:   --------- Time step 3, 6.0000000e+06 ~ 6.0000000e+06, rel diff:  0.00000e+00 ---------
test:excav.ex01: Global variables:
test:excav.ex01:    flux_out    rel diff:  1.8482021e+06 ~  1.8869535e+06 = 2.05365e-02 (FAILED)
test:excav.ex01:    mass_bal    rel diff:  1.9623270e-05 ~  1.9421510e-05 = 1.02817e-02 (FAILED)
test:excav.ex01: Nodal variables:
test:excav.ex01: 
test:excav.ex01: exodiff: Files are different
test:excav.ex01: 
test:excav.ex01:  -steps last
test:excav.ex01: ################################################################################
test:excav.ex01: Tester failed, reason: EXODIFF
test:excav.ex01: 
test:excav.ex01 ............................................................................. FAILED (EXODIFF)
```

## Description
The error can be reproduced on falcon with the following modules

```
Currently Loaded Modules:
  1) use.moose   2) GCC/4.9.2   3) cppunit/1.12.1-GCC-4.9.2   4) tbb/4.3.0.090   5) MVAPICH2/2.0.1-GCC-4.9.2   6) moose-dev-gcc_petsc-3.8.3
``` 

## Impact
Unknown

**Comment by WilkAndy** [comment]
Thanks for the notification, @aeslaughter .  I'll look into it soon

**Comment by aeslaughter** [comment]
@WilkAndy Thanks, I tried to fix these few but they are beyond my skills.

**Comment by WilkAndy** [comment]
I'm about to board a plane, so can't fix this now.  This is a note for future me:

The key quantity is the mass_bal, which is the mass-balance error.  It doesn't really matter about the exo-diff here because the point is that it is small.  Probably a better thing would be to use a CSV diff on mass_bal with an absolute tolerance of 1E-4 (anything smaller than 1E-4 is treated as zero).  Then we can ensure "zero" mass balance error.  Regarding the flux_out - it is not too strange that this differs a little bit.  ... Oh, final call!
