### ISSUE TITLE
Get rid of `store_stress_old` parameter in `ComputeStressBase`

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#12574]
## Rationale

It looks like the `store_stress_old` parameter in `ComputeStressBase.C` isn't used anywhere. I'm guessing it was used for something that was removed in the past, and this simply got missed in the cleanup.

## Description

I just stumbled across the `store_stress_old` parameter in `ComputeStressBase.C`, and was puzzled about why it existed (because the material models that need the old stress already call `getMaterialPropertyOld()` to get the old stress. It looks like that parameter and the member variable that it is stored in are not actually used anywhere.

## Impact

Should be a minor change, although there may be input files that set that parameter (even though it apparently doesn't do anything).

**Comment by bwspenc** [comment]
@WilkAndy From the commit history, it looks like you may know something about this.

**Comment by bwspenc** [comment]
@sveerara Do you know anything about this?

**Comment by sveerara** [comment]
@bwspenc, I had added this parameter to store old and older stresses for Rayleigh damping calculation. Since these old stress states were not required for most tensor mechanics problems, I added this flag to declare the old and older stress properties only when required. 

https://github.com/idaholab/moose/pull/8719 removes the need for declaring old and older material properties. So, this parameter is no longer required. I think only the dynamics tests in moose and mastodon contain this parameter. I can remove this parameter and correct the input files.

**Comment by bwspenc** [comment]
Update: It looks like there is a similar `store_stress_older` parameter in SolidMechanics that should also be removed.  @sveerara I've already almost finished this, so I'll just take care of it.

**Comment by sveerara** [comment]
Thanks, @bwspenc . Yes, the parameter in solid mechanics is also not required now.

**Comment by WilkAndy** [comment]
i don't remember much about this store_stress_old, @bwspenc .   i think you should go ahead and remove it and see if any tests fail.
