### ISSUE TITLE
AD versions of TensorMechanics kernels and materials

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12650]
## Rationale

Start working first on stress divergence kernels using the AD system and gradually expand to stain and stress calculation materials.

## Description

Using automatic differentiation will hopefully improve Jacobians for large strain problems and mechanics coupled to other physics.

## Impact

Improved convergence.

**Comment by aeslaughter** [comment]
@dschwen @permcody 

I am working on getting SQA documentation setup for the tensor mechanics module, in a bunch of tests you reference "design = jacobian_definition.md". This isn't adequate since this page doesn't discuss the objects being tested. @dschwen can you update these to something more relevant please.

**Comment by aeslaughter** [comment]
Here are the main files I need to be updated:

- test/tests/ad_elastic/tests
- test/tests/ad_plastic/tests
- test/tests/ad_simple_linear/tests
- test/tests/ad_linear_elasticity/tests

The other files I was able to update because they have non-AD versions in the specification that I used to provide the associated markdown files.

**Comment by aeslaughter** [comment]
Another key feature as the page should exist within the framework/doc or tensor_mechanics/doc; stuff in the modules/doc directory cannot be used because the documentation for each module should be stand-alone. 

I also don't want to move this file to the framework directory, since the framework docs should be as minimal as possible. They should only contain syntax and object docs, because someone creating an app should not be required to include all of our supplemental documentation about the systems. Their app may have limited syntax and not require objects to be coded thus information about Jacobians, AD, etc. etc. is not needed.

**Comment by dschwen** [comment]
Will do.

**Comment by permcody** [comment]
Closed by several merged PRs listed above.
