### ISSUE TITLE
Implement non-boost defined stochastic distributions  

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#12688]
## Rationale

We have some distributions implemented by boost library in stochastic_tools module. To use those distributions, users have to compile libmesh with boost library because it is not by default. It will be nice to provide those distributions with moose's own implementation without boost library. 

## Description
We will rename all the existing distributions which are defined by boost with a prefix 'BOOST' and implement their non-boost version. We will also move some existing distributions implemented in Grizzly to moose. 

## Impact
Rename some input tests and add some more.

**Comment by andrsd** [comment]
Idea: could you check for `HAVE_BOOST` from libmesh and use preprocessor? That way if you have boost, you use it and if not, you use your non-boost implementation... Would make your input files more stable.

**Comment by jiangwen84** [comment]
I think it is a good idea. @bwspenc and @aeslaughter , do you have any suggestion for this?

**Comment by bwspenc** [comment]
I would suggest we go a step farther and remove all of the BOOST distributions once we get the last missing one (lognormal) implemented.

**Comment by bwspenc** [comment]
I'm going to take the liberty of expanding the scope of this a bit to include two things:
1) Deprecate and remove the existing Boost distributions.
2) Re-name the existing Distribution classes to remove 'Distribution' from the end of their names. They're already aliased that way, and this will make deprecating the Boost distributions easier (because I can point to the replacement classes to them, rather than the ones with 'Distribution' in the name.
