### ISSUE TITLE
MeshGenerator not compatible with displacements

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#12712]
## Rationale

If I run the attached file, 'app -i debug_generated_mesh.txt --mesh-only', I get a seg fault in opt, a failed assert in debug.  If I comment out the displacements line, it runs.

## Description

See above.

## Impact

This error prevents us from using MeshGenerators in solid mechanics problems.

[debug_generated_mesh.txt](https://github.com/idaholab/moose/files/2765685/debug_generated_mesh.txt)

**Comment by permcody** [comment]
@leorachapuis, @friedmud - This is a very simple test, any ideas as to what's going on here?

**Comment by friedmud** [comment]
Definitely odd.  I can't think of any reason for this - I'll look into it.

**Comment by friedmud** [comment]
There shouldn't be a "second time through" though... the displaced mesh is
made from a _copy_ of the original mesh.... right?

**Comment by friedmud** [comment]
BTW: If you're actively trying to work around this issue - you can just
generate the mesh using --mesh-only and read it back in (until we get this
fixed).

**Comment by gambka** [comment]
For meshes that are composed of 2D elements within a 3D space --mesh-only does not appear to work.  Consider a mesh consisting of two squares, one defined in the x-y plane and one parallel to x-y plane but offset in the z direction by some value. The only way I've been able to output meshes of this type is to have the following in my input file:

```
[Outputs]
  [./out]
     type = Exodus 
     output_dimension = 3
  [../]
[]
```
If I don't and look at the results, only the square in the x-y plane will be displayed (e.g., in paraview).  Therefore, when using the --mesh-only option I get a single square in the x-y plane even when my MeshGenerator is creating the mesh with the two squares offset from one another.  It appears that the --mesh-only options looks at the element dimension of the mesh rather than the spatial dimension of the mesh and compresses everything into 2D (the x-y plane) because they are 2D elements.

**Comment by jasondhales** [comment]
@friedmud, I'm looking to send a recipe for PCMI analysis to a user, and so I don't want to tell him to run it with --mesh-only and then edit the input file and read in the mesh.  I'm trying to keep it as simple as possible.

I expected the displaced mesh to be made from a copy, but that isn't what it looked like was happening.

**Comment by permcody** [comment]
@jasondhales - Do you happen to know if this problem is isolated to the new MeshGenerator system? I'm working on a few things concerning that system (Kyle's ticket) and it might just be due to some of the assumptions made in the new system. I may be able to fix...

**Comment by jasondhales** [comment]
Yes, I think it is isolated to the MeshGenerator system.

**Comment by friedmud** [comment]
Sorry I still haven't had time to look at this.  It should be
straightforward to track down.  I'll try to get to it tomorrow.

Derek

**Comment by friedmud** [comment]
I'm working on this this morning

**Comment by friedmud** [comment]
Ok - wow.

I guess I didn't know how DisplacedMesh building was happening... but it turns out that we just completely create another mesh (we don't copy the existing one).

You can see this here: https://github.com/idaholab/moose/blob/next/framework/src/actions/SetupMeshAction.C#L219

Luckily - this should be a pretty easy fix for the MeshGenerator system... it's built for creating copies of the mesh... but I will probably need to structure things slightly differently.

@permcody let's have a quick conversation about this this morning...
