### ISSUE TITLE
Speed up AD calculation for undisplaced problems

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#13027]
## Rationale

All our base `ADKernel*` objects perform operations with AD versions of `JxW`, `coord`, and `grad_test`. For undisplaced problems this produces unnecessary `DualNumber` and `NumberArray` operations.

## Description

For the undisplaced problems:
- Worst case: performing operations between two numbers with zero derivative vectors: basically 2*`AD_MAX_DOFS_PER_ELEM` unnecessary operations (in the case of multiplication)
- Bad case: performing an operation between one number with zero derivatives and another with non-zero derivatives: `AD_MAX_DOFS_PER_ELEM` unnecessary operations in the case of multiplication (product rule)

## Impact

By using `Real` and `RealVectorValue` versions of the above members, we would speed up calculations for undisplaced problems.

**Comment by tophmatthews** [comment]
I'm hitting `AD_MAX_DOFS_PER_ELEM` on a simple 3D tensor mechanics problem. Is there a way to set this rather than hard coding it in `DualReal.h`?

**Comment by lindsayad** [comment]
The issue is that with the current derivative storage structure, the size of the derivative array must be known at compile time; we cannot make it an input file option. There are a couple of ways to make this more flexible:

1. Create a MOOSE configure, where the size of the derivative array is a configure option
2. Change the derivative storage structure. There are a few reasons for doing this:
    1. Applications like Rattlesnake that uses lots of field variables
    2. Applications like Relap-7 that uses lots of global variables
    3. 3D applications!

However, changing the derivative storage structure will almost certainly make AD slower. So there may very well be reason to do both 1. and 2.; a MOOSE configure could also allow the user to select what kind of AD storage they want. For traditional finite element simulations in > 3D, the user would probably want to select our current derivative storage structure. They even may want to select it in 3D too, but with a larger derivative storage size. But then applications like Rattlesnake that want to make use of AD would almost certainly want to select a sparse derivative storage structure.

**Comment by lindsayad** [comment]
Ping @friedmud and @permcody for a return to the `configure` question

**Comment by permcody** [comment]
I'm tired of pushing back on configure. If we really want it, we should be able to add it without changing our build process much.

As a start we could do something like adding it into the update_libmesh script so that people don't even know it's there. It's unlikely that people would need to run it any more often than they build libmesh so that would be a good way to get started. We could also make it so that when you run make without running configure that it prints out a friendly message telling users exactly what to do. I imagine that the first version of this will be really short, fast, and simple. Of course it might take off after that.
