### ISSUE TITLE
Improve Coupleables to allow couple any solution vector through tagging

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#13029]
## Rationale

Currently this parameter is in `TransientInterface`. What is does is really to choose which solution vector to couple with.

## Description

Moving this into `Coupleable` is the right thing to do. It also allows an extension to this parameter to a parameter like in `TagVectorAux`, `params.addParam<std::string>("vector_tag", ...)`. `vector_tag` can default to `current`, it can be set to `old` to reproduce the capability provided by `implicit`. Users can thus set this parameter to couple variables in whatever solution vector. This will also simplify the interfaces in `Coupleable` by removing all calls with `VectorTag` in their names. During the transition, we can mark `implicit` as deprecated. This capability will support the flexible executioner, which could have an iteration.

I will take a stab on this because while working on upgrading Rattlesnake executioners with tagging, it would be too hacky without this.

## Impact
Internal interface change. Will require updating applications to remove the deprecation messages.

**Comment by YaqiWang** [comment]
@friedmud @lindsayad @fdkong @permcody Do you have any comments?

**Comment by fdkong** [comment]
I could be wrong on this.  Let explain a bit on this.

`MatTag` and `VectorTag` in `Coupleable.C ` was originally designed  to visualize the residual vectors and the matrices  to make sure that the tagging system is running right. It can be used for other purposes for example replacing the save-in capability.  But we can not couple the residual vectors back to `Kernels` and `AuxKernels` because the residual vectors are changing  during the function evaluations. 

I understand what Yaqi needs is able to couple arbitrary  solution vectors to `Kernels`, `Aukernels` and whatever.  The big difference here is that the solution vectors is frozen during the function evaluations, and that is why PETSc is alway locking the solution vector in the callback.  Tagged vectors are residual vectors that are supposed to be accumulated  during the function evaluation, and then you could not couple them. 

This right solution might be to add another system that manages the extra solution vectors, and couples the extra solution vectors back to `Kernel` or `AuxKernles`.   But it is not a small change, and we need a right design before we add a big chunk of the code.  I would like to let @friedmud  and @permcody make the design decision.

**Comment by YaqiWang** [comment]
Editing my comments.

**Comment by YaqiWang** [comment]
Realized moving this parameter is not right because `Coupleable`, `ScalarCoupleable` and `NeighborCoupleable` are all using it. On the other hand, adding parameters `nonlinear_vector_tag` is possible. Since `TransientInterface` is hosting `implicit` parameter, we can just let it also host `nonlinear_vector_tag`. All three coupleables need to be updated. I will update the title of this issue later.

**Comment by YaqiWang** [comment]
I have almost done the implementation for this but realized that for doing my iteration I can just use the current tagging system. What I need to solve is Ax=b, where A is equal to A1 + A2. I basically solve the problem iteratively as A1 * x^(n) + A2 * x^(n-1) = b. So I can just tag kernels for A2 to a different residual vector which will be lagged by one iteration. I do still need a tagged vector, but this vector is used to save A2 * x^(n-1) but not x^(n-1) as I initially thought. I will send in a PR for demonstrating this iterative solve and close this issue. I will push in my implementation on this issue in case somebody is interested on coupling tagged vectors. Thanks.
