### ISSUE TITLE
MooseDocs doesn't render HTML inside of .md files

### ISSUE THREAD

**Issue by dylanjm** [idaholab/moose#13219]
## Bug Description

HTML does not render inside of dropdown menu when trying to alter aesthetic of menu.

![image](https://user-images.githubusercontent.com/15963026/56149785-8c81ce00-5f6a-11e9-8f13-27acf2e03dc0.png)

## Steps to Reproduce

Added `<font color="white">blank</font>` to `.md` file that gets rendered as a dropdown menu for the Bison website. 

## Impact

Prevents desired formatting of dropdown menu.

**Comment by dschwen** [comment]
The 90ies are calling, they want their HTML tag back!

Seriously, `<font>` has been deprecated since the advent of CSS and is actually not part of the HTML5 standard. Im pretty sure HTML tags get sanitized from md because they are not easily translatable into other representations, such as LaTeX. Your best bet is adding a custom CSS to your app docs.

**Comment by dylanjm** [comment]
@dschwen I did see that `<font>` was deprecated. I also tried `<p style="color:white">blank</p>` as another option. Results were the same. I'll look into adding custom CSS as a separate file.

**Comment by permcody** [comment]
Closing issue.
