### ISSUE TITLE
Add NearestPointLayeredSideAverage

### ISSUE THREAD

**Issue by jortensi** [idaholab/moose#13252]
To support MAMMOTH/Rattlesnake modeling needs per meeting held 4/17/19.

**Comment by permcody** [comment]
Tag @fdkong

**Comment by fdkong** [comment]
I will be here soon. The conservative transfer is almost done.

@jortensi  Do you mind send me some toy input files to demonstrate the requirements. It definitely speedups the development. @vincentlaboure  added one simple example for the conservative transfer that actually help me a lot!

I am asking because I want to focus on you guys' requirements at this point even though a lot of stuffs can be added to the transfer system.

**Comment by fdkong** [comment]
Resolved at https://github.com/idaholab/moose/pull/13060
