### ISSUE TITLE
403 Forbidden when clicked "Getting Started"

### ISSUE THREAD

**Issue by ccppoo** [idaholab/moose#13275]
While I was Looking around, (https://mooseframework.inl.gov/old/)

![cap2](https://user-images.githubusercontent.com/46418312/56548258-9c2c9280-65ba-11e9-8e78-220ee702120e.PNG)
![cap1](https://user-images.githubusercontent.com/46418312/56548261-9e8eec80-65ba-11e9-9bdb-ffd1986607aa.PNG)

403 error pops out.

**Comment by permcody** [comment]
We don't have plans to maintain the "old" site. Some of those pages have been removed since they haven't been updated in a long time and would yield outdated information. The reason the old site still exists is because not every piece of information has been transferred to the new site. Thanks for the report but we don't plan to fix this.
