### ISSUE TITLE
Wall time based default checkpoint writing

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#13562]
## Reason

It would be very handy to have checkpoint files written automatically for all simulations based on elapsed wall time. This is somewhat analogous to the "autosave" feature found in many desktop applications. Users that encounter failures would be able to restart their simulations from a previous checkpoint file and continue running.

## Design

The design for this system is straightforward. We already have "interval" parameter that writes out files every <n> time steps. This Boolean triggers whether or not the checkpoint object actually dumps a file or not. I would propose that we have a new "time-based" option that would trigger the existing Boolean so that it would be written at a reasonable interval (5 or perhaps even 10 mins of time). 

The other part of the design would require that we change the `CommonOutputAction` to setup checkpoint format by default. Additionally, we'd have to make sure that we don't collide with explicit checkpoint formats added by the user (or TestHarness).

## Impact

Moderate: New feature with high impact on usability

**Comment by pbehne** [comment]
I am working on this issue. Some of the fine details about creating and executing actions in MOOSE are still fuzzy to me, but I think I get the gist.

From [Checkpoint.C](https://github.com/idaholab/moose/blob/devel/framework/src/outputs/Checkpoint.C#L115-L128), it seems like there is already capability to spontaneously write a checkpoint when a certain signal is received (i.e., `kill -s USR1 <yourPIDhere>`). This occurs in the `Checkpoint::shouldOutput` method. I am thinking that we should add the logic for a wall timed-based checkpoint writing capability in this same method. To this end, I would propose adding an attribute to the `Checkpoint` class and using that to track the time that the last checkpoint was written.

My question is (because I am fuzzy on some things), how often is `Checkpoint::shouldOutput` called? My assumption is probably at least once per time step. Furthermore, it doesn't make sense to write a checkpoint in the middle of solving a time step, correct? If I run a problem that takes 1 hour to solve a time step, and I request a checkpoint every 30 minutes, I should only get a checkpoint every hour?

**Comment by permcody** [comment]
let's chat

**Comment by pbehne** [comment]
This issue can be closed now.

**Comment by lindsayad** [comment]
Closed by #26588
