### ISSUE TITLE
Add an electromagnetics physics module in MOOSE

### ISSUE THREAD

**Issue by chaitanyaBhave26** [idaholab/moose#13744]
**Description of the enhancement or error report**

Electromagnetics involves solving the Maxwell equations to calculate the electric or magnetic fields in the system. We want to create an electromagnetic physics module in MOOSE, and add documentation for solving the general Poisson equation for electrostatics problems using existing kernels in MOOSE.

**Rationale for the enhancement or error report**

The YellowJacket app in MOOSE is being developed to predict corrosion using phase field models. Calculating the electrical energy contribution to the system requires solving the Poisson equation. Currently I am solving it using ADMatDiffusion and MaskedBodyForce kernels with 2 material properties.

It would be great if we had a dedicated physics module that could do this for us, with a standardized documentation so that future users don’t have to figure this out all over again. The Poisson equation does not solve full electromagnetics problems, but it is a simplified version useful for a lot of electrostatics problems. In the future it might be possible to add kernels for more complex equations while still having the Poisson solver for simpler problems.

**Identified impact**

Add the electromagnetics module as a new physics module in MOOSE.

**Comment by cticenhour** [comment]
Thanks for adding this issue. I am actually in the process of creating this module (where electrostatic and electromagnetic field solutions will be possible). Currently we're in the process of open-sourcing the code so that it can be released publicly. Stay tuned!

**Comment by tonkmr** [comment]
@cticenhour we knew that there were others working on this, but we thought it would be good to create the module now and add the first set of tutorials using existing MOOSE capability. There are various MOOSE users doing this kind of work right now, so we should try to unify them around a single module as soon as possible. Then, when your open-sourcing process is complete, you can add the powerful new objects you have been working on. Another option would be for you to create the empty module now (so that you have the bragging rights), and then we add our tutorial. Later, you add your new objects when they are ready.

**Comment by dschwen** [comment]
I seriously question the value of creating an empty module just to add a
tutorial that will use classes from framework and from other modules (even
if it is for "bragging rights").
Duplicating objects just to rename them (e.g. ADMatDiffusion -> Poisson or
whatever) seems like a repeat of mistakes from the past (e.g. BodyForce ->
HeatSource). And if those objects reside in other modules (MaskedBodyForce)
you cannot even duplicate the objects through inheritance, you'd actually
have to duplicate code or add another module dependency. :-/
Daniel

**Comment by tonkmr** [comment]
Our tutorial doesn't create any new objects, it just uses existing objects. However, I do think that some of them reside in the phase field module. The tutorial shows how to solve simple electrostatic problems by solving the Poisson equation. So, I have two questions:
First, where would something like that go if it can't go in a module due to dependencies on other modules? Should it go in the combined module? 
Second, @cticenhour do you have an expected timeline until your work would be ready to put in a module? Do currently duplicate objects that already exist in other modules?

**Comment by cticenhour** [comment]
MOOSE does have a `tutorials` directory where extended examples of MOOSE usage can be placed, in its own contained "mini-app". @aeslaughter can chime in more about how a future second tutorial could be put together in a similar way. Considering this is using existing objects and pieces from phase field, that is where I would place it for now. 

To answer your second question, I am aiming for early fall semester (so 2-3 months). I am currently in the process of creating support documents (user and theory manuals) and fleshing out missing bits of code while the paperwork is being processed at the laboratory. This timeline is being driven by my PhD dissertation research milestones, so I have a particular urgency to get this out in the wild. :-) 

I do my best not to duplicate any objects that exist in other parts of MOOSE, and plan to do another code review to verify that I've not missed something prior to release.
