### ISSUE TITLE
Executing post-processor output on TIMESTEP_BEGIN gives end-of-time-step time value

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#14006]
## Bug Description
When a post-processor value is output on `TIMESTEP_BEGIN`, it does not use the beginning-of-time-step time value as expected; it uses the end-of-time-step time value.

## Steps to Reproduce
[execute_on_begin.txt](https://github.com/idaholab/moose/files/3584833/execute_on_begin.txt)

## Impact
Wrong output.

**Comment by joshuahansel** [comment]
@aeslaughter

**Comment by permcody** [comment]
In your input file you are telling the output system to run on TIMESTEP_BEGIN, but you aren't providing any "execute_on" value in your Postprocessor. By default that means your Postprocessor is going to run on TIMESTEP_END. So I would expect your post processor to have the previous time step's "end" value when outputting on the beginning of the next tilmestep. Is that what you are seeing?

**Comment by permcody** [comment]
Oh, I see your comment in the input file. I disagree with your expectation. I believe the current value is correct. What you need to do to obtain the results you want is do this instead:

```
[Postprocessors]
   ...
  execute_on = 'initial tilmestep_begin'
[]

[Outputs]
   ...
   execute_on = 'initial tilmestep_begin'
[]
```

See if that works and let me know if you agree.

**Comment by joshuahansel** [comment]
It's true that your suggestion does produce the desired output. However, I still don't understand the output for when the post-processor executes on `TIMESTEP_END` and output is on `TIMESTEP_BEGIN`:

- Step 1 (t0 -> t1), `TIMESTEP_BEGIN`: PP has not yet been executed (so it has value 0). Output executes - it should output (t0, 0). I see (t1, 0).
- Step 1 (t0 -> t1), `TIMESTEP_END`: PP executes at t1 and now has value PP(t1).
- Step 2 (t1 -> t2), `TIMESTEP_BEGIN`: Output executes - it should output (t1, PP(t1)). I see (t2, PP(t1)).

Does the actual output still not seem wrong to you? Have I made a mistake in my sequence above? Note, this is not a high priority to me anymore - I originally needed it for a test, but I've since worked around the issue. I originally ran into this because I was trying to test that a control was setting a parameter. Controls execute on `TIMESTEP_BEGIN`, after PPs. I had a PP that examined the value set by the control, so the test execution order was a bit tricky.

**Comment by permcody** [comment]
> Step 1 (t0 -> t1), TIMESTEP_BEGIN: PP has not yet been executed (so it has value 0). Output executes - it should output (t0, 0). I see (t1, 0).

Unless you also have "initial" in there you won't get output at time zero so that should explain why you see t1, not t0.

> Step 1 (t0 -> t1), TIMESTEP_END: PP executes at t1 and now has value PP(t1).

I think your confusion is the t0 -> t1. You are either on timestep 0 (initial) or timestep 1, you are not really ever between them. So since we already talked about the initial timestep and why you aren't seeing output, you are on t1 at this point, and yes your PP should have PP(t1) computed.

Step 2 (t1 -> t2), TIMESTEP_BEGIN: Output executes - it should output (t1, PP(t1)). I see (t2, PP(t1)).

Now we are on time step 2. We are going to begin this step by outputting (before the solve or anything else). Since we didn't execute the PP at the beginning, we will output PP(t1). We should see t2, PP(t1).

**Comment by YaqiWang** [comment]
The output line https://github.com/idaholab/moose/blob/next/framework/src/executioners/PicardSolve.C#L362 happens inside time stepper at here: https://github.com/idaholab/moose/blob/next/framework/src/executioners/Transient.C#L415, which is after https://github.com/idaholab/moose/blob/next/framework/src/executioners/Transient.C#L409 in `Transient`. When timestepper takes a step, its first thing is evaluate dt and set the system time to `_time_old + _dt`, where `_time_old` should be equal to `_time` after a time step is accepted in the previous time step. System time is basically a global thing for all objects.

On the other hand, I do not quite understand the purpose of having outputs on both timestep_begin and timestep_end, since they are using the same system time. I remembered that when outputting on nonlinear or linear, we manipulate the time temporarily for outputs. My opinion is to do the same time maniputation for timestep_begin.

**Comment by permcody** [comment]
No matter where you output you are going to find instances where somebody wants something slightly different. The way the time stepping is setup is to give you opportunities to do things before and after the current solve (but all within the same system time).

**Comment by joshuahansel** [comment]
My confusion with this came from the fact that both `TIMESTEP_BEGIN` and `TIMESTEP_END` for a given time step use the same time (the end-of-time-step time). I think the takeaway for outputting post-processors is this: use the same execute-on for PPs and the output.

I'd be ok with closing this issue if you want. Basically the issue remaining is just possible future confusion (but probably not common because it is rare to output on `TIMESTEP_BEGIN`).

**Comment by permcody** [comment]
Yeah the system is working as designed within the current constraints of the implementation. Things are always going to be a little bit odd until we have true cross-system dependency resolution working, which is a long ways off.
