### ISSUE TITLE
Allow using different quadrature order on different blocks

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#14055]
## Reason

In some problems, we need a much higher integration quadrature integration order in a given part of the problem. However, using that high order everywhere is wasteful.

## Design

Create a `Quadrature` block that can set various quadrature orders on various subdomains.

## Impact

Enhance the capabilities of doing high-order/low-order calculations.

**Comment by rwcarlsen** [comment]
I've started working on this FYI.

**Comment by YaqiWang** [comment]
I am having a crazy idea: how about let kernels, materials, etc. to decide what quadrature order they need? Basically we will need a virtual function in the base class, default to do nothing, derived object like kernels, materials can override the function, vote for desired quadrature order. This function will be called at the beginning of evaluations on elements, sides. The code will chose the maximum order for assembly, variables initialization. The only penalty is to loop through object to find the maximum order, but I guess its cost should be fairly small. In this way, we can avoid quadrature specification completely in the input by users.

**Comment by YaqiWang** [comment]
@friedmud what do you think of this idea? This will make the quadrature order transparent to users. It will be up to developer to choose the order. We can give users power to override the choice if desired.

**Comment by friedmud** [comment]
@YaqiWang So - I thought about this a bit more... andusing virtual functions won't quite work...

The reason why is that we can't have the quadrature order change in the middle of the solve.  Why?  Because of stateful boundary conditions.  They are stored at quadrature points and those quadrature points need to stay where they are.

However: I do think this could be done in `validParams()`... setting a "desired" quadrature order parameter that MOOSE could take into account.

**Comment by YaqiWang** [comment]
Oh, right. I did not think of the stateful material properties. Note though that: it will work for steady-state problems. `validParams()` way should work. We can gather desired order for all element and side objects on all blocks and side sets and use the maximum to generate the quadratures. Current `Executioner/Quadrature/order` will be a global users' option if users want to try higher orders.

**Comment by rwcarlsen** [comment]
I'm looking at picking this back up.  per-kernel/object won't work - because we initialize materials once for all kernels.  So if someone tried to have two separate kernels with different quadrature rules - they would require their own separate material initializations - which doesn't work with the current code structure.  And it rewinds performance progress gained via special quadrature rules by requiring more material reinits.  I think I'm going to go ahead and just stick with the per-block one-shot custom quadrature specification if everyone is okay with that for now.

**Comment by YaqiWang** [comment]
I am thinking the other options because let users setting the quadrature in the input is a burden to them.  Our users are often not FEM experts and cannot relate quadrature with the code outputs of their quantities of interest. We need to have block-wise quadrature rules, the question is just how do we control this. We possibly can have an input parameter to override whatever we have by default.

What I was proposing is to have a virtual function in `BlockRestrictable` like `requiredQuadratureOrder`, which will be called by MOOSE ONLY when the setup time once. It returns by default `donotCare`. In this way, the developers can control the default quadrature rule and no user intervention is required.

**Comment by rwcarlsen** [comment]
But this doesn't work in general - because then users could set inconsistent differing quadrature orders for different objects (e.g. kernels) on the same block.  Per-object quadrature specification just won't work.  It only makes sense to allow per-block quadrature specification.

**Comment by vincentlaboure** [comment]
I think @YaqiWang is suggesting to take the maximum order that all the objects return on a given block. Then this block is assigned that order.

**Comment by rwcarlsen** [comment]
Ah - I see.  For @YaqiWang's case - would it be enough for objects to just call createQRules in their constructor?  That seems easier to me here.  No need to introduce an object-specific parameter for users to set a block-specific parameter.  And you would still get your automatic quadrature case.  We might need to add a helper function that only reinitializes quadrature rules if the passed in order is higher than the current order (or something similar).  I think this would be a better approach for now.  And as this functionality begins to get more use we can consider adding appropriate convenience parameters/interfaces later when we understand needs better.

**Comment by YaqiWang** [comment]
That works for me. Just want a way for developers to change the default order.

**Comment by rwcarlsen** [comment]
Great! I'll see if I can get something working within the next week or so.
