### ISSUE TITLE
AnnularMeshGenerator is difficult to nail perfectly symmetric meshes

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#14115]
## Reason
When making an annular mesh, the `tmax` and `tmin` parameters can be used to set the angular sweep of the annulus. Unfortunately, `tmax` and `tmin` accept radians, which makes it impossible to get perfect right angles due to factors of Pi. Really, this should be in degrees, or even fractions of Pi, or even have options to do half or quarter meshes.

## Design
Easiest would be to convert to degrees in the input.

## Impact
Allow AnnularMeshGenerator is make perfectly symmetric meshes that can be reflected.

**Comment by tophmatthews** [comment]
I think you put `AnnularMesh` in originally @WilkAndy, and it's only being used in porous_flow. Do you have a way you tackle this issue? Even looking at your tutorials, ie `modules/porous_flow/examples/tutorial/00.i`:
```
  [annular]
    type = AnnularMeshGenerator
    nr = 10
    rmin = 1.0
    rmax = 10
    growth_r = 1.4
    nt = 4
    tmin = 0
    tmax = 1.57079632679
  []
```  results in a range of 4.8969e-11 to 10. I'm trying just to replace some cubit meshes in tensor_mechanics, so that is probably close enough, but I would imagine if it went negative (which can happen for certain Pi value cut offs) it'll start making things screwy.

**Comment by WilkAndy** [comment]
I agree that degrees is more sensible.  Perhaps it's rather aggressive, but i think we should simply change the input to degrees.  Can you do this, @tophmatthews ?   If you want to be gentler, we could have a bool or enum that allows the user to choose "degrees" or "radians".

**Comment by tophmatthews** [comment]
Yeah, I would vote just putting it all in degrees. I'll pull something together!

**Comment by tophmatthews** [comment]
Is there anyone else using it but you?

**Comment by WilkAndy** [comment]
I wouldn't be surprised if others are using it.  Having an annular mesh is quite common in porousflow simulations since it represents a scenario where fluids/heat are being injected/extracted from the centre of a 2D slice of rock.   Perhaps a enum is the best approach, but use degrees internally.  Perhaps having the enum to default to "degrees" but, for the next 3 months only, if someone doesn't specify the enum (as will be the case for all current users) then moose issues a warning saying that degrees are being used and the default is now degrees.

**Comment by tophmatthews** [comment]
Actually, I think deprecating `tmin` and `tmax`, and using `dmin` and `dmax` might work the easiest.

**Comment by WilkAndy** [comment]
OK
