### ISSUE TITLE
Make InputParameters able to remove parameters

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#14226]
## Reason
Although it is rare, there are certain cases where the derived objects do not want to have all parameters added in the base objects.

## Design
Currently I am using `suppressParameter` to achieve this goal, which of course is not ideal because the parameter is still hanging around and no way for further derived objects to add the suppressed parameter back again. If we can have a function `removeParameter`, the problem can be solved. This function can stand by itself in `InputParameters` anyway.

## Impact
New capability and should not have any impact.

**Comment by permcody** [comment]
How can removing a parameter not have an impact? If I build a class and add a parameter, and then try to retrieve it. It would be odd for that to break because a derived class removed that parameter. I'm having a difficult time trying to understand the use case. Even suppressing a parameter is a little odd. That function is there for cases where we set the parameter in the derived class. Removing is a little odd. That suggests to me that perhaps the parameter may not belong in the base?

**Comment by YaqiWang** [comment]
You are right. Removing will not possibly work because the base class might rely on those parameters. I was not thinking of this carefully. This is probably an invalid issue. The fact that I cannot add suppressed parameter back again simply means that I should not use the same name. I guess maybe we should move parameters for `FEProblemSolve` and `PicardSolve` in `Executioner` to derived executioners for solving my problem. I am closing this issue. Sorry about this.
