### ISSUE TITLE
MeshGenerators should keep track of "preparedness"

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#14329]
## Reason
The preparedness of the mesh needs to be kept track of while running mesh generators.

UPDATE: I'm adding additional information to this ticket based on our team design discussions. Our overarching goal is to have all MeshGenerators work with an actually distributed mesh (mesh with remotes deleted). More succinctly: Generators should work with as few non-local elements as possible.  However, realistically we need to support some middle ground where mesh generators will work for the majority of people in most cases. 

## Design
Not 100% sure yet.  Either have the Generators keep track of who is giving them the output (and which pointer is that output) or keep track of things during the execution of mesh generators.

It may be the case that MeshGenerators might want to specify both whether they require a prepared mesh to work... and whether or not they impact the preparedness of the mesh.  Not sure yet.

UPDATE: To make mesh generators work with an actually distributed mesh, we will need to keep more information around on the mesh so that elements do not get deleted before a downstream generators has a chance to act. We'd like to support adding RelationshipManagers from Generators so that individual generators can augment the ghosting as needed to work.

Task list including tasks from #15945 

1. [x] `set_isnt_prepared`: this is an API that should be used by generator developers at the end of `generate` if their generator doesn't alternatively call `prepare_for_use` at the end of `generate`. Another way to handle this would be to discourage users from ever calling `prepare_for_use` in `generate` and then we `set_isnt_prepared` post-`generate` in `generateInternal`
3. [ ] `requires_prepared_meshes`: seems like this should be a virtual member returning a boolean on the `MeshGenerator` class. If this is `true`, then in `MeshGenerator::generateInteral`, we should call `prepare_for_use` ahead of calling the derived mesh generator's `generate` method.
4. [ ] Verification checking: It is most straightforward to do verification checking of item 1. In debug mode, we could simply run `prepare_for_use` after `generate` if `is_prepared()` and ensure that nothing changes (can do this in `MeshGenerator::generateInternal`)

## Impact
Minimal - maybe some new functions in MeshGenerators

**Comment by permcody** [comment]
Tagging @lindsayad

**Comment by lindsayad** [comment]
Based on some extensive discussion in Slack, we are going to give `MeshGenerator` developers three options:

1. Advertise a GhostingFunctor up-front like our other `MooseObjects` can, to prevent remote elements that the `MeshGenerator` needs from getting deleted.
2. Do push-pull to get possible deleted elements that the `MeshGenerator` needs to work
3. Even though I believe it's pretty simple to do 1. (and 2. from what I've heard from @friedmud), give the developer to option to say "don't allow any remote element deletion" until all stages of mesh generation are complete. I don't really see this as a resource problem, because we're going to delete the remote elements eventually, so I'm fine with this.

Finally @YaqiWang has asked for a parameter in `MooseMesh` that allows the user in the input file to specify "please don't delete remote elements until all stages of mesh generation are done", because for example they may be executing a `GeneratedMeshGenerator` for just one of 10,000 fuel pins, and so it doesn't make sense to distribute just that single piece of the mesh. I think this is reasonable ask.

**Comment by lindsayad** [comment]
@YaqiWang do you think this belongs in the Griffin milestone or not?

**Comment by friedmud** [comment]
Glad to see some movement on this.  Even if it's not perfect in this iteration... at least it's a start that can be refined as we come across new cases.

**Comment by lindsayad** [comment]
I've removed the "(Distributed Mesh)" part of the title to reflect this issue's consolidation with #15945 which discusses the needs to keep track of the preparedness of the mesh independent of mesh mode. Our most recent preparedness concern was with a replicated mesh provided by @pbalest

**Comment by lindsayad** [comment]
@roystgnr @GiudGiud @loganharbour

**Comment by GiudGiud** [comment]
My take on this

- [ ] Task 1: what Alex has in his PR, a final prepare, only skipped with a boolean
Fix the test failures

- [ ] Task 2: clean up most of the prepare-for-use that are in the generate() and arent needed
Add the set_unprepared calls
Add docs in MG system for preparedness status

- [ ] Task 3: add the devel check to make sure we dont develop bad MGs (eg MGs that un-prepare the mesh, but dont set it as unprepared)

**Comment by GiudGiud** [comment]
I ll take a stab at task 2

**Comment by lindsayad** [comment]
Thanks @GiudGiud !

**Comment by roystgnr** [comment]
https://github.com/libMesh/libmesh/pull/3516 should get us 90% of the way there on task 3, after we add it into an assert to be called post-generate().  The one big thing it doesn't do yet is check whether a point locator has been generated + invalidated + not-cleared.
