### ISSUE TITLE
Allow MultiAppCopyTransfer to transfer multiple variables between systems

### ISSUE THREAD

**Issue by zachmprince** [idaholab/moose#14391]
## Reason
MultiAppCopyTransfer has a very nice API and it would be nice to be able to define multivariable transfers with an input in a single block and when implementing derived classes. This would include adding the ability to transfer array variables.

## Design
The design would be quite simple. `_to_var_name` and `_from_var_name` would now be vectors of variable names. If the inputs are array variables, they would be expanded into the component names. Finally, there would be loop over the number of names presented in the `transfer` member function.

## Impact
This would enhance the capability of variable transfers by reducing number of transfer blocks for multivariable transfers and increasing the usability of array variables.

**Comment by permcody** [comment]
A better design would be to enable all Transfers to handle a vector of variables. Not just a single Transfer. We could start by changing the base parameter and then simply throwing an error inside of Transfers that don't yet support multiple variable lists. @loganharbour recently did something very similar to this when he added the ability to use a single Transfer for multiple directions. All Transfers now have the capability even though only a few implement it.

**Comment by loganharbour** [comment]
Zach just came and talked to me a little about it. Right now, most of the variable transfers inherit from `MultiAppFieldTransfer`, which already has the multi-variable functionality and multi-variable integrity checks + a bunch of content for conservative transfers. 

What do you think about having `MultiAppCopyTransfer` inherit from `MultiAppFieldTransfer`. Then you suppress the two parameters that enable the conservative transfers because they're not needed and get all of the multi-variable integrity checks that come with it.

I think this may be better as not all transfers use variables in the first place.

**Comment by friedmud** [comment]
Sounds good to me.

All Transfers should be "multi-variable" enabled at some point.  It is MUCH more efficient.
