### ISSUE TITLE
shift a specific material property

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#14504]
## Reason

In my case, I only want to shift a specific material property back in time (shift current to old, old to older) instead of all. The current shift() method in MaterialData does not allow for that.

## Design

Another method like
```
void
MaterialPropertyStorage::shiftProperty(const FEProblemBase & fe_problem, unsigned int property_id)
```

## Impact

It adds API.

**Comment by permcody** [comment]
@hugary1995 - I don't think this is the right solution. First, there's not really a good way to call this method from any object in particular. Who would call it, the Executioner, the Problem, a specific object? If you did call it, who would perform the sanity check to ensure that other objects that want to consume an old property are still getting that old property? To be clear, there shouldn't be anything in the stateful store **unless** another object is consuming that property. That's a design feature we put in several years ago. So upon first inspection, I believe that by overriding this behavior, you'd either be doing nothing (because the property wouldn't even be in the map if it's not being consumed) or you'd be directly breaking another object. I don't see how this could work in a robust way as designed here.

**Comment by YaqiWang** [comment]
My understanding is that he does have an object calling `getMaterialPropertyOld(prop_name)`. He will be having a custom `SolveObject` doing a fixed point iteration that iterates on this property if we provide a way to copy the current to old for this material property. The custom `SolveObject` will be calling the copy function. What I was proposing in the email is like this:

1. change `getMaterialPropertyOld` to `getMaterialPropertyOld(const std::string & name, const std::string & tag = "")`;
2. `MaterialData` will maintain a map from tag to property ID. When `tag` argument is given, `MaterialData` will push the ID for the property into the map;
3. `MaterialData` will provide a function like `copyTaggedPropertyToOld(const std::string & tag)`, which will copy the current to old of all tagged properties;
4. `FEProblemBase` provide a wrapper function for calling `copyTaggedPropertyToOld(const std::string & tag)`;
5. The solve object has a function like `std::string fixedPointTag()`, which can be used by the object calling `getMaterialPropertyOld`. Of course, the object needs to get the solve object possibly through a custom executioner consuming that solve object.
6. The solve object can call the function in `FEProblemBase` to update the property at every fixed point iteration.

**Comment by hugary1995** [comment]
@permcody I see your reply on the mailing list. I am very glad to hear that we are getting a more flexible material store. Since it sounds like the material system will become much more powerful after the overhaul, and it is likely to be an overkill to what I am asking for here. Therefore, I wonder if I could do something meanwhile to get my work done. I can keep it in my branch instead of merging it -- I just need some guidance...

@YaqiWang 's proposal is what I had in mind. I only need to call the shift method in my Problem derived from FEProblemBase through a wrapper. Regarding point 5, the object calling getMaterialPropertyOld can maintain an optional parameter as the tag, so that I don't need to pass through the solve object to the consumer.

In terms of sanity check: I think it will be fine, as I only expect to be an internal functionality that is only callable from within FEProblemBase. It should only work for tagged material properties, therefore it should not break other objects in principal.

**Comment by hugary1995** [comment]
The bottom line is: I can wait. I can achieve effectively the same thing using MultiApp, in a much more complicated way.

**Comment by hugary1995** [comment]
I no longer need this.
