### ISSUE TITLE
executioners/nl_divergence_tolerance test fails with PETSc 3.11.4

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#14598]
## Reason
I'm preparing a VM with MOOSE preinstalled for an upcoming training. To set up the environment I followed the new conda instructions (this works beautifully and gets me to compile MOOSE right away). I noticed that one test exodiffs on a timestep size (`executioners/nl_divergence_tolerance.test`). 

## Design
Please, make this test more robust @frombs :-), or restrict it to older PETSc versions(?)

## Impact
Avoid tests breaking with new PETSc versions.

**Comment by hugary1995** [comment]
I have the same issue on Ubuntu 16.04 with conda moose-env build h2a4fc31_0

**Comment by frombs** [comment]
@dschwen and @fdkong , I am not sure if something changed between PETSc 3.11.3 and 3.11.4 or if there was a change to the MOOSE framework which caused the behavior of the `nl_divergence_tolerance` to change.  

I have fixed the test and can push the changes to the repository but cannot guarantee future updates won't be affected.  I am not sure how to make the test more robust.  I intentionally scaled the variables to make the system behave badly in order to trigger the tolerance.  I can't think of a better test unless we move it to the solid mechanics or contact modules. 

I initially added the test when we planned to set the `nl_divergence_tolerance` as a default within MOOSE.  However, we backtracked and turned it off by default when we found that many of the contact and solid mechanics tests triggered the tolerance.  Perhaps we should retire this test since it is not used by default and not widely used...what do you think?

**Comment by dschwen** [comment]
I'd be fine with retiring it.

**Comment by fdkong** [comment]
@frombs I think it is still a good idea to keep this test for ensuring that the code you added will be maintained in MOOSE evolution.

**Comment by frombs** [comment]
@dschwen: PR #14620 has merged and should resolve this issue

**Comment by frombs** [comment]
Can this issue be closed?

**Comment by GiudGiud** [comment]
Closing as resolved by #14620
