### ISSUE TITLE
multiapp clone_master_mesh

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#14608]
## Bug Description

In the master app, if I specify clone_master_mesh, I still have to provide a mesh block in the sub app input file, which doesn't make a lot of sense to me. Otherwise, I get the error:

```
Initializing All MultiApps
Creating MultiApp xxx of type raccoonApp of level 1 and number 0:
Cloned master mesh will be used for subapp xxx
xxx0: 


*** ERROR ***
No mesh file was supplied and no generation block was provided
```

## Steps to Reproduce

remove the mesh block in test/tests/multiapps/picard/picard_sub.i

## Impact

It is a pure annoyance.

**Comment by YaqiWang** [comment]
Removing mesh block in the subapp input file is discouraged because we want the subapp input file can run by itself. The way removing this annoyance is to not issue that error when a mesh is passed in through MooseApp valid parameters.

**Comment by permcody** [comment]
Yaqi is correct, we definitely thought about this and made this decision consciously. We do not consider it a bug for the reason Yaqi already pointed out. If you have a suggestion for making a better error message or better training users, we'd be happy to hear it. I can understand that you don't want to duplicate the mesh block so that it can run by itself, but perhaps there's a compromise where you put a mesh block in and indicate that it clearly isn't designed to work without being a sub app (explicitly declaring that you don't want it to work). Any thoughts? For now, I'm going to reclassify this as a task.

**Comment by hugary1995** [comment]
Okay I completely agree.

On Jan 21, 2020 4:26 PM, Cody Permann <notifications@github.com> wrote:

Yaqi is correct, we definitely thought about this and made this decision consciously. We do not consider it a bug for the reason Yaqi already pointed out. If you have a suggestion for making a better error message or better training users, we'd be happy to hear it. I can understand that you don't want to duplicate the mesh block so that it can run by itself, but perhaps there's a compromise where you put a mesh block in and indicate that it clearly isn't designed to work without being a sub app (explicitly declaring that you don't want it to work). Any thoughts? For now, I'm going to reclassify this as a task.
