### ISSUE TITLE
Make MultiAppPostprocessorInterpolationTransfer work with CONSTANT MONOMIAL variable

### ISSUE THREAD

**Issue by pbalest** [idaholab/moose#14631]
## Reason

Will make it easier to transfer variables that have to be preserved or used for interpolation

## Design
  
So far MultiAppPostprocessorInterpolationTransfer work with LINEAR LAGRANGE variables but if I use a CONSTANT MONOMIAL variable the code to not transfer the values and do not error out ( the CONSTANT MONOMIAL variable value do not change). Probably because the object parse just the nodes and not the elements.

## Input files
This is a simple case that demonstrate what I am talking about:
[multilevel_master.txt](https://github.com/idaholab/moose/files/4105615/multilevel_master.txt)
[multilevel_sub.txt](https://github.com/idaholab/moose/files/4105616/multilevel_sub.txt)

**Comment by pbalest** [comment]
@aeslaughter @snschune

**Comment by aeslaughter** [comment]
@idaholab/moose-team Does anyone know what needs to be done to make this work for a constant monomial on the receiving end?

https://github.com/idaholab/moose/blob/d4b1a6445f0f6ea99e2b120e24705cb9dfcb5243/framework/src/transfers/MultiAppPostprocessorInterpolationTransfer.C#L146

Is it as simple as performing an element loop instead of nodal for MONOMIAL?

**Comment by pbalest** [comment]
Thanks for the help @aeslaughter!!!

**Comment by vincentlaboure** [comment]
@pbalest Looks like this is a duplicate issue (see #12047) ;)
