### ISSUE TITLE
MOOSE cannot find a controllable param of AD material

### ISSUE THREAD

**Issue by shoheiogawa** [idaholab/moose#14706]
## Bug Description

When I have a controllable parameter in an automatic differentiation material property object, it seems that MOOSE cannot find the parameter properly.

After compiling, when I run the test executable with the input file below, I get an error:
```
*** ERROR ***
Unknown InputParameters object Materials/ad_mat_diffusivity
```
The input file indicates the controllable parameter is Materials/ad_mat_diffusivity/coef, but MOOSE somehow omits the last word.

## Steps to Reproduce

The code is in this branch: https://github.com/shoheiogawa/moose/tree/ad_mat_control_param
The input file is here: https://github.com/shoheiogawa/moose/blob/ad_mat_control_param/test/tests/controls/real_function_control/ad_mat_param_control.i

## Impact

This will extend the flexibility of AD materials.

**Comment by aeslaughter** [comment]
Thanks for building this input file. This isn't working because of the naming convention being used by AD objects. The fix will be to create an "alias" to the object name expected to the auto named AD objects. This should be similar to what is done when adding a Material object: https://github.com/idaholab/moose/blob/d9a0c8465efdea53d63d193560413314eec8807c/framework/src/problems/FEProblemBase.C#L2878
