### ISSUE TITLE
Change emissivity_1/2 to emissivity_master/slave

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#14746]
## Reason

Consistent naming between generic heat conduction module and 
BISON use. Currently emissivity_1/2 is simply renamed as emissivity_fuel/clad.
This leads to the unfortunate problem that heat conduction module input files do not work in BISON unless the parameter names are changed. 

## Design

Changing the name

## Impact

Change of parameter name.=

**Comment by snschune** [comment]
@permcody before closing this, I will change the default in heat conduction module to be 
consistent with what BISON has now. BISON is the largest customer of this capability and we should preserve their default.

**Comment by bwspenc** [comment]
We just stumbled across this because we were wondering why the radiant term would be on by default.  This change has some pretty bad unintended side effects. I think we should set this back to 0.

**Comment by snschune** [comment]
It was set to match BISON default. Can you be more specific what unintended side effects it caused? 
It seems to me that 0 or 1 for default would work, just needs to be documented sufficiently.

To be clear, you don't want to change the names back to not match BISON's anymore. That was just bad behavior.

**Comment by snschune** [comment]
Come to think about it, what I would advocate for is that a problem executed with heat conduction exec and one with BISON behaves exactly the same. That was the original driver for these changes.

**Comment by bwspenc** [comment]
Two issues with this change:
1) We should be really careful making changes to default settings in general. Silently changing the behavior of existing models without the user being aware is one of the worst things we can do with our code.
2) The default behavior of this model had previously been that it was conduction only. To be honest, I didn't even realize that there was an option for radiant heat transfer in this particular model. Changing this default made it so that the model behaves completely differently than it always did. There are options in this model to use it for other arbitrary variables for which radiant transfer makes no sense at all. We've been using it for a long time for things like concentration variables and electrical potential.

I need to investigate a little more what BISON did differently. BISON has an LWR-specific model that builds on this, and I suspect (hope!) that those different defaults were only used when you used the LWR model. For an LWR, it would make sense for an emissivity of 1 for the metal cladding and something like .5 for the ceramic. For the general-purpose model in MOOSE, it seems like if you wanted radiant heat transfer, you should be required to specify the emissivity because we don't know anything about the materials it is being applied to.

The way that BISON builds on the thermal contact model in MOOSE is ugly in many ways, and this is just another manifestation of that. @tophmatthews has been looking into ways to refactor this. Maybe a redesigned syntax can make it more clear to the users what features they want.

In the mean time, maybe the best solution here is to make those emissivities required parameters. I would prefer to just switch the defaults back to 0, but I'm pretty hesitant to do that because of the issue I raised above.

**Comment by snschune** [comment]
I don't disagree with you that changing defaults should only be done when necessary. Let me explain to you why it was necessary in this case. 

A thing that is worse than changing defaults is not fixing bugs. This change was not just some idle "Sebastian wants defaults the other way". The design of thermal contact and BISON's version was that BISON used the same syntax as heat conduction module and also inherited most of the code but it was suppressing the module's emissivity parameters to rename them to `emissivity_fuel` and `emissivity_clad`. The defaults of heat conduction module and BISON were different (module defaults to 0, BISON to 1). This will be important later. 

Now this design led to the following behavior: I created working models with heat conduction module. When I included them in multiphysics models, I had to run them in apps that included BISON (sabertooth in this case). However BISON "overrode" the syntax and required you to use different parameter names. So it would error out with previously working input files. This behavior is a bug. Any superset of apps should run input files that run in the separate apps. Therefore, I removed the different naming in BISON.  

However, removing the different names led to the problem that now I had to pick one set of default values (remember BISON and heat conduction module were different). BISON uses this model quite a bit and arguably has more customers relying on stable default values. Talking with developers, we decided to change the heat conduction module default.  

On the physics side, the model is called `ThermalContact` not `DiffusionContact`. Radiation happens in thermal transport through gaps if you want it or not. I mean, for real, the thing is called `ThermalContact` and radiation is important not just for LWRs but for gas cooled reactors, nuclear thermal propulsion systems, and many other systems - nuclear or not. You arguing that diffusion should be the main consideration for setting defaults doesn't make a lot of sense to me. 
Using thermal contact for diffusion across the gap is fine, but you have no tests for it in the module making it hard for generic reviews to catch issues like this.
