### ISSUE TITLE
Quit using square.e in tests

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#14766]
## Reason
`square.e` is used in ~140 tests as a 2x2 quad4 mesh. Switching to a `GeneratedMeshGenerator` instead will allow us to decrease IO, remove files, and will also be more intuitive to a user looking at input.

## Design
Use a `GeneratedMeshGenerator` instead of loading `square.e` in tests.

## Impact
Shouldn't be any - this is an improvement.

**Comment by gambka** [comment]
I believe not all square.e files are 2x2 meshes.  Some may contain 7 irregularly shaped elements known as a patch test.  These will exist mostly in the modules. I created an issue (#14229)  to change those inputs to use the PatchMeshGenerator. I haven't had time to track them all down because the meshes are not necessarily called `patch.e`.  If you come across any of those types of meshes can you keep a list so I can replace them in the future? In those cases, some regolding may be necessary as the node ids created by the generator are not necessarily what Cubit would have generated in the original .e files.

**Comment by cticenhour** [comment]
@gambka I only found two patch `square.e` tests when going through everything. Look in `peridynamics/simple_tests` when you get to #14229. Otherwise, everything else I found in modules and framework was the standard 2x2.

**Comment by gambka** [comment]
@cticenhour That is good to know if I ever get to that. I would like to as some point. Since there can be 2D and 3D patches and it isn't always `square.e` or `patch.e` I can try doing a couple merge requests, one for 2D and one for 3D rather than one large one.
