### ISSUE TITLE
Initial Condition from Postprocessor

### ISSUE THREAD

**Issue by crswong888** [idaholab/moose#14896]
## Reason
I am currently developing an action system for MASTODON which needs to set an initial condition from a value stored in a vectorpostprocessor. The action first extracts this key value with VectorPostprocessorComponent. It then should set this PP value as the IC.

## Design
With the advent of the PREIC setup stage, it seems natural that a “PostprocessorIC” object be implemented in MOOSE. I have already developed and tested such an object in my custom app, [here](https://github.com/crswong888/scorpion/blob/master/src/ics/PostprocessorIC.C). I would like to submit a PR for this code.

## Impact
An initial condition may be set using a postprocessor when that postprocessor is executed with `force_preic = true`, allowing for a broader, more diverse range of UserObjects capable of controlling the initial value of a MOOSE variable.

**Comment by permcody** [comment]
@crswong888 - We have to be very careful about this sort of feature. Keep in mind that in the general case, these types of objects can couple to many other systems and forcing them to run earlier than they were intended creates odd behaviors when these objects can't get values from the objects they depend on. When I created the PREIC flag, my intention was to limit it to GeneralUserObjects, which gives developers lots of flexibility. Almost anything can be implemented in a GeneralUserObject, PostProcessors, something that looks like a VectorPostProcessor, etc. The problem with adding this is that it's not very well defined. VectorPostprocessors can produce several "vectors" of data that are not necessarily related to the mesh at all. So if we add the ability to set an IC based on a VPP, what transformation do we support? Your case is one value at of one vector. Why not distribute the vector over the mesh? What happens if you have several vectors? It's hard to see what this should look like for the general case.

This doesn't mean you can't do this. It's possible that your object makes a lot of sense for Mastodon, in which case your object will live there. If your changes to the framework make sense and aren't intrusive, we can support this. Let me know what you think.

**Comment by crswong888** [comment]
@permcody yes, it is the case that my vpp doing the calculation has nothing to do with the mesh or, at least, has no dependency on the mesh details. It is a type of acceleration signal processing that is commonly used in earthquake engineering. Technically, the computation that my vpp does is a type of pre-processing that the user could perform on their own, but it can be a long and difficult procedure, and my action system would set everything up for the user with minimal input. As far as I am aware, most commercial FE packages that run structural dynamic simulations have this capability.

So this is what makes my vpp object unique, and probably not the general case you were imagining. I agree, especially for the case of _vector_ postprocessors, it is difficult to generalize. I actually wrote a "VectorPostprocessorIC" at one point that simply took a specific component of a member vector of a vpp, and I achieved the desired results. But I realized, that this is hardly something that would ever be useful to most problems. This is why I prefer the idea of just a "PostprocessorIC", because a PP always produces a unique value at any given step - much more appropriate for setting an IC. Now, I understand that there are vector initial conditions, for which the IC varies through space, perhaps a vpp could be useful here, but as of right now my research has no need for this sort of thing.

I could just implement my "PostprocessorIC" in MASTODON and this would be fine for me. But I really do think that a pp (not necessarily a vpp, for now) is general enough to set an IC. I can work on a PR, and we can see how it turns out. I think this could be more applicable then to just MASTODON.

**Comment by crswong888** [comment]
@cbolisetti could you please comment on this? This is regarding the Baseline Correction vpp I told you about. Do you think a "PostprocessorIC" could appropriately live in MASTODON? It would be useful for an action system that actually sets an adjusted time history acceleration as a boundary condition with PresetAcceleration. 

If you think it could be fine in MASTODON, I won't have to bother with making sure it is a good fit for MOOSE. The program is very simple:

```
Real
PostprocessorIC::value(const Point & /*p*/)
{
  return _pp_value;
}
```

**Comment by cbolisetti** [comment]
Hi @crswong888 since this is very specific to MASTODON, I think it's better for it to live there. However, I need to think about whats the right way to implement the baseline correction. I'll get back to you on that.

**Comment by crswong888** [comment]
@cbolisetti Well, the baseline correction itself is just a vectorpostprocessor. Only because I would like to create an action that sets the BC by interpolating the vpp data do I encounter this issue. But this is exactly the case, the action system would call the vpp first and correct the acceleration before enforcing the BC. However, the corrected acceleration at time zero is not zero, and so I need to set the accel aux variable initial condition for the Newmark integration to be carried out correctly.

Perhaps I could just PR only the vpp in MASTODON at first, and then after, I can show you what I mean with the action system. Let me know what you think.
