### ISSUE TITLE
While using Conda compilers, some tests are skipped

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#14967]
## Bug Description
Conda compilers are of a different naming convention for which our TestHarness is incapable of deciphering.

Conda:
```pre
x86_64-apple-darwin13.4.0-clang++
```
The rest of the world:
```pre
clang++
```

We end up skipping tests specifically designed for Clang, GCC, Intel, etc.

## Steps to Reproduce
Using our conda-moose channel, run the following test:
```pre
$ ./run_tests --re=mortar/1d.test
mortar/1d.test ....... [COMPILER!=GCC, CLANG] SKIP
--------------------------------------------------
Ran 0 tests in 1.6 seconds.
0 passed, 1 skipped, 0 pending, 0 failed
```

It will not run, because it thinks the compiler is something that it is not.

## Impact
While we transition over to Conda, we are skipping tests which should not be skipped

**Comment by permcody** [comment]
Jason, if the compiler is always assumed to be the first argument. You could use a Regex like this to just match at the end of the first space separated argument without doing splitting or anything else:


```
re.match([^\S]*clang++\s)
```

This translates to match only none-space characters followed by the thing you are looking for. Here I put clang++ but you could drop in the other compiler names as well. Followed by a space. Since we are using match this won't go past the beginning of the string so you should be good on all cases. You are just throwing away stuff for awhile and basically matching right before the first space.
