### ISSUE TITLE
Not allowing renumbering crashes with some element types

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#14963]
## Bug Description
`TET4`, `HEX8`, and `HEX20` in replicated mesh parallel will crash with the assertion

```
/Users/harblh/projects/moose/scripts/../libmesh/src/base/dof_map.C, line 355, compiled nodate at notime
Assertion `obj_procid != DofObject::invalid_processor_id' failed.
obj_procid = 4294967295
DofObject::invalid_processor_id = 4294967295
```

## Steps to Reproduce
Run `simple_diffusion` with the following mesh blocks:
```
[Mesh]
  type = GeneratedMesh
  dim = 3
  nx = 10
  ny = 10
  elem_type = TET4
  allow_renumbering = false
[]
```
```
[Mesh]
  type = GeneratedMesh
  dim = 3
  nx = 10
  ny = 10
  elem_type = HEX20
  allow_renumbering = false
[]
```
```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 10
  ny = 10
  elem_type = QUAD8
  allow_renumbering = false
[]
```
...with 2 or more MPI procs and replicated mesh.

## Impact
Bad error that shouldn't happen.

**Comment by roystgnr** [comment]
I can replicate this.  And there's like a 90% chance it's my fault, too, so I'm digging into it, but if anyone wants to bisect I'd appreciate the help.

**Comment by lindsayad** [comment]
If you haven't gotten to it, let me know and I will bisect first thing tomorrow

**Comment by roystgnr** [comment]
Well, I can see what's wrong: we're still generating second-order sets of nodes here even when we generate first-order or reduced-order elements, so some of the nodes end up unconnected to any element, so some of our algorithms (like in the partitioner) don't touch those, but since they remain in the mesh then other algorithms scream upon seeing them with unset partitioning.

**Comment by roystgnr** [comment]
Weird that HEX8 didn't have the same problem, though!

**Comment by roystgnr** [comment]
Oh, and now I get it.

HEX8 does begin with a first-order set of nodes, because we know a priori that that's all we'll need.

TET4 begins by making hexes and then breaks each into 24 tets, and it needs mid-hex and mid-face nodes to do that, but then the mid-edge nodes remain unconnected.

Normally, renumber_nodes_and_elements also deletes unconnected nodes as it goes, but when we turn off renumbering on a ReplicatedMesh then there's nothing that does so.

**Comment by loganharbour** [comment]
Heh, glad it's coming together. Thanks for taking the quick stab at it.
