### ISSUE TITLE
Revive the UMAT/CREEP interface and move it over to tensor_mechanics

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#14974]
## Reason
A lot of people have libraries of their own mechanical constitutive models written to the UMAT and CREEP interfaces. Providing an interface to them would allow those models to be used in MOOSE. There is an existing capability in solid_mechanics that has been around for a long time, but it has languished -- I think it's hardly being tested on any platforms currently.  This needs to be brought back to life and migrated to tensor_mechanics.

## Design
We should create appropriate Material classes in tensor_mechanics. I think we would have a UMAT stress calculator (which would get many of its properties from the existing strain calculators). We would also probably wrap the call to the CREEP model in a stress update material.

## Impact
This will just add new material models. As part of this, we may fix some minor issues with the current solid_mechnaics implementation as well.

**Comment by jessecarterMOOSE** [comment]
if you look at the commit I referenced above, I fixed the path to the umat plugin and removed the checks so they actually run. The user material test is ok but the user creep routine diffs. You can run these real quick if you do `./run_tests --re 'abaqus|umat'`

**Comment by permcody** [comment]
Since I missed the call I'll add one thing I was thinking about. We setup the Makefiles to compile the UMATs into ".plugin" files. I'm not sure what we were thinking. I guess we were hoping that we could avoid dealing with platform specific conventions way back then. A lot of things have changed since the original implementation. I suggest that we use normal suffixes for these libraries. There's no need to complicate things.

**Comment by jessecarterMOOSE** [comment]
@bwspenc @ramirezbrf @krisbaker8

**Comment by jessecarterMOOSE** [comment]
note there's also this #5104

**Comment by dschwen** [comment]
I'm now working on this.
