### ISSUE TITLE
Undesirable time-step behavior for multilevel transient simulations when some inter-level coupling is Picard and some is one-way

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#15166]
## Bug Description

When running a multilevel simulation (master -> sub1 -> sub2), in which master -> sub1 is *not* Picard but sub1 -> sub2 *is* Picard, if the Picard iterations between sub1 and sub2 fail, the time step is cut, as expected. However, `master` *advances* its time step with `dt` cut in half. From that point on,  the simulation keeps going with `sub1` and `sub2` behind `master` in terms of time step, which poses all sorts of issues.

Could be related to #15008

## Steps to Reproduce

[These input files](https://github.com/vincentlaboure/moose/tree/bug_multilevel/test/tests/multiapps/picard_multilevel/multilevel_dt_rejection) reproduce the issue.

## Impact

This is an issue to conduct multi-level transients with significant coupling between sub-apps. This can be added to the Rattlesnake/Mammoth Support Tasks FY20.

**Comment by lindsayad** [comment]
@vincentlaboure what's the desired behavior in the master app for this? Here's current output:
```
sub10_sub20: 
sub10_sub20: Time Step 2, time = 2, dt = 1
sub10_sub20:  0 Nonlinear |R| = 1.576427e-08
sub10_sub20:       0 Linear |R| = 1.576427e-08
sub10_sub20:       1 Linear |R| = 5.273447e-10
sub10_sub20:       2 Linear |R| = 9.682693e-12
sub10_sub20:       3 Linear |R| = 3.672491e-13
sub10_sub20:       4 Linear |R| = 7.732588e-15
sub10_sub20:  1 Nonlinear |R| = 7.593055e-15
sub10_sub20:  Solve Converged!
sub10: Successfully Solved MultiApp sub2.
sub10: Finished Executing MultiApps on TIMESTEP_END
sub10: 
sub10: 
sub10: Starting Transfers on TIMESTEP_END From MultiApps
sub10: Beginning NearestNodeTransfer v_to_v3
sub10: Finished NearestNodeTransfer v_to_v3
sub10: Transfers on TIMESTEP_END Are Finished
sub10: 
sub10: Picard Norm after TIMESTEP_END MultiApps: 2.350272e-09
sub10: 
sub10:  0 Picard |R| = 1.286170e-01
sub10:  1 Picard |R| = 3.647633e-03
sub10:  2 Picard |R| = 2.350272e-09
sub10: Picard converged reason: DIVERGED_MAX_ITS


*** Warning ***
sub10 failed to converge!

Successfully Solved MultiApp sub1.
Finished Executing MultiApps on TIMESTEP_END


No Transfers on TIMESTEP_END To MultiApps

sub10: Aborting as solve did not converge
sub10: 
sub10: Restoring Multiapps on TIMESTEP_END because of solve failure!
sub10: Begining restoring MultiApp sub2
sub10: Finished restoring MultiApp sub2
sub10: Finished Restoring MultiApps on TIMESTEP_END
sub10: 

Time Step 3, time = 2.5, dt = 0.5
```
Intuitively, I would think the desired behavior is that:

1. We shouldn't be getting the message `Successfully solve MultiApp sub1`
2. The last bit there should read `Time Step 2, time = 1.5`, e.g. because the sub app failed to converge, master should cut its time step and go back to Time Step 2, *not* Time Step 3

Am I right?

**Comment by vincentlaboure** [comment]
Wow @lindsayad you're on a roll, there won't be many bugs left soon! 

I just reran that problem and you are right (I think my description above is not accurate, not sure if the behavior changed or - more likely - if I just messed up), the master app should be considered converged and go back to Time 2.

**Comment by lindsayad** [comment]
Ok...so the master doesn't have Picard, but the mid-level sub (sub1) does. So under the master's influence, sub1 is supposed to auto-advance (because we're transient and we're not doing Picard), *but* because Picard between sub1 and sub2 failed, sub1 is supposed to cut it's timestep.

I dunno, who's supposed to win? @friedmud ?

**Comment by lindsayad** [comment]
I should clarify: `master.i` has `picard_max_its = 1`, and `PicardSolve` defines `_has_picard_its = _picard_max_its > 1`. @vincentlaboure if you set `picard_max_its = 2` in `master.i`, then all the timestep cutting works as it should.

**Comment by vincentlaboure** [comment]
You are correct @lindsayad, in the application I have in mind though the master app should _not_ use Picard iterations. Let me detail a little more the case I am concerned about.

I am originally running a multi-app like this: `app1 -> app2`
There is a parameter `p1` in app1 that gets updated on `timestep_end` but I noticed that this could lead to numerical instabilities with Picard iterations because this parameter has some strong nonlinear effects. Instead, I noticed that if I update that parameter between time steps, the solve is much better behaved. If there were a flag `execute_on = real_time_step_end` (since `timestep_end` is really updating at every Picard iteration when you use those, so multiple times per time step), I would be good to go.

Since I was not aware of such `execute_on`, I instead created a main app above app1 (`main -> app1 -> app2`) whose purpose was solely to compute `p1` and pass it to `app1` to effectively update it at the end each time step. In that case, `main` should not use Picard iterations (or that would defeat the whole purpose as p1 would once again be evaluated once per Picard iteration).

This worked well until the Picard iterations `app1 -> app2` failed and had to cut its time step, at which point main became de-synchronized and the results become unreliable.

Does that make sense?

**Comment by lindsayad** [comment]
Yes it does. I think I'm going to change the title of this issue since multilevel Picard does handle time step rejection correctly. The issue is when some some inter-level coupling is done with Picard and some is not. And in that scenario again I'm not quite sure what we would want to do. Perhaps add an input file option to turn off `auto_advance` from the master application? Then a user could choose to have the master app cut its timestep if the sub-app solve fails, *even* if not doing Picard. Does that sound like an ok solution @vincentlaboure ?

Then maybe we should open a different ticket if what you *really* want is to have an additional `execute_on` flag. Having to add another level `MultiApp` for what you're trying to do seems unfortunate. If we could handle your desired use without having to add that, then I think that would definitely be preferred.

**Comment by vincentlaboure** [comment]
Yes, the title change makes sense.

Having to turn off the `auto_advance` would work for me. One thing I forgot to mention is that if I use `sub_cycling=true` in `main`, then the time-step failure is properly handled.

And yes, the ideal solution would be to add a new `execute_on` flag. I didn't know if it would be realistic to request that feature in a pretty short time-frame but yes it would definitely be great!

**Comment by friedmud** [comment]
@vincentlaboure at one point in time we were going to add an execute_on called `picard_end` or `picard_begin`.  This would allow distinguishing between the end of a picard iteration and the end of a timestep.

Unfortunately though - it doesn't work that well because it is more often the case that an input file you've created by itself which has stuff on timestep_end will want to execute that stuff at the end of every picard iteration.

What's there now is definitely a trade-off... but it may not be the right one....

**Comment by vincentlaboure** [comment]
@friedmud Yes, changing the meaning of `timestep_end` would definitely break a lot of input files.
