### ISSUE TITLE
I believe we might have a bug

### ISSUE THREAD

**Issue by arovinelli** [idaholab/moose#15170]
https://github.com/idaholab/moose/blob/a2488d6519185070c9b1209bb8713c9b542b08ea/framework/src/interfacekernels/InterfaceKernel.C#L58-L59

@lindsayad 

I know that for Galerkin approaches trial and test functions are the same.
However shouldn't the highlighted lines call for GradTest and GradTestNeighbor??

Andrea

**Comment by lindsayad** [comment]
Those methods don't even exist. A `phi*` method called on a variable object returns the test/trial functions associated with that variable. Because we *are* doing Galerkin FEM, there is no problem with this. If this was a bug, then every computation every done with MOOSE has been buggy. You can see this same design pattern in `Kernel.C`.
