### ISSUE TITLE
use the --show-input option with run_tests

### ISSUE THREAD

**Issue by gardnerru** [idaholab/moose#15671]
## Reason
There is an executable option --show-input that will append the input file to the simulation output log. I would like this option to be available when using run_tests as well. 

Using the run_tests system we are currently running multiple, small parameter perturbation studies. The run_tests -x option will make separate output files for each simulation, but for review and verification purposes the input should be attached as well. 

I attached a small demo using the heat_source_bar.i regression test, and an "outfile" from using --show-input. 
[Archive.zip](https://github.com/idaholab/moose/files/4991071/Archive.zip)

## Design
I would like a ./run_tests -i <spec_file> -x --show-input, functionality.

## Impact
This will allow for the exact input used to be displayed with the output which will consolidate review locations and allow for a 100% confirmatory review.

**Comment by gardnerru** [comment]
@milljm @cticenhour 

Thanks

**Comment by milljm** [comment]
There is another issue I found when testing this; currently --cli-args can't take dash-dash arguments... uggh:

```bash
./run_tests --cli-args "--fake-arg"
usage: run_tests [-h] [--opt] [--dbg] [--devel] [--oprof] [--pro] [--run RUN]
                 [--ignore [caveat]] [-j [int]] [-e] [-c]
                 [--color-first-directory] [--heavy] [--all-tests] [-g GROUP]
                 [--not_group NOT_GROUP] [--dbfile [DBFILE]] [-l LOAD] [-t]
                 [-s] [-i INPUT_FILE_NAME] [--libmesh_dir LIBMESH_DIR]
                 [--skip-config-checks] [--parallel [PARALLEL]]
                 [--n-threads NTHREADS] [--recover]
                 [--recoversuffix RECOVERSUFFIX] [--valgrind]
                 [--valgrind-heavy] [--valgrind-max-fails VALGRIND_MAX_FAILS]
                 [--max-fails MAX_FAILS] [--re REG_EXP] [--failed-tests]
                 [--check-input] [--no-check-input] [--spec-file SPEC_FILE]
                 [-d] [--parallel-mesh] [--distributed-mesh] [--error]
                 [--error-unused] [--error-deprecated] [--cli-args [CLI_ARGS]]
                 [--dry-run] [--use-subdir-exe] [-v] [-q] [--no-report]
                 [--show-directory] [-o directory] [-f FILE] [-x]
                 [--sep-files-ok] [-a] [--testharness-unittest] [--yaml]
                 [--dump] [--no-trimmed-output] [--no-trimmed-output-on-error]
                 [--results-file RESULTS_FILE] [--pbs name] [--pbs-pre-source]
                 [--pbs-project] [--pbs-queue] [--pbs-node-cpus]
                 [--pbs-cleanup name] [--queue-project] [--queue-queue]
                 [--queue-cleanup]
run_tests: error: unrecognized arguments: --fake-arg
```

**Comment by gardnerru** [comment]
While I am sorry for the rabbit hole, I am also waiting for a commission for edge case testing ;)

**Comment by milljm** [comment]
Found a work-around. If you start the argument with a space, it works:

```bash
./run_tests --cli-args " --fake-arg"
```

**Comment by gardnerru** [comment]
weird. Why does that work?

Add it to the docs? :)

**Comment by milljm** [comment]
@gardnerru the PR in place, should allow for the following:

```bash
./run_tests -x --cli-args " -show-input"
```

Actually, my PR is to _fix_ an issue I discovered with some of _our_ tests. You may not have any issues on your side, if you want to try the above command?

**Comment by gardnerru** [comment]
just to confirm, you meant to have a double tick there right? --show-input

That does run, with my current moose/bison, and I confirm that the input is appended to the out log but run_tests reports a fail on "ERRMSG", but I dont see one and the out log shows completion..

**Comment by milljm** [comment]
Yep, I specifically meant two dashes. Is that not the option to use? I didn't bother trying one dash, since the option you posted in the OP uses two...

The _test_ fails when we supply --show-input? Or is it always failing? Can you post the error (or email me directly if it's sensitive). Just guessing here, but if the error is anything like what I received, then it would seem you will need the PR attached to this issue (it fixes nested test spec blocks). Consider the following:

```bash
[TestGroup]
   [./test_a]
   [../]

   [./test_b]
   [../]
[]
```

Will create a test, with the name: TestGroup/test_a/test, and TestGroup/test_b/test. The issue is that when the TestHarness is asked to write results to a file (-x), it is treating that last slash as a directory path (which doesn't exist). That is what my PR fixes. It will convert the above test name to: TestGroup/test_a.test, and TestGroup/test_b.test.

Is the test that failed using nested test blocks like the above example?

**Comment by gardnerru** [comment]
I just tested and the example that I attached to the original issue will err with --show-input, but actually complete according to the run log. Ill send an email with more.

**Comment by milljm** [comment]
To recap what we found, in order to keep this issue updated... it looks like including the contents of the input file in the output, which gets scrutinized during post-process tests, will not work. The contents of the input file can have any number of strings in it, which will trigger faulty situations.

Instead, we should either append, or prepend the input file after the test has completed.
