### ISSUE TITLE
Template RadialReturnSressUpdate class

### ISSUE THREAD

**Issue by dewenyushu** [idaholab/moose#16183]
## Reason

Template the AD and non-AD versions of `RadialReturnSressUpdate` would help unifying the material models in the `TensorMechanics` module.

## Design

Combine the AD and non-AD versions while keeping the behavior of the original classes

- [x] Template `StressUpdateBase`

- [x] Template `RadialReturnStressUpdate`

## Impact

Make it easier to keep consistent between the AD and non-AD material models

**Comment by tophmatthews** [comment]
I had some trouble combining an AD and non-AD creep model, mostly due to the use of pass by reference in `ADSingleVariableReturnMappingSolution` for ` computeResidual`, while `SingleVariableReturnMappingSolution` does pass by value. Do you think you can make an attempt at combining `PowerLawCreepStressUpdate` and `ADPowerLawCreepStressUpdate` @dewenyushu? It'll be a great example of how to do it on downstream apps.

**Comment by dewenyushu** [comment]
> I had some trouble combining an AD and non-AD creep model, mostly due to the use of pass by reference in `ADSingleVariableReturnMappingSolution` for ` computeResidual`, while `SingleVariableReturnMappingSolution` does pass by value. Do you think you can make an attempt at combining `PowerLawCreepStressUpdate` and `ADPowerLawCreepStressUpdate` @dewenyushu? It'll be a great example of how to do it on downstream apps.

Yes, I also realized that there are some inconsistencies in the parent classes between AD and non-AD versions in terms of passing by reference/value. I think it is a better strategy to unify the parent classes first. I would like to make some progress on this task. However, I am currently occupied by other things and I am not sure when I will be getting to this.
