### ISSUE TITLE
Porous flow Jacobian line sink test fails

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#16255]
## Bug Description
The `porous_flow/test:jacobian.line_sink03` test fails quite regularly on Mac

## Steps to Reproduce
Run CIVET

## Impact
This is really obnoxious. Totally unrelated PRs get red x's because of this, causing them alarm and really holding back development

**Comment by lindsayad** [comment]
If you go back through https://civet.inl.gov/branch/6695/ you'll see quite a few invalidations of `Mac Test`, all of which I believe were because of this guy. @WilkAndy I'm going to skip this test for now as it seems brittle. If you can robustify it, then we can restore the test

**Comment by WilkAndy** [comment]
Yep, that's fair.   I hope to work on this today.

**Comment by WilkAndy** [comment]
I've done as much testing as is practical on my local machine.  I believe this is related to #10471, which points to the problem originating with DerivativeMaterials that are involved with DiracKernels where there are a large number of DiracKernel points in an element.   That is an open issue that may keep raising its head occasionally.  For now, i'm going to re-instate the test with less Dirac Points in each element, because i want the Jacobian tested in this case, at least.
