### ISSUE TITLE
Improve `-v` version output

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#16637]
## Reason
```
(moose) [schwd][~/Programs/blackbear]> ./blackbear-opt -v

Application Version: 3877bd279e
```

Thats a lie! What's shown here is the framework version. Both need to be shown and labeled correctly.
Furthermore there is a Makefile issue where going back to an older commit will not re-generate the `*Revision.h` file. This has the potential to drive developers (@recuero) mad, as they see a hash not matching their checkout in the app's version output.

## Design
Just show the right stuff and make sure its updated.

## Impact
Better transparency.

**Comment by permcody** [comment]
I can tell that part of the issue is that repo dependencies (i.e. .git/HEAD and .git/index) don’t exist for submodules. They only exist for full clones. Our Makefile is going to miss those.

**Comment by permcody** [comment]
Just putting this here since I don’t have time finish it. I think the right approach in the app.mk file is to
Check if the current `.git` entry is a file or directory `[ -d $dir ]`
If it’s a file, we cut and append it to the current directory: `$dir + cut -d' ' -f 2 .git` .
The rest of the commands from that point stay about the same. This should handle arbitrary use of full clones versus submodules. Now getting all the right Makefile syntax and testing.
