### ISSUE TITLE
Allow MultiApp to construct its moose apps early when not doing recover/restart

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#17223]
## Reason
The main-app may add objects like a BC depending on the availability of a MultiApp. These objects may need to obtain some information from the moose app wrapped in the MultiApp but currently the moose app is not available at the construction of these objects even in their `initialSetup` unfortunately.

## Design
The currently design of recover/restart of multiapps makes the wrapped moose app must be constructed later if I understand correctly. However, if we are not doing recover/restart, we can create the moose app right after adding the MultiApp. If we change the design of recover/restart of multiapps in the future like what we did to the mesh meta data, we can just do the creation of moose app right after adding the MultiApp.

## Impact
A new capability.

**Comment by smpark7** [comment]
Hi I noticed that two of the heavy tests in Moltres which use multiapp are currently failing with the latest version of MOOSE with the new Reporter system and the associated changes to MultiAppPostprocessorTransfer. The error message is:
```
*** ERROR ***
The desired Reporter value 'Inlet_Average_pre1_/value' does not exist.
```
The main app simulates a molten salt reactor core and the sub app simulates the flow of the molten salt through the subcritical outer loop region before it flows back into the core. It uses MultiAppPostprocessorTransfer to transfer the average concentration at the inlet and outlet. In a single timestep, Moltres runs the sub app first before running the main app. I think the error may be caused by the non-initialization of the ```Inlet_Average_pre1_``` receiver postprocessor in the main app. Do you think this issue is related to the Moltres tests failing?
