### ISSUE TITLE
Less restrictive error for boundary-restricted auxkernel

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#17424]
## Reason

For conjugate heat transfer coupling of nekRS and MOOSE via Cardinal, we use a boundary-restricted auxkernel that computes a CONSTANT MONOMIAL conductive heat flux, `flux`, based on a LINEAR LAGRANGE temperature. This heat flux is then sent to nekRS as a boundary condition between the fluid and solid phases. We would like to run problems where we compute the `flux` on sidesets where elements may have more than one face on this sideset. However, this results in the following error:

> Boundary restricted auxiliary kernel 'flux' has element (id=4023) connected with more than one boundary sides.

Unfortunately, we need this auxkernel to be boundary-restricted because it relies on the normal to compute `k * grad(T) * hat(n)`. But we cannot split the auxkernel into multiple auxiliary variables (as the error message suggests as a fix) because we can’t restrict the flux transfer to our nekRS-wrapped app to a surface - the mesh mirror we construct for nekRS is _only_ a surface (AFAIK, you can only add sideset IDs to sides of volume elements). Even if a splitting solution possible, it’s quite tedious - for flow over 3 rectangular blocks, circumventing this error would need 6 * 3 = 18 separate auxvariables and transfers.

## Design
Add a flag that skips the error check, thereby simply applying the auxkernel to all sides of the element on the sideset based on an evaluation on the side evaluated last. 

## Impact
Allow boundary-restricted elemental auxkernels on multiple sides of an element as a numerical approximation with error that should decrease with mesh refinement. Vastly simpler problem setup and mesh generation for Cardinal.

**Comment by YaqiWang** [comment]
I should have added this comments here for our future reference: This is a numerical error but with refined mesh, the error can become smaller. Because we make model simplifications always, so I am ok with this parameter. The ideal solution is to add lower-dimensional elements on the surface and use an aux kernel to evaluate a variable defined on these lower-d elements that can bring in the coupling of normal elements. This is somewhat related with what I am doing with hybrid FEM.
