### ISSUE TITLE
Improve the design of using restricted blocks for BreakMeshByBlockGenerator

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#17749]
## Reason

`BreakMeshByBlockGenerator` currently cannot selectively generate interface between specific block pairs. 

## Design

Generate interfaces using block pairs. 

## Impact

New feature.

**Comment by arovinelli** [comment]
@jiangwen84 sorry for the delay, can you tell me more about what you are trying to achieve with this? Do you have a simple example?
block restricted should work properly according to the design I had in mind when I added it with CZM + CP in mind.

**Comment by arovinelli** [comment]
I see, let me explain why it works in this way:
When I designed it the block parameter was intended to say around which block you want an interface (I'm always thinking to the 3d case)

so if you have the following mesh (`|` means connected )
`B1 | B2 | B3`
and specify block='B1' you will come out with (`*`  means interface)
`B1 * B2 | B3`
if you specify block='B2' the result will be
`B1 * B2 * B3`

Now it was done in this way because in 2D or 3D you want to a simply connected interface surface to avoid stress concentrators for instance assume you have
```
B1 | B2 | B3
--   --   --
B4 | B5 | B6
--   --   --
B7 | B8 | B9
```
and you specify block = `2 5` we wanted to come out with
```
B1 * B2 * B3
--   **  --
B4 * B5 * B6
--   **  --
B7 | B8 | B9
```

and not 

```
B1 | B2 | B3
--   **  --
B4 | B5 | B6
--   --   --
B7 | B8 | B9
```

In the latter case you would have huge concentrators at the interface corners
So it's not technically not a bug, just a different requirement

**Comment by arovinelli** [comment]
Also which nodes would you duplicate for the second case?

**Comment by jiangwen84** [comment]
I see your point. For your design, we can never generate only a single interface like this `B1 | B2 * B3 | B4 `, correct? But this will be very useful if users want to selectively add `CZM` at certain locations. 

For your question regarding how to duplicate for nodes between `B2` and `B5`, the nodes only sharing between `B2` and `B5` should be duplicated.

**Comment by arovinelli** [comment]
I'm ok with what youare 

> I see your point. For your design, we can never generate a single interface like this `B1 | B2 * B3 | B4 `, correct? But this will be very useful if users want to selectively add `CZM` at certain locations.

yes you are correct.

> For your question regarding how to duplicate for nodes between `B2` and `B5`, the nodes only sharing between `B2` and `B5` should be duplicated.

This is tricky, for simple geometries, or for interfaces ending at the free surface, it will work. However, assume in my last example each block consists only of a single quad4, you will end out without duplicate nodes but an interface...

I guess one option might be the user providing block pairs between which you want to add an interface so that you can selectively add interfaces, what you think?

**Comment by jiangwen84** [comment]
One solution would be to have users to provide blocks pairs to selectively generate interfaces. I think that would work for both cases. What do you think? 
```
block_pairs = '1 2
               3 4'
```

**Comment by arovinelli** [comment]
> One solution would be to have users to provide blocks pairs to selectively generate interfaces. I think that would work for both cases. What do you think?
> 
> ```
> block_pairs = '1 2
>                3 4'
> ```

If assuming `B1 | B2 | B3 | B4` that would generate `B1 * B2 | B3 * B4` I'm ok with it

**Comment by jiangwen84** [comment]
Great! I guess I need to rework on my PR. I will let you know when it is ready for review.

> > One solution would be to have users to provide blocks pairs to selectively generate interfaces. I think that would work for both cases. What do you think?
> > ```
> > block_pairs = '1 2
> >                3 4'
> > ```
> 
> If assuming `B1 | B2 | B3 | B4` that would generate `B1 * B2 | B3 * B4` I'm ok with it

**Comment by arovinelli** [comment]
@jiangwen84 also just for clarity, can we rename the issue and PR to something like
`Allow breakMeshByBlock to selectively add interface using block pairs`, remove the defect label and add an improvement label?
