### ISSUE TITLE
Add the number of nested Newton iterations as material property to the NestedSolve class

### ISSUE THREAD

**Issue by xueyang94** [idaholab/moose#18980]
## Reason
By showing the nested Newton iteration number at each quadrature point, we can tell which points are difficult to solve. This helps with debugging. 

## Design
A slight change to the `n_iterations` variable in the NestedSolve.h will be made. `_n_iterations` will be made a protected member variable and a getter function for the last number of iterations will be added.

## Impact
Added capability.

 @jiangwen84 @tonkmr

**Comment by dschwen** [comment]
NestedSolve is a utility class that does not and should not have access to the material property interface. You could have multiple silver objects in a given class. You could however add an API to get the number of iterations and have the host class store them in a material property.

**Comment by tonkmr** [comment]
Daniel,

Our plan was to do exactly what you say here, to add an API to get the number of iterations to the NestedSolve.

Mike

--------------
Michael Tonks
Professor and Alumni Professor
Materials Science and Engineering
University of Florida

158 Rhines Hall, Gainesville, FL 32611
(352) 846-3779
***@***.******@***.***>




On Oct 2, 2021, at 9:53 AM, Daniel Schwen ***@***.******@***.***>> wrote:

[External Email]


NestedSolve is a utility class that does not and should not have access to the material property interface. You could have multiple silver objects in a given class. You could however add an API to get the number of iterations and have the host class store them in a material property.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_issues_18980-23issuecomment-2D932755816&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=lgDAUkWm1bPlUxKFrS-oL4zuAM_BGBxTPjoylriDcJM&m=-CJ4b8of8tOOIu--gvqVfb5T9Pdh3n3Ahf2teco3oZk&s=tUy-TLNrYjbz7MJVJ-fEli2wu9SBp691k5P90QUj3j4&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABSNSRDHAQDZODFLPJHMN5TUE4FEBANCNFSM5FFMY5LA&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=lgDAUkWm1bPlUxKFrS-oL4zuAM_BGBxTPjoylriDcJM&m=-CJ4b8of8tOOIu--gvqVfb5T9Pdh3n3Ahf2teco3oZk&s=HS1yDNJtsqlbEvCT_1ujDZs30jWEbLp8_Ov7EBucVbc&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=lgDAUkWm1bPlUxKFrS-oL4zuAM_BGBxTPjoylriDcJM&m=-CJ4b8of8tOOIu--gvqVfb5T9Pdh3n3Ahf2teco3oZk&s=62a7zfkXcSkFhqhG2P2-IW8xB9A4mVETx5ntk1dfSgI&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=lgDAUkWm1bPlUxKFrS-oL4zuAM_BGBxTPjoylriDcJM&m=-CJ4b8of8tOOIu--gvqVfb5T9Pdh3n3Ahf2teco3oZk&s=FjsTR0vYL9KbEjTbvqtFfAHiklqqnavmFyVIRTZZp3U&e=>.

**Comment by dschwen** [comment]
Ok, I edited the issue text accordingly and made it conform to our SQA template.
