### ISSUE TITLE
Scaling for Dirichlet bcs

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#1898]
The way MOOSE handles Dirichlet bcs is to zero the row in the matrix associated with the appropriate degree of freedom, place a one on the diagonal entry, and replace the RHS at that row with the prescribed value.  This has the drawback of the magnitude of the stiffness for that row being predetermined regardless of the magnitude of the row before the change or of the magnitude of the stiffness generally.  This adversely affects the conditioning of the problem, and in some cases the solver does not recover.

It would be helpful if scaling options were available for Dirichlet bcs.  For example, instead of using one on the diagonal, MOOSE could use the sum of the absolute values of the entries on the row and scale the RHS accordingly.  Another idea would be to allow the user to set the diagonal value.

**Comment by jwpeterson** [comment]
BCs which derive from `NodalBC` can now override `computeQpJacobian()` and `computeQpOffDiagJacobian()`.  I think you can probably use this to implement any kind of problem-dependent scaling you might require for DirichletBCs.  Also, since there hasn't been any response on this issue since David's first attempt to fix it, I'm closing...
