### ISSUE TITLE
Input File Include Capability

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#20125]
## Reason
This should work as a pre-processing step just like C++.  It should take the entire contents of the file and place it where the include directive is.

Related to : #17989 #9755

## Design
`!include file.i file2.i`

## Impact
Just new capability

**Comment by friedmud** [comment]
I want it to be cleaner than the dollar bracket expressions for sure.  I don't see a need for a terminator...

I will once again advocate for it simply being a regular "parameter":

`include = file.i`

**Comment by cticenhour** [comment]
Based on our meeting with @aprilnovak and @miaoyinb, I'm pursuing top-level, whole-block includes for the time being, with the eventual use case being a regular "parameter" as @friedmud stated, so that we can effectively use CLI and selectively change aspects of sub-blocks. 

One sticking point identified in the discussion was deciding the point at which included input file content is added and what (if any) metadata is carried forward to do appropriate error checking and user-friendly console output if something in the included input content is incorrect. I'll work on prototyping both the pre-process option (via hit, where MOOSE will have less information about the origin of a piece of text) and a later option (where we might carry file metadata, like a filename/location, to slipstream into the regular error checking procedure).

**Comment by lefebvrera** [comment]
I'm an advocate for the `include` directive taking a single file path. Multiple paths can become problematic for a user if on the same line so requiring an `include` directive per file can simplify interaction. 

Question: are the relative file paths included based on the input performing the include or can it be alternatively a function of the application executing? 

Today's meeting discussed application 'defaults' which made me think the ability to have the `include` search an app directory might be desired. 

e.g.,  in file problem.i the directive `include file.i` will first search adjacent to problem.i for the file `file.i` and if this file doesn't exist it will search for `file.i` in `/path/to/app-opt/../defaults` (i.e., /app/herd/app/defaults) before producing a `file not found` error. 

An additional example: in `playground/problem.i` an include directive of `include material/foo.i` will first attempt to import `playground/material/foo.i` and if this file doesn't exist will search the applications 'defaults' directory for `material/foo.i` (e.g., /app/heard/moose/defaults/material/foo.i). 

Certainly, the initial implementation of this feature supporting input-relative files is simplest but wanted to make sure the requirements were fully understood/specified.
