### ISSUE TITLE
FVKernel save_in

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#20331]
## Reason

The `save_in` feature of Kernels is very useful for recording physical quantities (such as fluxes) and for debugging.  It'd be great if `FVKernel` could have this feature.

## Design

I'm sure @rwcarlsen or @lindsayad would design something nice!

## Impact

Add ability to save residuals from finite-volume kernels.

**Comment by lindsayad** [comment]
`save_in` is technically a deprecated feature in MOOSE. Everything that `save_in` does should be achievable using the newer tagging system and that works now with `FVKernel`

**Comment by WilkAndy** [comment]
So perhaps this issue should be "provide more-accessible documentation"?  I see that 235 input files still have `save_in` and a few documentation pages mention it.

**Comment by lindsayad** [comment]
I should also note that sadly @rwcarlsen is no longer working on MOOSE. It's mostly myself and some @GiudGiud maintaining finite volume now. I'm happy to see your interest in it!

**Comment by lindsayad** [comment]
Ok @WilkAndy I think `test/tests/tag/2d_diffusion_tag_vector.i` is a good example. This is a little more verbose than `save_in` but it is more flexible. `Kernels/extra_vector_tags` (and similarly for the BCs) is instructing that the residuals of that kernel should be saved into two vectors called `vec_tag1` and `vec_tag2`. `TagVectorAux` takes a `vector_tag` argument and a `v` argument; what that will do is extract values of the `vector_tag` vector at the elements corresponding to the degrees of freedom of `v` and write them into your aux variable.

You also have to specify `extra_tag_vectors` in the `Problem` block in order to create the extra tag vectors that your residual objects can fill-in.

Does that make sense?

**Comment by loganharbour** [comment]
@WilkAndy please do offer feedback for the tagging system if able!
