### ISSUE TITLE
Make `VariableValueTransferMaterial` work with distributed mesh

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#20798]
## Reason

This will enable thermal hydraulics module to run on distributed mesh when there is heat transfer from heat structure in the input file.

## Design

The critical lines are:
```
    const Node * const nearest = _nearest_node.nearestNode(nd.id());
    mooseAssert(nearest, "I do not have the nearest node for you");
    const auto dof_number = nearest->dof_number(_nl_sys.number(), _paired_variable, 0);
```

It can happen that we don't find a nearest node when using a distributed mesh.  This is not such a critical problem. We just need to make sure that we transfer only values for which we found the nearest node.

## Impact

THM will fully run on distributed meshes.

NOTE:

THM meshes are not usually that big that one would need to switch to a distributed mesh. However, in a multi-app setup when a master application is running on a distributed mesh and THM would be a sub-app, we would need THM to run on a distributed mesh as well. But, also usually people use `MultiAppUserObjectTransfer` to transfer value between THM and other apps and this transfer does not work with distributed meshes, thus the distributed mesh restriction is not very pressing.

**Comment by joshuahansel** [comment]
@makeclean The lines quoted on the description are from `VariableValueTransferMaterial`.

I believe @lindsayad was the original author. Alex, for a refresher, this is for coupling flow channels and heat structures. Is there some known issue/solution for nearest node locator for distributed meshes?

**Comment by lindsayad** [comment]
The geometric search objects use some old ghosting APIs that I am not all that familiar with. Conceptually, there can obviously problems if, for instance, one process owned all the flow channel elements and one process owned all the heat structure elements and you didn't have any ghosting.

I tried running the first test in `components/heat_transfer_from_heat_structure_1phase` with two processes and a distributed mesh and I got the following stack trace
```
Stack frames: 18                                                                                                      
0: libMesh::print_trace(std::ostream&)                                                                                
1: libMesh::write_traceout()                                                                                          
2: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*, std::ostream&)                   
3: libMesh::DistributedMesh::elem_ptr(unsigned long) const                                                            
4: MooseMesh::elemPtr(unsigned long) const                                                                            
5: FlowChannelAlignment::check(std::vector<unsigned long, std::allocator<unsigned long> > const&) const               
6: HeatTransferFromHeatStructure1Phase::check() const                                                                 
7: Component::executeCheck() const                                                                                    
8: Simulation::integrityCheck() const                                                                                 
9: IntegrityCheckAction::act()                                                                                        
10: Action::timedAct()                                                                                                
11: ActionWarehouse::executeActionsWithAction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator\
<char> > const&)                                                                                                      
12: ActionWarehouse::executeAllActions()                                                                              
13: MooseApp::runInputFile()                                                                                          
14: MooseApp::run()                                                                                                   
15: main                                                                                                              
16: __libc_start_main                                                                                                 
17: /raid/lindad/moose/modules/thermal_hydraulics/thermal_hydraulics-dbg() [0x40d69e]                                 
Stack frames: 8                                                                                                       
0: libMesh::print_trace(std::ostream&)                                                                                
1: libMesh::write_traceout()                                                                                          
2: moose::internal::mooseErrorRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, st\
d::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)                                        
3: void mooseError<char const*>(char const*&&)                                                                        
4: MooseApp::run()                                                                                                    
5: main                                                                                                               
6: __libc_start_main                                                                                                  
7: /raid/lindad/moose/modules/thermal_hydraulics/thermal_hydraulics-dbg() [0x40d69e]
```
so it seems like there are other issues with running THM with a distributed mesh that you need to address before getting to the lines that are hypothesized to be problematic.

**Comment by joshuahansel** [comment]
Just to capture it here, this discussion motivates the recent comments: https://github.com/idaholab/moose/discussions/23276.

**Comment by joshuahansel** [comment]
I can see why the above stacktrace occurs, but I'd need to invest some significant time to learn how to address it, especially since I'm not very knowledgable regarding parallel execution and distributed meshes.

@makeclean So you're really doing THM simulations where you need to distribute the mesh? Just curious what kind of problem you're running.

**Comment by lindsayad** [comment]
If this is something that's important I could possibly work on this on the indirect number

**Comment by makeclean** [comment]
Well what I'm trying to do is for a large complex geometry, generate the fluid network for the problem and couple that to the thermal part of the problem, then use a MultiApp to solve the coupled mechanical part of the problem. For example,

There is a THM cooling fluid which runs down the middle of the tube, and then this uses HeatStructure3D to then do the thermal calculation. I plan on doing this for a much larger system, and this already required a very wasteful MPI configuration to get enough memory to do the replicated mesh. If there is a better way for me to couple the heat flux from the THM to the thermal solve then I am all ears, as I'm heading towards doing it on this system, which is at least an order of magnitude more elements

What I really want to do is do that for this system, which is much more complex (showing VM Stress rather than temp) for which I'm currently using a simplified HTC approach. In general we're interested in given this a go for fairly complex fluid networks, coupled to complex hot structures.

**Comment by makeclean** [comment]
Not sure why images aren't rendering in line?

**Comment by joshuahansel** [comment]
I see - that makes sense for wanting/needing this fix, since you're working with 3D heat structures. Are your flow channels curved inside of the heat structure? I'm just wondering if our coupling component can handle curves like this, or if it requires a straight flow channel where it couples to the heat structure (it at least requires a one-to-one axial element mapping).

As far as coupling options, the approach you're trying to take is nice in the sense of convergence because it's full coupling, whereas a multi-app approach will require fixed point iteration. I'm curious which option is faster in the end, since the solves for the full coupling case are more expensive, but obviously there should be less total iterations. I don't have much experience to say which is faster.

In any case, I think fixing this distributed mesh issue would be a great improvement for the module. I think we at least need the option to experiment with this approach. I can't see much advantage to the module having distributed mesh capability if it doesn't work to couple to the only 3D components 😛 

@lindsayad I'd obviously love if you worked on this, but I don't know what your other priorities are. I'd be happy to work with you if there would be any help I could give. I want to learn more in this area so that I'm less dumb.

**Comment by makeclean** [comment]
There are curved structures inside, but given the discussion we had in https://github.com/idaholab/moose/discussions/22787 I'm going with approximating them with line segments for now.

**Comment by joshuahansel** [comment]
Ok, that was going to be my follow-up question. Fixing that elbow channel and making a more general one are things I definitely want to do as well (and that work, I'm probably actually capable of without help), but I don't know if I'll be able to work on it soon or not.

**Comment by lindsayad** [comment]
@joshuahansel if you want to take the lead, it might get done faster; or I should say that in my list of tasks this would probably be a month out. If you do take it on, I am happy to answer any questions regarding mesh distribution

**Comment by joshuahansel** [comment]
I will also probably need a few weeks at least before diving into this.
