### ISSUE TITLE
Velocity and characteristic length should be available as functors in FV

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#21065]
## Reason

Many correlations need `ADRealVectorValue` version of velocity and `ADReal` functor for the characteristic length.
In `GeneralFunctorFluidProps` we treat `characteristic_length` as a Real parameter. However, in Pronghorn
`characteristic_length` is often required as a functor with name "characteristic_length".  

## Design

1. I would like to have velocity added automatically just like speed. 

2. For `characteristic_length`: would it make sense to have `characteristic_length` as a Real parameter in the `NavierStokesFV` action and then add it as a functor?  `characteristic_length`  might change as a function of block, but that makes its treatment no different than say `ambient_convection_alpha`.

## Impact

Potentially more input options for `NavierStokesFV` action. 

@lindsayad @grmnptr @GiudGiud.

**Comment by GiudGiud** [comment]
1) see slack discussion, i agree

2) The action does not deal with fluid properties from a fp object currently. They are defined outside then the action is told what name to use (mu = 'mu' type parameters). 
So that s why we dont deal with characteristic_length in the action currently.

I think the issues are connex. If we move the material treatment in the action (eg fluid_props = fp in the action's parameter) then I see use moving the characteristic length there too

**Comment by snschune** [comment]
From my last inputs, I think the most convenient way to define characteristic length is via `ADPiecewiseByBlockFunctorMaterial`. Then it would be good if `GeneralFunctorFluidProps` would just pick it up as functor.

**Comment by GiudGiud** [comment]
ok for me. I ll tag it in my friction diode PR

**Comment by GiudGiud** [comment]
Closed by #20743
