### ISSUE TITLE
PenaltyEqualValueConstraint allocates nonzeros

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#21569]
## Bug Description

`PenaltyEqualValueConstraint` allocates non-zeros. I am not sure if this is generally the case for Mortar, or just this object.

## Steps to Reproduce

Set `Problem/error_on_jacobian_nonzero_reallocation = true` in `test/tests/mortar/continuity-3d-non-conforming/continuity_penalty_sphere_hex8.i`.

## Impact

Slow initial Jacobian computation which eventually becomes a real problem when the mesh becomes large.

**Comment by hugary1995** [comment]
@lindsayad @recuero

**Comment by hugary1995** [comment]
If it is obvious to you why this is happening, please let me know. That'll save me some time digging into the code myself. Thanks!

**Comment by recuero** [comment]
The behavior you describe is not limited to this mortar constraint.

**Comment by lindsayad** [comment]
New nonzeros on an undisplaced mesh or for an initial Jacobian evaluation on a displaced mesh are unexpected behavior and a concern to me. I see that the test you reference is on an undisplaced mesh, so this is concerning. The `AugmentSparsityOnInterface` relationship manager should be handling this, but clearly it's not. @recuero you mentioned on Slack you might want to take a shot at this. If you want to look into why `AugmentSparsityOnInterface` isn't doing its job, please go ahead. Otherwise since it's my code, I might be able to figure it out a little more quickly. Up to you!

**Comment by hugary1995** [comment]
I just wanted to point out the RM isn't the only possible source of error. Three situations:
1. The RM is missing some coupling, and we are inserting the Jacobian entries correctly. This is what you mentioned.
2. The RM is doing its job, but we are inserting entries in the Jacobian that are supposed to be zero. This could happen if nude_indices get too aggressive.
3. Both are wrong -- hopefully that's not the case here.

**Comment by lindsayad** [comment]
Now that I think about this ... IIRC @jbadger95 and I removed the sparsity pattern couplings between `Secondary` and `Primary` because at the time the only couplings were with Lagrange Multipliers and were consequently:

- `LowerSecondary`
- `LowerPrimary`
- `LowerLower`
- `SecondaryLower`
- `PrimaryLower`

**Comment by lindsayad** [comment]
This should be pretty easy to undo
