### ISSUE TITLE
Add an introductory slideshow for the Navier Stokes module.

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#21589]
## Reason
The Navier Stokes module is gaining popularity and having a slideshow on the basic concepts for workshops to come is beneficial.

## Design
Add a workshop-like slideshow to the NS module.

## Impact
Enhance user experience, make the developer team's job easier during conferences/workshops.

**Comment by WilkAndy** [comment]
@grmnptr , i have a phd student who is currently learning NS+MOOSE.  She may contact you regarding this.  When i've written similar material for PorousFlow, TensorMechanics and Geochemistry, i've found user input quite valuable in helping me answer questions people are interested in, so i hope she does spam you with lots of ideas!

**Comment by JuliaHLee** [comment]
@grmnptr , hi, I am the PhD student @WilkAndy mentioned. I am really happy to hear the news that the "slideshow" will be added for the NS module. I made a simulation with a simple mesh working, using 'Incompressible Finite Volume Navier Stokes' for advective heat transport. However, when I used a mesh file with a "complicated" micro-scale geometry, the solve did not converge anymore. Would the slideshow include tips for setting properly boundary conditions, as well? Is there specific convergence criteria for NS module? Also, I am using FVInterfaceKernels for a transient simulation, but I only found examples for steady state simulations. Is there an available example of a transient simulation with this Kernel?

I hope these questions reach you. And thanks a lot in advance!

**Comment by JuliaHLee** [comment]
@grmnptr Thanks for the prompt reply and your suggestion! Sure, I will post the problem on the discussionn forum for the brainstorming. By the way, with the simple model, I also had an issue making me wonder. Eventhough I could make the model run without an error, varing velocity values did not change my results. Would it be a kind of basic problem? 

Due to the problem, I could not trust my simulation results. So I was thinking, it would be great if I know the very basic structure of an input file for 'Incompressible Finite Volume Navier Stokes' to simulate advective heat transport.

I am really looking forward to the slideshow!

**Comment by grmnptr** [comment]
Yes, I would not trust those results either. However, without knowing the details of your problem, I doubt we can help you. I encourage you to share as much of the details as possible on the github/discussion forum so that we can analyze where the strange behavior is coming from. Thanks!

**Comment by JuliaHLee** [comment]
@grmnptr Thanks! I will definitely use the discussion forum.
