### ISSUE TITLE
Nonlocal Scalar Damage Models

### ISSUE THREAD

**Issue by maxnezdyur** [idaholab/moose#21786]
## Reason
MOOSE has local damage models but they can exhibit mesh sensitivity. Nonlocal damage models allow for less mesh sensitivity while enabling the use of the same models. Damage averaging approach would be an easy first step that wouldn't require any change to existing damage models.
## Design
Create new damage model that would work with any existing damage model. It takes in a some form of averging user object and creates new damage_index for ComputeDamageStress.
## Impact
Would allow every current scalar local damage model to be used as a nonlocal version of itself.

**Comment by bwspenc** [comment]
We discovered that the initial version of this fails parallel tests for higher processor counts because we are not communicating data from processors that have elements that fall within the averaging radius, but are not the owning processors of the current element's neighbors. @dschwen has an idea on a pretty easy fix for this.

**Comment by loganharbour** [comment]
We need an open issue for this for SQA

**Comment by dschwen** [comment]
> We need an open issue for this for SQA

There ya go :-)
