### ISSUE TITLE
Set coordinate system error

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#22928]
## Reason
The set coordinate system stuff (related to multiapp transforms) broke a contact tutorial here: `moose/modules/combined/tutorials/introduction/thermal_mechanical_contact/thermomech_cont_step01.i`  (lesson learned: don't just do `check_input = true` testing!)

The error for `thermomech_cont_step01.i` is

```
*** ERROR ***
The following error occurred in the object "mesh", of type "MeshGeneratorMesh".

Requested subdomain 1 does not exist.
```

`Requested subdomain 1 does not exist.`  is confusing. This is a lower-d subdomain created by the contact action. It it referenced nowhere.

## Design

Make this work again (with a `block = 0` in `GlobalParams` to avoid doing mechanics on the lower-d subdomain)

## Impact
Working tutorial

**Comment by lindsayad** [comment]
So I don't think there's anyway we can just "make this work again" with no modification to the current input file. This has probably been broken since we changed to have `block` be a `Mesh` parameter as opposed to a `Problem` parameter. The only way I can think of to make this work again with no modification to this input is to change the parameter name. I don't think that `block` is a very descriptive parameter name for the mesh/problem coordinate system type.

Tangential to this, I can definitely make the current error message more descriptive which would make it obvious how a user should update this input file (e.g. what the correct values of `Mesh/block` should be to override the `GlobalParams/block`). Is that a viable solution?

**Comment by lindsayad** [comment]
What do you think of this output?
```
*** ERROR ***
/home/lindad/projects/moose/modules/combined/tutorials/introduction/thermal_mechanical_contact/thermomech_cont_step01.i:8: (GlobalParams/block):
    If the 'block' parameter is supplied to the Mesh, then it must cover all the mesh subdomains. However, the mesh subdomains: 'pillars_primary_subdomain, pillars_secondary_subdomain' were not specified in the 'Mesh/block' parameter. Please add these
```

**Comment by lindsayad** [comment]
If you don't like the solution, you need to propose another one. Do you want use to rename the `Mesh/block` parameter? As it is now, I don't think there's much more we can do technically. It appears that the user is giving a specification for  coordinate system types, but they haven't specified coordinate system types for all the blocks in the mesh. I think it would be irresponsible of us to assume a coordinate system type for unspecified blocks. Much better to error in my opinion
