### ISSUE TITLE
VectorPostprocessorFunction random behavior when using parallel execution

### ISSUE THREAD

**Issue by lingzou** [idaholab/moose#23514]
## Bug Description

When using `VectorPostprocessorFunction`, simulation produces random results with parallel execution depending on the number of CPUs used.

## Steps to Reproduce

The error could be reproduced with the attached input file.
[VecPPSFn.txt](https://github.com/idaholab/moose/files/10806248/VecPPSFn.txt)

The input file describes a one-dimensional diffusion equation with body force and two Dirichlet BCs. For the body force,

- when a constant value is used, the results are as expected using one CPU or parallel run
- when a linear function is used, all good (1 CPU or n CPUs)
- when the combination of `ConstantVectorPostprocessor` and `VectorPostprocessorFunction` is used, the results are good using 1 CPU, while it generates random results depending on the number of CPUs are used.
 
## Impact

Since it gives random results depending on the number of CPUs used, so this defect affects our simulations.

**Comment by lingzou** [comment]
@travismui FYI.

**Comment by GiudGiud** [comment]
We need to always broadcast results to all ranks, rather than only keep the full copy on rank 0. 
Only having a copy on rank 0 is an optimization for output & scalability.

The default should be changed. Scalability is much secondary to correctness

**Comment by friedmud** [comment]
Doing an all-to-all is non-trivial.  There could be a huge amount of date - even enough to crash the application.  Further, the VPP might be a per-processor value (or values)... that doesn't make sense to synchronize.  The default needs to be conservative and match the primary use case (outputting values) which it does.

But, maybe the documentation needs to be updated to make sure it's clear.

@lingzou , if you check the documentation here: https://mooseframework.inl.gov/syntax/VectorPostprocessors/index.html .  Is the way you're getting VPP values consistent with the documentation in the "Parallel Assumptions" section?

If you need the VPP to be synced to all procs... then you need to use this invocation:

```C++
getVectorPostprocessorValue('the_vpp_parameter_name', 'the_vector_name', true)
```

That `true` on the end tells MOOSE to replicate the vector on all the procs.

If you've already checked that - can you give us more info about your particular issue?

**Comment by friedmud** [comment]
Sorry, @lingzou ... didn't notice that you were using an object from MOOSE to get the value of the VPP.

The issue is here: https://github.com/idaholab/moose/blob/next/framework/src/functions/VectorPostprocessorFunction.C#L43

Looking at the tests for that object, it looks like it was intended to be used by a Postprocessor, which is why they didn't see an issue.  At the very least here, we need a `parallel_sync` or `parallel_broadcast` option for `VectorPostprocessorValue`.  Let me work up a quick PR.

@lingzou @travismui , for now, you can go put `true` as the last argument for each of those `getPostprocessorValue` calls and everything should work.

**Comment by friedmud** [comment]
Ok - the fix is up over here: https://github.com/idaholab/moose/pull/23588

It turns out that you just got TERRIBLY unlucky!  `ConstantVectorPostprocessor` is one of the very few in the framework that is not inherently synced... if you would have used ANY other VPP this would have been fine!

At any rate: it was a real bug... VectorPostprocessorFunction should definitely have been requesting parallel syncronized VPPs.

**Comment by travismui** [comment]
Thanks for the fix @friedmud!

**Comment by friedmud** [comment]
All fixed up and merged into `next` should travel through to `devel` and `master` over the next hour or so.

Thanks for the bug report - let me know if you have any further trouble with it!

**Comment by lingzou** [comment]
@friedmud Derek, thanks for the help!
