### ISSUE TITLE
./find_hung_process.py is outdated

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#23639]
## Reason
Still refers to bechler fission and falcon

## Design
Add Lemhi, Sawtooth and Hoodoo in there
Maybe also the ANL & ORNL clusters?

## Impact
Better debugging experience on INL infrastructure

**Comment by permcody** [comment]
Yeah... I don't disagree. It's hard to keep this up to date. Perhaps I should get the HPC team to own it!

**Comment by permcody** [comment]
The find_hung_process script was significantly updated in #23946. I purposely left the node name patterns in there for both fission and bechler because they are common patterns for non-INL clusters. Users do have to update the script to match their cluster so it's fine. As we get new clusters on site, we might update it again, but for now. I'm going to close this ticket so I don't plan to specifically address just the names.
