### ISSUE TITLE
Parallel inconsistency in _penalty_ mortar UO system

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#24664]
## Bug Description
Penalty mortar has parallel inconsistent results when the contact surface spans multiple MPI ranks. The weighted quantities (weighted gap) at nodes on proc boundaries have the wrong values.

### Baseline
In the contact module run

```
./run_tests --re cylinder_friction --heavy
```

See both tests passing when running on 4 CPUs. 

### Failure case
Apply [0001-test.patch](https://github.com/idaholab/moose/files/11727631/0001-test.patch)

```
./run_tests --re cylinder_friction --heavy
```

See `test:pdass_problems.cylinder_friction_penalty` fail when running on 1 CPU (because it was golded to a faulty 4 CPU run).

## Impact
Prevents use of MPI parallelism with mortar contact.

**Comment by lindsayad** [comment]
It seems like you've emphasized the penalty part of the issue. Have you tested with LMs?

**Comment by lindsayad** [comment]
Hmm I see that the corresponding LM test passes in serial

**Comment by recuero** [comment]
I used the option `send_data_back` for the penalty frictional object. I may have missed something there.

I did try to setup a `very_parallel_frictional_penalty` test to catch this type of issue.

**Comment by lindsayad** [comment]
Yea that test doesn't have a corresponding serial version, but I just ran `very_parallel_frictional_penalty` in serial and it passes. 

I also just removed the friction pieces from the cylinder test and then an exodiff passes between serial and parallel, so maybe it is the velocity portion?

**Comment by lindsayad** [comment]
Nothing appears blatantly wrong to me

**Comment by lindsayad** [comment]
@dschwen what diagnostic did you use for this conclusion?

> The weighted quantities (weighted gap) at nodes on proc boundaries have the wrong values.

**Comment by lindsayad** [comment]
Ok I executed the user object weighted gap computations on initial and those do not exodiff between serial and parallel, so I believe I can rule out issues there. Unfortunately there is nothing going on with the weighted velocities during initial so I don't have any data with that yet. I want to remove the solve from the "equation", so I can isolate possible differences due to solve vs. TIMPI communciations

**Comment by lindsayad** [comment]
Ok I turned off the contact constraints for one time step to allow the domain to move. yea it appears we are getting something wrong with the tangential velocities
```
Nodal variables:
   tangential_vel_one           rel diff: -2.0905693e-03 ~ -4.1811385e-03 = 5.00000e-01 (node 270)
```

**Comment by lindsayad** [comment]
Ok the problem is in the `_dof_to_real_tangential_velocity`. `_dof_to_weighted_tangential_velocity` is perfectly fine. The latter always does addition (`operator+=`) in the local (`computeQpIProperties`) code whereas for reasons @recuero will need to tell me, the former always just sets (`operator=`) in the local code. However, when we run in parallel we do `operator+=` for both weighted and non-weighted. 

For multiple quadrature points (which is always the case), it seems like the latter quadrature point will always set the `real_tangential_velocity`. That seems like a weird heuristic to me.

**Comment by recuero** [comment]
I agree that's best for consistency and for leveraging existing parallel API to make the real weighted velocities behave just like the weighted velocities.

**Comment by lindsayad** [comment]
So you think it's appropriate to use `operator+=` everywhere for both velocity kinds? And the "real" one is the non-weighted right? We don't multiply by test or JxW for that. 

What is the use case for the "real" vs "weighted" velocities?

**Comment by recuero** [comment]
Yes, I believe `operator+=` is appropriate to make the `real` computations behave the exact same way as the `weighted` (I remember I had a couple of things in mind when I was coding that object, and, obviously, I didn't clean up properly).

The usage for the `real` quantity lies in the fact that's more physical. As such, if we want to compute (weighted) slip quantities to build frictional penalty forces, the user can have a more direct information on how to select the frictional penalty value, i.e. he/she can have an idea of how much the system is going to slip. Therefore, the `real` quantity should also be a mortar quantity to preserve the consistency of the approach.

**Comment by recuero** [comment]
I think we do need to multiply by the `test` functions to perform regular interpolation of the "real" quantity.
