### ISSUE TITLE
Subapp of type FullSolveMultiapp does not output checkpoint when enabled in subapp input file

### ISSUE THREAD

**Issue by pbehne** [idaholab/moose#24777]
## Bug Description
When running a FullSolveMultiapp subapp after each time step of a transient parent app, subapp checkpoints are not written when Outputs/checkpoint = true is set in the subapp input file.

## Steps to Reproduce
Do not set Outputs/checkpoint in the main app input file. Set Outputs/checkpoint = true in the subapp input file. When running the main app input file, an empty folder is created for subapp checkpoints, but no checkpoints are written. When running the subapp file directly, checkpoints are written as expected. This undesired behavior can be remedied by adding the following block to the subapp input file:

[Outputs]
    [checkpoint]
        type = Checkpoint
        additional_execute_on = 'FINAL'
    []
[]

## Impact
Given the existence of the "additional_execute_on" workaround, this is an annoyance.

**Comment by GiudGiud** [comment]
I found the problem here (or at least one)

it does output, but it s output on 'FINAL' every fixed point iterations, and we end up meeting the num_files specified (2 by default) and DELETE the checkpoint from the folder.

@harterj

Proposed fixes:
- if outputting on FINAL, then add a check that num_files (in subapp) > num_fixed_point (in main app). 
This is not great. Subapp should not know about main app

- Execute final of the multiapp after the FP iterations only. This might be complicated because the main app makes this decision

- Add more logic to the deletion to check that there are actually this many files in the folder before deleting. We are deleting at 2+ files but there's only 1 file in that folder. We are counting the files wrong basically

**Comment by lindsayad** [comment]
Is this comment related to https://github.com/idaholab/virtual_test_bed/issues/369 ?

**Comment by GiudGiud** [comment]
Yes this is that problem

**Comment by harterj** [comment]
🔥  thank you!
