### ISSUE TITLE
Non-functor materials are listed under FunctorMaterials in doc

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#25109]
## Bug Description
On https://mooseframework.inl.gov/syntax/index.html, all types of Materials are listed under FunctorMaterials, not just FunctorMaterials.

## Steps to Reproduce
See above.

## Impact
Poor documentation; difficult to find actual list of FunctorMaterials.

**Comment by GiudGiud** [comment]
use this page for now
https://mooseframework.inl.gov/source/index.html

and this problem is not restricted to FunctorMaterials
ControlLogic shows all the Controls
Materials still shows FunctorMaterials

There is something I must have done incorrectly when I split off FunctorMaterials, that I did correctly when I split of SolidProperties. But I dont know what!

**Comment by joshuahansel** [comment]
> There is something I must have done incorrectly when I split off FunctorMaterials, that I did correctly when I split of SolidProperties. But I dont know what!

What did you split SolidProperties from? Does SolidProperties have any other syntax than "SolidProperties"? FunctorMaterials can be made under either "Materials" or "FunctorMaterials".

**Comment by GiudGiud** [comment]
It was documented under userobjects.
The fact that it has its own syntax is probably the answer here

**Comment by GiudGiud** [comment]
this should be resolved once #26377 is merged

**Comment by cticenhour** [comment]
Due to the noted PR, FunctorMaterials and regular Materials are now shown only in their particular sections on the MOOSE syntax page. Closing this issue.
