### ISSUE TITLE
Update SLEPc

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#25128]
## Reason
With the merging of https://gitlab.com/slepc/slepc/-/merge_requests/574 we will want to update SLEPc such that we can finish up #20095 

## Design
Update slepc after #23502 is merged, which updates PETSc to at least 3.19. I believe `--download-slepc` takes a commit hash

## Impact
New SLEPc features, including the ability to supply a custom normalization function

**Comment by cticenhour** [comment]
Do you know if updating to PETSc 3.20.0 would get you the updated SLEPc that you need? I just noticed your LSC scaling feature made it into the new release (tagged yesterday!). It is likely too soon for another full update, but I thought I would bring it up since it likely involves a SLEPc bump too.

**Comment by lindsayad** [comment]
Yes it would

**Comment by lindsayad** [comment]
Closed by #25784
