### ISSUE TITLE
Update WASP `gatherDocumentFormattingTextEdits` API

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#25558]
## Reason
WASP made changes to the `gatherDocumentFormattingTextEdits` API.

## Design
Correct the override for this API in the `MooseServer`.

## Impact
Minimal, adds features.

**Comment by brandonlangley** [comment]
@loganharbour -

I'm closing this since the API was updated in commit https://github.com/idaholab/moose/pull/25432/commits/063358bf07c675daf399119dc22eec2337a8941b of PR https://github.com/idaholab/moose/pull/25432 which was [merged](https://github.com/idaholab/moose/commit/ab89aee763cddf8689693629d508ad63a87bcd79) about two months ago.

**Comment by brandonlangley** [comment]
@loganharbour -

The API was updated in commit https://github.com/idaholab/moose/pull/25432/commits/063358bf07c675daf399119dc22eec2337a8941b of PR https://github.com/idaholab/moose/pull/25432 which was [merged](https://github.com/idaholab/moose/commit/ab89aee763cddf8689693629d508ad63a87bcd79) about two months ago, so this can be closed.
