### ISSUE TITLE
Output high order elemental variables into Exodus

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#2716]
Currently in libMesh::ExodusII_IO::write_element_data(), only variable in type of constant monomial is written. We probably can remove this limitation by getting the element averaged values of any high order variables (even for nodal variables).

@jwpeterson

**Comment by lindsayad** [comment]
@YaqiWang Did you ever open a ticket for this in libmesh?

**Comment by YaqiWang** [comment]
I did not. But I guess @jwpeterson did.

**Comment by jwpeterson** [comment]
It's libMesh/libmesh#1420

**Comment by lindsayad** [comment]
So it looks like there's a method in libmesh for writing out discontinuous solution data to exodus: `ExodusII_IO::write_discontinuous_exodusII`. We actually had someone here at the training demonstrate its output in VisIt and it looks exactly like the kind of thing I would like.

**Comment by YaqiWang** [comment]
I am glad to see that! If we can have a parameter to control the number of uniform cuts on each element in `es.build_discontinuous_solution_vector`, it will be even greater! We do not need to convert element variable to nodal for output anymore.

**Comment by YaqiWang** [comment]
There is a problem, if all other variables are nodal, except one elemental aux, we will have to create the discontinuous mesh for all variables. One solution is to generate two Exodus files, one for nodal another for elemental. Also the nodal exodus output can be used to restart a variable but elemental exodus output cannot. It will be ideal if we extend ExodusII format, so that elemental variable can store multiple values like what we did in L2_LAGRANGE...

**Comment by kevindugan** [comment]
Another option is to treat continuous variables as discontinuous when exporting to exodus files (By the way, this would also port to VTK formats as well). I believe the way Exodus handles discontinuous variables is to define a spatial coordinate multiple times for each nodal value it can have. Then the connectivity for a given element references the correct nodal coordinate corresponding to the value for that element. There's nothing to stop us from multiply defining coordinates that have the same value.

This would give us a continuous looking solution even if behind the scenes it is discontinuous. The only trouble I could see is that the gold files for regression tests would need to be updated under this scheme.

**Comment by kevindugan** [comment]
I opened up an issue in libMesh to add some functionality which will facilitate this issue.

libmesh/libmesh#1503

**Comment by kevindugan** [comment]
So I've finally gotten some free time to look back into this. I wanted to discuss the commit 8adf8f2 before submitting a pull request.

What do you guys think?

**Comment by permcody** [comment]
@kevindugan - Nice work, but there are a couple of things we should work out with the interface and the test you've supplied.

1) Interface: I think that `discontinuous` should just imply `elemental_as_nodal`. I would make that work so you don't have to turn them both on. However, you should still check the value and make sure that the user hasn't explicitly supplied conflicting values.

2) This test: Unfortunately, this test doesn't really show this capability really working. We can produce a field like this with elemental monomials already. Yes, I realize that this is actually a nodal field that is just constant across the element. So while this test is OK, it would be really cool to see something non-constant per element. I believe if you just jack up the order on this test, we'll start to see some shape on the elements. I'm not a huge fan of using RandomIC though for most tests so maybe we can use some sort of forcing function that produces shape? 

You can either just supply a higher order function with this kernel https://github.com/idaholab/moose/blob/devel/framework/src/kernels/BodyForce.C or come up with something that will give us confidence this is working.

Minor: I wouldn't use `SelfAux` at all. You should be able to setup the IC field and just not have any active AuxKernels at all.

Great new capability - Thanks!

**Comment by YaqiWang** [comment]
I added a legacy VTK writer in Rattlesnake, which can output high-order elemental variables in legacy VTK format (text file with the same idea of this discontinuous Exodus). They are better than nothing, but I have to admit all of this are not ideal.

The ultimate fix would be in Exodus format... The problem of Exodus format is that it is not aware of the type of shape function associated with the solution coefficients. I mentioned a idea to @jwpeterson long ago which is very similar like @kevindugan did here: to simply support multiple values of an element for elemental variables, which are the values on the connecting nodes of the element. If the mesh is not in high order, we can still virtually create more nodes in a high-order mesh and do the output. In this way, we eliminate the ambiguity of shape functions. Of cause when we load the variables, we have to perform an internal conversion from these values on nodes to coefficients of shape functions.

But this requires changes in Exodus, which does not have a public repository we can contribute to. And possibly even we made the change, it would take a while to have visualization packages to support the change.

**Comment by YaqiWang** [comment]
![screen shot 2018-04-06 at 11 52 07 am](https://user-images.githubusercontent.com/6607496/38436118-fbeb0c94-3990-11e8-88d6-a3242396f2df.png)
This is the screenshot on the user manual about the writer I have mentioned.

**Comment by kevindugan** [comment]
@permcody Thanks for the critiques. 

For your first point, is it possible to override a parameter that the user supplies? Originally I was wanting to force `elementa_as_nodal` to true if `discontinuous` was true, but I didn't think it was possible since the parameters argument passed around in constructors is `const`. Could you expand on how I could implement one parameter implying another?

For your second point, I agree that the test was a little simplistic. I've since worked on a more aggressive test which solves Poisson's equation in 2d with linear discontinuous elements. Blow is the solution output.

![screen shot 2018-04-06 at 14 17 10](https://user-images.githubusercontent.com/26255590/38438756-6b2142fa-39a9-11e8-973c-701d246c5d3a.png)

@YaqiWang If I understand your point, you're talking about how visualization formats won't allow you to specify the shape function within an element. I agree with this, but we can still take care of the intermediary step where continuity is not forced for discontinuous elements.

**Comment by permcody** [comment]
> For your first point, is it possible to override a parameter that the user supplies?

Yes, you can ask the InputParameters object how the parameter was set:
https://github.com/idaholab/moose/blob/devel/framework/include/utils/InputParameters.h#L376-L381

This can help you detect when a user actually puts something like this in the input file (invalid combination):
```
elemental_as_nodal = false
discontinuous = true
```

Since elemental_as_nodal defaults to false, you'd want to know whether or not the user actually typed this, or it just came in through the default. I'd suggest checking how it was set and if it just coming in as a default, you can promote that value automatically to true when discontinuous is true.

> Originally I was wanting to force elementa_as_nodal to true if discontinuous was true, but I didn't think it was possible since the parameters argument passed around in constructors is const

Correct! You don't want to try to change parameters in the InputParameters object. They aren't intended for communication between objects (actually that's not true for the special case of Controls, but that doesn't apply here). In general, parameters should be treated like inputs. However, your instance variables can be set however you want them to be set based on the InputParameters, they don't have to match (as I'm suggesting here).

Nice output. I'll load this up in Paraview and see what it does (probably Peacock too).

**Comment by kevindugan** [comment]
> I'd suggest checking how it was set and if it just coming in as a default, you can promote that value automatically to true when discontinuous is true. ... However, your instance variables can be set however you want them to be set based on the InputParameters, they don't have to match (as I'm suggesting here).

Ok I think I see where I was getting hung up. There doesn't seem to be an instance variable `_elementa_as_nodal` floating around. This is retrieved in `AdvancedOutput.C` through the getParam function. I'll add in some instance variables to handle this case.

**Comment by permcody** [comment]
Great Thanks!

**Comment by YaqiWang** [comment]
This can be closed. Thanks @kevindugan.
