### ISSUE TITLE
Support sub-app restart with different sub-app configuration

### ISSUE THREAD

**Issue by NamjaeChoi** [idaholab/moose#27178]
### Motivation

In reactor physics, it is common to perform an accident analysis for a depleted core condition. This is achieved by depleting a core to a certain point and restarting a transient calculation from it. Depletion calculation is a pseudo-state-state calculation, so sub-apps are typically configured in the steady-state mode (`Steady` executioner and `FullSolveMultiApp`). However, restarting a transient calculation from it requires changing sub-app configurations. Under this condition, it seems that the main-app cannot restart sub-apps automatically.

### Design

Support changing sub-app configurations during restart.

### Impact

Checkpoint restart will be able to support more variety of applications.

**Comment by NamjaeChoi** [comment]
@loganharbour

**Comment by loganharbour** [comment]
This configuration with default behavior is currently supported.

The issue with this example was that the `FullSolveMultiApp` was configured `no_backup_and_restore=true`, which was required for picard iteration within the multiapp. However, the desired FINAL checkpoint from the main application did not trigger a backup in the multiapps due to said parameter being set.
