### ISSUE TITLE
Default to running PenetrationAux on initialization

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#3796]
Modify the Action that sets up contact to ask for PenetrationAux to always be run on initialization.  This will make it so apps will run the same regardless of how legacyUoAuxComputationDefault() is called.

**Comment by GiudGiud** [comment]
Looking at 
https://github.com/idaholab/moose/blob/6463c4517ad5e4f604ae75607a2fcc83c4890f50/modules/heat_conduction/src/actions/ThermalContactAction.C
https://github.com/idaholab/moose/blob/ea3a5f0c994658267b551131fe73c93020b4a4da/modules/contact/src/actions/ContactAction.C
this has been fixed, it s executed on INITIAL

Fixed by https://github.com/idaholab/moose/pull/8452
