### ISSUE TITLE
Create meta material to sum up multiple Derivative Materials

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4486]
This meta-material will allow the user to generate a new Derivative Material from the sum of two or more Derivative Materials. Both the function values as well as all derivatives are summed up.

It would be nice, if this material could find out the set of existing derivatives automatically and only skip non existing derivatives automatically.

**Comment by andrsd** [comment]
This could be generalized to sum up any coupled material properties (not just the derivatives). I bumped into a use case once already, but it was a minor thing, so I did not get to implement this. Since MOOSE does have additive property on the material properties (unlike for example residuals), this would be a nice feature...

Just my 2 cents.
