### ISSUE TITLE
LinearElasticMaterial should provide d/dT derivatives

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4499]
Similar to the ```EigenStrainBasematerial``` there is a dependency of stress free strain on a nonlinear variable (in this case Temperature rather than concentration). So this material should provide the appropriate d/dT derivative, right @tonkmr ?

**Comment by WilkAndy** [comment]
Related to your question: is "T" included in the appropriate place in TensorMechanics?

Eg, for me, porepressure "P" is more useful, and is basically the same kind of coupling - modifying the diagonal terms of stress - but I have not yet included "P" in any code, eg, StressDivergenceTensors, because i don't think it's really the right place for it.  I would prefer to derive from StressDivergenceTensors some class with a "P" in it.

Other people will want both "T" and "P" coupling for Thermo-Hydro-Mechanical simulations.

So if you're looking at the "T" stuff, perhaps you could re-write stuff bearing in mind that I will eventually put a "P" there too.

a

**Comment by WilkAndy** [comment]
Oh, also i will want a "C" to modify the diagonal terms of stress - it is the concentration of a chemical

**Comment by dschwen** [comment]
We have c in EigenStrainBaseMaterial. In there you can see how to add it to
other materials.

**Comment by WilkAndy** [comment]
Aha, i see it.  I'm not sure how it works.  Does your method work for modifying the stress, rather than the strain, with plasticity?

**Comment by dschwen** [comment]
```LinearElasticMaterial``` is deprecated in favor of the plug&play TM system.
