### ISSUE TITLE
Multiphase plasticity discussion

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4505]
@tonkmr , @cpritam , and @WilkAndy I've just added the coupling of elastic and chemical free energies in a new (material based) way that allows us to construct multiphase materials. Each phase has its own ```LinearElasticMaterial``` (or derived class), and the global stress is computed from the phase stresses.

The issue is that strain is really not a phase property, but a global property. This is not yet a problem, as all  ```LinearElasticMaterial```s just compute the strain from the displacement (and thus get the same strain value in each phase). However when we allow for plasticity in the current system each phase could in theory compute its own plastic strain.

Am I seeing a problem where we won't have one? Should we maybe separate the stress and strain calculations into separate classes? I.e. have a per-phase stress, but only have a global strain calculation? How would that fit into the current plasticity system?

**Comment by cpritam** [comment]
The strain (kinematics) and stress calculation (constitutive) classes can
be separate. The plasticity system will still work as long as it receives
the correct strain increment (for rate formulations) or deformation
gradient (total formulation like crystal plasticity).

For multi-phase material with plasticity the evolution of state variables
of every phase has to be done carefully (relation of evolution of state
variables of a phase with the corresponding phase evolution).

**Comment by WilkAndy** [comment]
I can't make a lot of useful remarks because i don't know what multiphase plasticity is.  My plasticity algorithms have input (strain increment, old internal parameters, old stress, old plastic strain), and output (new internal parameters, new stress, new plastic strain).  So i think they would fit into your scheme.  

Somehow you have to calculate elastic strain given the total strain and all your phases' plastic strains, but i presume you know how to do that.   Perhaps it is similar to my multi-surface stuff where there are many internal parameters (measures of plastic strains), and there is a well-defined way of defining the plastic strain increment via the potential function.

Anyway, i bet whatever you do will be an improvement!

a

**Comment by dschwen** [comment]
Looks like @tonkmr 's work on #4716 and #4743 is where this should be discussed.
