### ISSUE TITLE
DG with second_order mesh is stuck (very slow)

### ISSUE THREAD

**Issue by lw4992** [idaholab/moose#4518]
I added "second_order = true" in mesh block using  moose/test/tests/dgkernels/3d_diffusion_dg/3d_diffusion_dg.i to test DG with second order element. There was no results printed out when one minutes passed. It was stuck.

**Comment by jwpeterson** [comment]
On Tue, Jan 13, 2015 at 8:50 AM, lw4992 <notifications@github.com> wrote:

> I added "second_order = true" in mesh block using
> moose/test/tests/dgkernels/3d_diffusion_dg/3d_diffusion_dg.i to test DG
> with second order element. There was no results printed out when one
> minutes passed. It was stuck.
>

That will only change the mesh, not the order of approximation of the
variables.

Nevertheless, it does sound like a bug.

-- 
John

**Comment by lw4992** [comment]
Yes, the results should be same with first order mesh, since the grid of this case is straight.

**Comment by permcody** [comment]
It's not stuck. I just ran a profiler on it and it's just very, very slow. It looks like we are calling libMesh::Elem::volume() inside of the computeQpJacobian() and computeQpResidual() which is taking a ridiculous amount of time. Optimization will be needed here. We could cache those calls if the mesh isn't moving. Even if it is moving some amount of caching could be done since we make these calls per neighbor element.

**Comment by friedmud** [comment]
We already cache those for this purpose: _current_elem_volume :
http://mooseframework.org/docs/doxygen/moose/classKernelBase.html#a030007b5c38c73792f1b5211f3fb22ed

If there is a neighbor volume or something that isn't currently there it
should get added.

If I remember correctly we are caching these in Assembly...

**Comment by lw4992** [comment]
Have fixed.
