### ISSUE TITLE
Need to error if trying to retrieve coupling that doesn't exist

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#4546]
It turns out that you can call `coupledValue()` or `coupledGradient()` or whatever and pass in _anything_ and `Coupleable` will happily give you back a vector with zeroes in it (the "default")... regardless of whether or not you added any coupling parameters in `validParams`.

This can manifest as just a slight misspelling between what you did in `validParams` and what you're doing in `coupledValue()` that can cause you to lose a whole night of progress while you try to figure out just _what_ in the hell is going on... :rage:

**Comment by permcody** [comment]
oh yes... I can see that happening - it's a new feature!

**Comment by permcody** [comment]
Wait - that's not what I see:

```
outputs/debug.show_var_residual_norms_debug: *** ERROR ***
outputs/debug.show_var_residual_norms_debug: Attempted to retrieve default value for coupled variable 'var2a' when none was provided. 
outputs/debug.show_var_residual_norms_debug: 
outputs/debug.show_var_residual_norms_debug: There are three reasons why this may have occurred:
outputs/debug.show_var_residual_norms_debug:  1. The other version of params.addCoupledVar() should be used in order to provde a default value. 
outputs/debug.show_var_residual_norms_debug:  2. This should have been a required coupled variable added with params.addRequiredCoupledVar() 
outputs/debug.show_var_residual_norms_debug:  3. The call to get the coupled value should have been properly guarded with isCoupled()
```

**Comment by friedmud** [comment]
I'll try to recreate it with a test case

**Comment by permcody** [comment]
Marking as minor unless you can reproduce.

**Comment by friedmud** [comment]
I'll give it a whirl tomorrow

**Comment by friedmud** [comment]
I can confirm it.  It happens when you call `CoupledGradient()`.

To test it I added a bogus `coupleGradient()` call in CoupledForce like this:

```C++
CoupledForce::CoupledForce(const std::string & name, InputParameters parameters) :
    Kernel(name, parameters),
    _v_var(coupled("v")),
    _v(coupledValue("v"))
{
  coupledGradient("q");
}
```

Then I just ran the `tests/coupled_dirichlet_bc` test (which uses CoupledGradient).

That _will_ error out if it is a `coupledValue("q")` call instead... but does absolutely nothing if it's CoupledGradient.

**Comment by permcody** [comment]
Cool thanks

**Comment by permcody** [comment]
Someone made a decision to make those coupling calls return zeros. IIRC this was to cleanup all of the ternary operators so that you don't have to check whether something was coupled or not to call the coupling method. You could just call it and have it return a sensible default (i.e. zero). There's a quick fix for this but we could also talk about extending the design too.

1. Quick Fix:
We could have the system throw a warning (or error) if the user requests a variable that was never added. This shouldn't break anything and should take care of this particular case (misspelled coupling).

2. Possible extended design: 
Support for additional defaults. What should the behavior be when you request a coupled gradient or second for a variable where you supply a default? Should we support a syntax where I can say the gradient is (1, 0, 0)? If so, what happens when the user wants both the value and gradient of a "default" value? In some cases those two may be in direct conflict (i.e. a constant value everywhere and a non-zero gradient). Implementing a system where the user supplies one specific type whether it be a scalar, vector or tensor wouldn't be difficult but I'm not sure anyone really needs this capability.

**Comment by friedmud** [comment]
1.  we should definitely do (that's really what this ticket is for).  If you never added a coupling parameter with that name - then you should get an error (you do for the value case).

2.  In the input file you can currently put 3 things:
  1.  Name of coupled variable
  2.  Constant value
  3.  "Function" expression

For each of these things here's what the Gradient and Second should do:

1.  Get the Gradient/Second from the system
2.  Be zero (which is what it does now)
3.  Use the automatic differentiation capabilities of ParsedFunction

I don't think we need to invent weird syntax for trying to get a gradient in there... we don't actually "couple to the gradient" we couple to the variable/value/expression...
