### ISSUE TITLE
Add example problem to tensor_mechanics module

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#4789]
I am adding an example directory in tensor_mechanics. The first example will be the bridge.

**Comment by WilkAndy** [comment]
@tonkmr , i have some examples in tests - one that *might* be appropriate is an unconfined compression test, which is common in rock mechanics.  I wanted it in tests because it IS a test (marked heavy).  Is this the sort of thing you're looking for, or are you after more complicated examples that aren't really benchmark tests, but illustrate the awesomeness of TensorMechanics?
