### ISSUE TITLE
Refactor FiniteStrainMultiPlasticity to use Mike's recent TensorMech refactor

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#4791]
Shouldn't be a big deal, but currently it is hardcoded for FiniteStrain (with all the rotations and so on).

**Comment by tonkmr** [comment]
I've been hard-coding the constitutive models for small or large strain as
well. In fact, the only small strain model I plan to support is elasticity.
In general I think that small strain plasticity is a bad idea, because
plasticity is almost never small strain.



On Sat, Mar 7, 2015 at 4:15 AM, Andy Wilkins <notifications@github.com>
wrote:

> Shouldn't be a big deal, but currently it is hardcoded for FiniteStrain
> (with all the rotations and so on).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/issues/4791>.
>



-- 

*************************

Michael R. Tonks

*Fuel Modeling and Simulation Department*

*Idaho National Laboratory*

208-526-6319

michael.tonks@inl.gov

**Comment by WilkAndy** [comment]
This was done in #5018.
