### ISSUE TITLE
Make app be able to use its custom parser

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#4840]
I have an action to set up bunch of variables, but their names are not exposed in the input file. When a user create a postprocessor, he will need to know the names. Although he can always obtain the names in the screen output, it will be nice for him to just say something in the input like, in my case, the scalar flux of energy group g ($ScalaFlux::g$), or all the scalar fluxes ($ScalarFlux$). Some times the number of variables could be large to make users' input tedious.

I am thinking maybe we can derive a new parser from Moose parser, which will interpret the string given in the input and set the correct variables. This new parser will be constructed by the app. The new parsing rule will be triggered by seeing some special characters like $$ in the above. Basically we can allow an application specific parser, which could potentially simplify the input syntax.

Comments are welcome.

**Comment by permcody** [comment]
Seems reasonable. The parser has no virtual methods and will need several
more before users can customize it but perhaps we have reached that time.
I'll chat with you about possible designs when I return.

**Comment by YaqiWang** [comment]
Just had a crazy idea. The app developer could use a complete new parser, like a xml parser, to drive its application.

**Comment by permcody** [comment]
Having a plug-able parser has always been our plan. Basically we just need
the parser to report sections and name/value pairs. I would recommend that
you avoid switching to xml simply because it's different. Let's start by
extending support of the existing parser.

**Comment by permcody** [comment]
@YaqiWang would you mind adding a small input file to this ticket that you'd like to support? I'll start thinking about how to extend the existing parser so that you can create new methods to do the extra work you need. To get started though, I'd like to see the whole layout to understand how you'd like it to work.

**Comment by YaqiWang** [comment]
@permcody The following file is from rattlesnake/tests/2G-Eigen-Wagner-test/wagner.i.

```
[Mesh]
 file = wagner_second_order.e
 uniform_refine = 0
[]

[RattleSnakeParams]
 calculation_type = 'SAAF'

 AQtype = Level-Symmetric
 AQorder = 4

 G = 2
 NA = 0

 eigenvalue = 1
 transient = 0
 depletion = 0

 ReflectingBoundary = '4 1 2 3'

 tau = 1.0
[]

[UserObjects]
 [./table]
   type = ElementReactionRates
   execute_on = custom
   scalar_fluxes = 'flux_moment_g0_L0_M0 flux_moment_g1_L0_M0'
   print_debug = true
 [../]
[]

[Materials]
  [./fuel]
    type = ConstantNeutronicsMaterial
    block = 1
    sigma_t = '0.22 0.8'
    NA = 0
    sigma_s = '0.193 0.0
               0.017 0.730'
    fissile = true
    nu_sigma_f = '0.006 0.1'
    chi = '1.0 0.0'
    plus = true
  [../]

  [./steel]
    type = ConstantNeutronicsMaterial
    block = 2
    sigma_t = '0.53 0.94'
    NA = 0
    sigma_s = '0.526 0.0
               0.001 0.83'
    fissile = false
  [../]

  [./water]
    type = ConstantNeutronicsMaterial
    block = 3
    sigma_t = '0.701 2.0'
    NA = 0
    sigma_s = '0.65 0.0
               0.05 1.97'
    fissile = false
  [../]
[]

[Executioner]
  type = NonlinearEigen

  #Preconditioned JFNK (default)
  solve_type = 'PJFNK'
  petsc_options_iname = '-pc_type -pc_hypre_type -ksp_gmres_restart '
  petsc_options_value = 'hypre boomeramg 100'

  free_power_iterations = 2
  output_after_power_iterations = false
  output_before_normalization = false
[]

[Outputs]
  file_base = out
  print_linear_residuals = true
  print_perf_log = true
  [./exodus]
    type = Exodus
    elemental_as_nodal = true
  [../]
[]
```

What I want to change is `scalar_fluxes = 'flux_moment_g0_L0_M0 flux_moment_g1_L0_M0'` in the UserObjects block. I'd like to change it to something `scalar_fluxes = $SAAF2$`, which contains the `calculation_type` and `G` in the `RattleSnakeParams`.

**Comment by permcody** [comment]
OK, well there's definitely some order dependencies in there. You'll need access to other parameters in order to build your substitution lists. This is why there needs to be a little thought and design to how the extension will work.

**Comment by YaqiWang** [comment]
@permcody That will be taken care of by myself. What I currently want is the possiblity of doing this substitution. In this case, we can just check if this is equal to SAAF2, if so, substitute it with `'flux_moment_g0_L0_M0 flux_moment_g1_L0_M0'`, otherwise error out. I am not asking the substitution to look for parammeters in another block.

**Comment by permcody** [comment]
OK - fair enough.  However, with GetPot it is actually possible to retrieve other raw parameters while we parse. I'll give it some thought add give you the proper interfaces you need to extend the parser. There are other cases where people want to add multiple items and do other tricks with small syntax changes.

**Comment by YaqiWang** [comment]
I am thinking to replace MooseObjectAction with my own MooseObjectAction, for example the AddMaterialAction. Then I can change object parameters before the creation of the object. I need to replace the syntax with my new action though. This seems a low risk change and can solve my problem. If you think this is better, you can close this issue for now.

**Comment by friedmud** [comment]
Please don't do something like that @YaqiWang .  Please don't change the basic way objects are created!

**Comment by permcody** [comment]
Agreed - If you do that, I don't know how we'll be able to support you. Of all the things in MOOSE this is really at the core and further divergence will certainly occur. If you need this parser enhancement to make your problem work then it'll be my priority. Let's chat about this again and make sure I'm on the right page with you.

**Comment by YaqiWang** [comment]
I basically need the keyword substitution somewhere in the code for making the input easier. Users does not have to remember specific variable or material property names for postprocessing especially they are added through actions. It is ok whenever the substitution happens before the construction of the objects. The earliest one would be in the parser, the latest would be in `MooseObjectAction::act()`.

How about I create a new input syntax for my modified MooseObjectAction? I am now afraid that doing the substitution in the parser could be too early when I do not have the information needed for the substitution.

**Comment by permcody** [comment]
I'm really busy today but I'll see if I can help you out tomorrow.

**Comment by permcody** [comment]
I'm ready to take a hard look at this today. I can see why you think the Parser may not have all the information it needs during parse time to make substitutions because right now the parse order is not defined, nor should it be. We want our input files to remain very flexible and have no defined order or creation.

That doesn't mean that we can't solve this problem in the Parser though. It would be very easy to have the parser save off partially "parsed" objects constructing them later when arguments become available. This is yet another dependency resolver problem which we are getting quite good at solving. However with the idea that I'm thinking of now, I don't even think this will be necessary as I will explain below. The bigger issue would be design. Exactly how do we define user defined callbacks that can be filled in? Let me take a rough stab at an idea here and we can flesh it out some more.

I see at least two types of substitution:
 - Simple, where a certain "key" appearing in the input file can be replaced with a "value" appearing elsewhere in the input file. This type of substitution can already be handled by the GlobalParams lookup but it might be nice to explicitly allow this kind of substitution in a new system for the more general case.
- User-defined, This would mean that the user would have a callback where they would be responsible for providing the "value" for a given "key". The tricky part would be deciding what information would be made available in this callback and what inputs would be provided as parameters to this callback?

As a first cut, I'm thinking about just making the GetPot object available directly. The reason for this is that it gives the maximum amount of flexibility, it is after all the same object the Parser uses to build the objects in the first place. Users could query raw input file syntax. The downside is that this make it the wild west with the users potentially doing all sorts of crazy stuff, possibly even injecting additional information into the GetPot object which could be really nasty. Building up a map of input file key value pairs doesn't really seem any more appealing to me, it still gives users access to all of the raw input file syntax. So, I believe unless anyone has any objections, I will start heading down this path.

I'm thinking of just putting a single new callback right in the user's `<Name>App` object providing the necessary parameters. I don't think I want to invent a whole new system just for filling in parameters at this point and I don't think this warrants making the Parser a base class or anything like that. I see you filling in one new routine in Yak to supply values for given keys while having access to the GetPot object. With that kind of callback, I can have the parser call it on demand meaning that I don't even have to wait until later to finish constructing the current parameter set. With raw access to the GetPot object, you should be able to fill in the object immediately.

Ok, so this is a long post, I'm open for feedback or criticism.

**Comment by YaqiWang** [comment]
So will the call back function be something like
```
std::string
MooseApp::userDefinedInputSubstitution(const GetPot & getpot, const std::string & tobesubstituted);
```
?

If so, few questions:
1. how the command-line parameters be passed in? Are they already in GetPot?
2. how easy to query the input syntax in GetPot? For example, can I check the following easily:
   the number of subblocks; if a particular parameter is given in a block; the value of a parameter, and etc.

I was thinking query the action warehouse, but that needs the action warehouse has been built. With the direct querying GetPot, I need to make some functions in my actions static and return names to me with the parameters obtained from GetPot. I think I am OK with this if you can find other use cases.

I kind of like my previous idea on creating a new input syntax and action for the substitution in `act`. Then I can control the substitution only happens on certain input blocks.

**Comment by permcody** [comment]
1. You bring up a good point and now I'm thinking this won't quite work like I want since you'll basically be reimplementing all of the logic in the Parser extraction routines which have to check CLI args before checking input parameter args. Also if I implement the parameter lookup that would also mess with this...

OK, so this design is out!
I think what I'll have to do is delay these calls until all parameters are available and allow you access to the InputParameterWarehouse instead.

2. Irrerlevant now.
As far as doing the substitutions in act(). I don't like that for one big reason: It's too late if a `MooseObject` needs to store off references to other things in the system. We work hard in MOOSE to make all parameters available during construction time. If we change that, people will start having to do more wonky things in their classes like using more pointers.

**Comment by YaqiWang** [comment]
There could be a misunderstanding. For example in `AddMaterialAction::act()`, a material will be constructed using the parameters passed by MooseObjectAction, which is set by the parser. What I want to do is that right before the construction, I do substitution. The parameters are indeed available during construction.

**Comment by permcody** [comment]
You aren't thinking about the general case. Some parameters that appear in a block are for the Action that reads the block while the remaining ones are for the object being constructed. There's no differentiation from a user perspective. If we did the substitution during act(), none of those Action parameters would be allowed to have substitution strings. Just take a look at `CreateExecutionAction` or `CreateProblemAction` for examples. This system needs to work for all parameters, not just `MooseObject` parameters.

**Comment by rwcarlsen** [comment]
The new parser merges CLI params into the same tree as the main input file.  Also, the new parser does all substitutions as a post-process later - so user-modified stuff can inject things that need substitutions.  So I vote we either implement this soon(ish) or close.

**Comment by YaqiWang** [comment]
I proposed this because I do not want to expose something (like variable, material property names) hidden in the custom actions to make user interface more friendly. However, if the user manual is well developed, users can live with the current way. So if the implementation is not hard, for example taking few days, we can implement this, otherwise, feel free to close it and I can create more specific requirements with new issues later.

**Comment by rwcarlsen** [comment]
I'd lean toward closing this for now.  Anybody can reopen if they disagree.
