### ISSUE TITLE
Fix or remove run_tests in the Darcy tutorial directories.

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4921]
It doesn't work if MOOSE_DIR is unset.

**Comment by aeslaughter** [comment]
This should work, I would like to add the creation of tests to the
training. So, we can demonstrate how you should develop. Get something
working, add a test, move on to the next thing.

**Comment by friedmud** [comment]
Hmm.

My intention was to have the tutorial directories look just like real MOOSE-based applications so that people could get used to the structure.

I agree with @aeslaughter that we should also add steps showing them how to create tests.  Ideally, that should be done in each step as you create a new piece of code you should test it...
