### ISSUE TITLE
Multiapp Restart capability

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4941]
We need to add the ability to do a restart/recover simulation inside of a Multiapp simulation. While the first versions of this system may require manually setting checkpoint = true and require careful design of the input files it should still work if done properly.

Ideally, I'd like to add warnings and other checks later to verify sanity in a multiapp simulation perhaps based on things that we can figure out like proper file numbers (assuming one to one timesteps) and matching times?

## Outputs
I'd like to see the information about which files are read for recovery displayed with the proper console tags for the subapps

**Comment by friedmud** [comment]
Reopening this to take another shot at it.

Ideally the top level Checkpoint file will contain all the data necessary to restart the sub-apps.  No need for the sub-apps to write checkpoint files.

First cut at this is not going to work with mesh adaptivity (because the mesh is not currently stored in the checkpoint file).

**Comment by permcody** [comment]
This issue has been closed.
