### ISSUE TITLE
Is MOOSE app a PETSc app?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#4985]
So with command line option `-h`, we can see all PETSc options will be used by the executioner? If not, do we have a plan to bring in this feature?

**Comment by permcody** [comment]
Is this a question or a statement? Maybe you're looking for "-help" instead?

**Comment by permcody** [comment]
In my discussion with @YaqiWang, this is another inquiry as to options and how/when they are available for a run. I showed him '-help' but that's not ideal since it currently requires that you run a problem to see options. We may bring this issue up in the tiger team. For now, I'm closing and will cross-reference this ticket on #727
