### ISSUE TITLE
Bring back Reportable

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5037]
@YaqiWang has a use for reporting data from executioners, for example the Eigen value as computed by EigenExecutionerBase. Currently, he stores the value in FEProblem::parameters() and then creates a Postprocessor that grabs the parameter for printing.

I propose bringing back the Reportable interface, so we can do something like this in the initialization list:
```
declareReportable("name_to_print", /*execute_on=*/ "timestep_end", /*aggregation=*/ "sum")
```

What are peoples opinions?

This would make updating YAK for the new constructors much cleaner, otherwise I will need to create special postprocessors for about a half a dozen parameters he would like reported. I also believe @WilkAndy also has a use case for this.

**Comment by aeslaughter** [comment]
@permcody @jwpeterson @friedmud @andrsd Please take a look at this.

**Comment by jwpeterson** [comment]
You can bring it back, but only if you agree to revert it again a few months later :smiling_imp:

**Comment by YaqiWang** [comment]
Can I call this `declareReportable()` in executioner init? Should I also pass in the reference to a real number to this function?

**Comment by aeslaughter** [comment]
I would like "declareReportable" to simply create a Postprocessor that will output the data when specified. This is a much lighter weight system then what was tried before, where the Reportable values could be arbitrarily retrieved across objects.

**Comment by friedmud** [comment]
I'm still against this... there is just no good way to do this for most MOOSE systems... and getting threading working and parallel aggregation working just isn't worth the effort.

I don't see what's wrong with the current setup.  It works, and the flow of information is in the right direction (the PP is reporting something it's getting from somewhere else... instead of trying to inject data into the PP system).

Can you describe the problem you're trying to solve?

**Comment by YaqiWang** [comment]
I can explain a little. I think Andrew came up with this idea from fixing yak due to his recent change of making parameters as const. 

Yak has an executioner which uses parameters of FEProblem to store two intermediate values during a time step. Two corresponding post processors are created to report those two values in outputs every time step. With the new change, executioner cannot create the two parameters. It will be nice to keep this functionality.

If we limit the reported value to be scalar  and only on master thread and processor for executioner, we will not need to handle all parallel issues.

**Comment by friedmud** [comment]
I still vote no.  We simply don't need a whole system for this when there are too many edge cases and special situations.

One simple fix for you is to store those values as member variables in your class and provide accessor functions.  Then get your Executioner in your Postprocessor, cast it and call the accessors.

Yep: it's a bit of work... but it's a special situation.

**Comment by WilkAndy** [comment]
I'm not entirely sure what this is about, sorry, @aeslaughter .  I have some Dirac Kernels that need to report how much flux is going into them.  I have a RichardsSumQuantity UserObject that captures the information.  David made it for me, and in the DiracKernel's constructor he wrote:

    _total_outflow_mass(const_cast<RichardsSumQuantity &>(getUserObject<RichardsSumQuantity>("SumQuantityUO"))),

(Messy!)  Then i use a RichardsPlotQuantity Postprocessor to get the value stored by that UserObject.

Sorry if i'm barking up the wrong tree,

a

**Comment by aeslaughter** [comment]
@friedmud My initial solution for this problem is exactly what you described, in EigenExecutionBase I have get/setEigenValue() methods. I then created EigenValueReporter postprocessor that knows how to go get this value.  The problem is that YAK has about a half-dozen of these parameters, so I need to create as many special reporting postprocessors that go get the value via the corresponding accessors.

So, I am trying to make a more generic way to do this so that we don't have a bunch of reporter PPs all over. One method I thought of was having a Postprocessor that has a parameter "value" that is a `Real *`, this pointer could be populated upon creation of the PP depending on another parameter "reporter_type" that is a list of possible values to report. This then made me think of the reportable idea.

**Comment by YaqiWang** [comment]
Executioner owns some arbitrary data and wants these data to be reported in Outputs. We cannot provide accessors of these data and then create postprocessors for each to report them, because it will be too messy like Andrew described. The simplest way IMO would create a method in Executioner something like `Real & Report(Real & name, ExecFlag on)`. Care needs to be taken when the method can be called: construction time, initialization or run-time.

**Comment by YaqiWang** [comment]
In @WilkAndy 's case, his code can be greatly simplified if such a `report` method is available. His case  is not as complicated as our first thought because there can be only one processor of one thread own the Dirac Kernel.

**Comment by friedmud** [comment]
How about a compromise without over designing this thing?

Let's give Executable alone the ability to report values like this.  It's not threaded and it can do it's own parallel aggregation so we don't need some complicated system for doing that.

Further, it will keep down potential "abuse".  I don't like the idea of having a global data store that anything in MOOSE can push and pull values from... it basically becomes a FORTRAN common block!

**Comment by permcody** [comment]
:+1:

**Comment by WilkAndy** [comment]
Let's calm down a bit here, @friedmud, there's no need to start using the F word !

;-)

a

**Comment by permcody** [comment]
@aeslaughter - I think this may be closed?
