### ISSUE TITLE
Move (Derivative)ParsedMaterial into framework

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5039]
There is nothing that makes these materials specific to the phase_field module. `ParsedMaterial` can be used in many applications to generate material properties that are functions of non-linear variables.  The autodiffed `DeriviativeParsedMaterial` does not necessarily have to represent a free energy either. @tonkmr 

The Doxygen pages for the classes in question are 
- [ParsedMaterial](http://mooseframework.org/docs/doxygen/modules/classParsedMaterial.html)
- [DerivativeParsedMaterial](http://mooseframework.org/docs/doxygen/modules/classDerivativeParsedMaterial.html)

Note that there are a few parent classes that would have to be moved as well (`DerivativeMaterialInterface` and `DerivativeMaterialPropertyNameInterface` are already located in framework).

**Comment by dschwen** [comment]
Requesting feedback from @permcody and @friedmud. At least that will give me a definitive **NO!** and we can close this issue ;-).

**Comment by friedmud** [comment]
Sigh.  It's hard to argue against the utility.  But the "abuse" is going to be rampant.  People will shoehorn entire applications into ParsedMaterials just to avoid using our "lovingly crafted" C++ ;-)

I honestly don't know what to do here.  It's one of those situations where this is obviously cool... and possibly able to destroy everything.

I'll wait to hear from @permcody

**Comment by permcody** [comment]
I'm willing to give this a shot. We'll avoid using it in our examples and tutorials for the time being and keep people away from the dark side but it is very useful. We can always put out guidelines for people on what tools they should use for what purposes.

**Comment by lindsayad** [comment]
Just today I was wondering why (Derivative)ParsedMaterial is in a module instead of the framework. I'm glad I checked here. I have a whole set of fuel salts, each of whose material properties (conductivity, density, heat capacity, etc.) are slightly different functions of temperature. Instead of hard-coding twenty different materials, ParsedMaterial seems like the way to go. So now I'm including the `phase_field` module in my application just for that capability even though I couldn't write down governing equations for a phase field problem if you held a gun to my head.

**Comment by dschwen** [comment]
Yeah, let me prepare a PR and we can discuss this further.
