### ISSUE TITLE
Make getDefaultMaterialProperty work correctly with block restrictions

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5055]
```getDefaultMaterialProperty``` is currently not working correctly when used on multiple blocks. This is due to ```hasMaterialProperty``` not being block restricted. Using ```hasBlockMaterialProperty``` should fix this. @jasondhales encountered this bug.

Assign to me.

**Comment by jasondhales** [comment]
Another wrinkle.  In the example I showed Daniel, multiple mesh blocks need
the same material for a solid mechanics application.  Since this material
is created three times (once for x, once for y, and once for z
displacements), the second two times getDefaultMaterialProperty is called
for a mesh block, it will see that the MatProp has been declared.  However,
those none of those materials compute the property, and the code errors
out.  Any ideas outside of vector variables in MOOSE?

On Tue, May 12, 2015 at 9:34 AM, Daniel Schwen <notifications@github.com>
wrote:

> getDefaultMaterialProperty is currently not working correctly when used
> on multiple blocks. This is due to hasMaterialProperty not being block
> restricted. Using hasBlockMaterialProperty should fix this. @jasondhales
> <https://github.com/jasondhales> encountered this bug.
>
> Assign to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/issues/5055>.
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by dschwen** [comment]
cfd4468 adds a new test (which fails in current moose) to demonstrate the problem (and to protect us from regressions once it is fixed)
