### ISSUE TITLE
Contact does not work with restarts/recovers

### ISSUE THREAD

**Issue by shanestafford** [idaholab/moose#5060]
This is because I overlooked PenetrationLocator::_has_penetrated when removing the restart structures. This state of this set of nodes needs to be preserved between time steps (which is also what is necessary for restarts/recovers).

To do this right, _has_penetrated should be moved into PenetrationInfo and then a new aux variable should be added along the boundary to ensure proper restarting and consistency (just like with the other restartable data in PenetrationInfo). Unfortunately, this requires storing a double when all we need is a bool. However, it should still be cheap, and it will improve reliability.

**Comment by shanestafford** [comment]
@bwspenc and I looked at this and determined that the aux vars are probably not helping us with either restarts or parallelism. Since the random failure issue we have been experiencing was found to be in PETSc, I am going to revert the aux var changes and put back the restartable data in PenetrationInfo.

**Comment by shanestafford** [comment]
@friedmud just to clarify, we were concerned that a PenetrationInfo on a given slave node could be deleted on one process and then new'd on another process at the same node as that slave node moves nearer to a master node that is also on the other process. If that happens, then the PenetrationInfo has incorrect state in contact_force, mechanical status, and some other vars. This was the justification for using AuxVars to hold those values.

However, Constraints are applied while iterating only over slave nodes that are owned by a process, which means those PenetrationInfos can never be destroyed on one process and then re-constructed on another process. Therefore, the above logic does not apply to MechanicalContactConstraint, so the AuxVars are probably unnecessary.

**Comment by friedmud** [comment]
The only thing I would add is that that isn't really true if you're using Mesh Adaptivity.

It's long been one of my goals to make contact work with mesh adaptivity (it's a perfect use case).

I'm not 100% sure... but I think that the AuxVar way of doing things is more amenable to mesh adaptivity (because the values get shipped around with the nodes automatically when the mesh is redistributed).

But... that's a long-term goal that doesn't need to be satisfied now... so if this is better for your current goals, go for it.

**Comment by shanestafford** [comment]
Closed by #5130
