### ISSUE TITLE
Easier creation of object in Actions (Idea for discussion)

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5168]
The conversations over the past day have me thinking about what Actions do here and how we can make creating objects within Actions. Here is what I am thinking, it is just an idea.

1. We expect that users will use Actions to create things, so the methods for creating them should be on the Action class (e.g., addPostprocessor, addKernel, ...). Similarly, `getValidParam` should be there as well. This would remove these functions from FEProblem and do what is needed to populate the warehouses.
2. This is the part I think will be more controversial. By default a user created Action should be associated  with the `meta-action` task. And, the `addWhatever` methods will, by default, create the correct MooseObjectActions. This will ensure that stuff created by users are created in the correct order. Of course, there will be some sort of option for the `addWhatever` to build the actual object and return a MooseSharedPointer to the object for manipulation. I am hoping this later case will be rare.
3. Doing this could allow us to make Factory::create private, thus the only method for creating things will be via actions.

Just an idea to limit how objects are created and simplify how objects are created by users (i.e., they never need to look at FEProblem), Action will have act() and a bunch of add methods.

**Comment by permcody** [comment]
1. First, we have to move centralized functions from FEProblem to decentralized locations in the Actions and at the same time we have to add several new accessor methods to get all of the warehouses stored in both FEProblem, Nonlinear, and Auxiliary systems for adding these objects. I don't see how this improves anything.

2. Creating Actions instead of Objects is just one more layer of abstraction for the user to think about. The correct ordering is already ensured by associating Actions with the proper tasks. We can even associate a single Action with several tasks to create different kinds of objects at the right time. So again, I fail to see any advantage to the proposed design.

3. Making the factory create private won't prevent users from doing bad things. If anything it'll just encourage users to go around the Factory system even more.

Creating new objects isn't perfect and we've talked about ways to simplify the process but I don't think that moving methods from one class to another accomplishes this. A simplified interface on the other hand might. We could work towards a single interface for adding _any_ object so that users don't have to think about what parameters are required for each object.
