### ISSUE TITLE
Error handling in ColumnMajorMatrix inverse

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#5201]
Currently when ColumnMajorMatrix calculates an inverse of a singular matrix it just bombs MOOSE out completely.  Could i change this to return an error code instead?

I'd like to use its inverse calculations in my TensorMechanics work, but sometimes the matrices i feed it will be singular (eg, for perfect incompressible plasticity).  I want to handle those cases differently, rather than kill MOOSE completely.

**Comment by YaqiWang** [comment]
wow, I thought this ColumnMajorMatrix is only for tensor but I was wrong. It is a general CSR matrix. I'd like to protect some of codes such as `Moose::out`, `mooseAssert`, `mooseError`, `DenseMatrix`, `Real` with a definitions, so that my stand-alone code can use it. Actually most of them can be removed by simply using std::ostream, assert, returning error code, changing to a template class etc. If this is acceptable, I can merge my implementations into it.

**Comment by WilkAndy** [comment]
Not exactly sure what you mean, Yaqi, but i trust you'll do a better job at anything than me.  All i was imagining was to get rid of

  if (return_value)
    mooseError("error in lapack inverse solve");

in favor of a return code.  If your plans include that too, then please do the work instead of me :-)

a

**Comment by permcody** [comment]
Andy,

I don't see any problems with enhancing the CoumnMajorMatrix (CMM)
interface to meet your needs. However before you start using this class in
several places in your code I should make sure you understand what the
original intent of this class was. CMM was originally designed for
interoperability with Fortran since Fortran lays out multidimensional
arrays differently than C/C++. If you are writing straight C++ code the
layout in CMM is exactly wrong for maximizing cache hits when used in the
typical "row major" traversal so that's something to think about. If you
are just looking for a general purpose "dense" matrix take a look at what
classes are available inside of libMesh. You may find the objects there
will better serve your purposes. Yaqi, You may want to consider looking
there as well depending on your needs.

Cody

**Comment by jwpeterson** [comment]
> It is a general CSR matrix.

ColumnMajorMatrix is not a CSR matrix, if by CSR you mean "Compressed Row Storage".  Its storage is simply a `std::vector` with `_n_rows * _n_cols` entries.

**Comment by YaqiWang** [comment]
oh, sorry for my misunderstanding. Forget about what I said. CMM is useless to me.

**Comment by WilkAndy** [comment]
Oh, thanks @permcody .  i will look at libmesh.  basically i just want the inverse of a dense matrix, and couldn't be bothered writing all that lapack junk.

a

**Comment by WilkAndy** [comment]
@permcody , i had a look at libmesh's dense matrix.  There is an inverse but it's commented out!

// This routine is commented out since it is not really a memory
// efficient implementation.  Also, you don't *need* the inverse
// for anything, instead just use lu_solve to solve Ax=b.
// template<typename T>
// void DenseMatrix<T>::inverse ()

So, maybe i don't strictly need the inverse, but it would make my code much cleaner if i had it.  Is there somewhere else i can get an inverse from?

**Comment by jwpeterson** [comment]
Not in libmesh, unless your matrix is 3x3, in which case there is a hand-coded `inverse()` method for `TypeTensor`.  I think your best bet is to change `ColumnMajorMatrix` so that it either throws an exception or returns an error code.  I'd go with the former since it doesn't change the behavior for existing code: any code that doesn't catch the exception will abort just like it does now.

**Comment by WilkAndy** [comment]
good-oh, thanks everyone.  i'll try throwing an exception.
