### ISSUE TITLE
MooseException may not work properly with stateful props - needs investigation

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5322]
@cpritam reported that he was unable to use this new capability in his crystal plasticity simulation. It seg. faults after cutting back on a bad access to a stateful vector material property.

**Comment by jwpeterson** [comment]
If the exception is not thrown during `NonlinearSystem::computeResidual()` or `computeJacobian()` then it wouldn't be caught by anything... Is it thrown in a setup routine or something?  Can @cpritam provide a stack trace?

**Comment by permcody** [comment]
He can. He said the cutback was working but when it reached the material
property compute values method it seg faulted since the "old" property
wasn't sized. I was thinking we could turn on your exception kernel in one
of the existing stateful material tests.

**Comment by cpritam** [comment]
Should I push the modified code and test so that you can have a look.

**Comment by permcody** [comment]
Let's hold off for now. I'd rather replicate with a much simpler material model if we can. Also, we may not get to this right away as we have a few other things we're working on right now. I'll let you know if we need more information from you.

**Comment by jwpeterson** [comment]
It wouldn't hurt anything for @cpritam to point us to a branch in his fork that also demonstrates the issue.

**Comment by friedmud** [comment]
I can see how this would happen.

The way stateful stuff works is that we swap in and out the memory that holds the value for the current element with a zero sized array (it's faster to swap than copy... but you have to have something to swap with).

So the problem is that when the exception is thrown the zero sized array is currently in the material property storage area.... and the real values are sitting in the "temporary" area where they're accessed by Kernels, etc.

We have two choices:

1.  Make sure we clean up stateful material properties when an exception is thrown.  The most secure way of doing that is probably with RAII... we make an object that when it is created it swaps the material properties out... and when it's destroyed it swaps them back.  This object will automatically get destroyed when when the exception is thrown so it can put stuff back to the correct state then.

2.  We change the semantics of stateful material properties.  Instead of doing a "swap"... maybe we just do a "shallow copy"....

**Comment by cpritam** [comment]
Pushed branch cp_exception with modified src and failing test. 5d02c535955e4cb79ec229c45b8a65db7798f27a

**Comment by dschwen** [comment]
Pretty sure this isn't an issue anymore
