### ISSUE TITLE
save_in parameter is needed for Nodal BCs

### ISSUE THREAD

**Issue by ragusa** [idaholab/moose#5374]
The save_in keyword is used to save the residual in an aux variable. I can see that the save_in keyword is in kernels and integrated BCs. However, if a user runs a simulation with Nodal BCs, the save_in residual will not be the same as the residual used in the solution process itself. I believe save_in should also be added in base/NonlinearSystem.C (NonlinearSystem::computeNodalBCs).
Thanks!

--jean ragusa

**Comment by YaqiWang** [comment]
@bwspenc and @friedmud should have comments on this. Because `NodalBC` is evaluated at the end, I think we should be able to directly set the DoF on boundary nodes to zero.

**Comment by friedmud** [comment]
It's fine with me.  Just be aware that most of the time it will be identically zero.  And if it's not identically zero then it's going to be dang close.

No one has asked for this because normally what you want to see is the "internal" residual at the boundary nodes (in solid mechanics they call it the "reaction force")... which is actually the residual the NodalBC's wipe out ;-)

**Comment by ragusa** [comment]
Derek,

Why do you say it will be 0 or close to 0?

If a kernel is saved in an aux var by looping over all elements, the rows corresponding to boundary unknowns are whatever. If a Dirichlet BC is requested, that forces a modification of the entry for some terms. This is why computeNodalBCs is done at the very end in NonlinearSystem::computeResidual.

If there are no save_in parameters passed to the NodalBC, then the residual used in MOOSE and the save_in residual must differ.

I agree that the residual that is used will be 0 at the Dirichlet nodes (b/c NodalBCs has been applied), but the save_in residual will be whatever.

--jean



________________________________

**Comment by friedmud** [comment]
Nope - you have it backwards.  `save_in` saves the residual _the object computes_.  It "saves" the residual of the object in a field so that you can inspect it.  It does this by _adding_ the residual the object computes to an Auxiliary field.  So `save_in` for a `DirichletBC` would basically save a field that is nearly always zero (if it's the only thing contributing to that Auxiliary field).

If you want to save the residual from all the other objects (i.e., the residual that the `NodalBC` overwrites) then you would put `save_in` in _their_ blocks.

Note that there is no "save in residual"... it's not ONE field.  You can have as many of them as you want and multiple objects can add to that field.  Take this input file example:

```
[Kernels]
  [./some_kernel]
    type = Something
    variable = junk_var
    save_in = 'something both'
  [../]

  [./other_kernel]
    type = Other
    variable = junk_var
    save_in = 'other both'
  [../]
[]
```

This would produce three fields (in addition to the normal solution field): `something`, `other` and `both`.  `something` would only contain the residual contributions from `some_kernel`, `other` would only show the residual contributions that `other_kernel` is computing and the field called `both` would have contributions from both `Kernels`.

`save_in` for `NodalBC` would always just _add_ ~zero into whatever field you specified... which wouldn't really do much.

Are you trying to output the real residual used by MOOSE?  If so, then use the `[Debug]` block to output the full residual for a variable like it shows here: https://github.com/idaholab/moose/blob/devel/test/tests/outputs/residual/output_residual_test.i

**Comment by ragusa** [comment]
What we need to do:
We are solving a modified transport equation. It contains various kernels (of course). The contributions of **some** of the kernels to the residual need to be save in an aux var and then we need to take the inner product of that aux var with an adjoint solution.

How we want to proceed:
We like the saving functionality and this is pretty much what we need. Basically, we are going to cherry pick the kernels we want to save in that aux var using the save_in parameter. In our case, all of the contributions will be saved in the same aux var because we need the accumulation of them. However, we need this aux var to also contain the contributions for the IntegratedBC residual (that’s fine, there is a save_in param passed to them) and we need that aux var to also satisfy the NodalBCs, if any . That’s when I noted save_in was not passed to NodalBCs. Basically, I need the save_in functionality there too.

Am I missing something?


--
Jean C. Ragusa, Ph.D.
Associate Professor, Department of Nuclear Engineering
Associate Director, Institute for Scientific Computation
Texas A&M University
Email: jean.ragusa@tamu.edu<mailto:jean.ragusa@tamu.edu>

College Station, TX 77843-3133
Phone: (979) 862-2033
FAX: (979) 845-6443

On Jul 15, 2015, at 6:24 PM, Derek Gaston <notifications@github.com<mailto:notifications@github.com>> wrote:


Nope - you have it backwards. save_in saves the residual the object computes. It "saves" the residual of the object in a field so that you can inspect it. It does this by adding the residual the object computes to an Auxiliary field. So save_in for a DirichletBC would basically save a field that is nearly always zero (if it's the only thing contributing to that Auxiliary field).

If you want to save the residual from all the other objects (i.e., the residual that the NodalBC overwrites) then you would put save_in in their blocks.

Note that there is no "save in residual"... it's not ONE field. You can have as many of them as you want and multiple objects can add to that field. Take this input file example:

[Kernels]
  [./some_kernel]
    type = Something
    variable = junk_var
    save_in = 'something both'
  [../]

  [./other_kernel]
    type = Other
    variable = junk_var
    save_in = 'other both'
  [../]
[]


This would produce three fields (in addition to the normal solution field): something, other and both. something would only contain the residual contributions from some_kernel, other would only show the residual contributions that other_kernel is computing and the field called both would have contributions from both Kernels.

save_in for NodalBC would always just add ~zero into whatever field you specified... which wouldn't really do much.

Are you trying to output the real residual used by MOOSE? If so, then use the [Debug] block to output the full residual for a variable like it shows here: https://github.com/idaholab/moose/blob/devel/test/tests/outputs/residual/output_residual_test.i

**Comment by friedmud** [comment]
I guess I don't know what you mean by "we need that aux var to also satisfy the NodalBCs".  Do you mean that you want that aux var to be zero where the NodalBCs are?

My question is: what do you mean by "satisfy"?

A DirichletBC looks like:  `u - value`.  When u=value (which is most of the time) the residual for a DirichletBC will just be zero.

In the true residual vector we replace the residual values where the NodalBCs apply with their residual (essentially setting them to zero for a DirichletBC... most of the time).

`save_in` doesn't work that way.  It currently _adds_ the residual value from the object into the field.  Are you suggesting that for a `NodalBC` it would overwrite the value instead?

What do you want in your Auxiliary field?
