### ISSUE TITLE
The delete_trailing_whitespace.sh script overwrites symlinks

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#5440]
For example, if you run it in BISON, we have a symlink to a .py file, and it overwrites that with a new file.  Is that intended behavior?

**Comment by jwpeterson** [comment]
Definitely not.  The script uses `find -type f`.  I kind of thought that would ignore symlinks, but maybe not?

**Comment by jwpeterson** [comment]
I think there is some bad interaction going on with our `-prune` logic.  For example, the command
```
find . -name "*.py" -type f | grep "tools/UO2/tests/mesh_script.py"
```
doesn't find anything in BISON -- as it shouldn't because the thing I grepped for is not a "regular file".  On the other hand, if I do something more similar to what delete_trailing_whitespace.sh does, e.g.:
```
find . -name "*.py" -or -name examples -prune -and -type f | grep "tools/UO2/tests/mesh_script.py"
```
then it *does* erroneously find the sybmolic link...

**Comment by jwpeterson** [comment]
After some googling, I think we can maybe use "-path" for this?  The following correctly ignores the symbolic link:
```
find . -path ./contrib -prune -o -name '*.py' -type f -print | grep "tools/UO2/tests/mesh_script.py"
```
whereas if you remove the "-type f" it will find it again.  I'll make a PR for this...

**Comment by permcody** [comment]
@jwpeterson - Can you close?
