### ISSUE TITLE
Add a dummy GrainTracker

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5453]
We would like to move more of our systems to GrainTracker. For simple simulations with low OP numbers it would be nice to have a userobject that provides the same interface as grain tracker, but does only return static mappings without performing flood counts and remapping. Opinions on that @permcody?

**Comment by permcody** [comment]
I'll look into it.

**Comment by permcody** [comment]
Now that I have a moment, what interface are you talking about specifically? Being able to get a grain number back for a node or element? If so there's a little more work than you might think because of adaptivity especially since you can turn the GrainTracker on at an arbitrary step. You can already turn off remapping but that's not the expensive part.

**Comment by permcody** [comment]
Capturing my conversation with @dschwen. We discussed a simple object that users could use instead of the grain tracker for cases where `grain number <= op number`. In these cases the object would have the same interface but simply return the existing op number in any accessor.
