### ISSUE TITLE
IterationAdaptiveDT cleanup

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5535]
I'm reading ```IterationAdaptiveDT``` (which does way more than its name suggests - can we make time steppers more modular somehow?!) and had the compulsion to adjust a few style details...
Courtesey ping @bwspenc

**Comment by friedmud** [comment]
I never mind cleanup... what what do you mean by "more modular"?

At a cursory glance they already look extremely modular... it's just that `IterationAdaptiveDT` is VERY particular so it overrides almost all of the possible functions.  I don't see anything that it's doing that is a duplication of other work in other `TimeSteppers` nor do I see any obvious points where functionality could get broken up more... it's already very broken out into individual virtual functions that each handle one and only one piece of functionality.

That's not being defensive... I honestly think it looks pretty good (from a design standpoint anyway... cleanup is always good) but I'm interested in how else you would design it.

**Comment by dschwen** [comment]
```IterationAdaptiveDT``` adapts based on
* Iteration count (like its name says)
* A ```MooseFunction``` that can limit the maximum change
* A real value that can limit the maximum change (this seems redundant as it can be folded into a (default)function
* An interpolation function that takes (t,dt) pairs

It also has the input parameters working in odd ways. It uses ```isParamValid``` to assign a default value for a parameter not specified. It happily sets the default, but creates an error if the parameter is specified (even with exactly the default value) if a second parameter is not specified as well. I'm probably picky here...

I also find its documentation insufficient (I'm trying to improve that).

The maximum change parameters seem to me like something that is not specific to this particular time stepper. This should be moved up in the inheritance hierarchy.

**Comment by bwspenc** [comment]
@dschwen  I wrote most of that, and I agree that it does a lot more than its name implies. It's our go-to time stepper for BISON, and we use that functionality for it to adapt based on the maximum function change and stop on function points all the time.  When I wrote it, I debated making another class that inherited from it to add additional capability just for BISON, but decided against it.  Maybe users could compose together multiple TimeSteppers that limit the time step in different ways. 

I need to look at the code to see what you're saying about the use of isParamValid. I think I recall needing to do something a little strange there to get it to handle defaults correctly. Maybe things have changed since then in the parsing system.

  The one thing that I've been meaning to get to on that class is to work on the mechanism to limit the step to limit the function change.  I think it just keeps subdividing the step until the function changes less than the specified value, but the function could actually go up and down more than that between the last time step and the subdivided time step.

**Comment by dschwen** [comment]
Why does ```timestep_limiting_function``` have to be a ```Piecewise``` function? I see that you are calling domain to get the x values (i.e. Times), but why not just sample the function at the current simulation time?

**Comment by bwspenc** [comment]
Now I remember why I handled the default values in a funny way.  If you have a default value, isValidParam() always returns true, so you can't tell whether the user specified it.  The presence of the parameter in the input file both turns an option on and sets a value.  By the way, this is documented in the BISON manual.  We should copy that over rather than starting from scratch.

**Comment by aeslaughter** [comment]
FYI, there is a method in InputParameters (paramSetByUser) that is true
only when the parameter is set in the input file.

**Comment by bwspenc** [comment]
@dschwen This was motivated by the need to have the time step adapt based on the function that we use to drive the power history for BISON analyses.  We have never used anything but a piecewise function for that, although it is certainly conceivable that we could. There's an option to force time steps at the "knots" in the function, which is extremely useful, but only applicable to piecewise functions. We could generalize this to accept other function types and only offer that option if it's a piecewise function. We've just never bothered because we haven't had a need.

I can't quite remember why we have two references to the function, but I think it was so that that we could allow other function types to be used for limiting the time step, but use the piecewise function to match the time step to the knots.  We just never got around to doing that, but it's probably trivial.

**Comment by bwspenc** [comment]
@aeslaughter Thanks for the tip on paramSetByUser.  That's exactly what we need here (and in other places).  Is that new?  I swear I've looked for something like that on multiple occasions and couldn't find it.

**Comment by aeslaughter** [comment]
It is newish: Apr. 8
