### ISSUE TITLE
MooseRandom::rand() must die

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5567]
Seriously, the static members of `MooseRandom` look like a terrible idea to me.
The implement _one_ single shared random number stream per process (and all of its threads).
That means calling `MooseRandom::seed()` will affect _all other objects_ pulling from that stream. It basically makes user specified seeds meaningless. Imagine an IC sets the seed in its CTOR, next a material overwrites the seed in its CTOR, then the IC's value method is executed. If the user changes the seed in the IC block in the input he/she will be surprised to see _no_ change in random numbers.

I suggest to remove the static methods and add the following methods instead

```
Real rand() { return rand(0); }
Real randNormal(Real a, Real b) { return randNormal(0, a, b); }
```

(off the top of my head). This would of course force users to instantiate MooseRandom, but I see no big deal here. Incidentally this would also be a nicer solution for #5560, as we do not really need the `_tid` at all! Replacing `_tid` with `0` would already be sufficient (and the function overloads would make it look nicer) as it already guarantees that each thread has its _own_ stream (just like MPI processes do).

Whatcha think @permcody and @friedmud?

**Comment by friedmud** [comment]
No - any solution that involves users instantiating MooseRandom is a non-starter for me.  We can do better.

I'll wait until @permcody chimes in to go further... he had to have a reason for what he did before.

**Comment by friedmud** [comment]
Just linking in that there is a fair bit of discussion over here as well: #5562

**Comment by permcody** [comment]
I left the static instances in there to give people a viable alternative to the library static methods which are just as evil. `srand()` and `rand()`. If we remove these methods, people might complain about extra work and just use library methods instead. If we really want to give these static methods the axe then we might need put the library methods in the banned keyword list too. How far do we want to go with this?

**Comment by dschwen** [comment]
8c424ea is a proof of concept to add ```RandomInterface``` to ```InitialCondition```. It makes ```RandomIC``` reproducible in threaded mode, **but** adds an odd MPI parallel bug, whereas the random IC diffs along the parallel boundary compared to the serial gold file :-/

Image of the diff for a 4 processor run:
![diff](https://cloud.githubusercontent.com/assets/202302/9312851/c43eeb2c-44dc-11e5-921d-ad4a4a2e7859.png)

**Comment by permcody** [comment]
So the problem with this is with our InitialCondition code once more. The InitialCondition code loops over elements and calls compute on each one. This is necessary in the general sense since we need to properly project all FETypes. The side effect of this code is that we end up calling compute() for each node several times (once for each semi-local active element) when computing ICs for C_ZERO types. In parallel this means you'll call the generator a different number of times depending on whether you are on node on a processor boundary.

I'm tempted to cache information at the MOOSE layer for Lagrange variables but even that may not be entirely safe. It's entirely feasible that somebody creates an initial condition that acts different for the same node depending on what element you are on (maybe)? Maybe we don't care... Hmm... We built all this `curr_node` and `curr_elem` capability into the IC system. Perhaps it's time to take it for a test drive...

**Comment by permcody** [comment]
@friedmud - any opinion on this? Any reason you can think of not to cache nodal or elemental values coming back from the initial condition callback? I won't attempt to cache results for the Hermites or other non-dof points...

**Comment by friedmud** [comment]
I would prefer a solution that gives a unique stream for mesh entities...
so that any processor could recreate the same stream... but what I want is
not always what's possible :-)

How about changing the initial condition code for Lagrange so that there is
a special loop just for them that goes over only local nodes?

I actually thought @andrsd had something like that in there a while ago...

**Comment by andrsd** [comment]
On Tue, Aug 25, 2015 at 9:29 PM, Derek Gaston <notifications@github.com>
wrote:

> I actually thought @andrsd had something like that in there a while ago...
>

​I think we discussed something like this before, but it never got
implemented.​..

**Comment by permcody** [comment]
Yes, I thought about that too, just didn't want to mess too much with the IC code. I'll look into one of these as a solution. Either one of these ideas would give us a solution that gives us a reproducible stream on any processor discretization.

**Comment by permcody** [comment]
I like the idea of getting rid of the statics, but there are several issues that we just don't have time to get to. Lowering the priority on this ticket.

**Comment by roystgnr** [comment]
Can someone verify for me that this issue is still expected to make RandomIC unrepeatable in parallel?

Looking into some -p 2 modules test failures, I see what looks like an obvious PRNG reproducibility failure in a RandomIC based phase field test: half of the t=0 solution (presumably the proc_id=0 half) appeared to be white noise which matched the gold standard perfectly, while the other half looked like unrelated (except in magnitude) white noise.  --n-threads=2 behaves similarly.

There are a ton of RandomIC based tests that do pass in parallel, because they're IMO quite clever: an eigensolve or a jacobian-only comparison (and in some cases perhaps a solve to steady state?) means that a correct solution won't depend on the initial conditions at all, so why not throw in some crazy initial conditions to make an incorrect solution more likely to trip a failure?

I would like to set max_parallel=1 and max_threads=1 on anything that's currently using RandomIC and failing in parallel, so we can get a little closer to regularly running the physics modules tests properly, at scale.

**Comment by permcody** [comment]
Correct, RandomIC was not designed to be parallel or thread agnostic at
all. There’s a whole Random Number system in MOOSE that is agnostic to
parallelism. This system is not because it uses the (old) projection code
to setup ICs. I’d like it to give us consistent random numbers in parallel
at some point but it can be restricted in the meantime.

**Comment by dschwen** [comment]
Ping @permcody for historical background

**Comment by permcody** [comment]
Acknowledged. I am working on a solution to the RandomIC problem.
