### ISSUE TITLE
PETSc malloc error for simple steady-state 3D diffusion problem

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5599]
As reported by @WilkAndy and Heather Sheldon.

This input file triggers an out of memory error saying it requested too much memory (18446744069961385984 ~ 18 Exabytes!). Yes it uses full SMP with ASM and an overlap of two but is this really right?

Input file is attached and runs (crashes) with moose_test:
```
# A 3D problem using the Laverton mesh
# Heather Sheldon, CSIRO Aug 2015
# TEST VERSION TO DEBUG MESH

[Mesh]
  type = GeneratedMesh
  dim = 3
  nx = 70
  ny = 60
  nz = 20
  xmin = 0
  xmax = 80E3
  ymin = 0
  ymax = 70E3
  zmin = -30E3
  zmax = 0
[]

[Variables]
  [./disp_x]
  [../]
  [./disp_y]
  [../]
  [./disp_z]
  [../]
  [./pp]
    [./InitialCondition]
      type = FunctionIC
      function = '10000-10000*z'
    [../]
  [../]
[]

[Kernels]
  [./a_x]
    type = Diffusion
    variable = disp_x
  [../]
  [./a_y]
    type = Diffusion
    variable = disp_y
  [../]
  [./a_z]
    type = Diffusion
    variable = disp_z
  [../]
  [./a_p]
    type = Diffusion
    variable = pp
  [../]
[]

[Preconditioning]
  [./andy]
    type = SMP
    full = true
  [../]
[]

[Executioner]
  solve_type = Newton
  type = Transient
  
  end_time = 1E7
  dt = 1E5      
 
  l_tol = 1E-3
  nl_abs_tol = 1E1
  nl_rel_tol = 1E-8
  l_max_its = 200
  nl_max_its = 400

  petsc_options_iname = '-pc_type -pc_asm_overlap -sub_pc_type -ksp_type -ksp_gmres_restart'
  petsc_options_value = ' asm      2              lu            gmres     200'
[]


[Outputs]
  file_base = andy_out
  output_on = 'initial timestep_end'
  print_perf_log = true
  [./console]
    type = Console
    output_linear = true
  [../]
[]
```

**Comment by permcody** [comment]
Tagging @karpeev.

Dmitry, maybe you can give me a quick education on what the estimated memory usage of this simple problem "should" be. It's a simple cube with 4 first order lagrange variables. He is building a full SMP preconditioner with an overlap value of "2". It allocated about 2.5 Gigs on my Mac before crashing with the out of memory error. 

```
Mesh: 
  Distribution:            serial
  Mesh Dimension:          3
  Spatial Dimension:       3
  Nodes:                   
    Total:                 90951
    Local:                 90951
  Elems:                   
    Total:                 84000
    Local:                 84000
  Num Subdomains:          1
  Num Partitions:          1

Nonlinear System:
  Num DOFs:                363804
  Num Local DOFs:          363804
  Variables:               { "disp_x" "disp_y" "disp_z" "pp" } 
  Finite Element Types:    "LAGRANGE" 
  Approximation Orders:    "FIRST" 
```

Also @jwpeterson, @andrsd, @friedmud

**Comment by friedmud** [comment]
Each row of the matrix will have `27*4 = 108` entries.  Multiplied by the full length that gives: `363804*108 = 39290832` total entries in the matrix.  Multiply by 8 for bytes/double and divide by 1e6 for bytes/megabyte: `(39290832*8)/1e6 = 314`.  So I would estimate that the matrix would take up about 314MB (which makes intuitive sense based on the size of the problem).

So... I have no idea what the problem is.

If you run with different preconditioners does it do anything different?

**Comment by permcody** [comment]
Ok, so it works with some fails with some. There's something going on when using the sub_pc_type.

This works:
`-pc_type lu`

So does this:
`-pc_type ilu -pc_sub_type lu'

This fails:
`-pc_type lu -pc_sub_type lu`

There's some multiplicative effect going on there...

**Comment by friedmud** [comment]
The option is `-sub_pc_type` is that what you meant?  Or were you really using `-pc_sub_type`... because I don't think that's anything.

`-sub_pc_type` doesn't make any sense for `lu`.  `lu` doesn't have a `sub_pc` at all....

**Comment by permcody** [comment]
Oh whoops, I think I did mix that option up part way through the testing so ignore my previous comment. PETSc will ignore unused arguments unless I tell it to complain so it's safe to assume that some of my tests are just invalid.

I tried once more and got it to fail with `-pc_type lu` ONLY so it's as simple as it gets now. I made sure to remove the lines in the input file just to be sure I wasn't overriding something. It's still requesting 18 Exabytes of memory...

**Comment by mangerij** [comment]
That is a pretty large problem for asm and lu on the sub block... I've never had good luck using asm and lu on large problems.

I was able to get this input file to run on 8 cores but had to reduce the mesh size by 2. I didn't see the failed petsc errors... 

also, shouldn't the petsc options be called in the preconditioner block?
 asm was not showing up in the console executioner information otherwise.

**Comment by permcody** [comment]
Yes, but we should be able to explain why it request 18 Exabytes. We've run into this kind of problem a few times and it would be nice to know when things should work and when they might fail and how to work around these issues. This isn't that big of a problem.

**Comment by karpeev** [comment]
Sorry, I was tied up this morning.

In SERIAL -pc_type asm -sub_pc_type lu will duplicate Jacobian storage,
because ASM
will extract the full matrix out of Jacobian (overlap has no effect in
serial, unless you are
requesting multiple subdomains explicitly).  LU will then go and do
symbolic elimination
to figure out how much to preallocate for the factors, and that will be
quite a bit.
In the worst case, assuming fully dense factors you are looking at,
roughly, (3e+5)^2 ~ 1e+11.
In reality it will probably be less, on the order of a few GB, but it might
push it close to the limit
of a laptop. That's still not 18 Exabytes or anywhere near that.  Can you
send the full error message?

Dmitry.

**Comment by permcody** [comment]
@karpeev, I'm also able to get this error with just "lu" - no ASM. It looks very similar to the errors you tried to troubleshoot with Brad and other "corrupted memory issues" here at the lab.

```
Time Step  1, time = 100000
                dt = 100000
 0 Nonlinear |R| = 1.212564e+12
moose_test-oprof(99375,0x7fff78851300) malloc: *** mach_vm_map(size=18446744069961388032) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Out of memory. This could be due to allocating
[0]PETSC ERROR: too large an object or bleeding by not properly
[0]PETSC ERROR: destroying unneeded objects.
[0]PETSC ERROR: Memory allocated 0 Memory used by process 2737668096
[0]PETSC ERROR: Try running with -malloc_dump or -malloc_log for info.
[0]PETSC ERROR: Memory requested 18446744069961385984
[0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.6.0, Jun, 09, 2015 
[0]PETSC ERROR: ./moose_test-oprof on a arch-darwin-c-opt named thearchitect.inel.gov by permcj Mon Aug 24 13:41:42 2015
[0]PETSC ERROR: Configure options --prefix=/opt/moose/petsc/mpich_petsc-3.6.0/clang-opt-superlu --download-hypre=1 --with-ssl=0 --with-debugging=no --with-pic=1 --with-shared-libraries=1 --with-cc=mpicc --with-cxx=mpicxx --with-fc=mpif90 --download-fblaslapack=1 --download-metis=1 --download-parmetis=1 --download-superlu_dist=1 CC=mpicc CXX=mpicxx FC=mpif90 F77=mpif77 F90=mpif90 CFLAGS="-fPIC -fopenmp" CXXFLAGS="-fPIC -fopenmp" FFLAGS="-fPIC -fopenmp" FCFLAGS="-fPIC -fopenmp" F90FLAGS="-fPIC -fopenmp" F77FLAGS="-fPIC -fopenmp" PETSC_DIR=/opt/moose/stack_src/petsc-3.6.0
[0]PETSC ERROR: #1 PetscFreeSpaceGet() line 13 in /opt/moose/stack_src/petsc-3.6.0/src/mat/utils/freespace.c
[0]PETSC ERROR: #2 PetscFreeSpaceGet() line 13 in /opt/moose/stack_src/petsc-3.6.0/src/mat/utils/freespace.c
[0]PETSC ERROR: #3 MatLUFactorSymbolic_SeqAIJ() line 353 in /opt/moose/stack_src/petsc-3.6.0/src/mat/impls/aij/seq/aijfact.c
[0]PETSC ERROR: #4 MatLUFactorSymbolic() line 2896 in /opt/moose/stack_src/petsc-3.6.0/src/mat/interface/matrix.c
[0]PETSC ERROR: #5 PCSetUp_LU() line 127 in /opt/moose/stack_src/petsc-3.6.0/src/ksp/pc/impls/factor/lu/lu.c
[0]PETSC ERROR: #6 PCSetUp() line 982 in /opt/moose/stack_src/petsc-3.6.0/src/ksp/pc/interface/precon.c
[0]PETSC ERROR: #7 KSPSetUp() line 332 in /opt/moose/stack_src/petsc-3.6.0/src/ksp/ksp/interface/itfunc.c
[0]PETSC ERROR: #8 KSPSolve() line 546 in /opt/moose/stack_src/petsc-3.6.0/src/ksp/ksp/interface/itfunc.c
[0]PETSC ERROR: #9 SNESSolve_NEWTONLS() line 233 in /opt/moose/stack_src/petsc-3.6.0/src/snes/impls/ls/ls.c
[0]PETSC ERROR: #10 SNESSolve() line 3894 in /opt/moose/stack_src/petsc-3.6.0/src/snes/interface/snes.c
[0]PETSC ERROR: #11 solve() line 715 in src/solvers/petsc_nonlinear_solver.C
application called MPI_Abort(MPI_COMM_WORLD, 55) - process 0
```

**Comment by karpeev** [comment]
Brad's problem seemed to be connected to AMR, but we never got to the
bottom of it, at least while I was involved.
His problem sizes were definitely more extreme than this.

Is there something wrong with github?
I'm trying to pull the latest version so I can try and reproduce this
(although I will try with what I have, since this might be independent of
MOOSE), and it's timing out.

Dmitry

**Comment by permcody** [comment]
Nothing is wrong with Github. Make sure you don't have any proxy stuff getting in your way on the CLI. Any help with this problem might yield clues to Brad's problem too.

**Comment by karpeev** [comment]
Must have been a local network hiccup -- I've pulled and rebuilding now.
My guess is that this is a memory corruption, so I'll try valgrind on this,
as soon as I can reproduce it.

**Comment by karpeev** [comment]
So, this problem is due to an internal overflow in PETSc:
During symbolic LU factorization the estimated amount of fill gets too large
for a 32-bit PetscInt, so it overflows to a negative value, which, when 
implicitly cast to size_t in a call to malloc, results in a huge value  -- a quirk
of two's-complement arithmetic (size_t is an unsigned type).

I'm working on a test and a fix, but it may be a little while before it percolates
up to a patch release.  I thought that configuring PETSc --with-64-bit-indices=1
would fix the problem in the interim, but I haven't found a way to configure libMesh
to use 64-bit indices.  As a result, I get errors such as these when building libMesh
against a PETSc with 64-bit indices:

~~~
 CXX      src/numerics/libmesh_dbg_la-sparse_matrix.lo
In file included from /Users/karpeev/libmesh/rev/src/numerics/petsc_matrix.C:31:0:
./include/libmesh/petsc_vector.h:1326:1: error: static assertion failed: PETSc and libMesh integer sizes must match!
 static_assert(sizeof(PetscInt) == sizeof(numeric_index_type),
~~~

**Comment by WilkAndy** [comment]
Aha, i understand, thanks Dimitry.  So in this case perhaps the easiest thing is not to use LU, do you think?  If you have any suggestions for other PCs, that would be welcome, otherwise heather and i will just try some random ones.

**Comment by karpeev** [comment]
Yes, in this case do not use LU: even once the bug is fixed, you might
still be running out of memory --
just not by trying to allocate exabytes -- because even the value that
causes the overflow is on the order of a few GB,
and the code wasn't even close to being done with the symbolic
factorization.  In other words, it would still require
many GB of RAM to store the LU factors.

What is the purpose of this test? Since it's a basically a Laplacian GAMG
or HYPRE/BoomerAMG should make a good preconditioner.
Another way to get a decent preconditioner without too much trouble is to
use ASM with many blocks -- it works even in serial --
a decent overlap and LU or ILU(n) on the blocks for some smallish n.
~~~
-pc_type asm -pc_asm_blocks 32 -pc_asm_overlap 2 -sub_pc_type lu
~~~
for ASM with 32 subdomains, overlap 2 and LU on the blocks, or
~~~
-pc_type asm -pc_asm_blocks 32 -pc_asm_overlap 2 -sub_pc_type ilu
-pc_factor_set_levels 4
~~~
for the same, except using ILU(4) on the blocks.
Note that when running in parallel you will need to use at least as many
blocks than there are MPI ranks,
and you really want to use a multiple of the MPI comm size for the number
of blocks.

**Comment by permcody** [comment]
Well this just comes down to not understanding the implications of playing
around with preconditioner options. Clearly none of the MOOSE guys caught
this either, maybe we can be more helpful with the error message.

**Comment by jwpeterson** [comment]
> I thought that configuring PETSc --with-64-bit-indices=1
> would fix the problem in the interim, but I haven't found a way to configure libMesh
> to use 64-bit indices.

`./configure --with-dof-id-bytes=8`

This worked as of a few months ago, please let me know if something broke with it @karpeev

**Comment by karpeev** [comment]
The confusing thing here was the enormous amount of storage that LU was
trying to allocate,
which made me suspect a memory corruption.  But even when this is fixed we
can still expect
an out-of-memory error.  Basically, if you use LU on a large problem you
can expect to run out of memory.

You can get a ballpark estimate of how much memory you will need by assume
fully dense factors,
which says you'll need 8*N^2 bytes of memory to store them (a bit
pessimistic, but will probably predict
these errors more or less correctly).

**Comment by friedmud** [comment]
Wow - ok.

This is still a bit counterintuitive to me... it's really not that big of a
problem!  (or at least it doesn't feel like it!).

**Comment by WilkAndy** [comment]
Thanks for your comments, everyone.  I will try your PC suggestions, Dimitry, although I should have said this example is actually nothing like Heather's original.   Hers is a solid-mechanics + fluid-mechanics problem: i just removed all her kernels to simplify the bug-search.

a

**Comment by karpeev** [comment]
@jwpeterson Thanks!  That got libMesh built and now I'm building MOOSE.

As I said, it's probably not a good idea to use LU on a problem like this, but we'll see.
At the very least we want to use SuperLU, hoping that they do a better job with fill 
(via a fill-reducing ordering or something).  

@friedmud It doesn't take that much to create a request of upwards of 2GB for LU factors (a problem with 300K will almost certainly do it) and that's enough to overflow a signed 32-bit integer, unfortunately.
We might have to start using size_t for all of the arithmetic in estimating preallocation.
However, it will probably still lead to out-of-memory problems, just with the requested allocation sizes
reported accurately :-)

**Comment by jwpeterson** [comment]
Wouldn't an NxN dense matrix, with N > sqrt(2^31) ~ 46,341 be enough to do it?

**Comment by hsheldon** [comment]
It works with BJACOBI instead of LU. Thanks for your help!

**Comment by WilkAndy** [comment]
Heather, are you talking about your real "Laverton" simulation, or this example?  I hope that "Laverton", because that takes the heat off me :-)

a

**Comment by hsheldon** [comment]
The real Laverton works! So yes, the heat is off you.

**Comment by karpeev** [comment]
BJACOBI is the default.  It really is Block Jacobi with ILU(0) on the blocks, and in serial it reduces to ILU(0).  If you are running in parallel and think it could do better, then you can try ASM with ILU(0) on the blocks.  By default ASM uses overlap of 1, aka ASM(1). ASM(0) will give you BJACOBI, but if ASM(1) works better than ASM(0) then you can try increasing the overlap, but not too much, since it gets progressively more expensive.

**Comment by permcody** [comment]
I'm going to close this issue for now. I think we have a reasonable resolution here.

**Comment by karpeev** [comment]
FWIW, I verified that this problem runs when PETSc is configured
--with-64-bit-indices=1 and libMesh is configured --with-dof-id-bytes=8.
It does slow my laptop way down, since so much memory is allocated for
the factors.

Incidentally, @jwpeterson, the factors don't have to be full, but
they are likely to be dense (e.g., for a banded matrix LU will fill between
the outer diagonals only; the inverse would be dense, however).
Fill-reducing orderings would help some.
