### ISSUE TITLE
Add convenience parameter for groups of coupled variables to SMP

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5679]
Add a parameter to ```SingleMatrixPreconditioner``` that will accept a list of couple variable groups:

```
coupled_groups = 'c,w,eta disp_x,gxx,gxy disp_y,gyx,gyy'
```

This will be a more convenient way of declaring the off-diagonal jacobian blocks for the preconditioning matrix for many phase field applications, where we have lots of coupling between groups of variables but where a ```full = true``` would be overkill.

**Comment by friedmud** [comment]
I think this could just be an addition to SMP... no need for a whole 'nother Preconditioner.

**Comment by dschwen** [comment]
Yeah, maybe, let me push what I have now and let's talk again.

**Comment by dschwen** [comment]
Here. Up to you if we add another parameter and another if clause to SMP. There is not that much code duplication between the two classes, which is why I went with a separate class for now.

**Comment by friedmud** [comment]
I agree about code duplication... but that's not really the issue here.  Your new Preconditioner is still an SMP preconditioner (it still stores everything in a single matrix in the exact same way as SMP)... you're just adding a different method or specifying off-diagonal blocks.

Just thinking of the documentation and explanation to users... I think it would be easier if this were just part of SMP.  Otherwise we'll get a lot of questions along the lines of "What's the difference between SingleMatrixPreconditioner and SparseCouplingPreconditioner??"  Or, even worse, people decide arbitrarily that "sparse coupling" sounds better... so they use it even though they aren't specifying any off-diagonal blocks or they ARE specifying all of them ;-)

I think the new one will just add confusion... so my vote is for just adding this option to SMP.  But maybe others want to weigh in on this ( @andrsd , @permcody , @aeslaughter )

**Comment by friedmud** [comment]
Why did I leave off John?  @jwpeterson ;-)

**Comment by andrsd** [comment]
> I think this could just be an addition to SMP... no need for a whole 'nother Preconditioner.

+1

**Comment by dschwen** [comment]
Ok, all the same to me. I'll rework the branch accordingly.

**Comment by dschwen** [comment]
Is there any benefit to declaring and implementing an empty virtual destructor (isn't it enough that the parent class declares a virtual DTOR)?

**Comment by permcody** [comment]
I don't believe declaring an empty dtor in a derived class is necessary. We seem to do it in MOOSE a lot, but it's not necessary.

**Comment by dschwen** [comment]
Soooo.... I'm removing it then?

**Comment by friedmud** [comment]
Yeah - we started doing that because if people copied our classes we wanted
them to know that the destructor needed to be virtual.

However, it's pretty dang rare for people to need destructors when using
MOOSE... so I vote to take them all out.  If people need destructors then
they should also know enough to make them virtual ;-)
