### ISSUE TITLE
FauxGrainTracker is not drop in for GrainTracker

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5686]
We need a common ```GrainTrackerInterface``` base class which both ```FauxGrainTracker``` and ```GrainTracker``` inherit from. Then all objects (Materials, AuxKernels, Kernels etc. ) that require a grain tracker object should actually call ```getUserObject<GrainTrackerInterface>```. Otherwise the faux grain tracker is pretty much useless...
Ping @permcody

**Comment by permcody** [comment]
Sounds good, I'll take care of this.

**Comment by permcody** [comment]
Actually I was just looking at this and we have a pretty good interface in the BASE CLASS already that both the real and faux grain tracker object inherit from. Does this not meet your needs?

http://mooseframework.org/docs/doxygen/modules/classFeatureFloodCount.html

**Comment by dschwen** [comment]
Oh... ```FeatureFloodCount``` has the full interface? So what happens if I pass a ```FeatureFloodCount``` object to an object that expects a ```GrainTracker```?

**Comment by permcody** [comment]
Well, I think you have it backwards. Your objects should actually use a `FeatureFloodCount` object instead of GrainTracker and you'd pass in either `FauxGrainTracker` or `GrainTracker` based on which object was active for your simulation. This is the way the `FeatureFloodCountAux` object already works. If I need to add additional methods to the BASE CLASS that's fine. It has several already.

**Comment by dschwen** [comment]
Per our discussion from two days ago: The question was whether it makes sense to set up objects to formally request a ```FeatureFloodCount``` object when they _conceptually_ require a grain-tracker-like object. I think the grain-trackerness should be enforced by inserting a class into the inheritance hierarchy below FeatureFloodCount and above the Faux- and real GrainTracker.
