### ISSUE TITLE
Move restart_file_base to [Problem]

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5714]
`restart_file_base` doesn't really belong in `[Executioner]`.  Not only is it not really an Executioner thing... but all the Executioner does is turn around and call `_problem.setRestartFile(_restart_file_base)`... which is just wrong for so many reasons...

**Comment by andrsd** [comment]
Is anybody working on this? If not, I'd do it...

**Comment by permcody** [comment]
Go for it

**Comment by permcody** [comment]
I just chatted with @YaqiWang and @snschune. It looks like none of the Eigen-Executioners support "restart" right now. For one thing they don't set the `restart_file_base` in their Executioners so nothing happens on the problem side. I guess that's a good thing since we won't have to worry about backwards compatibility when we move this. Also, this may have something (everything) to do with why #5436 exists.

@andrsd - Are you still planning on moving this? I don't want to work on #5792 until this issue is resolved. If you don't think you'll get to it, I'll take care of both.

**Comment by andrsd** [comment]
@permcody I won't be able to work on this because of the RIA problem ;-( So go ahead...

**Comment by permcody** [comment]
I bet you wish you were "through" with the Ria problem...
"through" -> dia
So more like "dia-ria"... :imp:
