### ISSUE TITLE
MOOSE Hangs in Multiapps

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5795]
Yikes! It turns out that the `TransientMultiapp::solveStep()` routine has several early exit points where the communicator is left in a swapped state. With the latest additions to the restart and recovery routines, we definitely need to make sure that MOOSE is left in a sane state so that it can recover after failure. I'll fix this.

**Comment by friedmud** [comment]
No - the communicators are not being swapped anymore. The only thing those
routines do is possibly change PETSc options.

If you were seeing a hang this probably wasn't the cause of it.

Derek

**Comment by friedmud** [comment]
Actually - I just looked... and we are swapping something... I don't know
why we're still doing that though... because we give each PETSc object its
own real comm now. I think this is only necessary during options setting. I
should probably revisit that.

**Comment by permcody** [comment]
Well we had a discussion with Dmitry about this. Even if each PETSc object
has it's own comm, there's no notion of a localized Options DB in PETSc.
That's actually a little problematic because if we really do want to have
different PETSc options on different Multiapps, we have to set them in the
Global database then reset them again for each multiapp (asking SNES to
load options from the global DB). We already do this anyway so it's not a
huge code change but the implication is that we can't run two independent
PETSc solves concurrently with that model.

**Comment by friedmud** [comment]
It's not really true. There is a proper way to do this with PETSc... We
just don't use it. The right way to do it is with prefixing:
http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/SNES/SNESSetOptionsPrefix.html

It lets you create a "namespace" for PETSc options so that different solves
can have their own database.

If we would actually use that capability than this kind of thing can go
away completely...

Derek

**Comment by permcody** [comment]
Cool! That's exactly what we need
