### ISSUE TITLE
Restart + Recover

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5877]
Make these two work together.

We'll have a need for running a restart test with recover in the future. While this currently "works" in that it runs, it doesn't seem to quite do the right thing all the way around. When both a restart and recover file exists, one has to take precedence over the other. It shouldn't be too hard to fix this, but the current tests don't quite do the right thing.

**Comment by roystgnr** [comment]
Oh, hey!  Would you look at this.

The discussion in #8410 probably should have gone here.

**Comment by roystgnr** [comment]
restart/new_dt.test now works just fine with recovery, and I think it ought to be representative enough to close this issue.  The restart file always loads time step 10 (in that test, but presumably other restart input files will be written to also load a specific time step), and the recovery always loads the latest time step, so it just works, and it should just work even if we have to do a real recovery.  If the pre-restart run needs to be recovered, the restart time step doesn't exist yet, so it can't take precedence, and if the post-restart run needs to be recovered, time steps after the restart time exist, and so they naturally take precedence.

That still leaves two points of concern IMHO:

If two runs are done using the same output directory (perhaps because the user made a significant change to the input file and wanted to start from t=0), then a recovery will grab the latest time step, even if it came from an older run.  That's a separate issue (or debatably "user error"), though, not related to restart.

If a run crashes while writing the latest time step, a recovery attempt won't know to load the previous time step unless the user manually deletes the broken half-output file.  We'd get a nice error message in devel or dbg modes, but just corrupted data in opt mode.  libMesh doesn't do a lot of opt-mode error checking on I/O, certainly not enough to make it safe to read a truncated file (or an incomplete distributed file set) if a computational node crashes and leaves us with one.  This is also a separate issue, unrelated to recovery, though.
