### ISSUE TITLE
Block restricted nodal user object on all blocks could behave differently from the unrestricted one

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5887]
If we have more than one block in the mesh and a nodal user object on all of these blocks, there will be nodes belongs to multiple blocks, which will make the nodal user object executed multiple times for the same node. On the other hand, unrestricted user object will execute on all nodes once. If the user object is doing some sorts of accumulation like `NodalL2Error`, this will end up with different values. Is this behavior desired? The relevant code for this issue is in `ComputeNodalUserObjectsThread.C`.

**Comment by permcody** [comment]
Yeah, I'm well aware of this issue. In general we call `value()` for every node for every element attached to a node even without bringing block restriction into the mix. Right now, the last person to set the value wins! However, when you consider the normal case of setting initial conditions on a continuous basis, this shouldn't be a problem. Hopefully each node has the same (or close enough to the same) value regardless of the owning element at the time it's called. If you are doing something more complicated, like error accumulation, that may indeed be a problem.

That all being said, we have worked around this problem at least once before. I added a _current_node pointer to ICs earlier this year that would be set if you happen to fall upon a node (something that happens *always* when you are working with LAGRANGE shape functions) and be NULL otherwise. I used this to set my IC per node knowing exactly what node I was located at. This code is in the phase_field module if it's of any use to you.

@dschwen may also be interested in this ticket - it caused us lots of grief here: https://github.com/idaholab/moose/issues/5567

**Comment by dschwen** [comment]
@YaqiWang how could that ever be solved? Imagine you have two different UOs on the two blocks... It boils down to _which block does a node belong to_. I don't see a good way to give a well defined answer to that question.

**Comment by YaqiWang** [comment]
UO is not assigning values of nodes, so it does not have the issue like in initial conditions. We do have the initial condition issue as well, but fortunately it is just for an initial guess, we do not care if it can be accurately done.

**Comment by permcody** [comment]
Sorry, I realize that my earlier comment is not relevant here. I was thinking about ICs when I responded.

I guess I'd like to hear both a use-case and a potential solution for this issue (if there is one). Generally when you are working at nodes you are doing something different (often explicit calculations) than when you are working at elements. Nodes do in fact have the issue of being owned by multiple elements which is why we have those seemingly weird restrictions about coupling in our AuxSystem. 

I'd say that the current behavior is desired and also understood, do you have a different idea?

**Comment by friedmud** [comment]
Yep... this is your own danmn "vault"

![large](https://cloud.githubusercontent.com/assets/870705/10837926/be8ed028-7e95-11e5-8f1b-e541bb7e89d2.png)

Nodes are shared between subdomains... what else could/should be done?

**Comment by YaqiWang** [comment]
Well I can give a use case where nodes are visited multiple times simply because it is connected with multiple blocks. Let's say we have a block restricted nodal variable and want to evaluate NodalL2Error. If we have to make the postprocessor block restricted, this error will give something different than the unrestrained one, which may be undesirable. The proper way of doing this is to create a node set from blocks then let the nodal uo on this node set.

**Comment by permcody** [comment]
"Multiple visitation" is an issue. We can take a look at that.

**Comment by aeslaughter** [comment]
I am running into this with the warehouse re-factor for UserObjects. It seems like the node iterator should handle this, not allowing a node to be visited twice.

I can replicate the current MOOSE behavior but it doesn't feel right to me, because the following two input file blocks give different results (two subdomains exists, 0 and 100, that encompass the entire domain and do not overlap):

```
  [./nodal_sum_block]
    type = NodalSum
    variable = u
    execute_on = 'initial timestep_end'
    block = '0 100'
  [../]

  [./nodal_sum]
    type = NodalSum
    variable = u
    execute_on = 'initial timestep_end'
  [../]
```

We need to make a decision on the desired behavior, because this is a blocker for me at the moment.
@idaholab/moose-developers

**Comment by permcody** [comment]
I believe that this is UserObject dependent. For a given user object this may or may not be desired. 
Maybe the ThreadedNodalLoop should maintain a hash table of visited nodes. Users could set a `unique_node` parameter to trigger one behavior or the other.

**Comment by aeslaughter** [comment]
I am on board with making it optional.

**Comment by YaqiWang** [comment]
This works for me. A nodal user object has this optional parameter.

**Comment by YaqiWang** [comment]
This has been resolved with the parameter `unique_node_execute` in `NodalUserObject` added by @aeslaughter .
