### ISSUE TITLE
Let User Objects know which execute_on stage they are currently being called by

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5888]
It would be useful to have a flag available in a UserObject that tells us whether we are called due to a residual evaluation or due to a Jacobian evaluation. The idea is that We need to assemble Jacobian information in a UserObject that computes a set of integrals over the domain. The Jacobian assembly adds quite a bit of cost and we'd like to avoid it if we only need the residual.

@SudiptaBiswas can use that in the force/torque UO for the rigid body motion system.

**Comment by aeslaughter** [comment]
I am working on cleaning up a few things related to this, I will try to incorporate this. I will add a function to SetupInterface called `getCurrentExecuteFlag` (other names suggests welcome) that returns a Moose::ExecFlagType that will be EXEC_NONE unless you call it from the execute/compute methods.

**Comment by YaqiWang** [comment]
Just let you know, materials are doing things differently. I'd actually like to have the similar thing for material, but it will be something like `FOR_UO FOR_AUX FOR_LINEAR FOR_NONLINEAR`.

**Comment by permcody** [comment]
@aeslaughter - if possible, we should probably do this with a member variable instead of a method. That's more MOOSE-y. It's tricky if you try to add a member to the interface. That member will probably have to go in MooseObject and be set by some internal routine in MOOSE.

**Comment by aeslaughter** [comment]
With my new 'FEProblem::execute' method it will be trivial to use a method of member variable. I already implemented it as a method, so I will wait to change until you have a look see.

**Comment by dschwen** [comment]
Hmm, a method has the advantage of being able to protect the underlying state variable from write access.

**Comment by aeslaughter** [comment]
As a member it would be a constant reference to something living on
FEProblem, so either way it would be protected.

**Comment by dschwen** [comment]
Oh, right.. :+1: then

**Comment by permcody** [comment]
The reason I prefer member over method is because most other state or values you need to access in MOOSE come through members not methods.

See https://github.com/idaholab/moose/blob/devel/framework/include/actions/Action.h#L125

**Comment by friedmud** [comment]
Guys... you should really be using `SystemBase::currentlyComputingJacobian()` for this...

http://mooseframework.org/docs/doxygen/moose/classSystemBase.html#aef317243e2df31c7eff9b5dd963a2ddb

It's the foolproof way to know you're in the Jacobian computation...

**Comment by dschwen** [comment]
> you should really be using SystemBase::currentlyComputingJacobian() for this

Great, for my purpose that would be enough. But making the execute_on flag available does seem more versatile.

**Comment by friedmud** [comment]
It does.  It's fine for both to exist.  Just realize that `execute_on` does not necessarily perfectly map to Jacobian computation.

For instance: someone might do residual computations during their Jacobian computation (some hand coded finite-difference maybe) so that `execute_on=residual`... but `currentlyComputingJacobian()` will be `true`.

Also... someone might do a Jacobian calculation outside of `execute_on=nonlinear`... for instance: to do some automatic residual scaling.  Again, `currentlyComputingJacobian()` should tell you the right thing.

Also: we could add a new `execute_on` flag that happens in the middle of computing a Jacobian... or maybe someone specializes a `Problem` to compute `execute_on=custom` stuff in the middle of their Jacobian computation.

My point is: if what you're trying to do is figure out if the Jacobian is being computed... the best way to know is with `currentlyComputingJacobian()`.  I do agree though that this new added bit of functionality (to get the current `execute_on` can be useful in other scenarios)

**Comment by dschwen** [comment]
@friedmud ```NonlinearSystem::computeJacobianInternal()``` never calls the UserObject stuff and that is the only place that ever sets ```_currently_computing_jacobian = true``` (which is what ```SystemBase::currentlyComputingJacobian()``` returns).

**Comment by friedmud** [comment]
Good catch @dschwen !  Our fix looks good
