### ISSUE TITLE
update_and_rebuild_libmesh.sh hangs, requires user interaction

### ISSUE THREAD

**Issue by jacklinzoho** [idaholab/moose#6072]
When running update_and_rebuild_libmesh.sh on a linux cluster, I get the following message:

"Attention! pax archive volume change required."

This can be manually fixed by entering '.' then enter.  It occurs twice in the script.

Basically, libmesh's configure file goes through a bunch of archiving utilities until one works, but PAX asks for a user prompt.  It needs to be skipped, or at least put on the back of the list.

My dodgy fix: in moose\libmesh\configure,

delete lines 4301 to 4305 inclusive;

change line 4743:
_am_tools='gnutar plaintar pax cpio none'

to

_am_tools='gnutar plaintar cpio none'
![screen shot 2015-12-16 at 2 30 15 pm](https://cloud.githubusercontent.com/assets/15973776/11832522/39db8f40-a40d-11e5-8d84-867c9aa91181.png)

**Comment by jwpeterson** [comment]
This is very strange.  I've never heard of "pax" and have no idea why it is in our configure script... what OS is the cluster you are logged into running??

I'm sure you may already know this, but be aware that manually changing the configure script won't be a permanent fix -- it will break again the next time we update libmesh within MOOSE...

**Comment by jwpeterson** [comment]
Also, can you post the contents of config.log from the original, unaltered configure?  Specifically, the part about why the tar tests failed on your system.  I suspect that we're seeing this because this is the first system where "tar" failed to work.  I'd be wary of any such system...

**Comment by jwpeterson** [comment]
As far as I can tell, there's no reasonable fix for this on our end.  It needs to be fixed by the automake people, but as far as I can tell, they don't consider it to be a bug.  For example, [this guy](http://tinyurl.com/z8elmc6) reported the same issue (as part of a separate problem) but no one mentioned anything about fixing it at the time.  It looks like one other temporary [solution](http://tinyurl.com/zup635e) is to patch configure by adding the `-O` flag to the call to pax, which might be simpler than your proposed fix...
