### ISSUE TITLE
Add target boundary to Multi App Nearest Node Transfer

### ISSUE THREAD

**Issue by sveerara** [idaholab/moose#6156]

**Comment by permcody** [comment]
@sveerara - Thank you, this has been needed for awhile (see #4559).

I do have a few comments though with this PR: First there isn't a test so we really shouldn't merge it as is. Since you are doing things with "active local nodes" and matching up processor ids, you should definitely make sure you get the correct answer in parallel too (which should happen automatically if you don't restrict the parallelism of this test).

On the design side, this class should probably be made to inherit from the BlockRestrictable or BoundaryRestrictable classes instead. I'd be willing to accept the current design in the short term though if you run into problems or don't have time, but @aeslaughter should be able to direct you on how you can use the functionality of those classes to keep the interfaces consistent throughout MOOSE. Again, thanks, we really do need this!

**Comment by sveerara** [comment]
@permcody, I can write a test for this. 
I was working on a simple wave propagation problem where I had to transfer velocity values at a boundary from a different problem but with a similar mesh at the boundary. I tested this on that problem and it worked well in serial as well as parallel. 

If it is not too difficult to make this class inherit from BlockRestrictable or BoundaryRestrictable classes, then I can give it a try. I will talk to @aeslaughter about it. 

Thanks for your comments @permcody and @friedmud.

**Comment by aeslaughter** [comment]
This class could use the `BoundaryRestrictable` interface class, this would replace the `target_boundary` parameter with `boundary`, where `boundary` would refer to the boundary ids/names that the simulation containing the multiapp is using. Doing this will provide you with some additional methods for examining the boundary ids.

I would be happy to do this part after a working test is submitted at it is merged, I will be updating the warehouses for transfers soon anyway.

**Comment by sveerara** [comment]
Great, Thanks! I will work on the test then.

**Comment by friedmud** [comment]
Actually: just inheriting from BoundaryRestrictable is not a good idea.  Transfers need to be specific about "target" and "source".  It's definitely possible that you might want to restrict one or both domains to boundaries...

The current code has only implemented it for "target" but in the future it could get the same ability for "source"

**Comment by permcody** [comment]
Closed in #6157
