### ISSUE TITLE
ExceptionKernel may be borked

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6167]
We have a class level variable that is set when an exception is thrown but we normally duplicate that kernel when we run threads which means we have n_threads copies of that kernel each with their own status variable. What I think should be happening is **all** threads should throw. However from the sporadic fails we are seeing, it appears that perhaps each thread is throwing in different attempts of the same timestep. Maybe when we throw the other thread gets interrupted and doesn't reach that region? We need to look into this and see if we can make it behave with a shared variable.

**Comment by friedmud** [comment]
We specifically want to test throwing from only one thread (that's actually the most common case... it will be rare for multiple objects to encounter an Exception simultaneously in different areas of the Mesh).

The reason that test doesn't work with threading is because of essentially a race condition for which one of the threaded objects is going to throw first.

The Kernel is set up to throw during the first nonlinear iteration.  If you have two threads it's entirely possible that one thread will throw before the other thread even gets started.  That will mean that the "non throwing" Kernel hasn't thrown yet (so ```jac_has_thrown``` is ```false```).  Then the time step will get cut back and on the retry the Kernel that didn't throw last time now will...

The fix is just to only throw from thread 0 (just check tid in the ExceptionKernel).

Note: we can't actually make a reliable test that throws from anything other than thread 0 because TBB is not guaranteed to ever start more than one thread (even if you tell it to).  Just one more reason I recommend not using TBB (especially for testing).

**Comment by permcody** [comment]
I had considered only throwing from thread zero but thought that was sort of side-stepping the whole threaded testing mechanism. What about having a shared variable somewhere that we set in either or any thread? We'd do what we normally do and set a scope lock where we inspect and take action or set a variable appropriately. That would make this test more robust and give us a little more realistic real world testing. Either way...
