### ISSUE TITLE
Crank-Nicolson, RK2, and DIRK time integrators with scalar variables seem not working properly

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6289]
With the following simple input
```
[Mesh]
  type = GeneratedMesh
  dim = 2
  xmin = 0
  xmax = 1
  ymin = 0
  ymax = 1
  nx = 1
  ny = 1
  elem_type = QUAD4
[]

[Variables]
  [./n]
    family = SCALAR
    order = FIRST
    initial_condition = 1
  [../]
[]

[ScalarKernels]
  [./dn]
    type = ODETimeDerivative
    variable = n
  [../]
  [./ode1]
    type = ParsedODEKernel
    function = '-n'
    variable = n
  [../]
[]

[Executioner]
 type = Transient
 start_time = 0
 end_time = 1
 dt = 0.0001
 scheme = bdf2
 solve_type = 'PJFNK'
 timestep_tolerance = 1e-12
[]

[Outputs]
 csv = true
[]
```
The expected value at the end time is exp(1) = 2.718281828459045.

By changing the `Executioner/scheme`, we can obtain:
implicit-euler: 2.7184177551987
explicit-euler: 2.7184177551987
crank-nicolson: 1.6488243172143
bdf2: 2.7182818581953
rk-2: solve did not converge!
dirk: solve did not converge!

As you can see, those three integrators seem not working properly. Did I miss something?

Thanks.

**Comment by jwpeterson** [comment]
Hmm, you probably didn't miss anything.  RK-2 is an explicit method, so you might have to try a much smaller timestep to make it converge?

DIRK2 is implicit and was added more recently.  It should be unconditionally stable and work with this timestep, but it was not yet tested with SCALAR variables, however, so I'm not sure what might be wrong.

**Comment by jwpeterson** [comment]
> RK-2 is an explicit method, so you might have to try a much smaller timestep

Actually no, I see that explicit Euler worked, so that's not the problem.

**Comment by YaqiWang** [comment]
Is this issue difficult enough to be a tiger team topic?

**Comment by jwpeterson** [comment]
I don't know how difficult it will be until I dig down into the problem, but I tagged this issue with the Tiger Team milestone.

**Comment by jwpeterson** [comment]
I dug into this a bit more, and I think the problem is related to the `ScalarKernels` not quite following the `Moose::KT_NONTIME/KT_TIME` classification system that other types of Kernels (for nonlinear variables) follow.

Note also that I can get the `rk-2` and `dirk` `TimeIntegrators` to work in your test problem if I just set `line_search = 'NONE'`, however I'm not sure they are really doing the right thing (probably not converging at the right rate) for Scalar variables because of the same problem that afflicts Crank-Nicolson.

Finally, the `BDF2` TimeIntegrator appears to be much more accurate than the others... I'm not sure why it would not be as strongly affected by the same issues.

**Comment by jwpeterson** [comment]
One other issue I noticed while debugging: the `implicit = false` parameter is not used by `ParsedODEKernel`, so there is currently no way to actually solve ODEs explicitly... the `ODEKernel` values are all evaluated at the new time.
