### ISSUE TITLE
tensor_mechanics axisym_resid test failure on my computer

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6301]
The test 2D_geometries.axisym_resid still fails.  Perhaps this is an important failure, as i **think** the force_z is supposed to agree with an analytical result, and i get things like:

2D_geometries.axisym_resid: force_z rel diff: -1.5825208e-10 ~ 2.2555469e-10 = 1.70161e+00 (node 15)

I really don't know whether this is just roundoff, or whether such a small force_z is actually significant and important, and the test failure is actually indicative of something wrong in moose.

Perhaps @sapitts or @waxmanr can have a quick look?

**Comment by permcody** [comment]
There aren't any problems here.

The problem is that you are down to such a tiny value that it's "flipped"
the sign on one of the architectures. This is fine and completely normal
but it can trip exodiff. There are multiple solutions to this problem.
First you can adjust your abs_zero tolerance. It's around 1e-10 by default
but sometimes that's too tight. Alternatively, you can set the
"use_old_floor" parameter instead which does the differencing slightly
differently to handle these sign flips.

**Comment by WilkAndy** [comment]
I'm not convinced, @permcody.  The header to the test contains this:

PostProcessor force_z plots the force on the top surface of the cylinder.
Displacement of 0.1 is applied to top of cylinder while other surfaces are
constrained. Plotting force_z vs stress_z will show a slope of 3.14159 (pi),
consistent with formula for normal stress:

I get a diff of "force_z" at almost all timesteps.  It seems that "force_z" is in fact quite important to get correct in this test.

If you are right, i can easily just change abs_zero and submit a PR, but i'd like @sapitts or @waxmanr to say "OK" first.

a

**Comment by permcody** [comment]
I believe you are looking at a residual value (axisym_resid) not an actual
value. In that case it could be positive or negative as long as it's close
to zero.

**Comment by sapitts** [comment]
I will need to go through the analytical solution first and the units, because, while 0.1 displacement will be 10% strain in this case, this test appears to be set up to isolate loading/ stress in the z direction.  As @WilkAndy noted, I would also like to double check that setting the abs_zero tolerance makes sense with the problem units, ect.

Give me the weekend to go through this problem (and ignore that this is also exactly what I said last week about the Xcode profiler)?

**Comment by WilkAndy** [comment]
Oh, i think @permcody is right, oops, thanks!  There is a Postprocessor "force_z", but there is also a residual value (from save_in) called "force_z".  It is the latter that is diff-ing.  That's certainly no big deal.  I'll issue a PR soon.

@sapitts - perhaps this means you can actually not work during your weekend?!

**Comment by permcody** [comment]
Alternatively look into the "use_old_floor" option. We've seen this several times before.
