### ISSUE TITLE
Run_tests does not run all tests when --pbs is invoked

### ISSUE THREAD

**Issue by gardnerru** [idaholab/moose#6338]
I noticed this from the bison nightly testing script which uses run_tests --pbs to run all simulations. If there is more than one test listed in the tests file of the directory, only the first is run. (Example below) I can see the results of this nightly because less than half of the bison tests run.

I tested this by running ./run_tests re=thermalFuelNFIR, which I know has 2 tests, and they both ran. I then ./run_tests re=thermalFuelNFIR --pbs and only the first test listed ran.

bison/tests/thermalFuel_NFIR/tests

[Tests]
  [./NFIR]
    type = 'Exodiff'
    input = 'thermalFuel_NFIR_test.i'
    exodiff = 'out_ThermalFuel_NFIR.e'
  [../]
  [./NFIR_Gd]
    type = 'Exodiff'
    input = 'thermalFuel_NFIR_Gd_test.i'
    exodiff = 'out_ThermalFuel_NFIR_Gd.e'
  [../]
[]

**Comment by permcody** [comment]
@milljm - perhaps you can take a look at this?

**Comment by milljm** [comment]
Turns out both tests do run. It is the TestHarness that only reports to the user, that its launching the ClusterLauncher once. The file the ClusterLauncher parses though, has _two_ tests in it, which get serialized into two separate _new_ directories that the TestHarness has no idea about.

I think I need to look at how the TestHarness is parsing what the ClusterLauncher returns. The ClusterLauncher reports its going to run two tests. So we should be able to inform the TestHarness about this case.

**Comment by permcody** [comment]
@milljm - Did #6456 fully resolve this issue?

**Comment by gardnerru** [comment]
Yep. It looks like all tests ran last night.

**Comment by permcody** [comment]
Great - just in time to merge some other new broken code!  Not really, just messing with ya
