### ISSUE TITLE
Minor console issues

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6361]
I have noticed two small issues related with console:
1. why console always output on initial even I said `execute_on = timestep_end`?
2. I cannot pass `_console` to my functions which accepts an `ostream`.

**Comment by aeslaughter** [comment]
On Mon, Feb 22, 2016 at 1:14 PM, Yaqi <notifications@github.com> wrote:

> I have noticed two small issues related with console:
> 1. why console always output on initial even I said execute_on =
> timestep_end?
>
From the wiki:

Console-based outputs have special inheritance of common parameters

   - The execute_on parameter, as detailed below, does not get inherited.


This was implemented because 99% of users would find it strange that
initial timestep information is not printed.

> 2. I cannot pass _console to my functions which accepts an ostream.
>
We should probably fix this.

**Comment by YaqiWang** [comment]
Great, I am the 1%... ;-) To me the initial values are just bunch of zeros and meaningless. Outputting them on screen seems odd. But I agree that it could contain vital information so I will live with it.

**Comment by permcody** [comment]
Both issues have been commented on here. Neither will be handled differently in the code so there are no actions remaining. Closing...
