### ISSUE TITLE
memory issue while using moose random number

### ISSUE THREAD

**Issue by hchen139** [idaholab/moose#6590]
### Description of the enhancement or error report
For problems with large number of elements, the use of moose random number generator causes critical memory issue. I tested the problem of ```moose/test/tests/utils/random/random.i```, the following is the amount of memory used during the run, which also can be seen from the attached memory_logger plots:

memory usage:----------------------------------------serial (1 proc)---------------parallel (20 procs)

turn on moose random number generator:---------------approx. 3 G-------------------approx. 55 G
 
turn off moose random number generator:---------------approx. 400 M---------------approx. 3.5 G

![const_proc1_memory](https://cloud.githubusercontent.com/assets/15823825/13789237/b010e458-eaa8-11e5-9209-5be145fdaf1c.png)
![const_proc20_memory](https://cloud.githubusercontent.com/assets/15823825/13789238/b02576de-eaa8-11e5-8d2c-0e87ef3a4543.png)
![random_proc1_memory](https://cloud.githubusercontent.com/assets/15823825/13789263/c9da1508-eaa8-11e5-87f3-877b95b9ed28.png)
![random_proc20_memory](https://cloud.githubusercontent.com/assets/15823825/13789264/c9e88278-eaa8-11e5-9507-687d32dfaaad.png)

### Rationale for the enhancement or information for reproducing the error
For the case of using moose random number, the mesh density was increased to 500 x 500 in random.i

For the case of assuming constant number, the class RandomAux.C (moose/test/src/auxkernels/RandomAux.C) was modified as follows:

commented out "setRandomResetFrequency(EXEC_LINEAR)" in the constructor;

replaced "return getRandomLong()" and "return getRandomReal()" with constant value returned in method "computeValue()". In my case, it was 0.01.

For both cases, the same mesh density was used, i.e., 500 x 500.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by hchen139** [comment]
@permcody Could you help me take a look at it? Thanks!

**Comment by permcody** [comment]
Excellent test case - Thank you! I'll take it from here but it might take me some time to dig to the bottom of it. I suggest you come up with another scheme in the meantime so that this doesn't hold you up.

**Comment by permcody** [comment]
I just did a little bit of digging and found some low hanging fruit. Currently, I'm storing all of the generator states on all processors instead of just the ones local to that processor, that can be quickly and easily fixed. I think there's still a significant overhead to storing states, but we should be able to get it down.

In this problem you have 250K elements. I looked up the state size and it's 624 bytes. We are using an unordered_map which has somewhere on the order of 3-4 pointers per entry. Finally we are storing two completely maps of pointers, one for the previous state and one for the current state (this can be consolidated).

250000 elems * 624 bytes per state * 4 pointers per cell * 2 maps = 1.2GB! 

When you run that on 20 processors, all of that is currently duplicated ~ 25GB!

I should be able to store only the local generators and reduce the map count to one. That will drastically reduce the memory usage but won't cut it all the way out.

**Comment by hchen139** [comment]
@permcody @bwspenc Thanks. This will definitely save large amount memory. But still may cause some trouble when running on HPC using many processors.

**Comment by permcody** [comment]
Yeah, those states can certainly add up with the maps and all the others pieces but in general you should have at least 4 GBs of memory / processor on a cluster so you should be OK as you spread the problem out. If you still run into problems, please report back and we'll look for more ways to save space. The graph I included goes up because there is some amount of duplicate storage as you add processors but it pays off in time saved.

**Comment by friedmud** [comment]
With the new fixes the memory should "scale" (nearly) perfectly... meaning,
as you spread the problem out the memory for states will also get spread
out. so it shouldn't be an issue when using many processors.

**Comment by hchen139** [comment]
@permcody  @friedmud Thanks. For my specific application, this still may not be the best solution. For example, the largest number of linear truss element I can use on HPC so far is 22 million. In terms of these many elements, the amount of memory consumed by the moose random number generator is not small at all.

**Comment by permcody** [comment]
Right. The MOOSE random number generator is for generating consistent
random numbers regardless of decomposition. You actually don't need that at
all for your case. You might just use the static methods and generate your
own stream of numbers without saving state for your use-case.

**Comment by permcody** [comment]
Alternatively I could add a flag for not saving state... Hmm that might be
a good idea

**Comment by hchen139** [comment]
Right, I'm now using the static method MooseRandom:randNormal() for my current purpose.
@permcody can you add a method for weibull distribution in MooseRandom.C from randistrs.C. So I can directly call from MooseRandom.C. Thanks.
