### ISSUE TITLE
run_tests with oprof gets slower after a dbg build

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#6668]
### Description of the enhancement or error report

Run tests gets slow after a debug build, can anyone else see if they have this problem? Or am I just crazy? Or both?
### Rationale for the enhancement or information for reproducing the error

(1) Build and run tests in oprof mode

```
cd ~/projects/moose
git clean -fxd
cd test
METHOD=oprof make -j90
./run_tests -j24 --oprof
```

```
Ran 1206 tests in 48.6 seconds
1206 passed, 17 skipped, 0 pending, 0 failed
```

(2) Build in debug mode

```
METHOD=dbg make -j90
```

(3) Run tests again in oprof:

```
./run_tests -j24 --oprof
```

```
Ran 1206 tests in 188.0 seconds
1206 passed, 17 skipped, 0 pending, 0 failed
```
### Identified impact

There should be no impact.

**Comment by permcody** [comment]
Could you do a full `make clobberall` in between?

**Comment by permcody** [comment]
We now know that this is caused by *not* including suffixes when building exodiff in contrib. Andrew had the sanitizer enabled on one of his modes and if he built debug mode, he'd sometimes get a sanitized enabled exodiff. We could fix this but it's really not a major issue. I'll mark it as minor and reclassify the component.

**Comment by aeslaughter** [comment]
This is no longer an issue with the changes to how we build MOOSE and the test harness itself.
