### ISSUE TITLE
Material Auxs at specified quad points

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6679]
Could we discuss the following?  Tagging @hsheldon

In tensor mechanics we often want to output Material values as AuxVars, e.g. stresses, internal parameters, yield function values, and so on.  Currently with the usual CONSTANT MONOMIAL AuxVariables we see the values averaged over the element.  It would be useful in certain instances to see them at a specified quad point.

The solid_mechanics/src/aux/MaterialTensorAux has this ability to specify the quadpoint you're interested in.

I think i'm asking two questions:

(1) Do people think this is dumb, or implementable with a simple change to the input file?

(2) Where/how should it be implemented.  Eg, right in framework/src/auxkernels/AuxKernel.C , or in individual derived classes, or somewhere intermediate (like MaterialAuxBase, but i'm not sure how to actually do that in practice), or somehow else?

**Comment by permcody** [comment]
I think it's worth stepping back and understanding why the AuxSystem and Materials are fundamentally different. The AuxSystem is full of discretized variables just like the nonlinear system. The only difference is that you are explicitly computing the values rather than solving a linear system. At the end of the day your "quadrature point" information is used to setup the coefficients so for the shape functions so we can't guarantee that you'll recover the information at the quadrature points "exactly" the same way as it goes in. 

Now we DO support higher order monomials so you aren't limited to just CONSTANT MONOMIAL. If you use a higher order you should be fairly close to getting back your exact same values depending on the order. There may be a few bugs that we need to work out here but it should be pretty close, there are even tests in the moose-test suite.

The material system was designed so you could compute exact values at quadrature points per element and furthermore, those values don't even have to be just double-precision. They can be rich types like vectors or tensors.

Could you just use a sufficiently high monomial order to get you past your current hurdle?

**Comment by pou036** [comment]
We found out a year ago, when building Redback, exactly what Cody mentioned. Using a higher order (in the .i file) for our total_porosity AuxVar did the trick.

**Comment by WilkAndy** [comment]
This is unrelated to a previous question concerning porosity.

@hsheldon wants to see exactly which quadpoint has yielded in plasticity (and how exactly that quadpoint has yielded in the case of multisurface plasticity), and also see the stresses there.  All these things - stresses, internal parameters, and yield functions - are calculated in a Material at each quadpoint.

Until now she has output these parameters as AuxVariables and been happy with using CONSTANT MONOMIAL, especially as that is paraviews default for visualisation, but of course she's only getting an average over the element in that case.  However, now she has a situation where one quadpoint in the element has yielded, whereas the others haven't, and it's that quadpoint that has the interesting physics associated with it.  When you do an average over the element the results are rather unhelpful and meaningless.  She wants to explore what's happening at that one quadpoint.

**Comment by permcody** [comment]
How about some sort of "save_in" capability where the exact computed values are saved in addition to being used to compute the shape functions? Yes this would add a fair amount of overhead but we could be smart about it. We could just keep the information around for a single timestep (if that's sufficient) and not bother with communicating that information globally.

Alternatively, you could just solve this problem with a UserObject. You'd just build your own cache of the data (it may be a little work to get it into the UO but should be doable).

**Comment by WilkAndy** [comment]
Hmmm, the save_in capability is something i hadn't thought of, and i reckon it'd work well.  It's a lot of work though.  Are you imagining that every Material now has a "save_in" for each of its properties?  At a given quadpoint in each element we'd want to be able to save components of Vectors, Tensors, and std::vectors.

**Comment by friedmud** [comment]
@WilkAndy 

@permcody 's explanation is spot on.  But let me add something else: there are currently no file formats available that would allow us to specify quadrature point information.

If there were... I would be open to it.  But there is nothing that I know of that Paraview reads that can have quadrature point data in it.

In the past I have thought about actually creating a new _mesh_... one that just contains nodes that correspond to the quadrature points and then setting values at each one and outputting that.  You would need to overlay it on top of your other "norma" mesh... but it might just do the trick.

It's definitely not something you would want to do very often... but it could be useful in debugging.

**Comment by WilkAndy** [comment]
Yea, it's a shame that paraview plots CellData as constant-monomial.  @hsheldon is simply going to create 8 aux variables, one for each quad point in the hexahedral elements, and manually inspect each of the 8 in paraview.  Not very satisfactory, i know, but as you say - this is not something she's doing every day.

**Comment by hsheldon** [comment]
Thanks for the discussion. Creating 8 aux vars and manually inspecting in Paraview would be fine, as Andy said its not something I would be doing all the time.

**Comment by WilkAndy** [comment]
Note to self: @hsheldon requires these classes to have this feature: RankTwoScalarAux, MaterialStdVectorAux.
