### ISSUE TITLE
--error is probably too heavy handed in run_tests

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6923]
### Description of the enhancement or error report

@sapitts wants to deprecate code however she can't get her PR to work because --error turns deprecated warnings into errors immediately.

### Rationale for the enhancement or information for reproducing the error

deprecating code is something we DO want to allow

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

moose_test, modules and marmot have all added "--error" to their run_tests scripts.

ping @dschwen and @YaqiWang

**Comment by YaqiWang** [comment]
Yes, I am working on fixing yak/rattlesnake for `--error`. `mooseInfo` is part of the efforts. This allowing deprecation is something I will need too.

**Comment by dschwen** [comment]
I don't get it. Just fix the tests?

**Comment by permcody** [comment]
With this flag, we can't deprecate code at all!

**Comment by dschwen** [comment]
Of course we can. We just cannot keep deprecated code in our tests. What am
I missing here?

**Comment by permcody** [comment]
It's just a pain to do these "incompatible API" changes. Yeah the core team
can handle them well enough but it's more difficult for everyone else.

**Comment by sapitts** [comment]
@dschwen I've introduced a separate material to calculate the thermal expansion as an eigenstrain, rather than in the compute*strain material, as we've discussed.  Obviously, this new material requires changes to the input file syntax.  To avoid needing an application patch, Cody suggested using the deprecated code flag in moose to pass Civet, then updating the three tests in marmot and bison.  

Would it be possible to allow deprecated code in the application tests for 48 or 72 hours for these sort of small input file changes?

**Comment by permcody** [comment]
We could do several things. See my comment here:
https://github.com/idaholab/moose/pull/6937

**Comment by sapitts** [comment]
Thanks @permcody, I'll wait (/ eavesdrop intently) on the developers' decision and adjust my PR as needed.  Thank you for the help!

**Comment by permcody** [comment]
http://mooseframework.org/blog/changing-a-published-api-deprecation/
