### ISSUE TITLE
Enable Transfers between relatives and not just parent/child apps

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#7026]
### Description of the enhancement or error report
Allow transfers between apps that are not parent/child apps.

### Rationale for the enhancement or information for reproducing the error
We have seen for a particular multiphysics reactor problem that coupling 
three different apps is best done using a multiapp setup like `app1 -> sub1 -> subsub1`.

However, `subsub1` computes the density of the moderator which is not used in `sub1`, but
is required `app1`. Moreover, `sub1` does not even have the moderator region. This forces a 
bunch of workarounds that are error-prone and not easy to setup for users. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Need to think carefully about making this user friendly. Note that the input file of `app1` does not
even know that `subsub1` exists so we need to deal with transfers to non-existing apps.

**Comment by YaqiWang** [comment]
Maybe we just need to enable a syntax in the `multi_app` parameter of the `MultiAppTransfer` something like `sub1::subsub1`. Then the transfer will grab the multiapp and do the transfer? The problem is that now that `sub1` could have multiple positions. I guess we can have multiple multiapps in the transfer?

**Comment by friedmud** [comment]
This breaks the entire idea of Multiapps.  The parent is not supposed to know or care that subsub1 exists.  It's like that in purpose.

The reason Multiapps have been successful is because of the encapsulation built into the system.  Yes, that encapsulation brings limitations, but without those limitations none of this would be usable by normal humans.

You're going to have to find another way to work this issue.

**Comment by andrsd** [comment]
> The parent is not supposed to know or care that subsub1 exists. It's like that in purpose.

Do we not specify the transfers and multi-apps in the parent? It is the subapp, that does not know about the parent, right?

**Comment by dschwen** [comment]
I think Derek was talking about one layer removed

```
parent -> sub1 -> subsub1
```

**Comment by andrsd** [comment]
Oh, I see, it is `subsub1`! I misread it as `sub1`. Makes sense now...

**Comment by snschune** [comment]
If that is a central point in MultiApps' design, we'll need to find another way. There are multiple other options. What I wanted to avoid is that we need to cater our app models to limitation in the system, which is exactly what we are doing right now. This is hard to sell to potential end users that do not care about
encapsulation as much as they care about their convenience. 

@friedmud What kind of scenario do you want to avoid that makes this unusable for humans? I would argue that information transfer between apps that vary in dimensionality and/or do not have all blocks in common is as unmanageable by humans. Especially if information is passed through an intermediate app that does not even use this information.

**Comment by permcody** [comment]
I thought about this last night. I was initially resistive when @snschune asked me about it yesterday for the same reasons Derek said (plus Daniel's correction), however it is worth putting aside that concern for a moment to realize that this capability would actually be quite useful if designed correctly so let's toss out some ideas and make the decision on whether we should or shouldn't go down this path after we've talked about real pros and cons.

The problem is real. I don't want to go into the specifics of the problem here but lets just say that the three different domains in the sprint problem are all *very* different. It's a real challenge to move information from the top layer to the third layer in some cases. Yes it can be done but not only does it require two transfers, there's no need for the information to land at layer two.

The current Transfers design allows you to move information from your layer down to the next layer regardless of the direction of the transfer. The biggest problem with this new idea is naming. With the current design, everything about the Transfer can be specified in the current input file (the multiapps are named in the current input file). If we allowed transferring to an indirect level we don't have a good way of saying what Multiapp you're transferring to or from. We'd have to devise a labeling system that could survive changes to either the main or sub input files and I'm not sure there is one. Yeah, I know you could say transfer to "subsub1" and then hope that the name in the child file doesn't change - YUCK. We might say transfer to the first child of sub1 or something... If we could come up with a sane way to do this, everything else would work fairly seamlessly. 

Assuming we solve the destination labeling problem, everything else would be fairly straightforward. We'd just setup the pointers to the meshes and objects after the Multiapp tree was constructed. We'd run the sanity checks in the same place to make sure all of the right objects exist. This would be a really cool feature and would probably go a long ways politically. Can you imagine the new graphs with arrows going from one part of the tree to another without the intermediary?

**Comment by YaqiWang** [comment]
This problem rises from the fact we do not have a good control on how multiapps are executed. We actually discussed this before. We want apps in a certain order and sometimes want to do Picard iteration on a small group of apps to let them converge first, so on and so forth. In the sprint problem, we set up multiapps in the way `master->sub->subsub` only because we want to let `sub` and `subsub` do the Picard iteration and converge first at every time step. If we can design a way to inform MOOSE to execute multiapps in a certain way, this transfer is not needed at least for this problem.

I tend to think this transfer is making the system even more complicated and harder to maintain. So overall I do not like it. But we do not make it very general, we can have an application specific transfer, which for example only allow such a transfer when `sub` and `subsub` have no multiple instances. Again @permcody spoke out the point, the problem is real, we ought to find out a way to resolve it.

**Comment by snschune** [comment]
So I am going to argue against my own suggestion by suggesting another way of dealing with the sprint issue. `subsub` is 1D and has a quantity that the master needs in its moderator block. Currently we simply use volumetric variables defined everywhere in the `sub` and `master` to store this information. That works if you do it right, but it's somewhat error prone.
 
What if we transfer it to a mortar 1D mesh in `sub` and then communicate it up to an identical mortar mesh in the master. From there we can assign it to the volumetric variable defined only in the moderator block. No layered averages or `1D->3D` nearest node transfers.
