### ISSUE TITLE
Make PETSc options from commandline always win

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#7224]
There are three ways to pass PETSc options through moose to PETSc: executioner, preconditioner, and commandline. The priority from high to low is: commandline, preconditioner and executioner.

Highly recommend that solver related PETSc options  should be listed in [Executioner] block,  and preconditioner related PETSc options in [Preconditioning] block. Options from commandline usually is used for debugging or tuning solvers.

**Comment by friedmud** [comment]
Seems fine to me... if you can pull it off.

What happens when someone puts (the equivalent of) `-pc_type asm -sub_pc_type lu` in their input file and then on the command-line they put `-pc_type bjacobi`?

Will the `-sub_pc_type lu` still stick... or will the `-pc_type bjacobi` wipe it out and use the default (`-sub_pc_type ilu`)?

Not trying to poke holes... just seriously asking what your plan is...

**Comment by friedmud** [comment]
Or, even worse, puts `-pc_type hypre -pc_hypre_type boomeramg` on the command-line (so `-sub_pc_type` isn't even an option anymore).

**Comment by fdkong** [comment]
Thanks a lot for your comments. 

Yes. -sub_pc_type lu will be used, and we do not wipe it out. There are many algorithms in PETSc, and different algorithms have totally different options.  There does not exist a mechanism (like "database" or something else ) in PETSc for us to query options for a given algorithm. We hence do not know how to swipe out useless or duplicate options in MOOSE. No way to do that right now.

 Those issues can not be fixed unless something new happens in PETSc.

**Comment by friedmud** [comment]
Sounds good

**Comment by lindsayad** [comment]
Should be closed by #7225

**Comment by fdkong** [comment]
Closed it thanks to #7225
