### ISSUE TITLE
Boundary conditions and block restricted variables

### ISSUE THREAD

**Issue by weixiongzheng1** [idaholab/moose#7300]
### Description of the enhancement or error report
The problem occurs if you have multiple variables restricted to separate blocks.
The boundary between the blocks (aka the interface) splits a domain boundary into two.

When a boundary condition is evaluated on the domain boundary, it is executed for all the
faces regardless of which block the associated element  belongs to. This leads to a segmentation fault.  
 
### Rationale for the enhancement or information for reproducing the error
BCs should only be evaluated on faces that belong to elements with the correct block id. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Changes to BC Warehouse and/or `ComputeResidualThread::onBoundary`

**Comment by mangerij** [comment]
Maybe I'm a bit out of my league getting involved with this discussion

But I _think_ I'm somewhat familiar with this problem, but it doesn't _always_ happen. 

I'm running a multiblock mesh right now, where {u,v} live on block 1, {v} lives on block 2} and I can set boundary conditions at the interface between block 1 and 2 on u with no problem. I also, if I wanted to, could set boundary conditions at the interface on v with no problem. Block 1 or 2 doesn't "own" the interface, it is shared between the two...

That being said, I have had situations where the above two scenarios could cause a segfault which is what I believe you are referring to?

**Comment by snschune** [comment]
I think this problem is a little different because it's not about the interface between the two problems. It's about the external boundary that is separated into two pieces by the internal interface. 

A simple example is a square domain [0,1]^2 that is divided into two blocks by a vertical line at x=0.5. The left block is 0 and the right block is 1. Block 0 defines variable v0 and block 1v1. The vertical line separates at x=0.5 separates the bottom and top boundaries into two, a left and a right piece each. The left piece belongs is adjacent to elements that belong to block 0 while the right piece is adjacent only to elements of block 1. 

We observed that BCs that are associated with variable v0 are called for elements' faces belonging to the bottom and top boundaries right of the x=0.5 line. This causes a seg fault as there are no dofs associated.

**Comment by weixiongzheng1** [comment]
The problem we have is a bit different. Define a problem with u and v living on two-block domain L (left) and R (right), respectively. The interface intersects the top and bottom boundaries. 

When you implement a boundary condition for top and bottom, you are supposed to impose a boundary at left parts of top/bottom for u and the other parts of the top/bottom domain boundaries for v. However, the implementation for the our current boundary implementation does not allow user to specify which part of a boundary one is gonna apply to which variable. It rather takes the whole top/bottom as the boundaries you are impose your conditions to both u and v.

So, when you restrict u to live on block L and do the same thing to v and R, the segfault comes. Because, part of the boundaries you impose are outside the subdomains where the variables live. But if you don't do the restriction, simulation runs, but results are not correct.

**Comment by mangerij** [comment]
I see. Thanks for clarifying.

**Comment by snschune** [comment]
We could override `BoundaryCondition::shouldApply()` somewhere (IntegratedBC ?). 
Instead of returning `true` we can do:
```
return _var.subdomainIds.count(_current_elem->subdomain_id());
```

or if we don't always want to search a `std::set` maybe add a variable
`_check_block' that defaults to false and do:
```
if (!_check_block)
  return true;
return _var.subdomainIds.count(_current_elem->subdomain_id());
```

**Comment by weixiongzheng1** [comment]
I actually wanna do a overloading here. I noticed that ComputeResidualThread is not the only class which uses BoundaryCondition::shouldApply. In fact, classes like NonlinearSystem also uses it. So I wanna keep shouldApply() as it is, meanwhile I generate a overload here:

BoundaryCondition::shouldApply(const Elem *elem)
{
  return (_var.activeSubdomains().count(elem->subdomain_id())>0);
}

So we the only extra work we need to do is to modify ComputeResidualThread a little bit without messing up other classes.

Does this make sense?

**Comment by friedmud** [comment]
Ummm... no.

This is just your fault.

You applied a boundary condition to a variable that doesn't live on that (complete) boundary.

There is nothing to fix here other than that should be an error from MOOSE.  I've opened a new Issue to do that here: #7301

The way to fix your problem is to not do this... you need to define two sidesets for that boundary - one for each portion of the boundary and apply a BC for each variable on the correct sideset for that variable.

**Comment by snschune** [comment]
Well, yeah, that is the other solution to the problem.
In 3D you might have quite a number of different sidesets though so it's really inconvenient having to define and associate them with the correct BCs. 

The purpose of this is multi scale transport and we will have to automate this somehow due to the large number of variables. That'll lead to a ton of code while this really is a lightweight change that doesn't seem to hurt anyone. Why the strong objection?

**Comment by friedmud** [comment]
It's just sloppy... and adding checking for this to `shouldApply()` (which isn't even the right thing to do) will slow everyone down.

If you tried this with Kernels (try applying a Kernel to a block where a variable doesn't exist) you would get an error.  BC's shouldn't be any different.

Further... making it silently do "something" could be hazardous in and of itself.  Maybe a mistake was made in mesh generation and a block wasn't defined correctly or a sideset... with this change it would give you an "answer" that could be wrong but you wouldn't notice or know.

The right thing to do is to specify everything correctly.

**Comment by friedmud** [comment]
BTW: It should be easy to add the sideset that you need.  `AddSideSetsFromNormals` should work well.
