### ISSUE TITLE
FeatureFloodCount results are incorrect and change with number of MPI tasks

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#7310]
### Description of the enhancement or error report
When using the FeatureFloodCount postprocessor I am getting incorrect/inconsistent results when I change the number of MPI tasks (with mpirun -np XX on the command line).
@permcody this is the one I was asking about this afternoon.

### Rationale for the enhancement or information for reproducing the error
I created an example file and included a copy in `modules/phase_field/tests/MultiSmoothCircleIC/kks_mech.i` (getting ready to create a branch to push). This is a coupled KKS phase-field model with mechanics where we should be able to count 5 precipitates 
-The postprocessor output to the console gives a different number for different number of MPI tasks
-In the bubble_volume file, the number of bubbles does not match the 5 bubbles you can count by looking at the simulation. Several bubbles have zero volume, and the number of bubbles and the volume of the bubbles changes with the number of MPI tasks.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by laagesen** [comment]
Here is my branch with the example file located at `modules/phase_field/tests/MultiSmoothCircleIC/kks_mech.i`

https://github.com/laagesen/moose/tree/ffc_mpi_7310

**Comment by permcody** [comment]
@laagesen This input file isn't running with this branch for me:

```
*** ERROR ***
A 'ComputeElasticityTensor' is not a registered object.

We loaded objects from the following libraries and still couldn't find your object:
	(NONE)


Make sure you have compiled the library and either set the "library_path" variable in your input file or exported "MOOSE_LIBRARY_PATH".
```

I noticed that you are using the nodal flood mode instead of elemental. If you get a chance see if it works with the elemental mode. (I've put a lot more effort into the elemental mode than I have the nodal mode. They both should work but I'd be curious if the bug is only present on the nodal branch)

```
flood_entity_type = ELEMENTAL
```

**Comment by laagesen** [comment]
OK I will try with elemental flood. When you tried to run, did you use the phase-field module executable or the combined module executable ? Sorry, I forgot to mention that I am running it with `modules-opt`.

**Comment by permcody** [comment]
It should work just fine with either. You might turn on the FeatureFloodAux in your input file so that you can see what the FeatureFloodCount object sees. Turn on the "UNIQUE_REGION" enum option.

**Comment by laagesen** [comment]
Right, sorry, what I meant was that the `modules-opt` is needed for the the elasticity stuff, so if you try to run this particular input file with the phase-field executable that's why you get the error message about the `ComputeElasticityTensor` object.

I tried running with `flood_entity_type = ELEMENTAL` using `modules-opt` and I did get the correct number of particles (5) in the console output, but the bubble_volume file had only two bubbles with non-zero volume, and three bubbles with zero volume.

**Comment by permcody** [comment]
OK - I'm currently reworking all of the volume calculation logic. I'm not satisfied at all with the existing logic after the refactoring so I'll fix that shortly (today or later this week) and we can try this file again. Thanks for letting me know I need the combined module, that gives me a test case. 

Also, I'll take a look at the nodal issue. Like I said, I've been really working the elemental flooding and there might be a few regressions in the nodal logic.

Finally, we should chat more about computing volume with the "nodal" method when @tonkmr and/or @dschwen gets in. The existing logic loops over elements and counts the volume if a majority of the nodes are flooded. I'm not sure I like this but if you or the others think it's fine, we can continue to support that, otherwise I might propose dropping the nodal "volume" method altogether since everything is much more simple and clean without it.

**Comment by laagesen** [comment]
Sounds good thanks! Also I tried adding the FeatureFloodCountAux with `UNIQUE_REGION`. At least for the elemental flood type it does look like it is correctly identifying the unique bubbles. I'll push the updated input file with the FeatureFloodCountAux to my branch (I tried uploading the image but for some reason that's not working)

**Comment by permcody** [comment]
@laagesen - can you see the images here? https://cloud.github.com

**Comment by laagesen** [comment]
I don't see them- using Chrome on Mac- is there a plugin I need to add or something?

**Comment by permcody** [comment]
@laagesen - The new volume calculation method has been checked in (only works with Elemental which is now the default). Try your test again and close this if everything is working for you.

Thanks

**Comment by laagesen** [comment]
Thanks! I will give it a try.

**Comment by laagesen** [comment]
Looks like it's working- thanks again! I will close the issue.

**Comment by permcody** [comment]
@laagesen - Since the documentation is lacking on the FeatureFloodCount object (hopefully will be rectified soon), I'll mention this here. The volume calculation can now be controlled by the `volume_threshold` parameter which can be different than the normal `threshold` parameter you set. If you don't set it, it uses uses `threshold`.
