### ISSUE TITLE
Migrate Smeared Cracking Materials to Tensor Mechanics

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#7415]
### Description of the enhancement or error report

The smeared cracking models in Solid Mechanics need to be migrated to Tensor Mechanics:
- RateDepSmearCrackModel
- RateDepSmearIsoCrackModel

As these materials are migrated, the original solid mechanics version will be modified by appending a _sm at the end of the file names until all of the fracture models are also migrated to tensor mechanics.  The tests for both solid mechanics and the new tensor mechanics materials will be moved to the combined folder.
### Rationale for the enhancement or information for reproducing the error

Keep chipping away at solid mechanics migration
### Identified impact

Keep chipping away at solid mechanics

**Comment by dschwen** [comment]
how about `RateDependentSmearCrackModel` (or `RateDepositionSmearCrackModel`, `RateDeportationSmearCrackModel`, `RateDepartureSmearCrackModel`, `RateDepletionSmearCrackModel`, `RateDepressedSmearCrackModel`, `RateDepthSmearCrackModel`, `RateDepravedSmearCrackModel`...)

**Comment by sapitts** [comment]
How about `ComputeRateDepSmearedCrackStress` for a name for the new tensor mechanics version?  (those material model names in the last row seem rather sad)

**Comment by sapitts** [comment]
@bwspenc are the capabilities for smeared cracking already in tensor mechanics via `ComputeElasticSmearedCrackingStress`? Looks like the codes are similar but `ComputeElasticSmearedCrackingStress` appears to have more options

**Comment by bwspenc** [comment]
@sapitts The `ComputeElasticSmearedCrackingStress` model is equivalent to what is available for all models that derive from `SolidModel`, but as its name implies, it is only implemented for an elastic material. The next step for that is to figure out to make that a recompute model so that we can use it with other inelastic models.

These models were developed by @cpritam, and I don't really know much about them.  As their name implies, They're rate-dependent, whereas the other smeared crack models are not. If possible, I think it would make a lot of sense to merge them with the other models, and maybe just have an option to turn the rate-dependence on or off.

**Comment by sapitts** [comment]
@cpritam Would you be willing to give me the name of the reference source for the rate dependent solid mechanics models?  With the equations it will be easier for me to figure out how to collect all of the different model options into a single code.

**Comment by sapitts** [comment]
Closed by #9586, #9540

**Comment by bwspenc** [comment]
We still need to migrate the full set of tests over before we can close this issue.
