### ISSUE TITLE
Arbitrary execute_on

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#7489]
### Description of the enhancement or error report

I want the ability to add my own options to `execute_on`... so I can add as many as I want and execute them arbitrarily.
### Rationale for the enhancement or information for reproducing the error

It would be useful for complex custom Executioners / Systems
### Identified impact

Storage for all objects will need to change.  Some amount of engineering required... probably associated with `MooseApp`.

**Comment by rwcarlsen** [comment]
How about something like:

```c++
class EventRouter
{
public:
  EventRouter(InputParameters& params) : _id(0), _events() {}

  void trigger(std::string event_name)
  {
    for (auto func : _events[event_name]) {
      func(event_name);
    }
  }

  int registerFor(std::string event, std::function<(std::string)> func)
  {
    _events[event].push_back(func);
    return _events[event].size()-1;
  }

  void unregister(std::string event, int index)
  {
    _events[event].erase(_events[event].begin()+index);
  }

private:
  std::map<std::string, std::vector<std::function<(std::string)>>> _events;
};
```
Then we just splatter MOOSE framework with calls to ``trigger([event])`` that allows any code to write callbacks for that point of execution.  For example, we could write ``trigger("feproblem-initialsetup-begin")`` at the start of FEProblemBase::initialSetup and then people could write ``registerFor("feproblem-initialsetup-begin", [this](std::string) {_problem.dt() *= 2;})`` or whatever.  User apps could easily come up with their own events to trigger that other parts of their code or other users' code could register against.

We could use enums, or whatever instead of strings for event ids/names - but something like strings makes it easy to allow users to add custom event triggers/callbacks.  We could have reserved event previx(es) for core moose events too.

Thoughts?

**Comment by rwcarlsen** [comment]
Actually - my naive unregister implementation is clearly fatally broken :-\  Ignore that - it wouldn't be hard to do it right :)

**Comment by friedmud** [comment]
The problem is dependencies between systems.  For instance: Material
properties might need initial setup before Postprocessors, etc.

What you're suggesting is actually down a different path: toward DAG based
execution.  To do that right we need much more than what you're
suggesting... dependencies have to be taken into account.  We're slowly
heading that direction... but that's not what this Issue is about.

All that this issue is asking for is for user-made, custom Executioners /
Systems to be able to have their own specific "execute_on" times.  Simply
allow the expansion of the current set of "execute_on" parameters.

It should be pretty simple.
