### ISSUE TITLE
A multiapp output issue with mooseWarning

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7498]
### Description of the enhancement or error report

Here I am attaching a piece of screen output from our coupling calculation:

```
bison0: 
bison0:     Mammoth version:     git commit a4113fa on 2016-08-03
bison0: Rattlesnake version:     git commit b075419 on 2016-08-03
bison0:         YAK version:     git commit ffd65ce on 2016-08-03
bison0:     RELAP-7 version:     beta-1.5-87-gc737274
bison0:       BISON version:     derived from v1.2, git commit 13831ab on 2016-08-03
bison0: 
bison0: 
*** Warning, This code is deprecated, and likely to be removed in future library versions!
getShortName() is deprecated.
/home/wangy2/trunk/falcon/github/ok/mammoth/moose/framework/src/actions/Action.C, line 61, compiled Aug  4 2016 at 00:14:12 ***
bison0: 
bison0: Running App: bison0
bison0: Diffusion coefficient option #3 selected for Sifgrs
bison0: Grain boundary sweeping capability in Sifgrs is activated
```

The subapp outputs is properly prefixed except the warning message. Also the non-prefixed warning destroys the coloring of the after outputs.
### Rationale for the enhancement or information for reproducing the error

Make the screen output prettier.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
No impact except human eyes.

**Comment by YaqiWang** [comment]
@permcody also this one.

**Comment by permcody** [comment]
So this is actually a really difficult problem to fix. The problem is that the `mooseWarning` and `mooseError` functions (technically macros) don't have any state associated with them. You can call them from anywhere and print out messages. Since we don't have any state or additional information  to use to know what a prefix should be. 

I can think of hacks that might work but I don't like any of them.

**Comment by YaqiWang** [comment]
Yes, it is using `Moose::err`. If it is using `_console`, prefixing will be easy. How about we create a global variable holding all `Console` objects? Then `mooseWarning` can use it.

**Comment by permcody** [comment]
The global console idea is error prone and actually not easily possible with the current console design. First of all, the consoles have several member variables to MooseApp and the OutputWarehouse. This is to support turning output on/off, controlling intervals, and other advanced buffering options. You can write to the console from anywhere and you can have arbitrary numbers of active consoles so there would be a lot of tricky bookkeeping to figure out which console is the "active" one at an arbitrary point in time. Finally, we always want errors and warnings to come out and consoles can be turned off.

If we really wanted to "fix" this I don't think the console route would be the way to go. Instead, we'd want to do something like maintain a global of the current application name that's executing. The warning and error macros could simply read that name and format the message as it send them out.

Tagging @aeslaughter

**Comment by friedmud** [comment]
Maintaining a global of the current application is simply not possible.  I
did it before when we had to swap the MPI Comm manually (before libMesh had
MPI Comm's attached to objects).  It was a nightmare... and trying to do it
for every single entry into a sub-app would be essentially impossible.

It's going to need to be something else.  Maybe we have two forms of
`MooseWarning`/`MooseError`... one that uses the `_console` (when possible)
and one that doesn't?

**Comment by permcody** [comment]
Hmm, I wonder if we could define a global "_console" that's just a reference to Moose::out. If we then use _console in the macro, it should be subject to normal scope lookup rules meaning it'd use the more local _console available almost everywhere but would still compile if used where _console was not available.

**Comment by friedmud** [comment]
That seems like it might work actually...

**Comment by aeslaughter** [comment]
I think @permcody is on the correct path. If we go with the global
"_console" it would also open up the possibility of "_debug_console" etc.,
which some people would like. This change would fit into the output system
update that I need to do to make it work with the new warehouses, but I am
not sure when I will get to this. It will probably be quite awhile.

**Comment by rwcarlsen** [comment]
Why not have a global variable that held a list of prefixes for each nesting level multi-app or otherwise.  Each level change location would be responsible for pushing/popping its prefix at the appropriate times.  And the actual console printing would consult this global for the prefix.  Then we would also be able to do level changes at things other than app boundaries too.

**Comment by aeslaughter** [comment]
Let me see if I can if I can clarify what I was saying about a global _console. I want a global object that would allow the app to set and unset prefix when it is run, which we have complete control over.

```
_global_thing.setPrefix(app.getPrefix);
app.doSomething();
_global_thing.clearPrefix();
```

**Comment by permcody** [comment]
@friedmud - I'm getting some pushback from most of the team on the approach taken in #8312. The scope lookup idea works pretty well with just a few exceptions. If it doesn't go in as-is, I do think that we could manage a global prefix without as much pain as you are making it out to be. We do have a well-defined tree order execution and setting up "indentation" is a normal problem for tree traversals.

Aside from the nasty static member function problem. #8312 doesn't format anything written to the standard error stream yet which is still a problem, but arguably less of a problem since errors crash your program anyway. 

I guess I'd still like to see this go in even if we do a prefix based solution later.

**Comment by permcody** [comment]
@YaqiWang - you are welcome to try the PR in #8312 and see if it helps you with real Multiapp runs.

**Comment by friedmud** [comment]
@permcody we _don't_ have a well defined tree execution order.  Just look at how many times `swapLibMeshComm()` is called here:

https://github.com/idaholab/moose/blob/devel/framework/src/transfers/MultiAppInterpolationTransfer.C

Those all represent moving from master->sub_app and back.

If you do this for printing we'll have to sprinkle it all over lots of transfers and certainly it will need to go all throughout each MultiApp

That said: I'm up for whatever.  My feelings aren't really strong about this.  I did it before with `swapLibMeshComm()` because I had to... if this just is the way then so be it.

Getting it to work 95% of the time shouldn't be too bad... but we'll always be missing corner cases where the printing will be off and we'll periodically screw it up here and there... but whatever... it's just printing... right?

:-)
