### ISSUE TITLE
Dump metadata relating to scalar, vector, double vector types

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7660]
### Description of the enhancement or error report

We need to dump additional information to make parsing of various types easier (no assumptions). Parameters that take a string type which is turned into a parsed function are tricky (i.e. they show up as an array but are really a "scalar" type), etc.
### Rationale for the enhancement or information for reproducing the error

NEAMS Workbench support
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment]
@brandonlangley - We are working to finishing up our Workbench tasks. I'm reading the text here and I recall the conversation but was there a specific issue that needed to be resolved here?

**Comment by brianmoose** [comment]
@lefebvrera or @brandonlangley Was there a specific issue that needs to be resolved here?

**Comment by brandonlangley** [comment]
@permcody @brianmoose @lefebvrera

The main things that I remember about this issue were the assumptions that I was making in the transformation from the dump information into the schema we use for validation.  For example, if I run:

`
./bison-opt --yaml | grep cpp_type | cut -d':' -f2- | sort | uniq -c | sort -n
`

I get:

```
   1  std::vector<MarkerName, std::allocator<MarkerName> >
   1  std::vector<MaterialName, std::allocator<MaterialName> >
   1  std::vector<MeshFileName, std::allocator<MeshFileName> >
   1  std::vector<MooseEnum, std::allocator<MooseEnum> >
   1  std::vector<short, std::allocator<short> >
   1  std::vector<std::vector<unsigned int, std::allocator<unsigned int> >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > >
   2  IndicatorName
   2  MarkerName
   2  libMesh::TensorValue<double>
   3  SubdomainName
   6  std::vector<FileName, std::allocator<FileName> >
   6  std::vector<int, std::allocator<int> >
   6  std::vector<unsigned short, std::allocator<unsigned short> >
   8  FileNameNoExtension
   9  std::vector<PostprocessorName, std::allocator<PostprocessorName> >
  10  VectorPostprocessorName
  11  MultiAppName
  13  MeshFileName
  13  short
  15  std::vector<UserObjectName, std::allocator<UserObjectName> >
  16  std::vector<NonlinearVariableName, std::allocator<NonlinearVariableName> >
  19  std::vector<VariableName, std::allocator<VariableName> >
  19  std::vector<libMesh::Point, std::allocator<libMesh::Point> >
  19  unsigned short
  26  std::vector<FunctionName, std::allocator<FunctionName> >
  37  std::vector<MaterialPropertyName, std::allocator<MaterialPropertyName> >
  41  FileName
  62  libMesh::Point
  67  std::vector<unsigned int, std::allocator<unsigned int> >
  75  BoundaryName
  88  int
  91  libMesh::VectorValue<double>
 124  PostprocessorName
 156  VariableName
 163  UserObjectName
 199  AuxVariableName
 208  MaterialPropertyName
 224  NonlinearVariableName
 306  std::vector<double, std::allocator<double> >
 344  FunctionName
 360  std::vector<AuxVariableName, std::allocator<AuxVariableName> >
 535  MooseEnum
 539  std::vector<OutputName, std::allocator<OutputName> >
 651  std::vector<BoundaryName, std::allocator<BoundaryName> >
 728  MultiMooseEnum
 824  std::vector<SubdomainName, std::allocator<SubdomainName> >
1129  std::vector<VariableName>
1420  unsigned int
1617  std::vector<std::string, std::allocator<std::string> >
1775  std::string
2674  double
4147  bool
```

I map these names to Integer, Real, String, Bool, or Arrays of all of these on our side.

The way I do these mappings is:

std::vector in the name OR MultiMooseEnum, libMesh::Point, VectorPostprocessorName, libMesh::TensorValue<double>, libMesh::VectorValue<double> --> **ARRAY** of values on our side

int, short, unsigned int, unsigned short -> **Integer** on our side
(unsigned specifies a minimum inclusive value of zero with validation on our side)

libMesh::TensorValue<double>, libMesh::VectorValue<double>, double --> **Real** on our side

std::string or ANYTHING ELSE --> **String** on our side
(bool is a String that must be either [ true false 1 0 ] on our side)

If any of the value types have std::vector in the name, then that is an array of whatever type is specified inside the < . . . >. We specify this in our validation schema by saying that any number of values can exist under that name.  If it is not an array of values, then at most one value can exist.

This is all fine, I have coded these assumptions into the logic that transforms the dump information into what we use.  @permcody mentioned that I should not have to make these assumptions, and instead that information should be provided.

However, in regards to this note above: 

> Parameters that take a string type which is turned into a parsed function are tricky (i.e. they show up as an array but are really a "scalar" type), etc.

This was in regards to the fact that we **parse** the input  **PRIOR** to any knowledge of the input definition or dump information. At the time of parsing, we have a simple rule that array values have single quote delimiters.  In a case like: 

`function = 'fission_rate * epf * (A*zirconium + B)'`

since we parse blind of any input definition or hierarchy rules up front (before validation - which is where the schema is used), we see the above as function being an array of 7 different values.  Then, on validation, the information about this function (from the YAML dump) is:

```
    - name: function
      required: Yes
      default: !!str 
      cpp_type: std::string
```

So, then since it says it **required** and is a std::string, the transformation into the schema we use for validation says that one and only one value must exist.  If it were one of the cases listed above where we would say it can be an Array of values, then any number of values could exist.

**Comment by dschwen** [comment]
> In a case like:
> `function = 'fission_rate * epf * (A*zirconium + B)'`

This will silently do the wrong thing by the way! It will only grab `fission_rate` and build a valid function out of it.

**Comment by brandonlangley** [comment]
If it did not have spaces in it, we would properly parse it as an array of single value (which would look the same in our DOM as a scalar) - so this would be okay.  However, we would get a validation error telling the user that **"fission_rate\*epf\*(A\*zirconium\+B)"** does not exist in the set of function names.

similar to what we already see in two other inputs with **"(sin(4\+x\*8\-y)\*cos(y\*10\+1.5\*x))\^2"** and **"300\*exp(\-t\*1.194e\-4)\+100"** not existing in the set of function names - where the set of function names that is being looked up into is the set of declarator names of subblocks under the "Functions" block.

This may be a different issue than this issue, however, and is described in more detail in case #7658.

**Comment by dschwen** [comment]
Well, you'll need to fix your validation...

**Comment by permcody** [comment]
@dschwen - Just for a little background, these Workbench tasks are basically to make sure that we provide the right metadata so that validation is possible. Right now we have to implement special rules in our various tools to handle the somewhat inconsistent data one receives in the YAML dump. For instance we have special case handling for things like the Executioner which we just shouldn't need.

This case of parsing the expression differently with and without spaces is indeed an issue on the Workbench side. Many of the others however are not.

**Comment by brianmoose** [comment]
So what kind of additional output do we want in the dump?
Do we want a `basic_type` that does what the validator rules above are doing?
This would at least keep them in a common place so all tools don't have to implement the same logic.
The main problem I see with that is apps having new types that MOOSE doesn't know about.

**Comment by dschwen** [comment]
Yeah, I got that. It is just that the validation of the function name needs dynamic validation. You could use the libmesh `fparser_parse-opt` executable for that (might need some modifications).

**Comment by brianmoose** [comment]
I put in a `basic_type` for the parameters in the Json output.
It seems there might still be an issue on the workbench side.
@permcody Does anything else need to be done for this issue?

**Comment by permcody** [comment]
Well this was my interpretation of what we needed. @brandonlangley - we may need some feedback from you on whether these changes Brian is making is helpful. Brian, alternatively as we make these changes we should eventually be able to clean up the assumptions we have to make in Peacock and the Atom.io plugin. That's _my_ measure of success.

**Comment by brandonlangley** [comment]
@brianmoose @permcody -

Thank you for putting in the basic_type.  After very briefly looking at the change set, I have one quick question. I see that the basic_types seem to be "Array" "String" "Integer" "Real" and "Boolean".

If it is an "Array" however, how do I know the basic type of what is in the array?  Array of Integers, Reals, Strings, etc. If it is an Array, do I then need to go back and look the old cpp_type and strip off the "std::vector< >" and do the logic above to figure out the type that was supposed to be in the array? There isn't a notion of ArrayString, ArrayInteger, ArrayReal, or ArrayBoolean is there?

**Comment by brianmoose** [comment]
There isn't currently any "Array of" in there but I will add them so that you don't have to do the additional logic.

**Comment by permcody** [comment]
Thanks Brian

**Comment by brianmoose** [comment]
This seems to done, if not, another issue with specific problems can be opened
