### ISSUE TITLE
Postprocessor::getValue() should be const

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7770]
### Description of the enhancement or error report

We have a non-const method `UserObject::finalize()` that's there for doing final aggregation. The method that retrieves the value really should be `const`.
### Rationale for the enhancement or information for reproducing the error

No errors, just another place to fix up some const-correctness.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Everything! Fixing this isn't exactly low difficulty because it's spread throughout the framework, modules and applications. Good luck.

**Comment by joshuahansel** [comment]
The original transition plan was as follows:

1. Add const `getValue()` and call it in MOOSE instead of the non-const one. Add default implementation of the const version that calls the non-const version (via `const_cast`) and emits a deprecation warning. Fix the deprecations in MOOSE.
2. Fix the deprecations in all of the apps.
3. Remove the non-const version from the base class.

However, it was found that there was a flaw in this plan, where intermediate base classes have implemented the const version in step 1. See https://moosedevelopers.slack.com/archives/C01054VRUEM/p1690121650273399 for more information. Therefore, the new proposed plan is:

1. Add const `getValue()` but don't call it yet. Do not make it pure virtual; just give it a dummy implementation that emits an error. Implement the const version for post-processors in MOOSE.
2. Call the const version in MOOSE instead of the non-const one. Add default implementation of the const version that calls the non-const version (via `const_cast`) and emits a deprecation warning. Doing this as a second step allows apps encountering the aforementioned intermediate base class issue to be fixed *during* this change, rather than "break" those apps.
3. Fix the deprecations in all of the apps.
4. Remove the non-const version from the base class.
