### ISSUE TITLE
Order matters in input file for UserObjects

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#7879]
### Description of the enhancement or error report

I was looking at `modules/phase_field/tests/reconstruction/1phase_evolution.i`
In the `UserObjects` block, if `ebsd` is defined after `tracker` (which references `ebsd`) then running gives the error `Unable to find user object with name 'ebsd'`
Andrew seemed to think this was a bug.

**Comment by dschwen** [comment]
Yeah, that'd be a bug.

**Comment by permcody** [comment]
Damn. We need a ticket for that. In general, all bindings need to be lazy
so that input file order doesn't matter.

**Comment by brianmoose** [comment]
This could be duplicate of #6254

**Comment by brianmoose** [comment]
This also seems to happen with `Functions`.
Reordering `ff_1` or `ff_2` in `test/tests/bcs/function_dirichlet_bc/function_dirichlet_bc_test.i` to after `forcing_func` causes the same issue.

**Comment by jessecarterMOOSE** [comment]
Yeah, I reported what led to #6254 a while back. I'm hazy now on the specifics, but it appeared that order didn't matter among a _specific_ user object type (Elemental, Nodal, General), but since they are constructed or initialized in a certain order (e.g. Elemental before General), I couldn't put a General before Elemental in the input file, unless I used a pointer instead of a reference and initialized it outside the constructor. That pretty much forced me to use pointers since I have elemental UO's that depend on general UO's and vice-versa so I couldn't find an order that worked. That might also hold in this case for UO's depending on PP's? I'm not familiar with the grain tracking stuff...

**Comment by permcody** [comment]
That sounds right. This might be tricky to fix up the UserObjectInterface because of the templated call. One of us will just have to dig in and figure it out.

**Comment by YaqiWang** [comment]
Thumbs up to @lindsayad !

**Comment by lindsayad** [comment]
I don't know why I closed this. This fixes evaluation ordering but doesn't fix issues with respect to use of `getUserObject` in a user object constructor, e.g. there are still construction order issues

**Comment by loganharbour** [comment]
> But then the question is whether we can perform dependency resolution at the parser stage? Is that a path we want to go down? I believe I saw @loganharbour talking about this in slack

We can. I don't think this would be a difficult task.

Is the name of the UO that you depend on known via input parameters?

**Comment by YaqiWang** [comment]
>Is the name of the UO that you depend on known via input parameters?

Probably. Even not, we can add a function that validParams can call to insert dependency.

**Comment by loganharbour** [comment]
> > Is the name of the UO that you depend on known via input parameters?
> 
> Probably. Even not, we can add a function that validParams can call to insert dependency.

How? I don't understand how you plan on doing this with something that is stateless.

**Comment by YaqiWang** [comment]
The simplest solution is to let user add a parameter `depends_on` or call a function like `dependingUOs()` which accepts the parameter name containing depending uo names.

**Comment by brianmoose** [comment]
Finally closed! I have been waiting for almost 10 years! :smile:
