### ISSUE TITLE
[Proposal] consolidate valid params declaration and object registration

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#8001]
Adding a new class to moose involves several things:

```c++
// in the new class header file:
class Foo; // A
template<> // B
InputParameters validParams<Foo>(); // C

// in the new class impl file:
template<> // D
InputParameters validParams<Foo>() // E
{
  InputParameters params = validParams<[Foo superclass or MooseObject]>(); // F
  params.addRequiredParam<Real>("bar", "bar doc string"); // G
  return params; // H
}

// in Moose.C or similar
registerObject(Foo); // K
```

* Items A, B, C can be generated from the class name (``Foo``) - eliminating the long declaration and redundant typing of ``Foo``.
* D and H are basically identical for every class and E and F can be generated from class name and parameters parent name(e.g. superclass).
* K can be accomplished at the ``Foo`` impl site - with a few mods to the ``Factory`` class.

The biggest benefit of this change would be the elimination of a separate registration step that is often forgotten or typo'd.  It would also make name-changes localized to the class of interest.  I have sketched out an implementation that uses macros :-/  - But we are already using macros for registration anyway.  The user-facing changes would be entirely optional, but would look something like this:

```diff
diff --git a/framework/src/base/Moose.C b/framework/src/base/Moose.C
index 4f09420..4ab3b93 100644
--- a/framework/src/base/Moose.C
+++ b/framework/src/base/Moose.C
@@ -733,7 +733,6 @@ registerObjects(Factory & factory)
   registerMultiApp(AutoPositionsMultiApp);

   // time steppers
-  registerTimeStepper(ConstantDT);
   registerTimeStepper(FunctionDT);
   registerTimeStepper(TimeSequenceStepper);
   registerTimeStepper(ExodusTimeSequenceStepper);
diff --git a/framework/include/timesteppers/ConstantDT.h b/framework/include/timesteppers/ConstantDT.h
index 84b6417..4f24321 100644
--- a/framework/include/timesteppers/ConstantDT.h
+++ b/framework/include/timesteppers/ConstantDT.h
@@ -17,10 +17,7 @@

 #include "TimeStepper.h"

-class ConstantDT;
-
-template<>
-InputParameters validParams<ConstantDT>();
+validParamsHeader(ConstantDT);

 class ConstantDT : public TimeStepper
 {
diff --git a/framework/src/timesteppers/ConstantDT.C b/framework/src/timesteppers/ConstantDT.C
index 649fcc5..4b7ca74 100644
--- a/framework/src/timesteppers/ConstantDT.C
+++ b/framework/src/timesteppers/ConstantDT.C
@@ -16,15 +16,12 @@
 #include "Stepper.h"
 #include "Transient.h"

-template<>
-InputParameters validParams<ConstantDT>()
+validParamsImpl(ConstantDT, TimeStepper, params)
 {
-  InputParameters params = validParams<TimeStepper>();
   params.addRequiredParam<Real>("dt", "Size of the time step");
   params.addRangeCheckedParam<Real>("growth_factor", 2, "growth_factor>=1",
     "Maximum ratio of new to previous timestep sizes following a step that required the time"
     " step to be cut due to a failed solve.");
-  return params;
 }
```

Thoughts?

**Comment by andrsd** [comment]
How did you `#define validParamsImpl`?

**Comment by rwcarlsen** [comment]
```c++
/// T is the class name
#define validParamsHeader(T) class T; template<> InputParameters validParams<T>()

/// T is the class name, P is the (parent) class name to build parameters off of,
/// N is the name of the parameters object that will be in-scope for the validParams 
/// function (arbitrary, user-decidable)
#define validParamsImpl(T,P,N) \
  static bool throwawayvar_##T = Factory::regGlobal<T>(#T); \
  void validParamsInner_##T(InputParameters& N); \
  template<> \
  InputParameters validParams<T>() { \
    InputParameters params = validParams<P>(); \
    validParamsInner_##T(params); \
    return params; \
  } \
  void validParamsInner_##T(InputParameters& N)
```

**Comment by friedmud** [comment]
In general we try to avoid using macros.  It makes things harder for debugging... and makes things less clear for engineers/scientists.

I've worked on heavily macro'd frameworks before and they just become a mess.

Instead: we try to define sensible C++ that is understandable... but still simple enough that it doesn't get in the way.  Our current stuff does that.

So: I'm against this change on the basic principle that it injects macros where there is no need.  It is rare that our users struggle with any part of what you're proposing to "fix" here.

As for the actual proposal... it will not work in several cases:

1.  There are times when you _don't_ inherit the parameters from your parent.
2.  There are times when you have multiple parents and you need to combine their parameters.
3.  Hiding `params` construction creates weird C++.  Users have to use that variable without seeing the definition (whereas right now the code is completely clear and understandable... it even "reads" well outside).

As for global registration: I'm against that idea in general... but I could be convinced.  To me: it's a separate issue from the macro.  We can decide to do global object registration regardless of using a macro or not.

The reason why I'm against it is because we have two different models of Application composition in MOOSE:

1.  You can use a MultiApps... and run the other app as a sub-application.  In that case the factories are _separate_.  Each Application maintains its own Factory (for objects and syntax)... and operates completely independent of each other.

  This is required for a couple of reasons: but the big one is simply reproducibility.  An application is not supposed to "know" that it's operating inside of a MultiApp... it should perceive an environment that is just exactly the same as if you were running the app by itself.  This is a key point of the MultiApp system.

  With a global factory you would be cross-registering objects from different Applications together... which would break that principle.

2.  You can can pull in the objects from another Application into this Application.  That would obviously work ok with a global factory.

So... (1) precludes the idea of a global factory... but there are ways to mitigate it... and I'm open to the idea... as long as we can work our way through (1)...

**Comment by rwcarlsen** [comment]
@friedmud

The macros are indeed separate issue from the global registration.  Regarding multi-apps - couldn't you just ``parameters.get<MooseApp *>("_moose_app")->getFactory().reg<[Foo]>;``?  Then there is no need for a global factory at all.  This would be a better approach than the global factory I had initially thought of.

Just because the macros exist doesn't mean they have to be used.  Anybody could write their validParams functions manually just like they do now.  And I'm generally not much of a fan of macros, but sometimes, code-gen helps users.  It is a spectrum - not a black/white issue.

**Comment by dschwen** [comment]
Anything boilerplate in the class' .h and .C files is hard to forget if you
use our atom snippets :-)

**Comment by rwcarlsen** [comment]
- nevermind on my getFactory suggestion - that obviously won't work because validParams isn't every called until *after* a class is registered with the factory.

**Comment by rwcarlsen** [comment]
You could have the global factory registration list be qualified by application name. And then the app-local factories could fetch relevant registrations from the global list.  But I don't think this sort of thing would be worth it without macros - it would just make more work for users not less.

**Comment by rwcarlsen** [comment]
ping - how is support for this - keep or close?

**Comment by friedmud** [comment]
I'm still negative on this.  It's a level of indirection that doesn't add much.  Also: I don't think it's worth changing every file in all of MOOSE...

**Comment by permcody** [comment]
I'm not for this change at this time. Large scale refactoring may be
considered later date. Thanks for the suggestion though.
