### ISSUE TITLE
Enhance convergence rate of NonlinearEigen executioner

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#8029]
I believe this could be done by including the non-local Jacobian contributions of the postprocessor. @YaqiWang have you ever thought about doing this? Do you think there would be any utility here?

**Comment by permcody** [comment]
I'm not sure what to do with this ticket, is this a discussion? Capability request? We have the non-local UserObjects so this should basically already work.

**Comment by lindsayad** [comment]
This would require modifying some of the Jacobian code in `EigenKernel`. I suppose it's mostly a discussion...I'm looking for some input from folks who have a lot more neutronics experience than me on whether they think adding those non-local contributions would aid solution of eigenvalue-type problems or whether time should be focused elsewhere. Maybe it's a more appropriate discussion for the list-serve.

**Comment by permcody** [comment]
Only a few people are crazy enough to watch the repository because of the
amount of activity that goes on there. Only a few people will look at that
ticket.

**Comment by lindsayad** [comment]
Fair enough. I can close this then, and then open it again if I get some feedback saying this might be helpful.

**Comment by YaqiWang** [comment]
Yes I thought about it, see this link: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/mjn5UvCt3OA/xGy7LWsbBgAJ. Then I figured the convergence issue is not caused by that and did not go further. IMO, moose framework needs to provide some help on evaluating the non-local jacobian. Otherwise the implementation could be very hacky and fragile.
