### ISSUE TITLE
CSV file reader

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#8151]
### Description of the enhancement or error report
I need to read a table of CSV formatted data from a file for a model I'm developing, and I don't think there's anything in MOOSE to do this.  If there is, please let me know.

### Rationale for the enhancement or information for reproducing the error
This seems like something that would be used enough by various codes that a common capability to do this should be in MOOSE.

### Identified impact
Add a class, probably in utils, to read CSV files.

**Comment by permcody** [comment]
As far as I know, there's not. Rather than write our own, we should probably just use an external library. There's a utility in BOOST. Here's one I just found on Github (header only!):
https://github.com/ben-strasser/fast-cpp-csv-parser 

As a bonus, it would be awesome to make a MOOSE wrapper around this utility that does the correct thing in parallel (i.e. read on rank 0 and MPI broadcast or scatter the vectors).

**Comment by permcody** [comment]
@idaholab/moose-team - any other suggestions?

**Comment by jwpeterson** [comment]
If the license on the one that @permcody mentioned is consistent with MOOSE's, we should definitely use something that's already out there rather than trying to write our own... assuming it's high quality.

**Comment by aeslaughter** [comment]
A CSV reader would be a nice utility to have, I don't really care much what we use.

**Comment by aeslaughter** [comment]
This might be an option: http://www.vtk.org/doc/nightly/html/classvtkDelimitedTextReader.html

**Comment by friedmud** [comment]
I'd rather not add VTK linkage baggage for something like reading a CSV
file...
