### ISSUE TITLE
Optionally run MeshModifier after uniform refine

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#8337]
### Description
I need to add subdomains to an existing mesh based on an image, but I want to do a uniform refine first so that the image is resolved nicely. But, I still want to be able to coarsen back out so I cannot just use a fine mesh.

### Rationale
This is need for Mastodon to allow the surface of a soil profile to be ignored.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Not sure, probably something will break.

**Comment by friedmud** [comment]
My suggestion: add a "UniformRefinementMeshModifier"... it takes in a mesh and uniformly refines it a set number of times.

The reason why you would do this is because then you can use the normal `depends_on` capability of MeshModifiers to control the execution order of them.

**Comment by friedmud** [comment]
To be clear: you _wouldn't_ use `Mesh/uniform_refine`... you would use the new MeshModifier instead.

**Comment by aeslaughter** [comment]
That is a good idea, I can even just build it into the MeshModifier I am creating.

**Comment by friedmud** [comment]
I think I would like to have it as a separate MeshModifier so that anyone can use it (and slot it in-between other MeshModifiers).  I would certainly make use of it.

But: If it's going to be a REALLY normal thing to use with your new MeshModifier (like you're ALWAYS going to need to do them together) then you might as well build in that capability.  It won't hurt anything :-)
