### ISSUE TITLE
Create MOOSE executable method for parsing input files.

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#8365]
### Description
It would be advantageous to have a single method for parsing input files (i.e., remove the python parser). There should be a command for moose `--parse-input` that dumps the input file to a JSON data structure that can easily be read.

### Rationale
Currently, the support syntax between the python parser and application parser are not the same. Rather than try to support two parsers, just use the parser in MOOSE.

### Impact
This will affect Peacock and MooseDocs, but in a good way.

**Comment by permcody** [comment]
You guys aren't planning to go build a parser are you? I think the current plan is to get the parser from the Oakridge guys.

**Comment by friedmud** [comment]
We need to maintain our own Python capability for reading input files.  It
serves a TON of utility.

For one thing: it means that we can read input files without needing to
have a run-able binary hanging around.  There are a number of circumstances
where we may not have access to an executable but want to read an input
file (like, if we're running on a workstation but our binary is on a
cluster, etc.).

**Comment by aeslaughter** [comment]
We can leave ParseGetPot for you to use, we need something more complete for what we are doing.

**Comment by aeslaughter** [comment]
@permcody We are not going to write one, we just want to use the same parser that MOOSE uses.

**Comment by friedmud** [comment]
I do think you're going to have more trouble getting GetPot (that MOOSE
uses) to read the input file in a way that can generate JSON... it's
doable, but it's going to take quite a bit of work.

That said: I'm not against that particular idea.  I still fantasize
sometimes about actually switching the MOOSE syntax over to JSON!  It would
simplify so many things.  This could be a good first step: the ability to
translate old input files into JSON!

**Comment by aeslaughter** [comment]
We shouldn't replace GetPot, writing JSON is not as clean as writing GetPot, in my opinion. I would be alright with supporting both.

**Comment by permcody** [comment]
@friedmud - we don't plan on doing any of this work. The Oakridge guys working on the NEAMS Workbench tasks have created a really good parser (far superior to either our Python parser or the GetPot parser). It uses flex/bison so it verifies the grammar, has semantic verification, and can provide useful error messages in malformed files. Since it's grammar based it should be adaptable to handle any syntax we want so talking about YAML vs JSON is not really relevant here.

If at all possible, I hope that we can make use of that parser without adding extra dependencies and I've conveyed that message to the Oakridge team on several occasions. I believe we should be getting access to that parser very soon and we can look at whether or not we can make use of it in the way that we require. *fingers crossed*

For the time being, lets let this ticket just sit until we have a chance to look at their work.

**Comment by aeslaughter** [comment]
The following should have syntax update to [Modules/tensor_mechanics/Master] when this issue is done:

- modules/tensor_mechanics/tests/finite_strain_elastic/elastic_rotation_test.i

**Comment by permcody** [comment]
We will drop the Getpot parser (not the syntax) hopefully sooner then
later. Ideally we will have a true LALR1 parser which will make it easier
to support several different syntaxes and make the parser much easier to
understand and maintain.

**Comment by brianmoose** [comment]
We still use the python GetPot parser just to parse the `tests` files used by the test harness. It would probably be a bad idea to make the test harness depend on an executable being built.
