### ISSUE TITLE
Method to calculate grain boundary area

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8448]
### Description of the enhancement or error report
Add a postprocessor that computes the total grain boundary area in a sample.

### Rationale for the enhancement or information for reproducing the error
Grain boundary area in a polycrystalline simulation is an important quantity. Observing its change over time will be useful.

### Identified impact
Added capability

**Comment by mangerij** [comment]
Really cool, does this only work in GrainTracker or could it work for block
restricted grains?

What about in 3D? I'm currently trying to do just that for hundreds of
grains but all I have so far is to calculate the volumes, assume the grain
is a sphere and extract the radius.

On Feb 1, 2017 5:41 PM, "Daniel Schwen" <notifications@github.com> wrote:

Description of the enhancement or error report

Add a postprocessor that computes the total grain boundary area in a sample.
Rationale for the enhancement or information for reproducing the error

Grain boundary area in a polycrystalline simulation is an important
quantity. Observing its change over time will be useful.
Identified impact

Added capability

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/idaholab/moose/issues/8448>, or mute the thread

**Comment by dschwen** [comment]
Working on it now. Should be dimension agnostic.

**Comment by permcody** [comment]
@mangerij, it should hopefully be complementary to this (if you weren't already aware that this VPP existed): https://github.com/idaholab/moose/blob/devel/modules/phase_field/src/vectorpostprocessors/FeatureVolumeVectorPostprocessor.C

Generally there's a way to do these things.

**Comment by dschwen** [comment]
Yeah, it's complementary. Volume != Surface area
