### ISSUE TITLE
Enable MOOSE to partially solve a problem 

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#8780]
### Description of the enhancement or error report
Suppose a problem has two primal variables u and v. We can ask FEProblem to solve u with a fixed v. Of course we can solve v with a fixed u. It's noted that both u and v are in the same FEProblem, so v can be coupled in kernels of u and vise versa. I suggest to create a function FEProblem::solve (std::vector<NonlinearVariableName>). PJFNK is still desired for those partial solves.

### Rationale for the enhancement or information for reproducing the error
This of cause can be implemented with MultiApp/Transfer, but it owns advantages MultiApp cannot provide:
1. No data transfer and extra storage for the transferred data;
2. No need to duplicate mesh;
3. Materials can be shared by both variables;
4. Enable much cleaner code if complicated iterative scheme is required.

This will clean up implementations of an acceleration scheme in Rattlesnake dramatically and pave a way of more advanced schemes which has been proved effective.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

New feature which will make Rattlesnake transport calculations more memory and CPU time efficiently and a much better user interface (no need to create two input files with multiapps).

**Comment by YaqiWang** [comment]
If needed I can create few slides and discuss with framework developers.

**Comment by andrsd** [comment]
This looks like you want to use `restrict_solve_to` from libmesh interface...

**Comment by permcody** [comment]
We can revisit this, but I think we need to look elsewhere first. We still need to get the DistributedMesh stuff working which will likely save more memory than this will. Also, I can revisit deleting MultiApps after they have completed. 

I seem to recall that there are restrictions at the libMesh level that require a Mesh for each EquationSystem. @roystgnr can you confirm this? If that's the case, then this request is kind of dead in the water to begin with. Also, we'll end up making this system do all the same things as the multiapp system does already.

To be clear, yes I understand the need for what you are requesting. However, we can likely meet your requirements with a different design.

**Comment by YaqiWang** [comment]
I found `PetscLinearSolver<T>::restrict_solve_to()` with the keyword provided by @andrsd. Not sure how well it interacts with PETSc, but I am glad people have done something. Comparing with the multi-mesh issue, this has minimum impact on the framework. We still have only one EquationSystem.

**Comment by fdkong** [comment]
> I found PetscLinearSolver<T>::restrict_solve_to() with the keyword provided by @andrsd. Not sure how well it interacts with PETSc, but I am glad people have done something. Comparing with the multi-mesh issue, this has minimum impact on the framework. We still have only one EquationSystem.

I do not think ` PetscLinearSolver<T>::restrict_solve_to() ` is what you want. You are actually having a problem like this:

`F(u, v) = 0`

(1) Solve for `u` with a given `v`

(2) Solve for `v` with the computed `u` from (1)

(3)  Solve for `u` again with the computed `v` from (2)

(4) ...


 It looks like a field-split based `nonlinear` solver. If so, I would suggest to add  a new algorithm in PETSc to achieve this goal.  I am trying to avoid implementing any solver in moose because it is hard to maintain. 

Could you tell us why you want to solve your problem in this way?

**Comment by roystgnr** [comment]
@permcody - yes, each EquationSystems object currently needs its own Mesh.  The intent was that if you had multiple problems which were independent except for their mesh, those would be in different System (or groups of System) objects within a single EquationSystems.

**Comment by roystgnr** [comment]
@fdkong - would you need a new algorithm in PETSc for that?  It sounds like block Gauss-Seidel over the field split with a Krylov solver as the inner preconditioner on each block, which you should be able to do from the command line.

**Comment by fdkong** [comment]
@roystgnr. PETSc does have a nonlinear GS, but it is used as a smoother for FAS. It simply does a few sweeps over variables.  It may not be what @YaqiWang wants. Or you are talking a solver in libMesh?

**Comment by roystgnr** [comment]
@fdkong, no, no, I misunderstood; for some reason I was picturing linear subproblems.

**Comment by friedmud** [comment]
I'm against this idea for now.  We don't need another way to do "Picard"...
we just need to make our current stuff work better for you.

**Comment by YaqiWang** [comment]
You did not read my post carefully. We have no way to make MultiApp/Transfer work ideally for me.

**Comment by friedmud** [comment]
I did read it - I just don't think the added complexity to the framework is
worth it when MultiApps work for this case.

**Comment by WilkAndy** [comment]
I can see this feature being useful for me too, but as an "exploratory" feature that wouldn't really be used in "production" simulations.  That is, it'd be me alone using this feature to explore different solving schemes, but I'd hope to provide something more robust to real users so they'd never have to use about this feature.

**Comment by friedmud** [comment]
It has been a few years since we've discussed this - but it's come up again.  I wanted to give a bit of a historical perspective on this and put this idea into a present-day context as well.

Firstly, it should be noted that MOOSE was originally designed to allow this.  Indeed, we had this capability for _many_ years... and only took it out "recently (6-7 years ago?).  This was actually part of @andrsd 's original redesign of the internals of MOOSE - and a lot of the driving reason behind the whole `System` class hierarchy.  You were supposed to be able to have Kernels assigned to multiple `System` objects and each system would have its own variables and could couple to the other system's variables.

This idea was tough to keep alive (it added a ton of code complexity)... and was never really used by anyone.  Once `MultiApps` came out - it was obviously useful in many more contexts than the multiple-system idea (and could, with an efficiency loss for storage) be used to do all the same things that the multiple-system solves could do.  Due to all of this we decided to remove the multiple-system capability from MOOSE (I believe the test object for it was something like `TwoSystem` or something, maybe @andrsd or @permcody could chime in...).

Reasons why `MultiApps` are better:
 - Can use different meshes
 - Can use different kinds of transfers (such as for multiscale)
 - Have a reasonable way to set execution ordering (execute_on)
 - Can control cycling from the input file (picard and sub_cycling)
 - Input files are self-contained, can be tested by themselves and then plugged together
 - Can instantiate any number of sub-apps (thousands)
 - Sub-apps can solve on different communicators
 - Sub-apps can solve simultaneously
 - Can create and destroy sub-apps during solve
 - Each sub-app can output independently

All of these things make `MultiApps` indispensable... no amount of multiple systems could ever replace `MultiApps`... but `MultiApps` can do what multiple systems can do (with some overhead, and, admittedly, sometimes awkwardness).

Making `MultiApps` work well has taken many years.  If we were to have two ways of doing the same thing, then it would have taken even longer.

My suggestion going forward: Let's build on what we've done with MultiApps... but make it better... and make it work more smoothly for use-cases like what @YaqiWang wants.

A list of ideas:
- "Mesh sharing"... for sub-apps which utilize the same mesh as the master... we should be able to use the same Mesh object... reducing memory overhead.
- EquationSystems sharing... can we make Sub-apps actually instantiate their `Systems` inside the EquationSystems of the master?  This would get us really close to what @YaqiWang wants.
- Automatic Transfers - The `CopyTransfer` is pretty optimal... can we make it automatic in the case where you're using the same mesh and referencing a variable in a sub-app?  This would effectively hide the multiapp complexity.

Any other ideas?

**Comment by YaqiWang** [comment]
@friedmud My motivation of proposing this is the drawbacks we saw of using MultiApp. This multi-system was proposed for accelerating our transport calculations with the high-order (HO) low-order (LO) approach. The high-order (discrete ordinates transport) and the low-order (diffusion approximation) share the same mesh because we want to the multiphysics calculations and other physics are coupled on the low-order system with the same spatial resolution. The high-order system provides some closures to the low-order system (either a source or velocity in a convection term) so that the low-order system can produce the same accuracy of doing the stand-alone high-order calculations. The HO and LO also share the same materials. The number of degrees of freedom of HO could be as high as a thousand times of the one of LO. The idea is to push as much as iterative evaluations in LO so that the calculation can be accelerated. To the users, they want the input exactly like the stand-alone transport input with only one parameter to turn HO-LO calculation on.

We have implemented the multiapp way. Actually it is application wrapper, which happens even before we introduce multiapp in MOOSE in 2013. We did have automatic transfers. I added `clone_master_mesh` capability so that the main and subapp can have the exact same partitioning to facilitate the transfer. We even thought of having a dedicated parser that can parse the single user input and generate internally the two inputs for the really calculation.

The multiapp way actually works pretty well. We do have some overheads, memory wise and initial setup wise. But they can be managed less than total about 10 percent. Although I hate these overheads, we tolerated them for years. Only recently we see gradually increased applications of discrete ordinates transport schemes for small reactors that push us to rethink a better design. I understand multi-system has some overlaps with multapp but it by not means is created to replace multapps. When I propose this, I was specifically keeping the same mesh shared by multiple systems in mind. The work in this issue should be minimized. Another application of this could be specific preconditioners requires geometric information. We should be able to attach UOs, materials on `FEProblem`, and aux variables on aux system easily to a particular system and do the solve on that system. The other system might need to be treated an aux system to the system. I have not thought of all the implications but think this could be doable without years of efforts that you are worrying.

The drawbacks of using multiapps for our HO-LO approach are:
1. requires two input files which share the same mesh, materials;
2. hard to manage the transient;
3. difficult for users to set up multiphysics calculations that requires users to manually transfer variables like temperature, displacements, density, etc;
4. difficult to introduce multi-level approach (HO-LO is a two-level approach);
5. overheads are just ugly and difficult to remove and make maintaining the codes difficult.

The extendibility and user friendliness of the multapp approach in my opinion is the killer. We have to make the design as strait-forward as possible in long term. Once the new system is ready, moving our application to the new system should not be difficult.

**Comment by friedmud** [comment]
Everything you're talking about is simply usability.  We just need to make using MultiApps more convenient for your use-cases:

1.  It doesn't.  There is nothing preventing us from programmatically creating the inputs for the MultiApp system without a separate input file.
2.  I don't understand this - this is actually one of the strengths of MultiApps (that their execution can be precisely controlled)
3.  Completely disagree and history shows that it's not hard.  MANY people are using MultiApps and Transfers.  In the case where everything is the same a CopyTransfer is trivial.  If the mesh/domain are not the same then you must use MultiApps anyway.
4.  Why?  Logan is doing it with MultiApp without issue.  This is just restating your opinion.
5.  I gave several examples above of ways we could enhance the MultiApp system to remove some of the overhead.

My previous post was trying to bridge the gap.  I was brainstorming about ways we could enhance the MultiApp system to help you out.  If all you're going to do is argue for your design then we're done and I'll just close this ticket.

The MultiApp system is here to stay.  It's used in too many ways and provides us too much power.  We shouldn't invent another way of doing MultiApps alongside it.  The most I will entertain are modifications to it for use-cases it's not optimal for at the moment.

**Comment by andrsd** [comment]
I agree with @friedmud here. It seems that most of the issues are just syntax-related. Nobody says you have to use the `[MultiApp]` block. We can easily deliver an action syntax that will setup the problem the way you need it with all the transfers, etc. But, under the hood, it can be multi-app system with maybe some changes that @friedmud outlined above.

For example, if we ever get to doing true explicit solve in THM, we will be splitting the flow solve with the heat structure solve and it will use multi-apps, but users won't even notice that...

**Comment by YaqiWang** [comment]
I should have made this clearer. It is not about only user interface but also about the extendibility, maintainability, and efficiency. I can conveniently not argue with you but might regret a few years later for not doing so due to lose of competition or funding. I do not want to be the only one providing opinions. Like @snschune, @vincentlaboure, @zachmprince in Griffin team can also provide independent reviews.

**Comment by fdkong** [comment]
OK, I possibly should not jump here. From my understanding of NDA and DSA, both the multisystem scheme and the multi-app system have disadvantages and problems. The multisystem scheme may be hard to maintain. If we implemented that, the moose framework might have lots of things like `if (extra_system) do bla bla`.  If we were going to do this using the multi-app system, we need to do hacking things to `merge` two apps together as if there was only one app.

If I am the guy who is going to do research on these fancy acceleration schemes, I would properly leverage the `PBP` technique to handle nonlinear problems.  PBP is a linear preconditioner right now. But we could create a nonlinear version of that system. Let us call it ` nonlinear acceleration`.  That is,  for every nonlinear solve, we will automatically involve one `nonlinear acceleration.` It may even allow us to do more tight coupling, that is, we could even involve `nonlinear acceleration` during every single nonlinear iteration. It might have a better convergence than `Picard`.  The advantage of this scheme is that  `nonlinear acceleration` does not bother anyone who does not care about these algorithms since it is a pluggable system (and also optional system). We do not inject COVID-19 into the moose framework either (that is, we do not touch `FEProblem` and `NonlinearSystem` much). So we are safe.

**Comment by YaqiWang** [comment]
The question is that is it possible to algebraically construct the low-order Jacobian for DSA. It might be possible. If so we can have a special preconditioner without multi-system or multi-app. For NDA, low-order system is typically the main system. This  function could be like
```
void
FEProblemBase::reinitElem(const Elem * elem, THREAD_ID tid)
{
  for (auto & sys : _all_systems)
    sys->reinitElem(elem, tid);

  if (_displaced_problem && _reinit_displaced_elem)
    _displaced_problem->reinitElem(_displaced_mesh->elemPtr(elem->id()), tid);
}
```
