### ISSUE TITLE
Peacock window cannot be made smaller

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8826]
### Description of the enhancement or error report

This is a problem on many projectors.

### Rationale for the enhancement or information for reproducing the error

Plug in a VGA connector and scream

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Peacock usability

@aeslaughter, @brianmoose, thoughts?

**Comment by brianmoose** [comment]
This is mostly likely due to setting a fixed size for some widgets in the ExodusViewer and/or Postprocessor viewers. We have had trouble with sizing with some of those widgets in the past.
How would you like all the widgets on the Exodusviewer to behave when the window gets small? Have a scroll bar appear and scroll through them? Try to make them collapsible? Move to "dockable" widgets that can move, float, close, etc?

**Comment by permcody** [comment]
No, let's just figure out some minimum supported size and make it fit. It's probably pretty close now. When I was running it in class today it was cut off on the bottom by just a little bit. Scroll bars in the interface pretty much suck. You can probably adjust your resolution on your screen to see what it looks like at different resolutions.

**Comment by brianmoose** [comment]
The lowest resolution on my workstation is 1024x640. All the left hand widgets on the ExodusViewer were completely unusable since they were all squished together. 1600x1000 was close but the variables widget was still squished. It wasn't until 2048x1280 that everything looked fine again.

Personally, I wouldn't mind scroll bars on lower resolutions. At least you can still use the widgets, which is not the case now. I do also think that having collapsible widgets might be decent. How often are you messing with the "Background and Labels" widget? Clipping? Contours? Yes there are times when you need to use them but maybe they don't need to be viewable all the time.

**Comment by permcody** [comment]
I'm just saying that for training it's nice to have a clean interface. The
old peacock looks great even on crappy projectors. We did a lot of the
training with old peacock just because it looks so good. We'll take a
closer look at what we want to do once Andrew and John get back as well.

**Comment by aeslaughter** [comment]
I can remove some of the plugins features that are necessary to give it
more room.
