### ISSUE TITLE
"Guarantees" - MaterialProperty meta data

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8881]
### Description of the enhancement or error report

I would be nice if MOOSE provided a way to decorate material properties with a specific type of meta data: guarantees that the material property satisfies. Guarantees could be given during material construction. And they could be enforced hard when getting the property (with MOOSE erroring out if not all materials that are supplying the property on the relevant subdomains make a required guarantee), or they could be queries softly and used to inform a cod path choice.

**Example:** A `RankFourTensor` (elasticity tensor) could be guaranteed to be isotropic.
* Certain calculations are dramatically _faster_ on isotropic tensors (divide by scalar) than on anisotropic tensors (invert a rank four tensor). 
* Some of our models yield _incorrect_ results when used with anisotropic tensors (finite strain models neglect to rotate the elasticity tensor into the current deformed configuration).

### Rationale for the enhancement or information for reproducing the error

Guarantees on material properties would allow us to
* implement incomplete models (like finite strain currently is) and properly warn our users when they are used improperly. 
* implement accelerated code paths (skip rotations and inverts on isotropic tensors etc.)

### Identified impact
New optional capability.

**Comment by dschwen** [comment]
Ping @bwspenc 
1e5e8b3 is a somewhat hacked proof-of-concept. `ComputeStressBase::isElasticityTensorGuaranteedIsotropic` loops through the material warehouse and asks the material classes if they guarantee an isotropic elasticity tensor. It totally works and provides solid error checking for `ComputeFiniteStrainElasticStress`. Of course a real MOOSE system for this would be way neater.

**Comment by permcody** [comment]
So why did you quote "Guarantees" anyway? Is that like "air quotes" or something. You aren't really guaranteeing anything are you. 

![image](https://cloud.githubusercontent.com/assets/3036960/25026110/43464eee-2062-11e7-8b83-7d596a64fc47.png)

**Comment by amjokisaari** [comment]
So, uh... go back to the non-tensor-based system from a while ago? ;)

**Comment by friedmud** [comment]
Just a general 👎 on this idea.

It feels like you should either be able to ask the Tensor type itself and make a decision based on that or the Tensor operations should be made much smarter so they do the optimized thing automatically (kind of like Eigen does).

**Comment by dschwen** [comment]
We've tried to go down the "smarter tensors" route. This is a different beast. We could very well add isotropic tensor types, but I fear this would lead to a ton of code duplication (the basic problem is mixing polymorphism and templating not working). 
Testing tensor properties is a very heavy operation. We cannot do that at every QP. For some classes that provide tensors we know ahead of time what the properties of the tensors will be. But it sounds like you've already got your minds made up anyways.

**Comment by amjokisaari** [comment]
@dschwen, sorry, I'm just trying to get a better idea here, mind isn't made up at all and my original comment was a bit flippant.  I'm wary of tweaking the system given how we got here in the first place - the original solid mechanics system was, I believe, based off of isotropic math that was then extended for anisotropy.  Ultimately it proved to be unsuited for what I needed to do and the way it was written made it very difficult to tweak.  I would hope that the tensor mechanics system remains clean, easy to work with, and easy to understand.  Though I understand my involvement with its development is essentially in contributing some opinion at this point. 

The rest of what I say is prefaced on that I'm being a bit dumb and not understanding when you say "the basic problem is mixing polymorphism and templating not working"...

I originally liked Derek's suggestion that the operators be made smarter, but the more I think of it, I don't think it's a good idea.  It might add in all the overhead of testing at each QP.  Also, why the heck would we want to define different kinds of math for the same tensor depending on what its filled with?  This would piss me off if I were trying to learn the system from scratch.

On the other hand, isotropic materials properties are a simplification of the full tensor formulation.  In a way it makes very good sense to me to create new, (I'd assume derived) isotropic tensor types, and you can overload your operators, etc.  Then your materials properties will be working with these new isotropic types and your model formulation issues are addressed.  You can do this isotropic testing in the constructor, *as you should do* when populating an isotropic tensor.  What kind of code duplication are you thinking of that would be so enormous?

**Comment by bwspenc** [comment]
The recent commit by @dschwen fixed the immediate problem we had, which was that with the plug and play material system, there were no protections against plugging together models that were incompatible.

The way it is currently implemented, `ComputeFiniteStrainElasticStress` only works with isotropic elasticity tensors because it does not rotate the elasticity tensor forward to the new configuration.  (Maybe we should rename it to `ComputeIsotropicFiniteStrainElasticStress` -- this is getting a little silly.) @dschwen's recent commit uncovered an alarming number of problems in our test suite that were incorrectly using it with anisotropic models.  It would certainly be possible to get it to work with anisotropic tensors, but that will involve more operations that would result in a significant performance penalty for the isotropic case. As was mentioned in the issue description, we have a similar situation with the plasticity models, where the performance penalty of supporting the general case is probably even more severe. This is not a matter of simply doing something to optimize the tensor operations -- we need to do a completely separate set of operations with the tensors because we can take important algorithmic shortcuts in the isotropic case that you can't take in the anisotropic case.

The whole idea of the plug and play system was to get rid of the proliferation of separate models for every combination of elasticity tensor, strain, and stress calculator.  That is an idea that sounds nice in theory, but is proving to be very difficult in practice.  I think it is working out well in the mixing of general elasticity tensors with small strain, linear elastic models, but making those models completely interoperable with the finite strain, inelastic models (which are what most of the models in solid_mechanics are) would come with too much baggage.

The check we have now, although a little bit ugly, gets the job done for us for the time being. We are well on our way to moving all of the solid_mechanics models into tensor_mechanics.  We may be able to work something out to allow more interchangeability between models down the road, but for the time being, having some checks to prevent the user from combining models in a way that is not supported will allow the anisotropic/small strain/elastic models to live in the same module as the isotropic/finite strain/inelastic models.

**Comment by dschwen** [comment]
@amjokisaari, I think the discussion is going in the wrong direction here. While the example is about a very specific RankFourTensor issue, the general proposal is much broader. Let me give you two more examples

1. The _Simple_ phase field classes require mobilities and gradient energy coefficients to be constant (the advanced classes still make certain assumptions about the gradient energy coefficient). Nothing stops the user from specifying properties that depend on phase variables, which will yields the _wrong_ results. We have no way of error checking (or even just warning) about this. 
2. In phase field kernels that use properties which can depend on non-linear variables use derivatives of these properties with respect to those variables to calculate gradients of properties. This _only_ works if there are no other terms that have a spatial derivative (but do not depend on non-linear variables - for example terms containing `x`, `y`, or `z` directly). Again this will cause calculations to silently give _wrong_ results, and we have no way of warning the user about this. 

So here you have two cases of `Real` properties that could be decorated with meta-data to prevent these stealthy physics failures. One guarantee could be that the property has a derivative of zero, and the other guarantee could be that the gradient id fully expressible in terms of the derivatives of the coupled non-linear variables. 

Just to finish up the dead-end discussion about "smart" tensors, which is really only at best tangentially related to this: By implementing all math operations for all tensors I mean that evert math operation should be implemented to yield a tensor of minimum symmetry _without_ fully expanding each operand into a full 81 (9) component tensor, performing the operation and then checking (with fuzzy equals) the symmetry of the resulting tensor (yuck!). You can imagine what a clusterf&^% of code that would make...

**Comment by amjokisaari** [comment]
@dschwen, thanks for arguing more thoroughly.  It does seem like some additional physics checks are needed within the materials properties and kernels that implement these models.  Are you saying that the only way those checks can be implemented are with this additional meta data on the tensors themselves?  

...I mean, maybe a tag (enum) should be generated from the "fill_method" that we already have that specifies the crystallography, which the material property could check with its own isIsotropic() call or whatever instead of adding a bunch of new functions to the tensor.  You could add in some error checking right at the beginning when this tag is set to make sure that the fill_method you say you have actually is obeying those rules, so that the offloaded isIsotropic() call in your material property doesn't pass yet do the wrong physics.   Am I being supremely dense about why this couldn't be done? 

From this tag I suppose you could also make your operators smarter to address the computational efficiency issue.

**Comment by bwspenc** [comment]
@amjokisaari I think @dschwen's point was that adding members to these tensor types doesn't really solve the problem because we need to know information for properties that are of simple types like floats.

**Comment by friedmud** [comment]
My issue with decoration like you're asking for is simple: it's just too damn complicated.

MOOSE is already complicated enough: and the (loose) binding between Kernels and Materials is one of the most complicated things for users to understand.  Layering *yet another* "linkage" requirement (on top of `name` and `type`) might be a step too far.

We have to be careful not to overburden the framework with pedantry for the sake of "correctness" while making the whole thing unusable for the average person.

**Comment by dschwen** [comment]
We can implement this backwards compatible and completely transparent to the user. Don't need it? Don't use it!

**Comment by friedmud** [comment]
That's not the point. You're going to proliferate it through all of the
modules (obviously phase field and tensor mechanics already). Users will
have no choice but to try to understand it and satisfy its requirements. We
would get a crap-ton if emails trying to understand why their simple
Material does work with some kernels and doesn't with others, etc.

Note: I'm not advocating doing nothing. I just think there is a better
solution than layering another "requirement" on top of the Material system.
I don't know what that is yet however...

**Comment by dschwen** [comment]
> Note: I'm not advocating doing nothing. 

I sure hope so. We are already getting email from people who are careful enough to check their results and see something is off. What worries me even more are people just accepting and publishing bullshit results. This reflects badly on MOOSE.

The guarantees are not a _requirement_. If your kernel implements the general case you will never need to even know about the guarantees. If you are writing a material for an incomplete physics model (kernel) you will get an error message (we could easily point to documentation right there).

> Users will have no choice but to try to understand it and satisfy its requirements

This is already the case with the physics they are implementing. If they understand the physics and derivations they understand what the required guarantees are. If they don't understand the physics they will at least not get a bogus simulation that yileds bullshit data without them ever knowing.

**Comment by dschwen** [comment]
To add a bit on this: If the user develops both kernel and material in their own app they do not have to care about any required guarantees at all. This real issue here are exceedingly complex models provided in the modules. We could either stop providing those, and answer every corresponding "Can MOOSE model ...?" With "No, but you are free to code it up yourself!" Or we provide them and with that comes some responsibility to make sure the objects cannot accidentally be used outside its specifications.

**Comment by friedmud** [comment]
I thought a lot about this on my 11 hour flight I just finished. I'm pretty
convinced that inheritance is the right fix here. Classes that require
specializations (symmetric, sparser, whatever) should require the
specialized version of the class. Classes that can work with the more
generic types do that.

The thing we'll have to change is how you get Material properties. We
currently try to get something _of_ a particular type... but now we want to
try to retrieve specializations or generalizations of that type. What we'll
need to do is try to get something with the name you specify and attempt to
dynamic cast it to what you want and see if it works.

Anyway: we can talk more about it... but I really think that using C++ type
hierarchies properly can fix this.

**Comment by dschwen** [comment]
Templating and polymorphism just don't work together. I don't see a way forward of doing this.

**Comment by dschwen** [comment]
Per RRP discussions with @bwspenc and @sapitts I'm going forward for now with writing an interface class that makes implementing new guarantees simpler and cleaner.
