### ISSUE TITLE
Output VectorPostprocessor data in order that they are declared

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#8974]
### Description of the enhancement or error report 
In Mastodon we are creating time histories using VectorPostprocessors, which include the time as well as other parameters. When output it would be nice if the column named "time" was the first column. 

### Rationale for the enhancement or information for reproducing the error
Currently, they are in alphabetical order because they are stored in a map. I propose adding a vector of the ordered names when the VPP is declaring vectors, which can then be iterated on during output.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
The order of CSV output would change.

@idaholab/moose-team Any objects before I whip this little guy out?

**Comment by permcody** [comment]
No need to store yet another piece of data that you have to manage and keep in sync. Just change the inner map to a vector of pairs instead. There are no speed issues here because we only declare a few vectors per vector postprocessor and those references are stored so we don't have to find them over and over again.

**Comment by friedmud** [comment]
I like Cody's suggestion and this whole thing sounds fine to me.
