### ISSUE TITLE
moosedocs.py MOOSE_DIR incorrect when MOOSE_DIR not set

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#9108]
### Description of the enhancement or error report
I tried running `moosedocs.py` on a machine that didn't have `MOOSE_DIR` set as an environment variable and it failed with a `failed to locate MOOSE` error.

Running `moosedocs.py` from `moose/docs`, the script sets `MOOSE_DIR = /moose/docs/../moose` which doesn't exist. 

I think that it is a simple fix by changing `'..'` to `'../..'` or equivalent on line 7, so that `MOOSE_DIR = /moose/docs/../../moose`.

This should also work for `moosedocs.py` in an app, eg. `app_name/docs/../../moose` as long as `moose` and `app_name` are in the same subfolder.

### Rationale for the enhancement or information for reproducing the error
While it is easy to set a `MOOSE_DIR` environment variable, `moosedocs.py` should work even when `MOOSE_DIR` environment variable isn't set.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Be able to run moosedocs.py when `MOOSE_DIR` isn't set

**Comment by cpgr** [comment]
PS - this documentation system is pretty cool. Thanks @aeslaughter

**Comment by aeslaughter** [comment]
I am not having this problem:

```
slauae@slaughter:~/projects/moose/docs (doc-dir-9108)$ echo $MOOSE_DIR

slauae@slaughter:~/projects/moose/docs (doc-dir-9108)$ ./moosedocs.py build --serve
Cleaning build directory: /Users/slauae/.local/share/moose/site
[I 170511 08:36:30 server:283] Serving on http://127.0.0.1:8000
[I 170511 08:36:30 handlers:60] Start watching changes
[I 170511 08:36:30 handlers:62] Start detecting changes
```

**Comment by permcody** [comment]
@aeslaughter, that script is definitely incorrect. It makes two bad assumptions. 

First, it retrieves the MOOSE_DIR environment variable without even checking if it's defined.
Second, it assumes that your projects directory is called "projects".

This is defect. We have the right logic in the run_tests script. You might want to look at that.

**Comment by aeslaughter** [comment]
> First, it retrieves the MOOSE_DIR environment variable without even checking if it's defined.

Not true, git calls "getenv" with a default.

> Second, it assumes that your projects directory is called "projects".

It makes this assumption only when the assumed default and the environment variable is not found (i.e., it trys ${HOME}/projects/moose as a last ditch effort before exiting).

That being said, I do think it should be a '../..' in the default, mine is working because of the /projects/moose guess at the end.

**Comment by permcody** [comment]
>> First, it retrieves the MOOSE_DIR environment variable without even checking if it's defined.

> Not true, git calls "getenv" with a default.

OK, but the default is wrong because it uses current working directory. It shouldn't do that at all, you know the location of the script so the working directory need not be used since it would only be correct in one case.

>> Second, it assumes that your projects directory is called "projects".

> It makes this assumption only when the assumed default and the environment variable is not found (i.e., it trys ${HOME}/projects/moose as a last ditch effort before exiting).

This isn't necessary. Since you know the location of the script within the MOOSE directory you need to try to find it with a last ditch effort. If MOOSE_DIR isn't defined, assume you are in the moose directory and use your knowledge of where the script is located to figure out where to go (don't use current working directory).

> That being said, I do think it should be a '../..' in the default, mine is working because of the /projects/moose guess at the end.

That's only correct when you happen to be in a certain location when running the script. If you move up or down that path would be wrong again.

We figured this all out long ago with the `./run_tests` script. You can run that script from anywhere and it does the right thing. It works when your projects directory isn't projects, etc. You might as well use that logic.

**Comment by aeslaughter** [comment]
> OK, but the default is wrong because it uses current working directory. It shouldn't do that at all, you know the location of the script so the working directory need not be used since it would only be correct in one case.

This is exactly equal to what is done in run_tests: https://github.com/idaholab/moose/blob/devel/test/run_tests#L10

```
MOOSE_DIR = os.path.abspath(os.path.join('..'))
```

However, this fails to pick up the script in a sister directory, which the change made in this PR does for the moosedocs script.

With my change, the logic is identical to run tests, with the added benefit of picking up MOOSE in a sister directory and the last ditch effort to look in "projects" if you are outside of the traditional directory structure.

I have this in this PR.
```
MOOSE_DIR = os.getenv('MOOSE_DIR', os.path.join(os.getcwd(), '..', '..', 'moose'))
```

Which is a one line equivalent to (with the improved sister directory locating):
```
MOOSE_DIR = os.path.abspath(os.path.join('..'))
#### See if MOOSE_DIR is already in the environment instead
if os.environ.has_key("MOOSE_DIR"):
MOOSE_DIR = os.environ['MOOSE_DIR']
```

**Comment by aeslaughter** [comment]
OK, run_tests also has this little guy.

```
# Set the current working directory to the directory where this script is located
os.chdir(os.path.abspath(os.path.dirname(sys.argv[0])))
```
