### ISSUE TITLE
Construct compliance tensor in tensor mechanics? 

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9149]
### Description of the enhancement or error report

Up for discussion: in the constructor of various elasticity-tensor classes, should we create a compliance tensor too?  (inverse of elasticity tensor)

### Rationale for the enhancement or information for reproducing the error

In my latest commit, i had to do this explicitly for Cosserat elasticity because its elasticity tensor is not symmetric so i can't use "invSymm" of RankFourTensor.  Then i realised that using "invSymm" on the fly all the time during plasticity takes quite a lot of time.  I need the compliance tensor during consistent tangent operator calculations.

So, what do you think?  ( @sapitts , @dschwen , @bwspenc , and anyone else).  As I see it:

pros - don't have to keep calling "invSymm"

cons - increased memory, slightly slower constructor

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by bwspenc** [comment]
@WilkAndy I don't think this is a thing that we have really needed because if we needed it, we probably would have made it, so you probably know much more about what is needed there. I guess it would be useful for things like return mapping iterations for plasticity models with general anisotropic materials.

Maybe we could just add an option to the models that form the elasticity tensor to have them also form the inverse of it, with a different property name?

**Comment by WilkAndy** [comment]
Yea, an optional thing migh be good, you're right.  Then we don't have to use memory/computation for many of the usual cases.

**Comment by permcody** [comment]
Closed by #9323
