### ISSUE TITLE
AuxVariable for velocity should be used in Kernel

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#9260]
### Description of the enhancement or error report
We compute velocity as an Aux but then duplicate the velocity calculation in the kernel. We should just couple in the Aux in the heat equation and perhaps use a higher-order monomial to curb the lose of resolution.

### Rationale for the enhancement or information for reproducing the error
It is confusing in the tutorial to compute velocity twice, so we shouldn't.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by friedmud** [comment]
Ummm.... how is this working?  You switched the Aux to be working at nodes... but the AuxKernel needs the _gradient_!

There is a _reason_ why we don't simply couple to the aux velocity field!  It's because there is no way to compute the Aux field accurately.  It's just there for output / visualization.

The Kernel should be (remain) coupled directly to the gradient of pressure.

**Comment by aeslaughter** [comment]
I believe all MONOMIALS are elemental based on this line in AuxKernel.C

```
  _is_nodal = _assembly.getFE(feType(),
_sys.mesh().dimension())->get_continuity() != DISCONTINUOUS;
```

**Comment by friedmud** [comment]
Yes: but you changed it to Nodal (Lagrange)... even though the AuxKernel is
using gradients. That shouldn't work...

**Comment by andrsd** [comment]
The diff shows FIRST MONOMIAL, not LAGRANGE.
