### ISSUE TITLE
Provide a Python control logic

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/moose#9281]
### Description of the enhancement or error report
it would be useful if there was a python control logic that applications could just use to be able to extend themselves with the Python programming language.

### Rationale for the enhancement or information for reproducing the error
Python is already used by MOOSE, so it is more or less available.  Allowing Python to be used to extend MOOSE applications provides additional flexibility for some applications.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This effectively adds another API to the modules directory.  Also python-config would need to be available and usable for compiling the module.

**Comment by permcody** [comment]
I'm going to close this ticket since we don't have any plans in the immediate future to support Python control logic in MOOSE. Our current Relap-7 customers are not asking for this and I'm not aware of any other projects or customers that are asking for this capability. 

There is some amount of interest, (but nothing firm) about supporting a scripting language interface into MOOSE but we are still awaiting the right application to begin designing this. It may or may not be Python, we might consider other lightweight languages when we get to this point.
