### ISSUE TITLE
Application revision header file may not be updated properly?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#9403]
### Description of the enhancement or error report
I met a problem in compiling MAMMOTH.

### Rationale for the enhancement or information for reproducing the error
I got a compiling error
```
use of undeclared identifier 'APPx_VERSION'
```
By checking `APP-xRevision.h`, I indeed cannot see it instead of `APP-x_VERSION`. I am guessing because I have a leftover of the header file, the make system did not update the file properly. Deleting the header file indeed fixed the problem.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Better user experience.

**Comment by permcody** [comment]
This recently changed so that it would regenerate more often. I'm curious under what conditions you encountered this error. It might be tricky to reproduce. 

Also, I'm having a bit of trouble understanding the text in your description. What's with the "x", is that meant to be a place holder for the animal name? Any more detail on what happened?

Tag @brianmoose

**Comment by YaqiWang** [comment]
`x` is a number. `APP-x` is the full animal name. I have not compiled MAMMOTH for a while. Today I did an update and then met this issue.

**Comment by brianmoose** [comment]
I could reproduce this directly in `APP-x` (why can't we say the name?).
This is due to `get_repo_revision.py` not handling the case where the revision file exists
but the `_REVISION` define is not there. #9342 changed the name of this define for this app.
It used to be `APP-x_REVISION` but now is `APPx_REVISION`. The old revision file had `APP-x_REVISION` in there but `get_repo_revision.py` is now searching for `APPx_REVISION`, couldn't find it, and decides the header doesn't need updating.

**Comment by andrsd** [comment]
Note that `APP-x_REVISION` is not a valid pre-processor identifier. That's why it was changed.
