### ISSUE TITLE
Add an "inactive" keyword to the input file parser

### ISSUE THREAD

**Issue by jessecarterMOOSE** [idaholab/moose#9411]
### Description of the enhancement or error report
Similar to the current "active" keyword, add an "inactive" keyword to ignore subblocks in the input file.

### Rationale for the enhancement or information for reproducing the error
Would be useful in large input files when needing to turn off just a few objects.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
New capability.

**Comment by jessecarterMOOSE** [comment]
Tagging @permcody. Feel free to modify this issue if it isn't clear.

Note I'm not volunteering to do this (at least not yet)...

**Comment by WilkAndy** [comment]
I know that for me, "inactive" would actually be more useful than "active", because i don't include un-needed things in input files, but i DO accidentally write incorrect things that i'd like to turn off, and often want to turn some things off just to see what happens.  Because the input files are so large, writing "active = 'a b c d e f g h i ....'" is a bit painful, so in order to mimic "inactive" i just end up making a new input file and hard-deleting a block.

Probably it'd be simplest to prohibit having both "inactive" and "active" in one block.
