### ISSUE TITLE
Need a non-const version of getAction in ActionWarehouse

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#9439]
### Description of the enhancement or error report
As the title.

### Rationale for the enhancement or information for reproducing the error
I am sorry to pollute the framework with this, but the complexity of our application reaches a point that more useful set-up information need to be pushed into actions which can provide a simpler interface for later runs. I will send a PR in.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
A new interface function.

**Comment by permcody** [comment]
Can you elaborate a little bit more of how you are using this capability? I want to make sure that it doesn't violate a design assumption.

**Comment by YaqiWang** [comment]
My ultimate goal is actually to have a function, which will be called inside an element or side loop, with interface as `bool propertyDefined(SubdomainID i, const MaterialPropertyName & mat_prop)` or `bool propertyDefined(SubdomainID i, unsigned int mat_prop_id)`.

The set-up in my application is that:
1. An action which holds the general description of the equation and is responsible for adding variables, kernels, BCs, etc. It has calls `getMaterialPropertyBlocks` for adding block restricted objects on the blocks where a particular property is available.
2. Materials are added with MOOSE input syntax, which accept the action name as a parameter and obtained and declare material properties with the property name returned by the action. There could be several materials each on non-overlapping subdomains.
3. An element user object needs to do some complicated integration over the entire domain involving several material properties declared in several materials.

Because this element user object needs to obtain more information from the action like what the materials do, I am thinking to let the materials add the information into action so that action can provide my needed function I mentioned at the beginning. I can call `getMaterialPropertyBlocks()` in `ElementUserObject` to set up this call by myself, but that will be tedious. And also I will have multiple objects like the element user object requiring this functionality. We could enhance `FEProblemBase` to provide this function call, but because I thought action is the more basic place holder, so to let action provide this function could be better. I am willing to accept if you think `FEProblemBase` is the way to go.

**Comment by YaqiWang** [comment]
`FEProblemBase::_map_block_material_prop` actually provides the information, but using it might make the function call inefficient, particularly inside an element loop. I now tend to close this issue and the PR and add the function in `FEProblemBase`. Any thoughts?

**Comment by permcody** [comment]
> Because this element user object needs to obtain more information from the action like what the materials do, I am thinking to let the materials add the information into action so that action can provide my needed function I mentioned at the beginning. I can call getMaterialPropertyBlocks() in ElementUserObject to set up this call by myself, but that will be tedious. And also I will have multiple objects like the element user object requiring this functionality. 

When I read that statement, I feel like we are really overcomplicating this whole setup process. I realize that your application is complicated and there are a lot of things to consider but it also seems like if there were fewer knobs to turns (at the input file level) a lot of this wouldn't be necessary. Imagine a master Action that could setup all of the objects directly based on the problem description so that you wouldn't be at the level of looking at boundaries and asking about materials. Yeah, it might seem more rigid, but it might also be more practical. Maybe that's too far away at this point but we are going to get there one way or the other. I know that the fuels performance team is really looking at dumping the full general syntax for their application in the next year or two. We may find we need to build more support at the framework level but I'm trying to avoid really screwy ways of working with the system if we can avoid it.

**Comment by YaqiWang** [comment]
OK, I will close this issue and add a new function `bool FEProblemBase::hasMaterialProperty(SubdomainID i, const MaterialPropertyName & mat_prop_name)` using `FEProblemBase::_map_block_material_prop`. I also rather not overcomplicate the system.
