### ISSUE TITLE
New interface functions in FEProblem are needed

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#9455]
### Description of the enhancement or error report
These new functions are used to check if a material property is defined on a block or a boundary.

### Rationale for the enhancement or information for reproducing the error
This allows integration of material properties over the entire domain or boundary without the properties being defined everywhere.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
New interface function.

**Comment by permcody** [comment]
I really don't like this. It'll be like 2nd or 3rd way we are doing this check. Maybe we don't have this exact use case covered but we should at least take a look at how you are going to use this. We have a similar method for telling us whether a material is defined where it's needed. That doesn't always work though because it's typically used during construction. Can you tell us the exact usage case?

**Comment by YaqiWang** [comment]
My use case is like the test I added but just more complicated. In the test I did not try to use the material properties.
