### ISSUE TITLE
Snap to Geometry

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9587]
### Description of the enhancement or error report
For curved domains it would be nice to have new nodes generated through adaptivity to _snap_ to a given geometry.

### Rationale for the enhancement or information for reproducing the error
This would allow a circular domain approximated by an n-gon to be adapted to an m-gon (with m>n) rather than a more refined n-gon.

### Identified impact
Added capability.

Ping @friedmud, who talked about this years ago already. I had a use case for this and implemented it using GeneralUserObjects and the MeshChangedInterface...

**Comment by permcody** [comment]
Right, he did, so why open a new ticket? #5932

**Comment by permcody** [comment]
Are you Chi Mad Bro?

**Comment by friedmud** [comment]
Also: I believe @roystgnr and co. are working on a native version of this in libMesh...

**Comment by dschwen** [comment]
We'll still need a moose interface for it though. I have an implementation,
and I frankly don't see that much is gained by having this in libmesh...

**Comment by dschwen** [comment]
![geo](https://user-images.githubusercontent.com/202302/28858867-5f2f6c04-7719-11e7-956a-d3e8a59b8f27.gif)

**Comment by dschwen** [comment]
The issue with the GeneralUserObject approach is that it is not executed during uniform refine. @friedmud's Geometry _System_ code has been rotting 1-2 years in the old issue. What prevented this from being turned into a PR?

**Comment by friedmud** [comment]
Meh - it was abandoned because it turned out not to really be what I wanted at that time... and I had more important things to work on then.... and then I never got back to it.

The support in libMesh should actually interface with CAD files... so it will be a lot more complete.  I'm ok with MOOSE also having its own support for simplified geometries if it will help us out in the interim.  We can then wrap up the libMesh support in our own system after it comes online.

Your animation looks good 👍

**Comment by roystgnr** [comment]
> The support in libMesh should actually interface with CAD files... so it will be a lot more complete. I'm ok with MOOSE also having its own support for simplified geometries if it will help us out in the interim. We can then wrap up the libMesh support in our own system after it comes online.

Strongly agreed.  The CAD stuff is going to take another year or so, and you shouldn't hold up MOOSE development waiting for it.  Keep pinging me when you chat about the MOOSE system, though, and with some luck we might be able to extend the same API and input deck later, to make things easier on app developers and users.

**Comment by dschwen** [comment]
Ok, cool, if the _uniform refine_ issue is not a deal breaker I can make a PR we could discuss. Otherwise this needs more work. Uniform refine is skipping anything moose right now, and it happens so early it might be problematic to call onMeshChanged on user objects.

**Comment by YaqiWang** [comment]
Uniform refine used to happen late in problem initial setup. We changed it a while ago because happening that late is much costly with all the dof information especially when the mesh is large, refer to https://github.com/idaholab/moose/pull/4638. Uniform refine is more like a mesh modifier now, which should not be a breaker.

**Comment by GiudGiud** [comment]
> Strongly agreed. The CAD stuff is going to take another year or so, and you shouldn't hold up MOOSE development waiting for it. Keep pinging me when you chat about the MOOSE system, though, and with some luck we might be able to extend the same API and input deck later, to make things easier on app developers and users.

@roystgnr would you mind updating us on this?
There's discussions on adding CSG-generation capabilities and ongoing work to be able to output CSG to other codes. It's not quite CAD but it's related
