### ISSUE TITLE
Want arithmetic operations in input files with new parser

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#9872]
### Description of the enhancement or error report

It's very handy to be able to do simple arithmetic in input files which we were able to do with the old getPot parser.

### Rationale for the enhancement or information for reproducing the error

This makes variable definition a lot cleaner as one variable can be shown to rely clearly on a couple or more other fundamental variables. Moreover, I know at least one application user (@jhaase1) that relies very heavily on such arithmetic.

### Identified impact

Make input files more flexible and clear.

**Comment by dschwen** [comment]
We could use FParser to evaluate such expressions.

**Comment by rwcarlsen** [comment]
The more involved ``${}`` were intentionally omitted from the new parser (except simple substitution) in order to allow us to have a conversation about what syntax/functionality we want to support - and to allow us to design things how we want rather than being at the mercy of  [random third party project].  Implementing this sort of functionality (if we decide we want it) should be quite easy - we just need to decide what we want - and implement it in a clean, extensible, future-proof way.

**Comment by lindsayad** [comment]
So I think @jhaase1 and I are only interested in basic arithmetic operations (+,-,*,/). We've never tried or felt the need to try anything more complex. It would be nice to get this resolved because I can't help debug @jhaase1's simulation cases without reverting to a really old version of MOOSE (which I'm unwilling to do) or doing a lot of manual arithmetic.

**Comment by rwcarlsen** [comment]
I think something like ``${func ${complicated}^42/${equation}}`` where we just pass the contents after ``func`` to fparser could be okay.  Then the existing ``${}`` variable expansion could just be reused and run before passing the content to fparser.  The big downside to doing something like that is it becomes more difficult to maintain feature-parity with input file parsing from the python side since fparser is part of libmesh/moose and not accessible in python currently.  There are all kinds of ways around this issue, but none that I can think of that are "nice" solutions.

**Comment by rwcarlsen** [comment]
@idaholab/moose-team thoughts?

**Comment by dschwen** [comment]
Use python's `eval()`, LOL

**Comment by rwcarlsen** [comment]
...only if fparser is an identically behaving subset of what eval takes...

**Comment by friedmud** [comment]
I would vote for using FParser if possible - just for consistency sake.

**Comment by lindsayad** [comment]
I'm just going to ping this whenever @jhaase1 sends me an input file :smile:

**Comment by joshuahansel** [comment]
I would use this often. For instance, when I define a problem in an input file, I might specify that I'm specifying a pipe of a certain radius, and I might need to use the corresponding pipe cross-sectional area somewhere. It's ideal to have visibility of that calculation there (otherwise one might see a numerical value and assume that algebra was done correctly, when in fact, it might just be some value that was copy-and-pasted from another input file).

I don't know how un-nice the FParser solution would be. If it is in fact the worst, perhaps we can define a set of operations we need and do our own parse the expressions ourselves if there is concern about the future-proof-ness of using existing python packages to parse the expressions. I'd at least want to have support for `+,-,*,/,^,abs,pi`.

**Comment by dschwen** [comment]
The python parser is just a binding for the c++ parser. So calling fparser
in that context could work.

**Comment by jhaase1** [comment]
Does anyone have even a basic version that works? Because I think I need to
be on the current version of Moose to get this working (
https://github.com/idaholab/moose/pull/10599) rather than just trying to
copy specific functions from the current version of Moose.

Regards,

John Haase

**Comment by rwcarlsen** [comment]
I'm working on something to help address this.  It isn't my top priority,
but I hope to have something within the next couple weeks.  We will want it
to handle arbitrary nesting of brace expressions and customizable functions
among other things.

**Comment by joshuahansel** [comment]
Is this still in the works? I find myself wanting this about every other input file I write.

**Comment by rwcarlsen** [comment]
Working on this is currently not a very high priority for me, but I still
plan on working on it some day.  If you want to rally and campaign for a
higher priority that's fine with me :-)

**Comment by joshuahansel** [comment]
How many 👍 on this issue would it take for you to prioritize this? 😛 Then we could send out an email to the moose users list saying, "If we get 15 likes on #9872, then we'll get arithmetic operations in input files!".

**Comment by rwcarlsen** [comment]
The threshold is however many it takes for cody and/or rich to tell me
prioritize it.

**Comment by lindsayad** [comment]
@friedmud We talked in the cube today about how this would work. I think we decided we like the `${}` syntax familiar to our users best along with dependency resolution done lexically (also as has been done in the best). Does this sound ok to you?

**Comment by friedmud** [comment]
I suppose.  I was never very happy with ${} notation, but if that's what
the people want... :-)
