### ISSUE TITLE
Add execute_on = FINAL for transfers

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9923]
## Rationale
Use case are statistical sampling multiapps that only care about the final state of the subapp.

## Description
Currently multi transfers have to occur at least one per timestep. In simulations that only care about the final state of a subapp this adds substantial overhead (as observerd by @bwspenc)

## Impact
Added capability.

**Comment by dschwen** [comment]
Hmmm,

`Transfer` gets the `execute_on` `MultiMooseEnum` from `SetupInterface`:

```
MultiMooseEnum
SetupInterface::getExecuteOptions()
{
  return MultiMooseEnum("none=0x00 initial=0x01 linear=0x02 nonlinear=0x04 timestep_end=0x08 "
                        "timestep_begin=0x10 custom=0x100",
                        "linear");
}
```

in `MultiAppTransfer` an option gets "added" to that `MultiMooseEnum` like so:

```
  MultiMooseEnum multi_transfer_execute_on(params.get<MultiMooseEnum>("execute_on").getRawNames() +
                                               " same_as_multiapp",
                                           "same_as_multiapp");
```

**However**, `getRawNames()` does not dump the explicit value assignments for the enum items (e.g. `custom`**`=0x100`**. Do I need to worry about that @permcody ?

**Comment by permcody** [comment]
Even if we don't, I really don't like the fact that the C++ enum and this enum are separate and it's easy to get them out of sync. I'm not sure how to really fix this though. C++ enums are really crappy.

**Comment by dschwen** [comment]
I think I'll table this after seeing that final is really only bolted on for output. The better approach for the problem at hand seems to be to introduce a `SamplerFullSolveMultiApp`

**Comment by permcody** [comment]
Still not in there. It should be a one-line fix but the question is where to put that one line and also, do we also execute the multiapp on final? I don't think we are doing that right now. Perhaps we should start with an input file that we want to work, and then use that to get the logic in the right place. Reopen if you want this.

**Comment by bwspenc** [comment]
I discussed this with @aeslaughter last week, and I think this is the same thing I want for my application. I want to be able to use the multiapp system for sampling calculations, and only transfer the results back from the sub-app on final (so that we don't incur the unnecessary computational cost of transferring back on every time step, which I have found to be pretty significant, when I only want the end result). Also, that should allow us to have the sub-apps take their own time steps, and not force the master app to take any sort of time stepping if all it's doing is firing off the sub-apps for sampling.

**Comment by jiangwen84** [comment]
@aeslaughter I wonder what is your opinion on introducing a ``SamplerFullSolveMultiApp``. For our statistical analysis, a full solve multi app makes more sense than a transient one as we want each sub-app to do a full solve and then transfers data on final. 

Should we have both  ``SamplerFullSolveMultiApp`` and ``SamplerTransientMultiApp``, OR, just have old ``SamplerMultiApp`` to derive from ``FullSolveMultiApp`` instead of `TransientMultiApp` if the transient one is not practical for statistic analysis.
