### ISSUE TITLE
Richards module test failing in parallel

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#9970]
## Rationale

The test richards/test:pressure_pulse.pp_fu_lumped_22 fails for me on 2 processors, with a SIGFPV, shortly after the first linear residual evaluation in the first time step:
```
Time Step  0, time = 0
                dt = 0

Time Step  1, time = 1000
                dt = 1000
 0 Nonlinear |R| = 1.414214e+06
  0 SNES Function norm 1.414213562373e+06 
      0 Linear |R| = 1.414214e+06

Floating point exception signaled (invalid floating point operation)!
```

## Description

```
METHOD=dbg ./run_tests -p 2 --re 'richards/test:pressure_pulse.pp_fu_lumped_22'
```

## Impact

I've determined that the failure comes from a MooseVariable querying an out of date System::current_local_solution, which has a value of -inf rather than the distributed solution's value of 2e6.

The fix is almost certainly just a single call to System::update(), but I can't find where we're missing an update.  Since that synchronization is done automatically by libMesh for solver solutions, and since we don't see this bug in any of the framework tests, I presume that something in this module in particular is trying to set a solution value directly and not doing so properly.  But, grepping through the code finds no likely culprits.

**Comment by permcody** [comment]
I'll tag @WilkAndy on here to see if he has any ideas but I wouldn't be too concerned with fixing up the Richard's module. There are plans to deprecate it as most if not all of the functionality in this module is now available in the "porous flow" module. It can't immediately go away though because there are active applications using the Richard's module as it sits today. If we can't figure this one out, we can probably just restrict the test to serial only.

**Comment by WilkAndy** [comment]
The Richards module will be deprecated at some stage.  However, it would be good to fix this because of that active App that uses Richards, and because PorousFlow uses quite similar logic to Richards, so there could be the same bug in PorousFlow but we haven't uncovered it yet.  There are some unusual things about this test:

 - src/materials/RichardsMaterial.C uses information about the finite element in its SUPG computations.  See particularly its computeSUPG() method.

 - src/kernels/RichardsFullyUpwindFlux and src/kernels/RichardsLumpedMassChange both use nodal values of variables rather than QP values.  See their prepareNodalValues() methods. 

a

**Comment by permcody** [comment]
Richards is deprecated in favor of porous_flow - closing.
